### ISSUE TITLE
 The filter for the monitor works poorly and there is no documentation for cmake. (IDFGH-1654)

### ISSUE THREAD

**Issue by ArTyGill** [espressif/esp-idf#3901] opened 2019-08-08 18:04 UTC
idf.py monitor --print-filter="*:E GATTS_TABLE_DEMO:I"
Displays a message ( Error: No such command "GATTS_TABLE_DEMO:I". )

**Comment by ArTyGill** [comment] 2019-08-08 18:06
idf.py monitor --print-filter="GATTS_TABLE_DEMO:I"
this works good, but I need the rest of the tags

**Comment by negativekelvin** [comment] 2019-08-08 19:00
Which os and shell?  Did you try escaping the space?

**Comment by dobairoland** [comment] 2019-08-09 08:25
Hi @ArTyGill. Thanks for reporting the issue but unfortunately I cannot reproduce it based on the information you've provided. The `print-filter` used by you is working for me. 

So please provide also the full log message and IDF version beside the previously mentioned OS and shell. Thanks!

**Comment by dobairoland** [comment] 2019-08-13 13:53
@ArTyGill Do you have any update regarding your issue?

**Comment by Alvin1Zhang** [comment] 2019-08-21 07:33
@ArTyGill Thanks for reporting the issue, will close this due to short of feedback. Feel free to reopen if you still have this issue, thanks.

**Closed by Alvin1Zhang** 2019-08-21 07:33 UTC
