### ISSUE TITLE
[ESP32 MQTT] Print No PING_RESP, disconnected (IDFGH-446)

### ISSUE THREAD

**Issue by Freepom** [espressif/esp-idf#2671] opened 2018-11-06 08:42 UTC
使用过程突然断开连接，串口打印了No PING_RESP, disconnected，这个是什么错误造成的

**Comment by Alvin1Zhang** [comment] 2018-11-06 08:51
The translation of the issue description is: When MQTT is in use, it suddenly lost connection and then printed No. PING_RESP, disconnected. Do you have any idea what caused this issue? @Freepom Please help correct if the translation is not correct. Thanks.

**Comment by david-cermak** [comment] 2018-11-06 09:37
Hi @Freepom ,

Generally this is caused by the MQTT broker not responding to pings. By default the client keep-alive setting is to 120s, so the issue indicates there was no communication server-client for this period.

If your connection is stable and your broker is online, this might also be an issue with mqtt-client not correctly processing some messages and thus not correctly sending pings (so the broker does not send ping responses). It is not easy to tell what is wrong in this case without deep understanding  of your application (plus the cause might have happened more than 120s before no ping response).

Can you please share, what is your application doing, what kind of data publishing. Also might be helpful to setup "verbose" log level (from menuconfig -> Component config -> Log output -> Verbose), so you can see more details what is going on. Example of such  log is here:
```
I (3012) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=45992
D (63022) MQTT_CLIENT: Sent PING successful
D (63022) MQTT_CLIENT: PING sent
D (63182) MQTT_CLIENT: msg_type=13, msg_id=0
D (63182) MQTT_CLIENT: MQTT_MSG_TYPE_PINGRESP
```
As you can see, the output contains also 'D(ebug)' logs about sending PINGs, msg types, etc.

Thanks, David.

**Comment by david-cermak** [comment] 2018-12-12 09:09
Hi @Freepom, 
any update from your side? Have you succeeded in connecting?

Thanks for keeping us posted! David

**Comment by Alvin1Zhang** [comment] 2019-03-15 03:44
@Freepom  Any updates? Thanks.

**Comment by Alvin1Zhang** [comment] 2019-05-16 11:45
@Freepom Thanks for reporting the issue. Will close the issue for now due to lack of updates and details. Feel free to reopen the issue, and please help share updates then. Thanks.

**Closed by Alvin1Zhang** 2019-05-16 11:45 UTC

**Comment by controllermaster** [comment] 2019-11-15 08:31
Below are the logs I am receiving while there is a random disconnection. 
Publish frequency is one min and publish data length is around 200bytes 
The network is stable and broker is online (as other devices are publishing successfully at same time ) 
Keepalive time is 30sec.

```
D (480354) MQTT_CLIENT: mqtt_enqueue id: 33373, type=3 successful
D (495464) MQTT_CLIENT: Sent PING successful
D (495464) MQTT_CLIENT: PING sent
E (511464) MQTT_CLIENT: No PING_RESP, disconnected
D (511464) MQTT_CLIENT: Reconnect after 10000 ms
I (511464) MQTT_EVENT: MQTT_EVENT_DISCONNECTED
D (526464) MQTT_CLIENT: Reconnecting...
I (531464) MQTT_EVENT: MQTT_EVENT_BEFORE_CONNECTED
D (544744) MQTT_CLIENT: Transport connected to mqtts://192.168.1.10:8883
I (544744) MQTT_CLIENT: Sending MQTT CONNECT message, type: 1, id: 0000
D (544754) MQTT_CLIENT: Connected
I (544754) MQTT_EVENT: MQTT_EVENT_CONNECTED
D (544754) MQTT_CLIENT: mqtt_enqueue id: 0, type=1 successful
I (544764) publish_data: 
```
Please help with this.
Thanks

**Comment by Alex-Smart** [comment] 2020-04-14 17:26
So Ive got even worse situation, constant **No PING_RESP, disconnected**
Ive added some debug lines in mqtt_client.c, 
`ESP_LOGE(TAG, "\r\n in mqtt_write_data() \r\n Platform: %llu,client_tick: %llu, keepalive: %d,\r\n", platform_tick_get_ms(),client->keepalive_tick, (client->connect_info.keepalive* 1000)/2);`
and the reason as I see it is **platform_tick_get_ms()** does not work properly
```
E (4451) MQTT_CLIENT: 
 in esp_mqtt_client_init() 
 Platform: 0,client_tick: 0, keepalive: 60000 

E (4461) MQTT_EXAMPLE:  -------------------- MQTT CLIENT CREATED -------------------- 
I (4471) MQTT_EXAMPLE: Other event id:7
I (4481) MQTT_CLIENT: Connecting to: mqtt://192.168.198.151:1883
I (4501) MQTT_CLIENT: Sending MQTT CONNECT message, type: 1, id: 0000
I (4521) MQTT_EXAMPLE: MQTT_EVENT_CONNECTED
E (5521) MQTT_CLIENT: 
 in esp_mqtt_task() 
 Platform: 1072513,client_tick: 0, keepalive: 60000 

E (5521) MQTT_CLIENT: 
 in mqtt_write_data() 
 Platform: 18446741927103497129,client_tick: 18446741927103497129, keepalive: 60000,

E (5531) MQTT_CLIENT: 
 in esp_mqtt_task() 
 Platform: 1072513,client_tick: 18446741927103497129, keepalive: 60000 

E (5541) MQTT_CLIENT: 
 in mqtt_write_data() 
 Platform: 18446741927103497129,client_tick: 18446741927103497129, keepalive: 60000,

E (5551) MQTT_CLIENT: 
 in esp_mqtt_task() 
 Platform: 1072513,client_tick: 18446741927103497129, keepalive: 60000 

E (5571) MQTT_CLIENT: 
 in mqtt_write_data() 
 Platform: 18446741927103497129,client_tick: 18446741927103497129, keepalive: 60000,

E (5581) MQTT_CLIENT: 
 in esp_mqtt_task() 
 Platform: 1072513,client_tick: 18446741927103497129, keepalive: 60000 
```

**Comment by eric-Kiaofarming** [comment] 2023-08-17 06:59
Hi everyone

I have the same problem,
The information captured by ESP-IDF is as follows:
```
D (106239) transport_base: poll_read: select - Timeout before any socket was ready!
D (106239) transport_base: poll_read: select - Timeout before any socket was ready!
D (106239) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
D (106249) mqtt_client: Sent PING successful
D (106259) mqtt_client: mqtt_message_receive: first byte: 0xd0
D (106259) mqtt_client: mqtt_message_receive: read "remaining length" byte: 0x0
D (106269) mqtt_client: mqtt_message_receive: total message length: 2 (already read: 2)
D (106279) mqtt_client: mqtt_message_receive: transport_read():2 2
D (106279) mqtt_client: msg_type=13, msg_id=0
D (106289) mqtt_client: MQTT_MSG_TYPE_PINGRESP
D (107299) transport_base: poll_read: select - Timeout before any socket was ready!
D (107299) transport_base: poll_read: select - Timeout before any socket was ready!
D (107299) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
D (108319) transport_base: poll_read: select - Timeout before any socket was ready!
D (108319) transport_base: poll_read: select - Timeout before any socket was ready!
D (108319) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
D (108329) mqtt_client: Sent PING successful
D (109349) transport_base: poll_read: select - Timeout before any socket was ready!
D (109349) transport_base: poll_read: select - Timeout before any socket was ready!
D (109349) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
E (109359) mqtt_client: No PING_RESP, disconnected
D (109369) mqtt_client: Reconnect after 10000 ms
D (109369) event: running post MQTT_EVENTS:2 with handler 0x400d51d8 and context 0x3ffdcf6c on loop 0x3ffdce50
D (109379) myMQTT: Event dispatched from event loop base=MQTT_EVENTS, event_id=2
I (109389) myMQTT: MQTT_EVENT_DISCONNECTED 1
D (119389) mqtt_client: Reconnecting...
D (119389) event: running post MQTT_EVENTS:7 with handler 0x400d51d8 and context 0x3ffdcf6c on loop 0x3ffdce50
D (119389) myMQTT: Event dispatched from event loop base=MQTT_EVENTS, event_id=7
I (119399) myMQTT: MQTT_EVENT_BEFORE_CONNECT
D (119399) esp-tls: host:192.168.31.26: strlen 13
D (119409) esp-tls: [sock=51] Resolved IPv4 address: 192.168.31.26
D (119409) esp-tls: [sock=51] Connecting to server. HOST: 192.168.31.26, Port: 1883
D (119429) mqtt_client: Transport connected to mqtt://192.168.31.26:1883
D (119429) mqtt_client: Sending MQTT CONNECT message, type: 1, id: 0000
D (119499) mqtt_client: mqtt_message_receive: first byte: 0x20
D (119509) mqtt_client: mqtt_message_receive: read "remaining length" byte: 0x2
D (119509) mqtt_client: mqtt_message_receive: total message length: 4 (already read: 2)
D (119519) mqtt_client: mqtt_message_receive: read_len=2
D (119519) mqtt_client: mqtt_message_receive: transport_read():4 4
D (119529) mqtt_client: Connected
D (119529) event: running post MQTT_EVENTS:1 with handler 0x400d51d8 and context 0x3ffdcf6c on loop 0x3ffdce50
D (119539) myMQTT: Event dispatched from event loop base=MQTT_EVENTS, event_id=1
I (119549) myMQTT: MQTT_EVENT_CONNECTED
D (119549) mqtt_client: mqtt_enqueue id: 31646, type=8 successful
D (119559) outbox: ENQUEUE msgid=31646, msg_type=8, len=17, size=17
D (119569) mqtt_client: Sent subscribe topic=Y5mJL/PING, id: 31646, type=8 successful
D (119599) mqtt_client: mqtt_message_receive: first byte: 0x90
D (119599) mqtt_client: mqtt_message_receive: read "remaining length" byte: 0x3
D (119599) mqtt_client: mqtt_message_receive: total message length: 5 (already read: 2)
D (119609) mqtt_client: mqtt_message_receive: read_len=3
D (119609) mqtt_client: mqtt_message_receive: transport_read():5 5
D (119619) mqtt_client: msg_type=9, msg_id=31646
D (119619) mqtt_client: pending_id=31646, pending_msg_count = 1
D (119629) outbox: DELETED msgid=31646, msg_type=8, remain size=0
D (119639) mqtt_client: deliver_suback, message_length_read=5, message_length=5
D (119639) event: running post MQTT_EVENTS:3 with handler 0x400d51d8 and context 0x3ffdcf6c on loop 0x3ffdce50
D (119649) myMQTT: Event dispatched from event loop base=MQTT_EVENTS, event_id=3
I (119659) myMQTT: MQTT_EVENT_SUBSCRIBED, msg_id=31646
D (119669) mqtt_client: mqtt_enqueue id: 48336, type=3 successful
D (119669) outbox: ENQUEUE msgid=48336, msg_type=3, len=20, size=20
I (119679) MyAgri: mqtt_event_handler => dataRefresh
D (119689) mqtt_client: mqtt_enqueue id: 27541, type=3 successful
D (119689) outbox: ENQUEUE msgid=27541, msg_type=3, len=73, size=93
I (119699) MyAgri: wf8098 00000000,0.000,0,2,0,info,M207,2,1692253651,unsaved[58]
D (119699) mqtt_client: mqtt_message_receive: first byte: 0x40
D (119709) mqtt_client: mqtt_message_receive: read "remaining length" byte: 0x2
D (119719) mqtt_client: mqtt_message_receive: total message length: 4 (already read: 2)
D (119729) mqtt_client: mqtt_message_receive: read_len=2
D (119729) mqtt_client: mqtt_message_receive: transport_read():4 4
D (119739) mqtt_client: msg_type=4, msg_id=48336
D (119739) mqtt_client: pending_id=27541, pending_msg_count = 2
D (119749) outbox: DELETED msgid=48336, msg_type=3, remain size=73
D (119759) mqtt_client: received MQTT_MSG_TYPE_PUBACK, finish QoS1 publish
D (119759) event: running post MQTT_EVENTS:5 with handler 0x400d51d8 and context 0x3ffdcf6c on loop 0x3ffdce50
D (119769) myMQTT: Event dispatched from event loop base=MQTT_EVENTS, event_id=5
D (119779) mqtt_client: mqtt_message_receive: first byte: 0x40
D (119789) mqtt_client: mqtt_message_receive: read "remaining length" byte: 0x2
D (119789) mqtt_client: mqtt_message_receive: total message length: 4 (already read: 2)
D (119799) mqtt_client: mqtt_message_receive: read_len=2
D (119809) mqtt_client: mqtt_message_receive: transport_read():4 4
D (119809) mqtt_client: msg_type=4, msg_id=27541
D (119819) mqtt_client: pending_id=27541, pending_msg_count = 1
D (119819) outbox: DELETED msgid=27541, msg_type=3, remain size=0
D (119829) mqtt_client: received MQTT_MSG_TYPE_PUBACK, finish QoS1 publish
D (119839) event: running post MQTT_EVENTS:5 with handler 0x400d51d8 and context 0x3ffdcf6c on loop 0x3ffdce50
D (119849) myMQTT: Event dispatched from event loop base=MQTT_EVENTS, event_id=5
D (120869) transport_base: poll_read: select - Timeout before any socket was ready!
D (120869) transport_base: poll_read: select - Timeout before any socket was ready!
D (120869) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
D (121889) transport_base: poll_read: select - Timeout before any socket was ready!
D (121889) transport_base: poll_read: select - Timeout before any socket was ready!
D (121889) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
D (121899) mqtt_client: Sent PING successful
D (121969) mqtt_client: mqtt_enqueue id: 33971, type=3 successful
D (121969) outbox: ENQUEUE msgid=33971, msg_type=3, len=65, size=65
I (121969) MyAgri: wf8098 00000000,0.000,0,2,0,info,M207,2,1692253653[50]
D (121979) mqtt_client: mqtt_message_receive: first byte: 0xd0
D (121979) mqtt_client: mqtt_message_receive: read "remaining length" byte: 0x0
D (121989) mqtt_client: mqtt_message_receive: total message length: 2 (already read: 2)
D (121999) mqtt_client: mqtt_message_receive: transport_read():2 2
D (121999) mqtt_client: msg_type=13, msg_id=0
D (122009) mqtt_client: MQTT_MSG_TYPE_PINGRESP
D (122019) mqtt_client: mqtt_message_receive: first byte: 0x40
D (122019) mqtt_client: mqtt_message_receive: read "remaining length" byte: 0x2
D (122029) mqtt_client: mqtt_message_receive: total message length: 4 (already read: 2)
D (122039) mqtt_client: mqtt_message_receive: read_len=2
D (122039) mqtt_client: mqtt_message_receive: transport_read():4 4
D (122049) mqtt_client: msg_type=4, msg_id=33971
D (122049) mqtt_client: pending_id=33971, pending_msg_count = 1
D (122059) outbox: DELETED msgid=33971, msg_type=3, remain size=0
D (122059) mqtt_client: received MQTT_MSG_TYPE_PUBACK, finish QoS1 publish
D (122069) event: running post MQTT_EVENTS:5 with handler 0x400d51d8 and context 0x3ffdcf6c on loop 0x3ffdce50
D (122079) myMQTT: Event dispatched from event loop base=MQTT_EVENTS, event_id=5
D (123099) transport_base: poll_read: select - Timeout before any socket was ready!
D (123099) transport_base: poll_read: select - Timeout before any socket was ready!
D (123099) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
```

The captured network packets are as follows:

![image](http://www.ilaopo.xyz/test/mqtt.png)


My development environment is as follows:
```
I (29) boot: ESP-IDF 5.0.2 2nd stage bootloader
I (29) boot: compile time 13:56:48
I (29) boot: chip revision: v3.0
I (32) boot.esp32: SPI Speed      : 40MHz
I (37) boot.esp32: SPI Mode       : DIO
I (41) boot.esp32: SPI Flash Size : 8MB
I (46) boot: Enabling RNG early entropy source...
I (51) boot: Partition Table:
I (55) boot: ## Label            Usage          Type ST Offset   Length
I (62) boot:  0 nvs              WiFi data        01 02 00009000 00005000
I (70) boot:  1 otadata          OTA data         01 00 0000e000 00002000
I (77) boot:  2 app0             OTA app          00 10 00010000 00350000
I (84) boot:  3 app1             OTA app          00 11 00360000 00350000
I (92) boot:  4 spiffs           Unknown data     01 82 006b0000 00140000
I (99) boot: End of partition table
I (104) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=330e8h (209128) map
I (188) esp_image: segment 1: paddr=00043110 vaddr=3ffbdb60 size=051a4h ( 20900) load
I (196) esp_image: segment 2: paddr=000482bc vaddr=40080000 size=07d5ch ( 32092) load
I (210) esp_image: segment 3: paddr=00050020 vaddr=400d0020 size=b629ch (746140) map
I (479) esp_image: segment 4: paddr=001062c4 vaddr=40087d5c size=0ed30h ( 60720) load
I (516) boot: Loaded app from partition at offset 0x10000
I (516) boot: Disabling RNG early entropy source...
I (528) cpu_start: Pro cpu up.
I (528) cpu_start: Starting app cpu, entry point is 0x40081be0
I (0) cpu_start: App cpu up.
D (536) clk: RTC_SLOW_CLK calibration value: 3321498
I (549) cpu_start: Pro cpu start user code
I (549) cpu_start: cpu freq: 160000000 Hz
I (550) cpu_start: Application information:
I (554) cpu_start: Project name:     controller
I (559) cpu_start: App version:      18b9876-dirty
I (565) cpu_start: Compile time:     Aug 17 2023 13:56:24
I (571) cpu_start: ELF file SHA256:  81f5676df903c66e...
I (577) cpu_start: ESP-IDF:          5.0.2
I (582) cpu_start: Min chip rev:     v0.0
I (586) cpu_start: Max chip rev:     v3.99 
I (591) cpu_start: Chip rev:         v3.0
```

**Comment by LHYYSY** [comment] 2024-01-05 06:23
![image](https://github.com/espressif/esp-idf/assets/112528246/e00db489-cbb1-4c95-a8b3-8dc51534ef23)
Hello, these errors will appear after I disconnect the link, but I can reconnect back.

**Comment by dvdobrovolskiy** [comment] 2026-05-01 09:25
same issue E (26-05-01 12:18:46.544) mqtt_client: No PING_RESP, disconnected
ESP-IDF 5.5.1.251215
