### ISSUE TITLE
ADC2 support

### ISSUE THREAD

**Issue by bmetman** [espressif/esp-idf#969] opened 2017-09-07 15:01 UTC
I was wondering when the ADC2 will be supported. As of now, only ADC1 channels 0 to 9 are supported. Is there any timeline for ADC2 and its channels?

**Comment by krzychb** [comment] 2017-09-07 15:09
https://github.com/espressif/esp-idf/issues/461#issuecomment-300794116

**Comment by igrr** [comment] 2017-09-08 09:38
Closing as duplicate of #461. If you wish to receive updates, follow the link to that issue and click "Subscribe" button.

**Closed by igrr** 2017-09-08 09:38 UTC

**Comment by bmetman** [comment] 2017-09-08 12:15
Thank you!
