### ISSUE TITLE
install.bat error while installing ninja: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] (IDFGH-6023)

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [espressif/esp-idf#7709] opened 2021-10-16 13:45 UTC
I conventionally have esp-idf and the tooclhain installed in C:/dev/esp (env variables are set up that way). Just now I wanted to erase the whole installation and redownload it again using

git clone 
install.bat

It failed the first time already but some modules were downloaded. This is how the error looks on the second time:

```
Installing ESP-IDF tools
Selected targets are: esp32, esp32c3, esp32s2, esp32s3
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, cmake, openocd-esp32, ninja, idf-exe, ccache, dfu-util
Skipping xtensa-esp32-elf@esp-2021r1-8.4.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2021r1-8.4.0 (already installed)
Skipping xtensa-esp32s3-elf@esp-2021r1-8.4.0 (already installed)
Skipping riscv32-esp-elf@esp-2021r1-8.4.0 (already installed)
Skipping esp32ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping esp32s2ulp-elf@2.28.51-esp-20191205 (already installed)
Skipping cmake@3.20.3 (already installed)
Skipping openocd-esp32@v0.10.0-esp32-20210902 (already installed)
Installing ninja@1.10.2
Downloading ninja-1.10.2-win64.zip to C:\dev\esp\.espressif\dist\ninja-1.10.2-win64.zip.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\dev\esp\.espressif\dist\ninja-1.10.2-win64.zip.tmp
Downloading ninja-1.10.2-win64.zip to C:\dev\esp\.espressif\dist\ninja-1.10.2-win64.zip.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\dev\esp\.espressif\dist\ninja-1.10.2-win64.zip.tmp
Downloading ninja-1.10.2-win64.zip to C:\dev\esp\.espressif\dist\ninja-1.10.2-win64.zip.tmp
WARNING: Download failure <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1125)>
WARNING: Failed to download https://dl.espressif.com/dl/ninja-1.10.2-win64.zip to C:\dev\esp\.espressif\dist\ninja-1.10.2-win64.zip.tmp
ERROR: Failed to download, and retry count has expired
Traceback (most recent call last):
  File "C:\dev\esp\esp-idf\tools\idf_tools.py", line 1819, in <module>
    main(sys.argv[1:])
  File "C:\dev\esp\esp-idf\tools\idf_tools.py", line 1815, in main
    action_func(args)
  File "C:\dev\esp\esp-idf\tools\idf_tools.py", line 1462, in action_install
    tool_obj.download(tool_version)
  File "C:\dev\esp\esp-idf\tools\idf_tools.py", line 718, in download
    raise DownloadError()
__main__.DownloadError
```

It seems Ninja can't be downloaded because the certificate is not valid.

I do not know if this could also be because I recently installed other python versions for another project (default is still 3.8 however) and there's a thread on [stackexchange](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error) that blames python. However, installing the certifi package does not get rid of the error. So I thought maybe the problem actually is with ninja?

**Comment by dobairoland** [comment] 2021-10-17 14:37
Hi @MartyMcFlyInTheSky. We are sorry for this issue. I believe this is a duplicate of https://github.com/espressif/esp-idf/issues/7672. I recommend there to use the offline installer until it is not solved.

Can we close this? You can subscribe to https://github.com/espressif/esp-idf/issues/7672 instead.

**Comment by MartyMcFlyInTheSky** [comment] 2021-10-18 09:57
Thanks yes this is a duplicate! Can be closed!

**Closed** 2021-10-18 10:19 UTC
Labels: Status: Opened
