### ISSUE TITLE
espidf 5.1、4.4 运行ethernet的iperf示例出现insufficient TX buffer size (IDFGH-12604)

### ISSUE THREAD

**Issue by NSsimple** [espressif/esp-idf#13602] opened 2024-04-13 17:14 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

![image](https://github.com/espressif/esp-idf/assets/112064914/4f7246fd-6123-489c-b8e8-838b6178f0cd)
<img width="412" alt="Snipaste_2024-04-14_01-10-03" src="https://github.com/espressif/esp-idf/assets/112064914/c700fa7b-cc6e-4a6b-856b-915af9f75099">
lan8720已经正确配置，我已经尝试过很多板子，包括淘宝发售的WT32-ETH01。
只要运行iperf -u -c SERVER_IP -t 60 -i 3就会出现错误 esp.emac: emac_esp32_transmit(232): insufficient TX buffer size。能力有限，尝试调节了很多内存、队列相关的参数仍然没能解决。很头疼

**Comment by kostaond** [comment] 2024-04-15 10:17
Closing the issue, since this is expected behavior.

**Closed by kostaond** 2024-04-15 10:17 UTC
Labels: Status: Opened
