### ISSUE TITLE
Missing pthread functions in ESP-IDF implementation: pthread_set/getschedparam (IDFGH-13997)

### ISSUE THREAD

**Issue by georgik** [espressif/esp-idf#14821] opened 2024-11-04 08:49 UTC
### Description

pthread implementation in ESP-IDF 5.4 is missing functions:
- `int pthread_setschedparam(pthread_t thread, int policy, const struct sched_param *param)`
- `int pthread_getschedparam(pthread_t thread, int *policy, struct sched_param *param)`

### Desired state

The API should be implemented.

### Workaround

Mock those functions in the project like: https://github.com/georgik/esp-idf-component-SDL/blob/main/src/thread/pthread/pthread_espidf.c
```c
/**
 * Stub for pthread_setschedparam which is missing in ESP-IDF
 */
int pthread_setschedparam(pthread_t thread, int policy, const struct sched_param *param) {
    // Dummy implementation: do nothing and return success
    return 0;
}

/**
 * Stub for pthread_setschedparam which is missing in ESP-IDF
 */
int pthread_getschedparam(pthread_t thread, int *policy, struct sched_param *param) {
    if (policy) {
        *policy = SCHED_OTHER; // Default scheduling policy
    }
    if (param) {
        param->sched_priority = 0; // Default priority
    }
    return 0;
}
```

**Comment by igrr** [comment] 2024-11-04 13:11
This is probably a duplicate of https://github.com/espressif/esp-idf/issues/8594.

**Closed** 2024-11-14 06:02 UTC
Labels: Type: Feature Request, Status: Done, Resolution: NA
