### ISSUE TITLE
WPA2 enterprise example not working with eduroam (IDFGH-85)

### ISSUE THREAD

**Issue by maur3ra** [espressif/esp-idf#1054] opened 2017-09-30 09:25 UTC
I got myself [this ESP32 development board](https://www.amazon.de/dp/B071P98VTG/ref=pe_3044161_189395811_TE_dp_1)
and installed the toolchain as described [here](https://esp-idf.readthedocs.io/en/v2.1/get-started/macos-setup.html)

When I now use the wpa2_enterprise example, configured (make menuconfig) with WiFI SSID "eduroam", EAP method 1, my email as EAP1 ID, EAP user name (xxxxx@uni-tuebingen.de) and password as described at [my home institution](http://www.uni-tuebingen.de/en/facilities/zentrum-fuer-datenverarbeitung/dienstleistungen/netzzugang/wlan.html), this compiles and uploads: 

> WARNING: Toolchain version is not supported: 1.22.0-61-gab8375a
> Expected to see version: 1.22.0-73-ge28a011
> Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
> WARNING: Toolchain version is not supported: 1.22.0-61-gab8375a
> Expected to see version: 1.22.0-73-ge28a011
> Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
> Flashing binaries to serial port /dev/tty.SLAB_USBtoUART (app at offset 0x10000)...
> esptool.py v2.1
> Traceback (most recent call last):
>   File "/Users/maurera/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2524, in <module>
>     _main()
>   File "/Users/maurera/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2517, in _main
>     main()
>   File "/Users/maurera/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 2246, in main
>     esp = chip_class(args.port, initial_baud)
>   File "/Users/maurera/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 177, in __init__
>     self._port = serial.serial_for_url(port)
>   File "/Library/Python/2.7/site-packages/serial/__init__.py", line 78, in serial_for_url
>     instance.open()
>   File "/Library/Python/2.7/site-packages/serial/serialposix.py", line 289, in open
>     self.fd = os.open(self.portstr, os.O_RDWR|os.O_NOCTTY|os.O_NONBLOCK)
> OSError: [Errno 16] Resource busy: '/dev/tty.SLAB_USBtoUART'
> make: *** [flash] Error 1
> mbple-3:wpa2_enterprise maurera$ make flash
> WARNING: Toolchain version is not supported: 1.22.0-61-gab8375a
> Expected to see version: 1.22.0-73-ge28a011
> Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
> WARNING: Toolchain version is not supported: 1.22.0-61-gab8375a
> Expected to see version: 1.22.0-73-ge28a011
> Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
> Flashing binaries to serial port /dev/tty.SLAB_USBtoUART (app at offset 0x10000)...
> esptool.py v2.1
> Connecting......
> Chip is ESP32D0WDQ6 (revision 1)
> Uploading stub...
> Running stub...
> Stub running...
> Configuring flash size...
> Auto-detected Flash size: 4MB
> Flash params set to 0x0220
> Compressed 17776 bytes to 10472...
> Wrote 17776 bytes (10472 compressed) at 0x00001000 in 0.9 seconds (effective 153.1 kbit/s)...
> Hash of data verified.
> Compressed 509920 bytes to 325366...
> Wrote 509920 bytes (325366 compressed) at 0x00010000 in 28.8 seconds (effective 141.7 kbit/s)...
> Hash of data verified.
> Compressed 3072 bytes to 82...
> Wrote 3072 bytes (82 compressed) at 0x00008000 in 0.0 seconds (effective 2051.7 kbit/s)...
> Hash of data verified.
> 
> Leaving...
> Hard resetting...

but doesn't connect to eduroam: 

> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0010,len:4
> load:0x3fff0014,len:5492
> load:0x40078000,len:0
> load:0x40078000,len:12180
> entry 0x40078f54
> [0;33mW (33) rtc_clk: Possibly invalid CONFIG_ESP32_XTAL_FREQ setting (40MHz). Detected 40 MHz.[0m
> [0;32mI (57) boot: ESP-IDF v3.0-dev-753-g845c3fb-dirty 2nd stage bootloader[0m
> [0;32mI (58) boot: compile time 11:05:26[0m
> [0;32mI (62) boot: Enabling RNG early entropy source...[0m
> [0;32mI (78) boot: SPI Speed      : 40MHz[0m
> [0;32mI (91) boot: SPI Mode       : DIO[0m
> [0;32mI (103) boot: SPI Flash Size : 4MB[0m
> [0;32mI (116) boot: Partition Table:[0m
> [0;32mI (127) boot: ## Label            Usage          Type ST Offset   Length[0m
> [0;32mI (150) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
> [0;32mI (173) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
> [0;32mI (196) boot:  2 factory          factory app      00 00 00010000 00100000[0m
> [0;32mI (220) boot: End of partition table[0m
> [0;32mI (233) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x13654 ( 79444) map[0m
> [0;32mI (345) esp_image: segment 1: paddr=0x0002367c vaddr=0x3ffb0000 size=0x030c0 ( 12480) load[0m
> [0;32mI (361) esp_image: segment 2: paddr=0x00026744 vaddr=0x40080000 size=0x00400 (  1024) load[0m
> [0;32mI (367) esp_image: segment 3: paddr=0x00026b4c vaddr=0x40080400 size=0x094c4 ( 38084) load[0m
> [0;32mI (442) esp_image: segment 4: paddr=0x00030018 vaddr=0x400d0018 size=0x5676c (354156) map[0m
> [0;32mI (820) esp_image: segment 5: paddr=0x0008678c vaddr=0x400898c4 size=0x06020 ( 24608) load[0m
> [0;32mI (852) esp_image: segment 6: paddr=0x0008c7b4 vaddr=0x400c0000 size=0x00000 (     0) load[0m
> [0;32mI (881) boot: Loaded app from partition at offset 0x10000[0m
> [0;32mI (881) boot: Disabling RNG early entropy source...[0m
> [0;32mI (884) cpu_start: Pro cpu up.[0m
> [0;32mI (894) cpu_start: Starting app cpu, entry point is 0x40080ed0[0m
> [0;32mI (0) cpu_start: App cpu up.[0m
> [0;32mI (927) heap_init: Initializing. RAM available for dynamic allocation:[0m
> [0;32mI (948) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM[0m
> [0;32mI (966) heap_init: At 3FFB8958 len 000276A8 (157 KiB): DRAM[0m
> [0;32mI (986) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
> [0;32mI (1005) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
> [0;32mI (1025) heap_init: At 4008F8E4 len 0001071C (65 KiB): IRAM[0m
> [0;32mI (1044) cpu_start: Pro cpu start user code[0m
> [0;32mI (1105) cpu_start: Starting scheduler on PRO CPU.[0m
> [0;32mI (197) cpu_start: Starting scheduler on APP CPU.[0m
> I (207) wifi: wifi firmware version: 731ced4
> I (207) wifi: config NVS flash: enabled
> I (207) wifi: config nano formating: disabled
> [0;32mI (207) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
> [0;32mI (217) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
> I (247) wifi: Init dynamic tx buffer num: 32
> I (247) wifi: Init data frame dynamic rx buffer num: 32
> I (247) wifi: Init management frame dynamic rx buffer num: 32
> I (247) wifi: wifi driver task: 3ffc5288, prio:23, stack:4096
> I (257) wifi: Init static rx buffer num: 10
> I (257) wifi: Init dynamic rx buffer num: 32
> I (257) wifi: Init rx ampdu len mblock:7
> I (267) wifi: Init lldesc rx ampdu entry mblock:4
> I (267) wifi: wifi power manager task: 0x3ffca6f4 prio: 21 stack: 2560
> [0;32mI (277) example: Setting WiFi configuration SSID eduroam...[0m
> I (287) wpa: WPA2 ENTERPRISE VERSION: [v2.0] enable
> 
> [0;32mI (317) phy: phy_version: 359.0, e79c19d, Aug 31 2017, 17:06:07, 0, 0[0m
> I (317) wifi: mode : sta (24:0a:c4:0e:0d:b0)
> I (1037) wifi: n:6 0, o:1 0, ap:255 255, sta:6 0, prof:1
> I (2017) wifi: state: init -> auth (b0)
> I (2017) wifi: state: auth -> assoc (0)
> I (2027) wifi: state: assoc -> run (10)
> I (2027) wpa: wpa2_task prio:2, stack:6656
> 
> I (4037) wpa: >>>>>wpa2 FIALED
> 
> I (4047) wpa: wpa2 task delete
> 
> [0;32mI (4317) example: ~~~~~~~~~~~[0m
> [0;32mI (4317) example: IP:0.0.0.0[0m
> [0;32mI (4317) example: MASK:0.0.0.0[0m
> [0;32mI (4317) example: GW:0.0.0.0[0m
> [0;32mI (4317) example: ~~~~~~~~~~~[0m
> I (5027) wifi: pm start, type:0
> 
> [0;32mI (6317) example: ~~~~~~~~~~~[0m
> [0;32mI (6317) example: IP:0.0.0.0[0m
> [0;32mI (6317) example: MASK:0.0.0.0[0m
> [0;32mI (6317) example: GW:0.0.0.0[0m
> [0;32mI (6317) example: ~~~~~~~~~~~[0m
> [0;32mI (8317) example: ~~~~~~~~~~~[0m
> [0;32mI (8317) example: IP:0.0.0.0[0m
> [0;32mI (8317) example: MASK:0.0.0.0[0m
> [0;32mI (8317) example: GW:0.0.0.0[0m
> [0;32mI (8317) example: ~~~~~~~~~~~[0m
> [0;32mI (10317) example: ~~~~~~~~~~~[0m
> [0;32mI (10317) example: IP:0.0.0.0[0m
> [0;32mI (10317) example: MASK:0.0.0.0[0m
> [0;32mI (10317) example: GW:0.0.0.0[0m
> [0;32mI (10317) example: ~~~~~~~~~~~[0m
> [0;32mI (12317) example: ~~~~~~~~~~~[0m
> [0;32mI (12317) example: IP:0.0.0.0[0m
> [0;32mI (12317) example: MASK:0.0.0.0[0m
> [0;32mI (12317) example: GW:0.0.0.0[0m
> [0;32mI (12317) example: ~~~~~~~~~~~[0m
> [0;32mI (14317) example: ~~~~~~~~~~~[0m
> [0;32mI (14317) example: IP:0.0.0.0[0m
> [0;32mI (14317) example: MASK:0.0.0.0[0m
> [0;32mI (14317) example: GW:0.0.0.0[0m
> [0;32mI (14317) example: ~~~~~~~~~~~[0m
> [0;32mI (16317) example: ~~~~~~~~~~~[0m
> [0;32mI (16317) example: IP:0.0.0.0[0m
> [0;32mI (16317) example: MASK:0.0.0.0[0m
> [0;32mI (16317) example: GW:0.0.0.0[0m
> [0;32mI (16317) example: ~~~~~~~~~~~[0m
> [0;32mI (18317) example: ~~~~~~~~~~~[0m
> [0;32mI (18317) example: IP:0.0.0.0[0m
> [0;32mI (18317) example: MASK:0.0.0.0[0m
> [0;32mI (18317) example: GW:0.0.0.0[0m
> [0;32mI (18317) example: ~~~~~~~~~~~[0m
> [0;32mI (20317) example: ~~~~~~~~~~~[0m
> [0;32mI (20317) example: IP:0.0.0.0[0m
> [0;32mI (20317) example: MASK:0.0.0.0[0m
> [0;32mI (20317) example: GW:0.0.0.0[0m
> [0;32mI (20317) example: ~~~~~~~~~~~[0m
> [0;32mI (22317) example: ~~~~~~~~~~~[0m
> [0;32mI (22317) example: IP:0.0.0.0[0m
> [0;32mI (22317) example: MASK:0.0.0.0[0m
> [0;32mI (22317) example: GW:0.0.0.0[0m
> [0;32mI (22317) example: ~~~~~~~~~~~[0m
> [0;32mI (24317) example: ~~~~~~~~~~~[0m
> [0;32mI (24317) example: IP:0.0.0.0[0m
> [0;32mI (24317) example: MASK:0.0.0.0[0m
> [0;32mI (24317) example: GW:0.0.0.0[0m
> [0;32mI (24317) example: ~~~~~~~~~~~[0m
> [0;32mI (26317) example: ~~~~~~~~~~~[0m
> [0;32mI (26317) example: IP:0.0.0.0[0m
> [0;32mI (26317) example: MASK:0.0.0.0[0m
> [0;32mI (26317) example: GW:0.0.0.0[0m
> [0;32mI (26317) example: ~~~~~~~~~~~[0m
> [0;32mI (28317) example: ~~~~~~~~~~~[0m
> [0;32mI (28317) example: IP:0.0.0.0[0m
> [0;32mI (28317) example: MASK:0.0.0.0[0m
> [0;32mI (28317) example: GW:0.0.0.0[0m
> [0;32mI (28317) example: ~~~~~~~~~~~[0m
> [0;32mI (30317) example: ~~~~~~~~~~~[0m
> [0;32mI (30317) example: IP:0.0.0.0[0m
> [0;32mI (30317) example: MASK:0.0.0.0[0m
> [0;32mI (30317) example: GW:0.0.0.0[0m
> [0;32mI (30317) example: ~~~~~~~~~~~[0m
> I (32027) wifi: state: run -> init (2)
> I (32027) wifi: pm stop, total sleep time: 0/27001132
> 
> I (32027) wifi: n:6 0, o:6 0, ap:255 255, sta:6 0, prof:1
> I (32157) wifi: n:6 0, o:6 0, ap:255 255, sta:6 0, prof:1
> I (32157) wifi: state: init -> auth (b0)
> I (32157) wifi: state: auth -> assoc (0)
> I (32167) wifi: state: assoc -> run (10)
> I (32167) wpa: wpa2_task prio:2, stack:6656
> 
> [0;32mI (32317) example: ~~~~~~~~~~~[0m
> [0;32mI (32317) example: IP:0.0.0.0[0m
> [0;32mI (32317) example: MASK:0.0.0.0[0m
> [0;32mI (32317) example: GW:0.0.0.0[0m
> [0;32mI (32317) example: ~~~~~~~~~~~[0m
> I (34237) wpa: >>>>>wpa2 FIALED
> 
> I (34247) wpa: wpa2 task delete
> 
> [0;32mI (34317) example: ~~~~~~~~~~~[0m
> [0;32mI (34317) example: IP:0.0.0.0[0m
> [0;32mI (34317) example: MASK:0.0.0.0[0m
> [0;32mI (34317) example: GW:0.0.0.0[0m
> [0;32mI (34317) example: ~~~~~~~~~~~[0m
> I (35167) wifi: pm start, type:0
> 
> [0;32mI (36317) example: ~~~~~~~~~~~[0m
> [0;32mI (36317) example: IP:0.0.0.0[0m
> [0;32mI (36317) example: MASK:0.0.0.0[0m
> [0;32mI (36317) example: GW:0.0.0.0[0m
> [0;32mI (36317) example: ~~~~~~~~~~~[0m
> [0;32mI (38317) example: ~~~~~~~~~~~[0m
> [0;32mI (38317) example: IP:0.0.0.0[0m
> [0;32mI (38317) example: MASK:0.0.0.0[0m
> [0;32mI (38317) example: GW:0.0.0.0[0m
> [0;32mI (38317) example: ~~~~~~~~~~~[0m

Adding the Telekom root certificate as wpa2_ca.pem doesn't seem to change anything. Is there anything I could do, and to get more details where/how it failed?

**Comment by XinDeng11** [comment] 2017-11-14 02:47
Hi @maur3ra Sorry for later reply, have you tried with our latest IDF? What's more, have you udpate the router server's certificate in the example's main folder? There is another customer also met the problem, we suggest them update their router server's certificate and problem solved. There are two certificates wpa_server.key and wpa_server.pem, you need copy them to the router server and replace the original, after change them, rename the name to server.key and server.pem

**Comment by maur3ra** [comment] 2017-11-18 11:24
Hi @XinDeng11 , thanks for the helpful reply! You suggest changing the certificate on the router? Or Where exactly would the router server sit within the eduroam infrastructure (world-wide between schools and universities)? As far as I know, the authentication is done by the server at the "home organization" (my university), nevertheless at which partner site and in which building you are.  And I probably don't have access to the router, right? 

On eduroam, with the iPhone I just connect using username and password, on Android devices you also have to add the root certificate. Do you suggest the opposite (changing it on the server rather than getting the server certificate), or did I misunderstand you?

**Comment by sagb2015** [comment] 2019-06-19 05:18
@maur3ra - This is probably too late to ask for, but if you still face the issue with latest release, we will actively look into it. Thank you and apologies for the delay!

**Comment by sagb2015** [comment] 2019-08-20 05:49
Closing this issue because of lack of updates. Feel free to re-open if the issue is observed again.

**Closed by sagb2015** 2019-08-20 05:49 UTC
