### ISSUE TITLE
ESP-IDF执行./install出错 (IDFGH-10126)

### ISSUE THREAD

**Issue by MrYanLK** [espressif/esp-idf#11400] opened 2023-05-15 03:05 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0-541-g885e501d99

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

1

### What is the actual behavior?

我想编译AT固件，在esp-at目录下初次执行./build.py menuconfig时会自动下载一个对应的esp-idf仓库，在esp-idf下执行./install时报错如下，网上没有找到解决方法。

### Steps to reproduce.

1

### Build or installation Logs.

```plain
ylk@DESKTOP-6TBOMGV:~/esp-at/esp-idf$
ylk@DESKTOP-6TBOMGV:~/esp-at/esp-idf$ ./install.sh
Detecting the Python interpreter
Checking "python3" ...
Python 3.10.6
"python3" has been detected
Checking Python compatibility
Installing ESP-IDF tools
Current system platform: linux-amd64
Selected targets are: esp32s2, esp32s3, esp32c2, esp32, esp32h2, esp32c3
Installing tools: xtensa-esp-elf-gdb, riscv32-esp-elf-gdb, xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, openocd-esp32, esp-rom-elfs
Skipping xtensa-esp-elf-gdb@11.2_20220823 (already installed)
Skipping riscv32-esp-elf-gdb@11.2_20220823 (already installed)
Skipping xtensa-esp32-elf@esp-2022r1-11.2.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2022r1-11.2.0 (already installed)
Skipping xtensa-esp32s3-elf@esp-2022r1-11.2.0 (already installed)
Skipping riscv32-esp-elf@esp-2022r1-11.2.0 (already installed)
Skipping esp32ulp-elf@2.35_20220830 (already installed)
Skipping openocd-esp32@v0.11.0-esp32-20221026 (already installed)
Skipping esp-rom-elfs@20220823 (already installed)
Installing Python environment and packages
Python 3.10.6
pip 23.1.2 from /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/pip (python 3.10)
Upgrading pip and setuptools...
Requirement already satisfied: pip in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (23.1.2)
Requirement already satisfied: setuptools in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (67.7.2)
Skipping the download of /home/ylk/.espressif/espidf.constraints.v5.0.txt because it was downloaded recently.
Installing Python packages
 Constraint file: /home/ylk/.espressif/espidf.constraints.v5.0.txt
 Requirement files:
  - /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt
  - /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt
Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
Ignoring windows-curses: markers 'sys_platform == "win32"' don't match your environment
Collecting idf-build-apps (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 5))
  Using cached idf_build_apps-0.6.1-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: pyserial in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 8)) (3.5)
Requirement already satisfied: pyyaml in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 9)) (6.0)
Collecting junit_xml (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 10))
  Using cached junit_xml-1.9-py2.py3-none-any.whl (7.1 kB)
Collecting netifaces (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 11))
  Using cached netifaces-0.11.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting pexpect (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 14))
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting python-gitlab (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 15))
  Using cached python_gitlab-3.14.0-py3-none-any.whl (135 kB)
Requirement already satisfied: pygdbmi in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 16)) (0.9.0.2)
Requirement already satisfied: future in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 19)) (0.18.2)
Collecting dbus-python (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 20))
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [94 lines of output]
      + meson setup /tmp/pip-install-l60nu1iy/dbus-python_3321b57663e444edb2f42aa252e803aa /tmp/pip-install-l60nu1iy/dbus-python_3321b57663e444edb2f42aa252e803aa/.mesonpy-kyd3itze/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-l60nu1iy/dbus-python_3321b57663e444edb2f42aa252e803aa/.mesonpy-kyd3itze/build/meson-python-native-file.ini
      The Meson build system
      Version: 1.1.0
      Source dir: /tmp/pip-install-l60nu1iy/dbus-python_3321b57663e444edb2f42aa252e803aa
      Build dir: /tmp/pip-install-l60nu1iy/dbus-python_3321b57663e444edb2f42aa252e803aa/.mesonpy-kyd3itze/build
      Build type: native build
      Project name: dbus-python
      Project version: 1.3.2
      C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
      C linker for the host machine: cc ld.bfd 2.38
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -fno-common: YES
      Compiler for C supports arguments -Wno-missing-field-initializers: YES
      Compiler for C supports arguments -Wno-declaration-after-statement: YES
      Compiler for C supports arguments -Wno-inline: YES
      Compiler for C supports arguments -Wno-redundant-decls: YES
      Compiler for C supports arguments -Wno-switch-default: YES
      Compiler for C supports arguments -Wno-write-strings: YES
      Compiler for C supports arguments -Wcast-align: YES
      Compiler for C supports arguments -Wdouble-promotion: YES
      Compiler for C supports arguments -Wduplicated-cond: YES
      Compiler for C supports arguments -Wfloat-equal: YES
      Compiler for C supports arguments -Wformat-nonliteral: YES
      Compiler for C supports arguments -Wformat-security: YES
      Compiler for C supports arguments -Wformat=2: YES
      Compiler for C supports arguments -Winit-self: YES
      Compiler for C supports arguments -Wlogical-op: YES
      Compiler for C supports arguments -Wmissing-declarations: YES
      Compiler for C supports arguments -Wmissing-format-attribute: YES
      Compiler for C supports arguments -Wmissing-include-dirs: YES
      Compiler for C supports arguments -Wmissing-noreturn: YES
      Compiler for C supports arguments -Wnull-dereference: YES
      Compiler for C supports arguments -Wpacked: YES
      Compiler for C supports arguments -Wpointer-arith: YES
      Compiler for C supports arguments -Wshadow: YES
      Compiler for C supports arguments -Wswitch-enum: YES
      Compiler for C supports arguments -Wundef: YES
      Compiler for C supports arguments -Wunused-but-set-variable: YES
      Compiler for C supports arguments -Wjump-misses-init: YES
      Compiler for C supports arguments -Wmissing-prototypes: YES
      Compiler for C supports arguments -Wnested-externs: YES
      Compiler for C supports arguments -Wold-style-definition: YES
      Compiler for C supports arguments -Wpointer-sign: YES
      Compiler for C supports arguments -Wstrict-prototypes: YES
      Configuring _dbus-python-config.h using configuration

      Executing subproject dbus-gmain

      dbus-gmain| Project name: dbus-gmain
      dbus-gmain| Project version: undefined
      dbus-gmain| C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
      dbus-gmain| C linker for the host machine: cc ld.bfd 2.38
      dbus-gmain| Compiler for C supports arguments -fno-common: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wno-missing-field-initializers: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wcast-align: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wdouble-promotion: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wduplicated-branches: YES
      dbus-gmain| Compiler for C supports arguments -Wduplicated-cond: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wfloat-equal: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-nonliteral: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat-security: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wformat=2: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Winit-self: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wlogical-op: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-declarations: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-format-attribute: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-include-dirs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-noreturn: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnull-dereference: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpacked: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-arith: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wredundant-decls: YES
      dbus-gmain| Compiler for C supports arguments -Wshadow: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wswitch-default: YES
      dbus-gmain| Compiler for C supports arguments -Wswitch-enum: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wundef: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wunused-but-set-variable: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wwrite-strings: YES
      dbus-gmain| Compiler for C supports arguments -Wdeclaration-after-statement: YES
      dbus-gmain| Compiler for C supports arguments -Wjump-misses-init: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wmissing-prototypes: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wnested-externs: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wold-style-definition: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wpointer-sign: YES (cached)
      dbus-gmain| Compiler for C supports arguments -Wstrict-prototypes: YES (cached)
      dbus-gmain| Did not find pkg-config by name 'pkg-config'
      dbus-gmain| Found Pkg-config: NO
      dbus-gmain| Found CMake: /bin/cmake (3.22.1)
      dbus-gmain| Run-time dependency dbus-1 found: NO (tried cmake)

      ../../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency lookup for dbus-1 with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.

      A full log can be found at /tmp/pip-install-l60nu1iy/dbus-python_3321b57663e444edb2f42aa252e803aa/.mesonpy-kyd3itze/build/meson-logs/meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/home/ylk/esp-at/esp-idf/tools/idf_tools.py", line 2610, in <module>
    main(sys.argv[1:])
  File "/home/ylk/esp-at/esp-idf/tools/idf_tools.py", line 2602, in main
    action_func(args)
  File "/home/ylk/esp-at/esp-idf/tools/idf_tools.py", line 2063, in action_install_python_env
    subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr, env=env_copy)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ylk/.espressif/python_env/idf5.0_py3.10_env/bin/python', '-m', 'pip', 'install', '--no-warn-script-location', '-r', '/home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt', '-r', '/home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt', '--upgrade', '--constraint', '/home/ylk/.espressif/espidf.constraints.v5.0.txt', '--extra-index-url', 'https://dl.espressif.com/pypi']' returned non-zero exit status 1.
ylk@DESKTOP-6TBOMGV:~/esp-at/esp-idf$
```

**Comment by gm-jiang** [comment] 2023-05-15 10:04
To resolve this issue, maybe you can try the following steps:
Install pkg-config: Check if pkg-config is installed on your system. You can do this by running the command pkg-config --version in a terminal. If it's not installed, you will need to install it. The process varies depending on your operating system.

* For Debian-based systems (e.g., Ubuntu): Run sudo apt-get install pkg-config to install it.
* For Red Hat-based systems (e.g., Fedora): Run sudo dnf install pkg-config to install it.
* For macOS (using Homebrew): Run brew install pkg-config to install it.

**Comment by MrYanLK** [comment] 2023-05-18 07:12
请问这个问题怎么解决呢

ylk@DESKTOP-6TBOMGV:~/esp-at/esp-idf$ ./install.sh
Detecting the Python interpreter
Checking "python3" ...
Python 3.10.6
"python3" has been detected
Checking Python compatibility
Installing ESP-IDF tools
Current system platform: linux-amd64
Selected targets are: esp32c2, esp32, esp32s2, esp32c3, esp32s3, esp32h2
Installing tools: xtensa-esp-elf-gdb, riscv32-esp-elf-gdb, xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, openocd-esp32, esp-rom-elfs
Skipping xtensa-esp-elf-gdb@11.2_20220823 (already installed)
Skipping riscv32-esp-elf-gdb@11.2_20220823 (already installed)
Skipping xtensa-esp32-elf@esp-2022r1-11.2.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2022r1-11.2.0 (already installed)
Skipping xtensa-esp32s3-elf@esp-2022r1-11.2.0 (already installed)
Skipping riscv32-esp-elf@esp-2022r1-11.2.0 (already installed)
Skipping esp32ulp-elf@2.35_20220830 (already installed)
Skipping openocd-esp32@v0.11.0-esp32-20221026 (already installed)
Skipping esp-rom-elfs@20220823 (already installed)
Installing Python environment and packages
Python 3.10.6
pip 23.1.2 from /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/pip (python 3.10)
Upgrading pip and setuptools...
Requirement already satisfied: pip in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (23.1.2)
Requirement already satisfied: setuptools in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (67.7.2)
Skipping the download of /home/ylk/.espressif/espidf.constraints.v5.0.txt because it was downloaded recently.
Installing Python packages
 Constraint file: /home/ylk/.espressif/espidf.constraints.v5.0.txt
 Requirement files:
  - /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt
  - /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt
Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
Ignoring windows-curses: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: setuptools in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 3)) (67.7.2)
Requirement already satisfied: click in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 4)) (8.0.4)
Requirement already satisfied: pyserial in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 5)) (3.5)
Requirement already satisfied: future in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 6)) (0.18.2)
Requirement already satisfied: cryptography in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 7)) (36.0.2)
Requirement already satisfied: pyparsing in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 8)) (3.0.9)
Requirement already satisfied: pyelftools in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 9)) (0.27)
Requirement already satisfied: idf-component-manager in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 10)) (1.2.2)
Requirement already satisfied: esp-coredump in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 11)) (1.5.0)
Requirement already satisfied: esptool in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 12)) (4.5.1)
Requirement already satisfied: kconfiglib in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 15)) (14.1.0)
Requirement already satisfied: freertos_gdb in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt (line 19)) (1.0.2)
Collecting idf-build-apps (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 5))
  Using cached idf_build_apps-0.6.1-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: pyyaml in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 9)) (6.0)
Collecting junit_xml (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 10))
  Using cached https://dl.espressif.cn/pypi/junit-xml/junit_xml-1.9-py2.py3-none-any.whl (7.1 kB)
Collecting netifaces (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 11))
  Using cached netifaces-0.11.0.tar.gz (30 kB)
  Preparing metadata (setup.py) ... done
Collecting pexpect (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 14))
  Using cached https://dl.espressif.cn/pypi/pexpect/pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting python-gitlab (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 15))
  Using cached python_gitlab-3.14.0-py3-none-any.whl (135 kB)
Requirement already satisfied: pygdbmi in /home/ylk/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 16)) (0.9.0.2)
Collecting dbus-python (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 20))
  Using cached https://dl.espressif.cn/pypi/dbus-python/dbus_python-1.3.2-cp310-cp310-linux_x86_64.whl (122 kB)
Collecting pygobject (from -r /home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt (line 21))
  Using cached PyGObject-3.44.1.tar.gz (720 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
      Collecting setuptools
        Using cached https://dl.espressif.cn/pypi/setuptools/setuptools-67.7.2-py3-none-any.whl (1.1 MB)
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting pycairo
        Using cached pycairo-1.23.0.tar.gz (344 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for pycairo (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-x86_64-cpython-310
            creating build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-310/cairo
            copying cairo/py.typed -> build/lib.linux-x86_64-cpython-310/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            No package 'cairo' found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/home/ylk/esp-at/esp-idf/tools/idf_tools.py", line 2610, in <module>
    main(sys.argv[1:])
  File "/home/ylk/esp-at/esp-idf/tools/idf_tools.py", line 2602, in main
    action_func(args)
  File "/home/ylk/esp-at/esp-idf/tools/idf_tools.py", line 2063, in action_install_python_env
    subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr, env=env_copy)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ylk/.espressif/python_env/idf5.0_py3.10_env/bin/python', '-m', 'pip', 'install', '--no-warn-script-location', '-r', '/home/ylk/esp-at/esp-idf/tools/requirements/requirements.core.txt', '-r', '/home/ylk/esp-at/esp-idf/tools/requirements/requirements.ttfw.txt', '--upgrade', '--constraint', '/home/ylk/.espressif/espidf.constraints.v5.0.txt', '--extra-index-url', 'https://dl.espressif.com/pypi']' returned non-zero exit status 1.
ylk@DESKTOP-6TBOMGV:~/esp-at/esp-idf$

**Comment by wanckl** [comment] 2023-05-22 02:37
你的这个依赖解决了吗
```
dbus-gmain| Run-time dependency dbus-1 found: NO (tried pkgconfig and cmake)
../../subprojects/dbus-gmain/meson.build:107:11: ERROR: Dependency "dbus-1" not found, tried pkgconfig and cmake
```

**Comment by dobairoland** [comment] 2024-12-17 09:42
I'm closing this one and half year old report. 

I think the issue was caused by trying to install the ttfw dependencies which is our old test infrastructure package and is deprecated now. I don't think esp-at would need it.

The issue keeps repeating because `./install.sh --enable-ttfw` was executed once. The issue can be resolved by removing the ttfw keyword by manually editing the `~/.espressif/idf-env.json` file. The file can be in other locations if it was changed,

**Closed by dobairoland** 2024-12-17 09:42 UTC
Labels: Type: Bug, Status: Opened
