### ISSUE TITLE
[esp32-S2] download flash tool cant flash S2 over USB (IDFGH-4355)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#6193] opened 2020-12-01 16:16 UTC
I am trying to flash custom PCB with esp32 S2 wrover module. I do have both buttons so i can easy enter download mode.
I am trying to use native USB to flash on windows and after some time this is the log:
```
no log file output ...
test offset :  65536 0x10000
case ok
test offset :  32768 0x8000
case ok
test offset :  57344 0xe000
case ok
test offset :  4096 0x1000
case ok
======
CONNECT BAUD: 115200
============
Uploading stub...
Running stub...
[2020-12-01 16:08:13,358][ESP8266Loader_spi[1]][espDownloader.py][line:554][ERROR]: ESP32S2 Chip stub error esp_stub_and_set_baud.
no log file output ...
```

With S2 devkit and UART there is no problem to flash.

**Comment by igrr** [comment] 2020-12-01 16:59
@chegewara are you able to flash with esptool.py provided in ESP-IDF?

**Comment by chegewara** [comment] 2020-12-01 16:59
Now even more weird part. After connecting USB to UART to my custom PCB i am getting this message from flash download tool when i am trying to erase it:
```
.Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
[2020-12-01 16:24:18,009][ESP8266Loader_spi[1]][espDownloader.py][line:1767][ERROR]: ESP32 efuse secure check fail:Already secure boot, NOT Allow download bootloader again!!!
[2020-12-01 16:24:18,009][ESP8266Loader_spi[1]][espDownloader.py][line:528][ERROR]: ESP32S2 Secure Encrypt check error flash_erase_func.
```
and here we can see all my efuses:
```
Connecting...
Detecting chip type... ESP32-S2
espefuse.py v3.0
EFUSE_NAME (Block)                       Description  = [Meaningful Value] [Readable/Writeable] (Hex Value)
----------------------------------------------------------------------------------------
Calibration fuses:
TEMP_SENSOR_CAL (BLOCK2)                 Temperature calibration                            = -8.3 R/W (0b101010011)
ADC1_MODE0_D2 (BLOCK2)                   ADC1 calibration 1                                 = -104 R/W (0x9a)
ADC1_MODE1_D2 (BLOCK2)                   ADC1 calibration 2                                 = -100 R/W (0x99)
ADC1_MODE2_D2 (BLOCK2)                   ADC1 calibration 3                                 = -104 R/W (0x9a)
ADC1_MODE3_D2 (BLOCK2)                   ADC1 calibration 4                                 = -112 R/W (0x9c)
ADC2_MODE0_D2 (BLOCK2)                   ADC2 calibration 5                                 = -16 R/W (0x84)
ADC2_MODE1_D2 (BLOCK2)                   ADC2 calibration 6                                 = -12 R/W (0x83)
ADC2_MODE2_D2 (BLOCK2)                   ADC2 calibration 7                                 = -12 R/W (0x83)
ADC2_MODE3_D2 (BLOCK2)                   ADC2 calibration 8                                 = 4 R/W (0x01)
ADC1_MODE0_D1 (BLOCK2)                   ADC1 calibration 9                                 = -32 R/W (0b101000)
ADC1_MODE1_D1 (BLOCK2)                   ADC1 calibration 10                                = -24 R/W (0b100110)
ADC1_MODE2_D1 (BLOCK2)                   ADC1 calibration 11                                = -20 R/W (0b100101)
ADC1_MODE3_D1 (BLOCK2)                   ADC1 calibration 12                                = -12 R/W (0b100011)
ADC2_MODE0_D1 (BLOCK2)                   ADC2 calibration 13                                = -16 R/W (0b100100)
ADC2_MODE1_D1 (BLOCK2)                   ADC2 calibration 14                                = -8 R/W (0b100010)
ADC2_MODE2_D1 (BLOCK2)                   ADC2 calibration 15                                = -8 R/W (0b100010)
ADC2_MODE3_D1 (BLOCK2)                   ADC2 calibration 16                                = -4 R/W (0b100001)

Config fuses:
DIS_RTC_RAM_BOOT (BLOCK0)                Disables boot from RTC RAM                         = False R/W (0b0)
DIS_ICACHE (BLOCK0)                      Disables ICache                                    = False R/W (0b0)
DIS_DCACHE (BLOCK0)                      Disables DCache                                    = False R/W (0b0)
DIS_DOWNLOAD_ICACHE (BLOCK0)             Disables Icache when SoC is in Download mode       = False R/W (0b0)
DIS_DOWNLOAD_DCACHE (BLOCK0)             Disables Dcache when SoC is in Download mode       = False R/W (0b0)
DIS_FORCE_DOWNLOAD (BLOCK0)              Disables forcing chip into Download mode           = False R/W (0b0)
DIS_CAN (BLOCK0)                         Disables the TWAI Controller hardware              = False R/W (0b0)
DIS_BOOT_REMAP (BLOCK0)                  Disables capability to Remap RAM to ROM address sp = False R/W (0b0)
                                         ace
FLASH_TPUW (BLOCK0)                      Configures flash startup delay after SoC power-up, = 0 R/W (0x0)
                                          unit is (ms/2). When the value is 15, delay is 7.
                                         5 ms
DIS_LEGACY_SPI_BOOT (BLOCK0)             Disables Legacy SPI boot mode                      = False R/W (0b0)
UART_PRINT_CHANNEL (BLOCK0)              Selects the default UART for printing boot msg     = UART0 R/W (0b0)
DIS_USB_DOWNLOAD_MODE (BLOCK0)           Disables use of USB in UART download boot mode     = False R/W (0b0)
UART_PRINT_CONTROL (BLOCK0)              Sets the default UART boot message output mode     = Enabled R/W (0b00)
FLASH_TYPE (BLOCK0)                      Selects SPI flash type                             = 4 data lines R/W (0b0)
FORCE_SEND_RESUME (BLOCK0)               Forces ROM code to send an SPI flash resume comman = False R/W (0b0)
                                         d during SPI boot
BLOCK_USR_DATA (BLOCK3)                  User data
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W

Efuse fuses:
WR_DIS (BLOCK0)                          Disables programming of individual eFuses          = 0 R/W (0x00000000)
RD_DIS (BLOCK0)                          Disables software reading from BLOCK4-10           = 0 R/W (0b0000000)

Identity fuses:
BLOCK0_VERSION (BLOCK0)                  BLOCK0 efuse version                               = 0 R/W (0b00)
SECURE_VERSION (BLOCK0)                  Secure version (used by ESP-IDF anti-rollback feat = 0 R/W (0x0000)
                                         ure)
MAC (BLOCK1)                             Factory MAC Address
   = 7c:df:a1:01:76:a4: (OK) R/W
WAFER_VERSION (BLOCK1)                   WAFER version                                      = A R/W (0b000)
PKG_VERSION (BLOCK1)                     Package version
   = ESP32-S2, QFN 7x7 56 pins R/W (0x0)
BLOCK1_VERSION (BLOCK1)                  BLOCK1 efuse version                               = 0 R/W (0b000)
OPTIONAL_UNIQUE_ID (BLOCK2)(0 errors):   Optional unique 128-bit ID
   = 7b b0 ac 68 1f 76 d1 76 8d 3b 02 5a fd fe c2 9b R/W
BLOCK2_VERSION (BLOCK2)                  Version of BLOCK2                                  = With calibration R/W (0b001)

Security fuses:
SOFT_DIS_JTAG (BLOCK0)                   Software disables JTAG. When software disabled, JT = False R/W (0b0)
                                         AG can be activated temporarily by HMAC peripheral
HARD_DIS_JTAG (BLOCK0)                   Hardware disables JTAG permanently                 = False R/W (0b0)
DIS_DOWNLOAD_MANUAL_ENCRYPT (BLOCK0)     Disables flash encryption when in download boot mo = False R/W (0b0)
                                         des
SPI_BOOT_CRYPT_CNT (BLOCK0)              Enables encryption and decryption, when an SPI boo = Disable R/W (0b000)
                                         t mode is set. Enabled when 1 or 3 bits are set,di
                                         sabled otherwise
SECURE_BOOT_KEY_REVOKE0 (BLOCK0)         If set, revokes use of secure boot key digest 0    = False R/W (0b0)
SECURE_BOOT_KEY_REVOKE1 (BLOCK0)         If set, revokes use of secure boot key digest 1    = False R/W (0b0)
SECURE_BOOT_KEY_REVOKE2 (BLOCK0)         If set, revokes use of secure boot key digest 2    = False R/W (0b0)
KEY_PURPOSE_0 (BLOCK0)                   KEY0 purpose                                       = USER R/W (0x0)
KEY_PURPOSE_1 (BLOCK0)                   KEY1 purpose                                       = USER R/W (0x0)
KEY_PURPOSE_2 (BLOCK0)                   KEY2 purpose                                       = USER R/W (0x0)
KEY_PURPOSE_3 (BLOCK0)                   KEY3 purpose                                       = USER R/W (0x0)
KEY_PURPOSE_4 (BLOCK0)                   KEY4 purpose                                       = USER R/W (0x0)
KEY_PURPOSE_5 (BLOCK0)                   KEY5 purpose                                       = USER R/W (0x0)
SECURE_BOOT_EN (BLOCK0)                  Enables secure boot                                = False R/W (0b0)
SECURE_BOOT_AGGRESSIVE_REVOKE (BLOCK0)   Enables aggressive secure boot key revocation mode = False R/W (0b0)
DIS_DOWNLOAD_MODE (BLOCK0)               Disables all Download boot modes                   = False R/W (0b0)
ENABLE_SECURITY_DOWNLOAD (BLOCK0)        Enables secure UART download mode (read/write flas = False R/W (0b0)
                                         h only)
BLOCK_KEY0 (BLOCK4)(0 errors):
  Purpose: USER
  Encryption key0 or user data
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W
BLOCK_KEY1 (BLOCK5)(0 errors):
  Purpose: USER
  Encryption key1 or user data
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W
BLOCK_KEY2 (BLOCK6)(0 errors):
  Purpose: USER
  Encryption key2 or user data
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W
BLOCK_KEY3 (BLOCK7)(0 errors):
  Purpose: USER
  Encryption key3 or user data
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W
BLOCK_KEY4 (BLOCK8)(0 errors):
  Purpose: USER
  Encryption key4 or user data
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W
BLOCK_KEY5 (BLOCK9)(0 errors):
  Purpose: USER
  Encryption key5 or user data
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W
BLOCK_SYS_DATA2 (BLOCK10)                System data (part 2)
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W

Spi_Pad_Config fuses:
SPI_PAD_CONFIG_CLK (BLOCK1)              SPI CLK pad                                        = 0 R/W (0b000000)
SPI_PAD_CONFIG_Q (BLOCK1)                SPI Q (D1) pad                                     = 0 R/W (0b000000)
SPI_PAD_CONFIG_D (BLOCK1)                SPI D (D0) pad                                     = 0 R/W (0b000000)
SPI_PAD_CONFIG_CS (BLOCK1)               SPI CS pad                                         = 0 R/W (0b000000)
SPI_PAD_CONFIG_HD (BLOCK1)               SPI HD (D3) pad                                    = 0 R/W (0b000000)
SPI_PAD_CONFIG_WP (BLOCK1)               SPI WP (D2) pad                                    = 0 R/W (0b000000)
SPI_PAD_CONFIG_DQS (BLOCK1)              SPI DQS pad                                        = 0 R/W (0b000000)
SPI_PAD_CONFIG_D4 (BLOCK1)               SPI D4 pad                                         = 0 R/W (0b000000)
SPI_PAD_CONFIG_D5 (BLOCK1)               SPI D5 pad                                         = 0 R/W (0b000000)
SPI_PAD_CONFIG_D6 (BLOCK1)               SPI D6 pad                                         = 0 R/W (0b000000)
SPI_PAD_CONFIG_D7 (BLOCK1)               SPI D7 pad                                         = 0 R/W (0b000000)

Usb Config fuses:
DIS_USB (BLOCK0)                         Disables the USB OTG hardware                      = False R/W (0b0)
USB_EXCHG_PINS (BLOCK0)                  Exchanges USB D+ and D- pins                       = False R/W (0b0)
EXT_PHY_ENABLE (BLOCK0)                  Enables external USB PHY                           = False R/W (0b0)
USB_FORCE_NOPERSIST (BLOCK0)             Forces to set USB BVALID to 1                      = False R/W (0b0)

Vdd_Spi Config fuses:
VDD_SPI_FORCE (BLOCK0)                   Force using VDD_SPI_XPD and VDD_SPI_TIEH to config = False R/W (0b0)
                                         ure VDD_SPI LDO
VDD_SPI_XPD (BLOCK0)                     The VDD_SPI regulator is powered on                = False R/W (0b0)
VDD_SPI_TIEH (BLOCK0)                    The VDD_SPI power supply voltage at reset          = Connect to 1.8V LDO R/W (0b0)
PIN_POWER_SELECTION (BLOCK0)             Sets default power supply for GPIO33..37, set when = VDD3P3_CPU R/W (0b0)
                                          SPI flash is initialized

Wdt Config fuses:
WDT_DELAY_SEL (BLOCK0)                   Selects RTC WDT timeout threshold at startup       = 0 R/W (0b00)

Flash voltage (VDD_SPI) determined by GPIO45 on reset (GPIO45=High: VDD_SPI pin is powered from internal 1.8V LDO
GPIO45=Low or NC: VDD_SPI pin is powered directly from VDD3P3_RTC_IO via resistor Rspi. Typically this voltage is 3.3 V).
```

I can easy flash with arduino, with both modes, or from esp-idf. The only issue is flash download tool.

All 4 bootstrap pins (including pin26 - psram) are kept not connected, except IO0 to button.
Any help @projectgus 

Thanks

PS i managed to flash with USB to UART module, but its not easy

**Comment by chegewara** [comment] 2020-12-01 17:01
> @chegewara are you able to flash with esptool.py provided in ESP-IDF?

With esp-idf and arduino, using UART or USB, even dfu.

**Comment by chegewara** [comment] 2020-12-01 17:04
There is one more thing, which i will just mention here, but i think it requires to open new issue. When i eventually flashed S2 with tool i am getting this message, which didnt appear when i flash with arduino IDE:
```
load:0x3ffe6108,len:0x570
load:0x4004c000,len:0xb0c
load:0x40050000,len:0x25a4
SHA-256 comparison failed:
Calculated: f0f97a4a55bc2315c896597accd6a483c70f87997eda7dfae11029f3603c0017
Expected: 28f622ecd5b38a7f0d09f7835c477d1ccc24c9e1591844b3faabc39b1235a77a
Attempting to boot anyway...
entry 0x4004c180
```

**Comment by igrr** [comment] 2020-12-01 20:37
> With esp-idf and arduino, using UART or USB, even dfu.

Sorry, did you mean that you *are* able to flash using these options, or you *are not*?

If the issue is only with Flash download tools, I am sorry but this is out of scope of ESP-IDF project issue tracker.

**Comment by chegewara** [comment] 2020-12-01 21:29
Sorry @igrr 
yes, i am able to flash using all those option. Only issue i have is flash over USB using flash download tool.

Where i can open issue with tool then, sorry for wrong issue tracker?

**Closed** 2023-03-23 23:35 UTC
