### ISSUE TITLE
Unified Provisioning BLE bug, connection lost   (IDFGH-6908)

### ISSUE THREAD

**Issue by Divraj-Dev** [espressif/esp-idf#8528] opened 2022-03-08 23:07 UTC
## Environment
- Module or chip used:  ESP32-WROOM-32E
- IDF version : Latest Master Branch
- Build System:         idf.py
- Compiler version: esp-2021r2-8.4.0
- Operating System:     n/a but building on MACOS
- Using an IDE?:  VSCODE
- Power Supply:         external powersuply

## Problem Description

When testing the unified provisioning BLE, I have noticed that some phones (mainly android Samsungs) have an issue where when you select the ESP device from the scanned Provisioning list, the bluetooth connection established and disconnected instantly. Then proceeding to select the esp device again, it works fine. It is a minor bug but happens quite often on newer samsung devices.

### Expected Behavior

Like other devices, when bluetooth conection is established during provisoining, that it connects first try.

### Actual Behavior
Samsung devices (mainly) disconnect on the first connection establishment but connect on a second try.

### Steps to reproduce

1. Download the ESP BLE provisioning on your samsung device
2. Install the example provisoioning to your ESP device with BLE as the scheme
3. Run through the proviosioning

## Debug Logs

```
 (1828) main: Provisioning started
I (1858) NimBLE: GAP procedure initiated: advertise;
I (1858) NimBLE: disc_mode=2
I (1858) NimBLE: adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=256 adv_itvl_max=256
I (1868) NimBLE:

// This is where the disconnection happens

I (18668) NimBLE: GAP procedure initiated: advertise;
I (18668) NimBLE: disc_mode=2
I (18668) NimBLE: adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=256 adv_itvl_max=256
I (18678) NimBLE:
```

**Comment by ocESP** [comment] 2022-03-10 10:19
Hello @divrajBevie,
 
We tried reproducing the issue. At our end we saw that if there is any wifi authentication failure, the user will get `NimBLE: disc_mode=2` print, but still the provisioning will be successful! As the provisioning is successful despite of getting failure, we were unable to try provisioning in the second run. We directly got the print `Already provisioned, starting Wi-Fi STA`

In order to understand deeper and debug the issue, could you please enable debugging and share the console logs?

You can do this using the following steps - 
run `idf.py menuconfig`
In menuconfig -> Component config -> Bluetooth -> NimBLE Options -> NimBLE Host log verbosity -> select Debug logs
Moreover, in menuconfig -> Component config -> Log output -> Default log verbosity -> select Debug

**Comment by Alvin1Zhang** [comment] 2022-04-12 08:54
@divrajBevie Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by divrajBevie** [comment] 2022-04-26 01:49
@Alvin1Zhang We did not find a fix for this, however we made minor tweaks to the android plugin to retry multiple times before displaying the error message. This is indeed just a work around to the problem which is working for us currently.

**Comment by Alvin1Zhang** [comment] 2022-04-26 04:28
@divrajBevie Thanks for sharing the updates, would you please help share debug logs per [earlier comment on that issue](https://github.com/espressif/esp-idf/issues/8528#issuecomment-1063892139)? Thanks.

**Comment by Alvin1Zhang** [comment] 2022-10-10 08:50
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.

**Closed as completed by Alvin1Zhang** 2022-10-10 08:50 UTC
Labels: Awaiting Response, Status: Done, Resolution: Done

**Comment by lucamae** [comment] 2023-05-25 22:22
Hi, I have exaclty the same issue with Samsung. Does someone have updates about the reason of this problem and/or a solution?

**Comment by Divraj-Dev** [comment] 2023-05-25 22:25
Hi @lucamae . I ended up changing to NimBLE for my Bluetooth stack and keeping my espidf updated (Currently on 5.0.2). Not sure what fixed it for me
