### ISSUE TITLE
Not able to auto-reconnect with Azure Cloud (IDFGH-7184)

### ISSUE THREAD

**Issue by harshalbhav** [espressif/esp-idf#8783] opened 2022-04-16 07:28 UTC
## Environment

- Development Kit:      ESP32-Wrover-Kit and Other
- Kit version (for WroverKit/PicoKit/DevKitC): 
- Module or chip used:  ESP32-WROOM-32D
- IDF version (run ``git describe --tags`` to find it):
    // v4.4
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE?: No
- Power Supply:         USB and external 3.3

## Problem Description

We have developed one hardware based on ESP32. We are using Azue-SDK for same development. We enabled debug flag for Azure-SDK so we are receiving all debug logs on console. 

Right now we are facing issue with Azure-SDK. We have received disconnect event from Azure stack. As per the Azure stack we are expecting following points in this scenario.
1. Azure cloud should be update the device status like Device is disconnected.
2. Device should be reconnect to the Azure cloud automatically.

We are not able to full fill above both points. So, our Device and Azure cloud not able to get into valid state. 

Please update us how to drive this thing.

Thanks,
Harshal

### Expected Behavior
1. Azure cloud should be update the device status like Device is disconnected.
2. Device should be reconnect to the Azure cloud automatically.

Confirmation[346] received for message tracking id = 346 with result = IOTHUB_CLIENT_CONFIRMATION_OK
-> 06:26:46 DISCONNECT
Connection Status result: IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Connection Status reason: IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN

******* SAS TOKEN EXPIRE RECEIVED **********

-> 06:26:49 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: .... | PWD: XXXX | CLEAN: 0

<- 06:26:49 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0

### Actual Behavior
1. Azure cloud not getting Device status as its disconnected.
2. Device is not able to reconnect with Azure cloud. (We had wait till 5 to 8 min)

Confirmation[346] received for message tracking id = 346 with result = IOTHUB_CLIENT_CONFIRMATION_OK
-> 06:26:46 DISCONNECT
Connection Status result: IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, Connection Status reason: IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN

******* SAS TOKEN EXPIRE RECEIVED **********
.
.
.

### Steps to reproduce

No any particular step we observed.

**Comment by Alvin1Zhang** [comment] 2022-04-18 06:00
Duplicate of https://github.com/espressif/esp-azure/issues/126, close this one and tracked in esp-azure issue tracker. Thanks.

**Closed by Alvin1Zhang** 2022-04-18 06:00 UTC
Labels: Status: Done, Resolution: Duplicate
