### ISSUE TITLE
[Discussion] Remove the support of ADC2 digital controller on ESP32-S3 and ESP32-C3 (IDFGH-8691)

### ISSUE THREAD

**Issue by ginkgm** [espressif/esp-idf#10135] opened 2022-11-08 09:37 UTC
Due to the hardware limitation of ESP32-S3 and ESP32-C3 (See errata: [S3 section 1.1](https://www.espressif.com/sites/default/files/documentation/esp32-s3_errata_cn.pdf), [C3 section 1.1](https://www.espressif.com/sites/default/files/documentation/esp32-c3_errata_en.pdf)), we plan to remove the support for ADC2 in IDF drivers.

Affected:

- For S3, the digital controller (ADC-DMA) can't be used with ADC2, while you are still able to use ADC2 with RTC controller (one-shot).
- For C3, the ADC2 can't be used at all, because both one-shot and ADC-DMA are realized by digital controller.

For more details and questions, please contact sales@espressif.com.

We would like to adjust IDF drivers as follows:

- Print error and directly return from all the path that may make use of the digital controller with ADC2. 
- If user insist on using it, turn on a Kconfig option. Then the driver will print warning and continue working. (As a back-compatible approach). In this case, user is on their own risk.

Suggestions are welcome.

**Comment by bbinet** [comment] 2023-02-22 15:04
Could you please explain in more details what's wrong with ADC2?
As we currently have boards for which GPIO05 is hardwired to measure external analog voltage, what is the actual risk if we continue to use ADC2 using CONFIG_ADC_ONESHOT_FORCE_USE_ADC2_ON_C3 option? 
Until now, we do not experience any issue with ADC2 here, and we would prefer to avoid a hardware redesign of the board...

**Comment by bbinet** [comment] 2023-02-23 10:16
Ok, so the only risk is to get some wrong values (raw value equals 0) from time to time?
So I could ignore values which equals 0, and I'll be fine, right?

**Comment by Icarus113** [comment] 2023-02-24 06:22
Hi, @bbinet , the 0 result is just one of the potential issues, it appears on some chips. Generally speaking, the result isn't reliable. 

> So I could ignore values which equals 0, and I'll be fine, right?

I would say no. We can't guarantee other results are correct.

**Comment by bbinet** [comment] 2023-02-24 13:30
Thank you @Icarus113 for this information.

**Comment by Icarus113** [comment] 2023-03-27 11:16
Hi watchers, the code changes for this issue have been merged in to all related releases.

If there's no other comments, I'm gonna close this issue in 1 day.

**Closed** 2023-03-29 02:14 UTC
Labels: Type: Feature Request, Status: Done, Resolution: Done

**Comment by moefear85** [comment] 2023-07-02 16:49
so what this means is, if continuous sampling adc1 and adc2 simultaneously, then even if sampling starts fine... at any random moment, a spurious `sampling enable` may happen, that then causes the entire DMA controller to crash, hence making all read attempts after that fail?

If this is correct, then, if user code determines such a failed state has been entered, is it possible to simply reconfigure the adc and start over, or would it require a restart of the entire chip?

**Comment by Icarus113** [comment] 2023-07-03 11:46
> so what this means is, if continuous sampling adc1 and adc2 simultaneously, then even if sampling starts fine... at any random moment, a spurious sampling enable may happen, that then causes the entire DMA controller to crash, hence making all read attempts after that fail?

Actually I don't actually know if this will be one of the conditions. (I didn't meet such scenario yet).

> if user code determines such a failed state has been entered, is it possible to simply reconfigure the adc and start over, or would it require a restart of the entire chip?

The problem is that, there's no flag or similar thing that indicating issue happens. And you can't recover it by reconfigure adc or restart the whole chip. The issue is always there.

@moefear85

**Comment by moefear85** [comment] 2023-07-03 16:08
strange... either way please leave the functionality available if possible, ie don't deprecate it. I find it very useful and the results I'm getting seem fine. Hopefully it might be fixed in a future revision of the chip.

**Comment by devitalii** [comment] 2024-01-11 03:44
so, ok how do I actually use A5  analog pin under ADC1 ?
