### ISSUE TITLE
Mqtt set uri function doesn't set transport to ssl with uri being 'mqtts://' (IDFGH-523)

### ISSUE THREAD

**Issue by AadiMehta** [espressif/esp-idf#2870] opened 2018-12-23 05:03 UTC
## Problem Description

esp_mqtt_client_set_uri function doesn't work when uri is mqtts://

Following example doesn't work:
```
static esp_err_t mqtt_event_handler(esp_mqtt_event_handle_t event) {
}

const esp_mqtt_client_config_t mqtt_cfg = {
        .event_handle = mqtt_event_handler,
        .transport = MQTT_TRANSPORT_OVER_SSL,
	.username = "username",
	.password = "password",
};

void main() {
    char mqtt_url[] = "mqtts://iot.eclipse.org:8883"
    esp_mqtt_client_handle_t mqtt_client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_set_uri(mqtt_client, mqtt_url);
    esp_mqtt_client_start(mqtt_client);
}
```

Above example only works if ".transport = MQTT_TRANSPORT_OVER_SSL," is added over mqtt_cfg.

**Comment by david-cermak** [comment] 2018-12-23 19:58
Hi @AadiMehta 

Thanks for reporting this issue. 

The issue is that if transport is not (statically) selected upon `esp_mqtt_client_init`, mqtt library sets "mqtt" (over tcp) as default scheme and it is used in further library use.
This can be easily fixed by removing the below lines in function `esp_mqtt_client_init(..)` in module `mqtt_client.c`:
```
    if (client->config->scheme == NULL) {
        client->config->scheme = create_string("mqtt", 4);
        ESP_MEM_CHECK(TAG, client->config->scheme, goto _mqtt_init_failed);
    }
```

We will check if this change does not break anything else and go ahead with the fix.

**Closed** 2019-03-27 14:08 UTC
