### ISSUE TITLE
2 Units with W5500 dont work (IDFGH-13462)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#14364] opened 2024-08-14 09:09 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

@david-cermak 

        0x02, 0x00, 0x00, 0x12, 0x34, 0x56

https://github.com/espressif/esp-idf/blob/e8bdaf91986a41678adc6be13888fc037b1acb68/examples/common_components/protocol_examples_common/connect.c#L450

this is bad, when one wants to run e.g. the MODBUS-TCP Example. 

the 2 Units get the same IP Address from the Router. 

Search-Hints: 

`esp_eth.netif.netif_glue: 02:00:00:12:34:56`

**Comment by kostaond** [comment] 2024-08-16 06:44
The problem is the SPI ETH modules don't have MAC address burned. Therefore it's set by SW, that's basically the snipped you sent. Your problem is that two devices have the same MAC address. You can address it in similar way how it's done in [`basic` example](https://github.com/espressif/esp-idf/blob/master/examples/ethernet/basic/components/ethernet_init/ethernet_init.c#L272-L292).

**Comment by diplfranzhoepfinger** [comment] 2024-08-21 22:03
YES, this is true. 
it should be added to all Ethernet Examples.

**Comment by kostaond** [comment] 2024-08-22 07:17
It doesn't have to be part of [eth_connect.c](https://github.com/espressif/esp-idf/blob/master/examples/common_components/protocol_examples_common/eth_connect.c) since this particular example initializes only one SPI Ethernet device. Setting unique MAC addresses for both devices is already present in `basic` example and in [Ethernet init](https://github.com/espressif/esp-eth-drivers/tree/master/ethernet_init) component. The only thing which could be considered is to use Ethernet init component in Protocols examples. However, that would require redesign of protocols examples which I don't think is intended. The goal of these examples is to demonstrate simple usage of multiple protocols over single interface. Introducing support of multiple interfaces would increase complexity of those examples. For that reason, I'm closing the issue.

**Closed by kostaond** 2024-08-22 07:17 UTC
Labels: Status: Opened

**Comment by diplfranzhoepfinger** [comment] 2024-08-22 07:28
No, the Topic is e.g. Modbus TCP Example. 
it is not about multiple Interfaces. it is about 2 or more ESP32 in 1 Network. 
the Samples are not running out of the Box.

**Comment by kostaond** [comment] 2024-08-22 07:43
I see. This fix is already there. It just needs to be released, see https://github.com/espressif/esp-idf/blob/release/v5.3/examples/common_components/protocol_examples_common/eth_connect.c#L161
