### ISSUE TITLE
Using RS485 from M5 Stack (IDFGH-13043)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#13989] opened 2024-06-15 20:07 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi. 

M5 Stack used quite different pinout:

See ESP-IDF 
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart/uart_echo_rs485

https://github.com/espressif/esp-idf/tree/master/examples/protocols/modbus/serial/mb_master

new Information: 
https://docs.espressif.com/projects/esp-idf/en/release-v5.3/esp32s3/api-reference/peripherals/uart.html

Compare to M5 Stack:

https://docs.m5stack.com/en/base/lan_poe_v12

https://static-cdn.m5stack.com/resource/docs/products/base/lan_poe_v12/lan_poe_v12_sch_04.webp

Main difference is the number of line to the ESP32 2 vs. 3

Any help?

Can this HW be used with ESP-IDF modbus?

Or better let M5 design new Boards?

They belong to you:

https://www.espressif.com/en/news/Espressif_Acquires_M5Stack

**Comment by nopnop2002** [comment] 2024-06-15 22:22
There are no restrictions on GPIO used with ESP-IDF's UART.
You can use any pin you like on M5STACK.

**Comment by diplfranzhoepfinger** [comment] 2024-06-16 13:02
> There are no restrictions on GPIO used with ESP-IDF's UART. You can use any pin you like on M5STACK.

set RTS to -1 then ?

**Comment by diplfranzhoepfinger** [comment] 2024-06-16 15:37
i made a Test Setup: 

use the 2 PCBs from https://static-cdn.m5stack.com/resource/docs/products/base/lan_poe_v12/lan_poe_v12_sch_03.webp

with this code: 
https://github.com/DiplomInformatikerFranzHoepfinger/m5stack-modbus/tree/rs-232-ok


and it works. 
Log: https://gist.github.com/diplfranzhoepfinger/6a896cf1cc1dba1e8d0bf36eb6e328e4

**Comment by diplfranzhoepfinger** [comment] 2024-06-16 15:45
same Software, using RS-485 PCB: 

https://gist.github.com/diplfranzhoepfinger/ff6ec398b999edde3b6ee178f1f6be2c

does not work.

**Comment by diplfranzhoepfinger** [comment] 2024-06-18 19:23
https://community.m5stack.com/topic/306/plc-module/12?_=1718738548748

**Comment by diplfranzhoepfinger** [comment] 2024-06-18 19:24
I now made a own PCB for M5 Stack: 

with a correct wired RS-485, 
also Chip which has Dual Volt: 

![image](https://github.com/espressif/esp-idf/assets/37779037/aaa8db2c-df1e-463f-85fd-82bf40736816)

**Comment by alisitsyn** [comment] 2024-07-25 08:49
Hi @diplfranzhoepfinger,

Could you update with the results of investigation? The schematic above should work just fine with esp32 driver in half duplex mode. Please let me know if you still have any issues. Thanks.

**Comment by diplfranzhoepfinger** [comment] 2024-07-25 08:52
I am just ordering PCBs this day.

**Comment by alisitsyn** [comment] 2024-07-25 08:53
Ok, thank you for update. Please let me know once you have results. Thanks.

**Comment by diplfranzhoepfinger** [comment] 2024-08-13 07:29
Hi, 

i made EAGLE Files public here: 
https://github.com/Fliegl-Agrartechnik-GmbH/M5_COMMS

the PCBs should arrive tomorrow, i will post you the Results then. 

Thanks,
Franz

**Comment by franzhoepfinger** [comment] 2024-08-14 13:28
got the Boards today: 

1. MAX3485, is a Fully 3.3V RS-485 Transceiver
<img src="https://github.com/user-attachments/assets/df20ec8f-62f4-41ff-aea9-63415f9ed6cb" width="400" height="400">

2. LTC2877IMSE, is a 5V RS-485 Transceiver with a VIO Pin, so can interface to a 3.3V and even 1.8 V MCU
<img src="https://github.com/user-attachments/assets/84ce737d-b0ee-4c55-b311-826991d22512" width="400" height="400">


3. MAX485 is a 5V only Transceiver, using the Schottky Diode to not damage the ESP32 at RX.
<img src="https://github.com/user-attachments/assets/67820d9d-fa34-4c29-a037-ff9f005b1057" width="400" height="400">


4. CAN-Bus with a Infineon Transceiver
<img src="https://github.com/user-attachments/assets/2f8137bf-8ed6-4aaf-af31-53aff309fcd3" width="400" height="400">

**Comment by alisitsyn** [comment] 2024-08-14 14:00
@franzhoepfinger,

The boards look nice. However, I would recommend galvanic isolation on the RS485 interface. This would allow to solve many of possible issues in future. The chips like TI ISO1500, Analog Devices ADM2485, work good. Probably this suggestion is not for your project.
Looking forward to get some test results with ESP32 for these chips. Just because some users reported issues with the SP3485 chip for example connected to ESP32. I personally could not check it on my side and do not expect any issues with the selected chips.

Thanks.

**Comment by franzhoepfinger** [comment] 2024-08-16 10:06
> Hi @franzhoepfinger,
> 
> The boards look nice. However, I would recommend galvanic isolation on the RS485 interface.

i did share this meaning a long time, say years, unless i realized that most people do not understand it. 
if the Device provide galvanic isolation and the Electrican connects the GND to the common GND, all isolation is fully gone. 

so, yes, isolation is cool, but all circumstances must support it wisely. 

> This would allow to solve many of possible issues in future. The chips like TI ISO1500, Analog Devices ADM2485, work good. Probably this suggestion is not for your project. Looking forward to get some test results with ESP32 for these chips. 

> Just because some users reported issues with the SP3485 chip for example connected to ESP32. 

> I personally could not check it on my side and do not expect any issues with the selected chips.

this here is manly about the Connection 3 Wire vs. 2wire from Chip to ESP32, 
because the Boards from M5Stack @m5stack seem really not working. 

> 
> Thanks.

**Comment by alisitsyn** [comment] 2024-08-16 13:01
@franzhoepfinger,

> so, yes, isolation is cool, but all circumstances must support it wisely.

Agree.

> this here is manly about the Connection 3 Wire vs. 2wire from Chip to ESP32,
because the Boards from M5Stack https://github.com/m5stack seem really not working.

Sorry, I did not understand why the RS485 board from M5 Stack with 2 wire connection (auto switching of direction) does not work with ESP32 on your side. If it is, the reason for this should be found.

![image](https://github.com/user-attachments/assets/cf3ab219-4718-4383-926c-5d8e2d17845e)

It should work just fine and it is [recommended](https://docs.espressif.com/projects/esp-idf/en/v4.3.2/esp32/api-reference/peripherals/uart.html#circuit-c-auto-switching-transmitter-receiver) and tested variant except the chip is different.
It does not matter which connection type is used for ESP32 3 or 2 wire, both are supported and tested. With the 3-wire variant the difference is that driver is controlled from the TX line and differential high level on output is set by the pull-up(pull_down) resisters (RTS is not used for driver control). I remember that long time ago I was able to verify your M5 adapter board with the schematic as above and it was working just fine with ESP32.

Please let me know if I miss something.

**Comment by diplfranzhoepfinger** [comment] 2024-08-17 10:06
also visible in IDF 5.3
https://docs.espressif.com/projects/esp-idf/en/release-v5.3/esp32s3/api-reference/peripherals/uart.html

must make more Tests. 
for sure i did not set this Bits.

**Comment by franzhoepfinger** [comment] 2024-08-17 11:07
next bad thing: 
how to set these Bits.

**Comment by franzhoepfinger** [comment] 2024-08-17 11:20
it is working as well, Circuit C: 
https://github.com/Fliegl-Agrartechnik-GmbH/uart_echo_rs485/tree/feature/Circuit-C

the Signals using the M5 Board are not as clean as using the other 3 Boards, especcially the Mid-Voltage is offset a lot. (2V Mid, while Max Voltage of B Channel is about 4.6V, and Min of A Channel 0.35V

but other than this the Echo App is working fine so far ...

**Comment by franzhoepfinger** [comment] 2024-08-17 11:47
Next Problem: 
https://github.com/espressif/esp-idf/tree/master/examples/protocols/modbus/serial/mb_master

cannot set RTS to -1 by SDKCONFIG

**Comment by diplfranzhoepfinger** [comment] 2024-08-17 19:03
> Hi @franzhoepfinger,
> 
> The boards look nice. However, I would recommend galvanic isolation on the RS485 interface. 

https://docs.m5stack.com/en/module/Module13.2-PwrCAN

M5 seems to have a isolated one now.

**Comment by alisitsyn** [comment] 2024-08-19 08:06
@franzhoepfinger,

> should have hints about this. they only show Circuit B.

The example shows just the recommended type of connection, which is `Circuit B`. All possible variants are supported by UART driver and explained on its page and responsibility of user. However, I agree it worth to add at least the link to the documentation related to UART driver options where all these variants and options are explained. 

> cannot set RTS to -1 by SDKCONFIG

Yes, this is because the original example designed to use the recommended type of connection which is `Circuit A` or `Circuit B` as showed on the connection diagram. The "-1" can be changed in the source code in this case or just keep it as is and do not connect the RTS pin at all. I will try to address this later.

> (2V Mid, while Max Voltage of B Channel is about 4.6V, and Min of A Channel 0.35V 
but other than this the Echo App is working fine so far ...

Is not excellent but can work. Could you send the picture from oscilloscope for more details? If it is possible. 


> next bad thing: how to set these Bits.

If you are talking about the UART register bits, you do not need to set it manually (the information there is just for reference). The UART driver will take care of it. What you need is to install driver and set communication options for RS485 HALF DUPLEX. The driver will do the rest. For variant C of connection it does not matter which mode is used (PURE UART communication or HALF DUPLEX). However, it is better to set the RTS to "-1" to free the GPIO for other purposes.

```c
ESP_ERROR_CHECK(uart_driver_install(uart_num, BUF_SIZE * 2, 0, 0, NULL, 0));

    // Configure UART parameters
    ESP_ERROR_CHECK(uart_param_config(uart_num, &uart_config));

    ESP_LOGI(TAG, "UART set pins, mode and install driver.");

    // Set UART pins as per KConfig settings (The ECHO_TEST_RTS needs to be set manually to -1, to be fixed.)
    ESP_ERROR_CHECK(uart_set_pin(uart_num, ECHO_TEST_TXD, ECHO_TEST_RXD,  -1, ECHO_TEST_CTS));

    // Set RS485 half duplex mode (Note: is not required for variant C of RS485 connection. This line can be kept or removed.)
    // ESP_ERROR_CHECK(uart_set_mode(uart_num, UART_MODE_RS485_HALF_DUPLEX));

    // Set read timeout of UART TOUT feature
    ESP_ERROR_CHECK(uart_set_rx_timeout(uart_num, ECHO_READ_TOUT));
```

> M5 seems to have a isolated one now.

Thanks for the link. I see it now. So, the ISO_5V should come from isolated power supply `DC 050 connector` on user side, otherwise this is useless.

Thank you for your comments and will try to address them a bit later.

**Comment by diplfranzhoepfinger** [comment] 2024-08-19 10:46
> @franzhoepfinger,
> 
> > should have hints about this. they only show Circuit B.
> 

true. for Circuit C i used the M5 Stack PCBs. 




> The example shows just the recommended type of connection, which is `Circuit B`. All possible variants are supported by UART driver and explained on its page and responsibility of user. However, I agree it worth to add at least the link to the documentation related to UART driver options where all these variants and options are explained.
> 
> > cannot set RTS to -1 by SDKCONFIG
> 
> Yes, this is because the original example designed to use the recommended type of connection which is `Circuit A` or `Circuit B` as showed on the connection diagram. The "-1" can be changed in the source code in this case or just keep it as is and do not connect the RTS pin at all. I will try to address this later.

i did edit it, and it is working. 



> 
> > (2V Mid, while Max Voltage of B Channel is about 4.6V, and Min of A Channel 0.35V
> > but other than this the Echo App is working fine so far ...
> 
> Is not excellent but can work. Could you send the picture from oscilloscope for more details? If it is possible.


YES, i will share it, already captured all these pics.

**Comment by diplfranzhoepfinger** [comment] 2024-08-19 10:47
true. 

so you can set Circuit B this way: 



```c
    // Set RS485 half duplex mode
    ESP_ERROR_CHECK(uart_set_mode(UART_NUM_1, UART_MODE_RS485_HALF_DUPLEX));
```

and Circuit A this way: 

```c
    // Set RS485 collision detection UART mode
    ESP_ERROR_CHECK(uart_set_mode(UART_NUM_1, UART_MODE_RS485_COLLISION_DETECT));
```

**Comment by diplfranzhoepfinger** [comment] 2024-08-19 10:50
> > M5 seems to have a isolated one now.
> 
> Thanks for the link. I see it now. So, the ISO\_5V should come from isolated power supply `DC 050 connector` on user side, otherwise this is useless. Ah, I see the isolated power over U4 F0505S now.

true, but again: if you sell the Devices, to my Experience many Customers just Bridge the 2 GNDs, and all isolation is useless. 

so, need to sell traingins as well, otherwise no benefit.

**Comment by alisitsyn** [comment] 2024-08-30 13:07
@diplfranzhoepfinger,

Is your issue addressed? Can this ticket be closed? 
Your other comments about stack are addressed separately and merged.

**Comment by alisitsyn** [comment] 2024-09-04 09:22
The issue is closed. Feel free to reopen.

**Closed by alisitsyn** 2024-09-04 09:22 UTC
Labels: Status: Opened

**Comment by diplfranzhoepfinger** [comment] 2024-09-04 11:36
> @diplfranzhoepfinger,
> 
> Is your issue addressed? Can this ticket be closed? Your other comments about stack are addressed separately and merged.

YES, can be closed for now. 
i have all RS-485 Stuff running. 

Problems which are left are in the BSP Repo, mainly Display and Ethernet.

**Comment by alisitsyn** [comment] 2024-09-04 12:21
@diplfranzhoepfinger,

Thank you for update. 

> YES, can be closed for now.
i have all RS-485 Stuff running.

If it is possible please share the communication diagrams for your boards. They might be useful to determine some aspects related to different chips.

>  Problems which are left are in the BSP Repo, mainly Display and Ethernet.

Please submit the separate tickets for these components.

**Comment by diplfranzhoepfinger** [comment] 2024-09-04 13:24
![SDS00001](https://github.com/user-attachments/assets/a3fd9178-608b-4910-ab3e-387182444a02)
![SDS00002](https://github.com/user-attachments/assets/d357d53a-2787-49fb-ac22-224893ce0083)
![SDS00003](https://github.com/user-attachments/assets/99c20a92-e21c-4d8c-bbe2-6c5cecb9ac75)
![SDS00004](https://github.com/user-attachments/assets/f71ea4f7-09e3-49b5-b969-d46179888c3d)
![SDS00005](https://github.com/user-attachments/assets/a1d5e5f1-3571-4518-9a05-fbc21da3e77a)
![SDS00006](https://github.com/user-attachments/assets/3739ec87-96ff-4324-bd0c-c72a7d8cb355)
![SDS00007](https://github.com/user-attachments/assets/59eefa87-29eb-40d6-9f8b-addefc38cef0)
![SDS00008](https://github.com/user-attachments/assets/256b2fd4-885c-4e0b-940d-30bfcb60ad7e)
![SDS00009](https://github.com/user-attachments/assets/7cf965eb-c209-4318-9128-9076cbe804f2)
![SDS00010](https://github.com/user-attachments/assets/74edaa51-a1f0-4f0c-a7fa-3db767a50e9e)
![SDS00011](https://github.com/user-attachments/assets/e7df2ea1-5ca5-47f6-9a6c-3e7b60089a97)
![SDS00012](https://github.com/user-attachments/assets/5ab01b11-b7ec-4ed6-a9af-edd565090f5c)
![SDS00013](https://github.com/user-attachments/assets/467aba0f-cbdb-484a-b03c-d2118abd1daa)
![SDS00014](https://github.com/user-attachments/assets/c5ccc9db-cc24-4fa4-9023-406f11eb52cf)
![SDS00015](https://github.com/user-attachments/assets/ea80795e-1d45-48c5-834a-ea3364a44752)
![SDS00016](https://github.com/user-attachments/assets/7eae18a0-0f9f-460c-bbc8-539408d51aab)
![SDS00017](https://github.com/user-attachments/assets/720d28a1-8121-4069-b7a3-99b4bb8dc949)
![SDS00018](https://github.com/user-attachments/assets/29f6e173-750b-4eee-938a-094ebc9b0472)
![SDS00019](https://github.com/user-attachments/assets/65d22a4a-bf4a-4ca6-bac3-f766844caed5)
![SDS00020](https://github.com/user-attachments/assets/247bb264-a85d-409d-b3f0-35f332953dff)
![SDS00021](https://github.com/user-attachments/assets/95335a8a-b454-4a56-b3f1-5c799ce4be55)
![SDS00022](https://github.com/user-attachments/assets/8ea5a580-4a11-4da2-8976-69f16cd5ab05)
![SDS00023](https://github.com/user-attachments/assets/95e3e4fa-a129-4710-a17c-87b5c6b3a702)
![SDS00024](https://github.com/user-attachments/assets/26eeacd7-43b4-41ab-8c33-d6461067871a)
![SDS00025](https://github.com/user-attachments/assets/99431d2b-4785-44e8-a0c6-195d2d1162ee)
![SDS00026](https://github.com/user-attachments/assets/384efa7f-b21e-47a0-88d4-178bed435342)
![SDS00027](https://github.com/user-attachments/assets/03688c08-e438-4701-a0ee-d799ff9317bf)
![SDS00028](https://github.com/user-attachments/assets/3bccf502-7901-41a7-bfef-eb12bab7c3fc)
![SDS00029](https://github.com/user-attachments/assets/80732e28-24a4-4277-8a13-60e2a6de103f)
![SDS00030](https://github.com/user-attachments/assets/957de0e8-033a-4ad4-b6f6-f3aa0f092b20)
![SDS00031](https://github.com/user-attachments/assets/8cd17a99-34b6-4dd1-933d-f73a343ec640)
![SDS00032](https://github.com/user-attachments/assets/e9a87453-7d3b-442b-97a5-8591ee0fc997)
![SDS00033](https://github.com/user-attachments/assets/7dd643d9-5b2b-4130-a8d5-423752966b31)
![SDS00034](https://github.com/user-attachments/assets/816a57a4-6b57-4ab5-84f6-2737a3353b14)
![SDS00035](https://github.com/user-attachments/assets/ab59851e-7b88-40c3-bb40-ec95eae583b6)
![SDS00036](https://github.com/user-attachments/assets/dc5f5136-514a-474d-81ec-3d1ffc346d96)
![SDS00037](https://github.com/user-attachments/assets/aa9785d6-e07e-4e5d-8fdc-26e7d0fe170b)
![SDS00038](https://github.com/user-attachments/assets/a9403f22-18e1-4936-bb62-198fa413361d)
![SDS00039](https://github.com/user-attachments/assets/cc687e11-7371-4dcd-b222-2b2108d6e16d)
![SDS00040](https://github.com/user-attachments/assets/c0be4740-546c-40b6-90cb-10f416e95e75)
![SDS00041](https://github.com/user-attachments/assets/ec84252c-3c71-43b8-937d-8e03ade8c146)
![SDS00042](https://github.com/user-attachments/assets/26d49f36-2432-4f1c-86ad-c92ba68510e6)
![SDS00043](https://github.com/user-attachments/assets/a4655615-2556-4096-be3b-c5e3b59a4e58)
![SDS00044](https://github.com/user-attachments/assets/0f46f9e4-7373-4810-8edd-3dc8ecc393ab)
![SDS00045](https://github.com/user-attachments/assets/11c63f5e-92e4-486d-8366-063274257881)
![SDS00046](https://github.com/user-attachments/assets/0416c36e-d33f-440e-ae1a-d2b83183ba46)
![SDS00047](https://github.com/user-attachments/assets/5b28f77d-8896-4afc-8a01-ed0019fa04ae)

**Comment by alisitsyn** [comment] 2024-09-04 13:49
> Descriptions missing, also the Version with the M5 Original PCB missing yet.

This is ok, I can guess  the missing aspects)
What I was interested in is to see the diagram for that original board with TX - RX connection (5V) and the  LTC2877 one with RTS (3.3V + 5V). No problem, the diagrams are still can be useful. 

Thanks again for sharing.
