### ISSUE TITLE
Socket connection delay after wifi connect (IDFGH-5987)

### ISSUE THREAD

**Issue by joncmaloney** [espressif/esp-idf#7673] opened 2021-10-11 05:52 UTC
## Environment

* Development Kit: ESP32\-C3\-DevKitC\-02\(v1\.1\) \| ESP32\-DevKit\-Lipo \(Rev\_A\)
* Module or chip used: ESP32\-WROOM\-32 \| ESP32\-c3WROOM\-02
* IDF version: v4.3.1
* Build System: idf.py
* Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
* Operating System: macOS
* Using an IDE?: No
* Power Supply: USB

## Problem Description

A large delay in the IP stack is experienced immediately after wifi connected. If we attempt a TCP connection or to transmit UDP packet immediately after <span class="colour" style="color:rgb(212, 212, 212)">IP\_EVENT\_STA\_GOT\_IP </span> there is a delay of aprox \~800ms before a TCP connection or UDP packet is transmitted.<span class="colour" style="color:rgb(212, 212, 212)"> </span>

### Expected Behavior

* TCP connection expected to be established in <40ms immediately after <span class="colour" style="color:rgb(212, 212, 212)">IP\_EVENT\_STA\_GOT\_IP</span>.
* UDP packet TX \~3ms immediately after <span class="colour" style="color:rgb(212, 212, 212)">IP\_EVENT\_STA\_GOT\_IP</span>.

### Actual Behavior

* TCP connection takes \~800ms before connection is established.
* UDP packet TX \~800ms after <span class="colour" style="color:rgb(212, 212, 212)">IP\_EVENT\_STA\_GOT\_IP</span>.

## Steps to reproduce TCP scenario

1. Using example code $IDF\_PATH/examples/protocols/sockets/tcp\_client
2. Replace code with [tcp\_client.c](https://gist.github.com/joncmaloney/f6bca240468097ec6a798f4534a0073c).
3. Run python example\_test.py IPv4
4. idf.py menuconfig -> update SSID, PWD, IP\_ADDR
5. idf.py build flash monitor

### Code to reproduce this issue

gist link: [tcp\_client.c](https://gist.github.com/joncmaloney/f6bca240468097ec6a798f4534a0073c)

### Debug Logs

><Startup debug logs (removed for brevity)>

>I (723) TCP Client: Wifi connected - @ 270ms
I (723) TCP Client: Socket created, connecting to 10.212.11.10:3333
I (1343) TCP Client: TCP socket connected - @ 890ms, <span class="colour" style="color:#ff6647">**delay: 620ms**</span>
I (1353) TCP Client: Received @ 900ms - 23 bytes from 10.212.11.10:
I (1353) TCP Client: OK: Message from ESP32 
I (6543) TCP Client: Wifi connected - @ 150ms
I (6543) TCP Client: Socket created, connecting to 10.212.11.10:3333
I (7353) TCP Client: TCP socket connected - @ 960ms, <span class="colour" style="color:#ff6647">**delay: 810ms**</span>
I (7363) TCP Client: Received @ 970ms - 23 bytes from 10.212.11.10:
I (7363) TCP Client: OK: Message from ESP32 
I (12593) TCP Client: Wifi connected - @ 150ms
I (12593) TCP Client: Socket created, connecting to 10.212.11.10:3333
I (13343) TCP Client: TCP socket connected - @ 900ms, <span class="colour" style="color:#ff6647">**delay: 740ms**</span>
I (13353) TCP Client: Received @ 910ms - 23 bytes from 10.212.11.10:
I (13353) TCP Client: OK: Message from ESP32

## Steps to reproduce UPD scenario

1. Using example code $IDF\_PATH/examples/protocols/sockets/udp\_client
2. Replace code with [udp\_client.c](https://gist.github.com/joncmaloney/a61a4e1831403f81ed51acdc405a6d2b).
3. Run python example\_test.py IPv4
4. idf.py menuconfig -> update SSID, PWD, IP\_ADDR
5. idf.py build flash monitor

### Code to reproduce this issue

gist link: [udp\_client.c](https://gist.github.com/joncmaloney/a61a4e1831403f81ed51acdc405a6d2b)

### Debug Logs

><Startup debug logs (removed for brevity)>

>I (732) UDP Client: Wifi connected - @ 280ms
I (732) UDP Client: Socket created, sending to 10.212.11.10:3333
I (732) UDP Client: Message sent
I (1342) UDP Client: Received @ 890ms - 23 bytes from: 10.212.11.10, <span class="colour" style="color:#ff6647">**delay: 610**</span>
I (1342) UDP Client: OK: Message from ESP32 
I (6532) UDP Client: Wifi connected - @ 150ms
I (6532) UDP Client: Socket created, sending to 10.212.11.10:3333
I (6532) UDP Client: Message sent
I (7342) UDP Client: Received @ 960ms - 23 bytes from: 10.212.11.10, <span class="colour" style="color:#ff6647">**delay: 810**</span>
I (7342) UDP Client: OK: Message from ESP32 
I (12532) UDP Client: Wifi connected - @ 150ms
I (12532) UDP Client: Socket created, sending to 10.212.11.10:3333
I (12532) UDP Client: Message sent
I (13342) UDP Client: Received @ 960ms - 23 bytes from: 10.212.11.10, <span class="colour" style="color:#ff6647">**delay: 810**</span>
I (13342) UDP Client: OK: Message from ESP32 
I (18552) UDP Client: Wifi connected - @ 170ms
I (18552) UDP Client: Socket created, sending to 10.212.11.10:3333
I (18552) UDP Client: Message sent
I (19342) UDP Client: Received @ 960ms - 23 bytes from: 10.212.11.10, <span class="colour" style="color:#ff6647">**delay: 790**</span>
I (19342) UDP Client: OK: Message from ESP3

**Comment by ESP-YJM** [comment] 2021-10-11 12:12
@joncmaloney I think the time is cost by arp. After getting the IP and before establishing TCP，will send arp packet. Could you try calucate time cost of the second tcp connection.

**Comment by ESP-YJM** [comment] 2021-10-21 06:24
@joncmaloney Can the problem be reproduced stably using this method? You can test several times, and also test the previous situation. Also you can capture the wifi packet to check.

**Comment by Alvin1Zhang** [comment] 2021-11-22 07:34
@joncmaloney Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by joncmaloney** [comment] 2021-11-23 00:12
Hi @ESP-YJM  and @Alvin1Zhang, 

Sorry for the delayed response. And thanks for the reminder about this. @ESP-YJM yes I am able to reproduce this problem with the above code every time. 

Using the above example (tcp_client.c.), i've been able to sniff 802.11 packets and simultaneously capture eth frames for both scenario's ( with / without ) 22ms delay between IP_EVENT_STA_GOT_IP event and creating a tcp socket. In these packet captures when the delay is not present I can see that ESP32 sends 2x Null function (No data) packets before sending actual data. This timestamps of the packet captures correlates with an observed delay to create TCP connection (this delay is aprox ~800ms). When vTaskDelay(pdMS_TO_TICKS(22)) is present the Null function (No data) packets are not preset (see wireshark captures below). 

Scenario 1. The esp32 is connecting via tcp to python server sending TCP packet on port 3333 via IPv4. There is no delay between the IP_EVENT_STA_GOT_IP event and creating a TCP connection. Below is a packet capture of 802.11 frames from this scenario. 
![image](https://user-images.githubusercontent.com/5607410/142952547-0bcaba56-cd64-4279-8e60-3c9659cfe474.png)

Below is further detail of the Null function (No data) packet from this capture. 
![image](https://user-images.githubusercontent.com/5607410/142952614-96c228dd-2b66-4bae-b325-d8128a5c0053.png)

Scenario 2. The esp32 is connecting via tcp to python server sending TCP packet on port 3333 via IPv4. There is a 22ms delay between the IP_EVENT_STA_GOT_IP event and creating a TCP connection. Below is a packet capture of 802.11 frames from this scenario. 
![image](https://user-images.githubusercontent.com/5607410/142952698-0ec60f5c-d723-4aa2-ad63-2cac8a702aef.png)

For further detail i've also captured eth frames from the same transactions. The ARP is completed within <100us in both cases and therefore doesn't contribute a delay of the order of magnitude 100's of ms. 

Below is a packet capture of eth frames of scenario 1. 
![image](https://user-images.githubusercontent.com/5607410/142953376-011c8982-3090-4625-a366-8598b905c00b.png)

The below is a packet capture of Scenario 2. 
![image](https://user-images.githubusercontent.com/5607410/142953331-f3ad81b1-9015-4646-8388-053fb6d953c9.png)

**Comment by ESP-YJM** [comment] 2021-11-23 02:34
@joncmaloney It seems the station enter in sleep mode, could you please try call `esp_wifi_set_ps(WIFI_PS_NONE)` before the function `esp_wifi_start()`.

**Comment by joncmaloney** [comment] 2021-11-23 03:59
Hi @ESP-YJM, 

I have added esp_wifi_set_ps(WIFI_PS_NONE) before the function esp_wifi_start(). We still observe the same delay ~800ms however we no longer observe Null function (No data) packets. See the wireshark trace of 802.11 packets. See below. 

![596E2161-5CAD-44AC-BF1C-8FF3C443FE77](https://user-images.githubusercontent.com/5607410/142969372-092cbcc2-4077-416e-96b6-e4d4030e1c99.png)

**Comment by ESP-YJM** [comment] 2021-11-23 07:20
@joncmaloney Could you please try add `esp_wifi_set_protocol(0, 3);` before `esp_wifi_start` to only enable b/g mode.

**Comment by joncmaloney** [comment] 2021-11-23 08:36
@ESP-YJM i've added sp_wifi_set_protocol(0, 3); before esp_wifi_start. This doesn't seem to affect the behaviour; the delay is still ~800ms.

**Comment by ESP-YJM** [comment] 2021-11-23 08:43
@joncmaloney I use your code and test, the delay in my environment is about 400-500 ms, but when i call `esp_wifi_set_protocol(0, 3)`, it reduces to 50-100 ms. And i also add delay in the code you point out, It seems that add delay in code can't reduce the delay time for me. Very strange. Could you please add follow patch and show your log to me. Thanks.
[print_tcp_data.zip](https://github.com/espressif/esp-idf/files/7586691/print_tcp_data.zip)

**Comment by joncmaloney** [comment] 2021-11-23 09:19
Hi @ESP-YJM I've applied the patch the log output after applying the patch is below. Also thank you so much for your assistance with this issue so far. 

```
I (146) spi_flash: detected chip: generic
I (147) spi_flash: flash io: dio
I (147) sleep: Configure to isolate all GPIO pins in sleep state
I (151) sleep: Enable automatic switching of GPIO sleep configuration
I (158) cpu_start: Starting scheduler.
I (174) pp: pp rom version: 9387209
I (175) net80211: net80211 rom version: 9387209
I (178) wifi:wifi driver task: 3fc9e288, prio:23, stack:6656, core=0
I (183) system_api: Base MAC address is not set
I (188) system_api: read default base MAC address from EFUSE
I (198) wifi:wifi firmware version: 88c8747
I (198) wifi:wifi certification version: v7.0
I (202) wifi:config NVS flash: enabled
I (206) wifi:config nano formating: disabled
I (210) wifi:Init data frame dynamic rx buffer num: 32
I (215) wifi:Init management frame dynamic rx buffer num: 32
I (220) wifi:Init management short buffer num: 32
I (225) wifi:Init dynamic tx buffer num: 32
I (228) wifi:Init static tx FG buffer num: 2
I (233) wifi:Init static rx buffer size: 1600
I (237) wifi:Init static rx buffer num: 10
I (240) wifi:Init dynamic rx buffer num: 32
I (245) wifi_init: rx ba win: 6
I (248) wifi_init: tcpip mbox: 32
I (252) wifi_init: udp mbox: 6
I (256) wifi_init: tcp mbox: 6
I (259) wifi_init: tcp tx win: 5744
I (264) wifi_init: tcp rx win: 5744
I (268) wifi_init: tcp mss: 1440
I (272) wifi_init: WiFi IRAM OP enabled
I (276) wifi_init: WiFi RX IRAM OP enabled
I (283) phy_init: phy_version 500,985899c,Apr 19 2021,16:05:08
I (549) TCP Client: Wifi connected - @ 267ms
I (550) TCP Client: Socket created, connecting to 10.212.11.10:3333
I (1174) TEST: @@ WiFi Tx TCP - L:44, S:3655749629, A:0, SP:63958, DP:3333, F:2
I (1176) TEST: @@ WiFi Rx TCP - L:44, S:2297431972, A:3655749630, SP:3333, DP:63958, F:12
I (1181) TEST: @@ WiFi Tx TCP - L:40, S:3655749630, A:2297431973, SP:63958, DP:3333, F:10
I (1190) TCP Client: TCP socket connected - @ 908ms, delay: 639ms
I (1196) TEST: @@ WiFi Tx TCP - L:59, S:3655749630, A:2297431973, SP:63958, DP:3333, F:18
I (1206) TEST: @@ WiFi Rx TCP - L:40, S:2297431973, A:3655749649, SP:3333, DP:63958, F:10
I (1214) TEST: @@ WiFi Rx TCP - L:63, S:2297431973, A:3655749649, SP:3333, DP:63958, F:18
I (1223) TEST: @@ WiFi Rx TCP - L:40, S:2297431996, A:3655749649, SP:3333, DP:63958, F:11
I (1232) TEST: @@ WiFi Tx TCP - L:40, S:3655749649, A:2297431997, SP:63958, DP:3333, F:10
I (1241) TCP Client: Received @ 959ms - 23 bytes from 10.212.11.10:
I (1247) TCP Client: OK: Message from ESP32 

I (1253) TEST: @@ WiFi Tx TCP - L:40, S:3655749649, A:2297431997, SP:63958, DP:3333, F:11
I (1264) TEST: @@ WiFi Tx TCP - L:40, S:3655749650, A:2297431997, SP:63958, DP:3333, F:14
I (6449) TCP Client: Wifi connected - @ 158ms
I (6450) TCP Client: Socket created, connecting to 10.212.11.10:3333
I (7176) TEST: @@ WiFi Tx TCP - L:44, S:1954321073, A:0, SP:63959, DP:3333, F:2
I (7178) TEST: @@ WiFi Rx TCP - L:44, S:1149719647, A:1954321074, SP:3333, DP:63959, F:12
I (7183) TEST: @@ WiFi Tx TCP - L:40, S:1954321074, A:1149719648, SP:63959, DP:3333, F:10
I (7191) TCP Client: TCP socket connected - @ 900ms, delay: 741ms
I (7198) TEST: @@ WiFi Tx TCP - L:59, S:1954321074, A:1149719648, SP:63959, DP:3333, F:18
I (7208) TEST: @@ WiFi Rx TCP - L:40, S:1149719648, A:1954321093, SP:3333, DP:63959, F:10
I (7215) TEST: @@ WiFi Rx TCP - L:63, S:1149719648, A:1954321093, SP:3333, DP:63959, F:18
I (7224) TEST: @@ WiFi Rx TCP - L:40, S:1149719671, A:1954321093, SP:3333, DP:63959, F:11
I (7234) TEST: @@ WiFi Tx TCP - L:40, S:1954321093, A:1149719672, SP:63959, DP:3333, F:10
I (7243) TCP Client: Received @ 952ms - 23 bytes from 10.212.11.10:
I (7249) TCP Client: OK: Message from ESP32 

I (7255) TEST: @@ WiFi Tx TCP - L:40, S:1954321093, A:1149719672, SP:63959, DP:3333, F:11
I (7265) TEST: @@ WiFi Tx TCP - L:40, S:1954321094, A:1149719672, SP:63959, DP:3333, F:14
I (12449) TCP Client: Wifi connected - @ 157ms
I (12450) TCP Client: Socket created, connecting to 10.212.11.10:3333
I (13174) TEST: @@ WiFi Tx TCP - L:44, S:2547778853, A:0, SP:63960, DP:3333, F:2
I (13176) TEST: @@ WiFi Rx TCP - L:44, S:3208237490, A:2547778854, SP:3333, DP:63960, F:12
I (13181) TEST: @@ WiFi Tx TCP - L:40, S:2547778854, A:3208237491, SP:63960, DP:3333, F:10
I (13190) TCP Client: TCP socket connected - @ 898ms, delay: 739ms
I (13197) TEST: @@ WiFi Tx TCP - L:59, S:2547778854, A:3208237491, SP:63960, DP:3333, F:18
I (13207) TEST: @@ WiFi Rx TCP - L:40, S:3208237491, A:2547778873, SP:3333, DP:63960, F:10
I (13214) TEST: @@ WiFi Rx TCP - L:63, S:3208237491, A:2547778873, SP:3333, DP:63960, F:18
I (13223) TEST: @@ WiFi Rx TCP - L:40, S:3208237514, A:2547778873, SP:3333, DP:63960, F:11
I (13233) TEST: @@ WiFi Tx TCP - L:40, S:2547778873, A:3208237515, SP:63960, DP:3333, F:10
I (13242) TCP Client: Received @ 950ms - 23 bytes from 10.212.11.10:
I (13248) TCP Client: OK: Message from ESP32 

I (13254) TEST: @@ WiFi Tx TCP - L:40, S:2547778873, A:3208237515, SP:63960, DP:3333, F:11
I (13264) TEST: @@ WiFi Tx TCP - L:40, S:2547778874, A:3208237515, SP:63960, DP:3333, F:14
```

**Comment by ESP-YJM** [comment] 2021-11-25 08:29
@joncmaloney Very sorry for the late reply. From the log, the time costs a lot when LWIP send TCP `SYN`. Could you please do a test that not disconnect the WIFI and only close the TCP socket and re-connect TCP. To check the second time or later, the time costs can reduce.

**Comment by joncmaloney** [comment] 2021-11-25 08:59
Hi @ESP-YJM, I can confirm that if the WIFI is not disconnected that the delay for creating TCP connection is only ~25ms. However our solution is a battery powered IOT sensor. To save battery we will deep sleep between sensor readings. Each time the sensor is read we will report the reading via WiFi. For simplicity to help troubleshooting, the above example tcp_client.c does not sleep instead just does a vTaskDelay(5000 / portTICK_PERIOD_MS).

**Comment by ESP-YJM** [comment] 2021-11-25 09:11
@joncmaloney I still doubt the time cost by arp. Could you please enable `CONFIG_LWIP_ETHARP_DEBUG=y` and share me the log or add static arp table with `etharp_add_static_entry` after set static IP address before connect TCP. To enable static arp table, you may add `#define ETHARP_SUPPORT_STATIC_ENTRIES 1` in lwipopts.h

**Comment by ESP-YJM** [comment] 2021-12-31 07:34
@joncmaloney Any update for this issue?

**Comment by Indastri** [comment] 2024-03-06 14:27
Closing the issue since there is no reply from the user. If the issue still persists feel free to reopen this or to create a new issue.

Cheers!

**Closed by Indastri** 2024-03-06 14:27 UTC
Labels: Awaiting Response, Status: Done, Resolution: NA
