### ISSUE TITLE
How to store panic handler cored dump information in esp-idf (IDFGH-5768)

### ISSUE THREAD

**Issue by dimpalsharm** [espressif/esp-idf#7476] opened 2021-08-26 14:49 UTC
Is there any implementation has been done in esp-idf to store the cored ump information in Flash ,if we change sdk config setting to flash like below snip.
![image](https://user-images.githubusercontent.com/89241509/130984611-f63af4f6-a850-47d6-8b00-5e42066313e4.png)

**Comment by dimpalsharm** [comment] 2021-08-30 09:04
![image](https://user-images.githubusercontent.com/89241509/131314805-62c610a2-3beb-4f84-b743-e094aa179ff8.png)

How we can read the Core dump data from flash after every powerup in ESP32 without using the below command.

![image](https://user-images.githubusercontent.com/89241509/131315040-d0a1a93d-71de-435b-a093-196966d65610.png)

**Comment by igrr** [comment] 2021-08-30 17:50
@dimpalsharm You can use `esp_partition` APIs to read the contents of core dump partition. Please see the answer to a similar question [here](https://github.com/espressif/esp-idf/issues/7283#issuecomment-882734395).

**Comment by dimpalsharm** [comment] 2021-08-31 06:54
Hi Team,

after using below command getting some data but right after that its getting crashed.

![image](https://user-images.githubusercontent.com/89241509/131456071-69667a5c-1365-427c-a00f-a71c75b976fd.png)

![image](https://user-images.githubusercontent.com/89241509/131456387-86309de6-4940-4e1b-a078-2e954497d1e0.png)

**Comment by igrr** [comment] 2021-09-15 13:15
Could you please attach the core dump file (location is in the Temp directory, noted after "Read partition 'coredump' contents..." line, plus the program ELF file (esp32_sample_app.elf)? We'll try to reproduce this issue.

**Comment by Alvin1Zhang** [comment] 2021-10-13 03:33
@dimpalsharm Thanks for reporting, would you please help share more information as suggested in https://github.com/espressif/esp-idf/issues/7476#issuecomment-920008837? Thanks.

**Comment by Alvin1Zhang** [comment] 2021-11-22 09:56
@dimpalsharm Thanks for reporting, would you please help share more information? Thanks.

**Comment by MarkEvens** [comment] 2022-06-06 05:43
@dimpalsharm  check this out I think it will help you.
[https://medium.com/@markevens36/esp-idf-core-dump-on-the-uart-store-to-flash-and-send-to-a-server-f84064d1af6f](url)

**Comment by igrr** [comment] 2022-09-29 20:54
I'm going to close this issue since there was no feedback.

**Closed by igrr** 2022-09-29 20:54 UTC
Labels: Type: Feature Request, Awaiting Response, Status: Opened
