### ISSUE TITLE
support for linux-arm64 (IDFGH-4663)

### ISSUE THREAD

**Issue by DJSundog** [espressif/esp-idf#6475] opened 2021-01-29 01:10 UTC
I have a number of ESP32-based boards that I'd like to develop against using my arm64-based linux systems.

Following the installation instructions for ESP-IDF results in an error that linux-arm64 isn't supported.

Examination of tools/tools.json shows that there are, indeed, no entries for linux-arm64, though the 32-bit linux-armel builds are there.

Is there something preventing linux-arm64 builds from being provided? The number of linux-arm64 systems in use is only going to increase now that Apple is releasing M1-based hardware.

**Comment by igrr** [comment] 2021-01-29 08:59
Hi @DJSundog, we will add arm64 build next time we release the toolchain. I can't give an exact timeline but most likely there will be a release in Q1. We are already tracking this in https://github.com/espressif/esp-idf/issues/6432, so I will close this issue. Please follow the link to that older issue and click "Subscribe" to get notified when the issue is resolved.

**Closed by igrr** 2021-01-29 08:59 UTC
Labels: Type: Feature Request

**Comment by axelcordes** [comment] 2021-08-28 20:52
Hey, do you now have a timeline for the next release? The feature is highly appreciated.
