### ISSUE TITLE
定时器扫描矩阵led 时出现闪烁问题！！紧急 (IDFGH-3658)

### ISSUE THREAD

**Issue by dgjeffrey123** [espressif/esp-idf#5593] opened 2020-07-15 01:01 UTC
我们在..\esp-idf\examples\bluetooth\bluedroid\ble\blufi 的例子上面创建一个定时器：

        esp_timer_handle_t fw_timer_handle = 0;

	esp_err_t err = esp_timer_create(&fw_timer, &fw_timer_handle);

	err = esp_timer_start_periodic(fw_timer_handle, 500);// 500us

	if(err == ESP_OK)

	{
	printf("fw timer cteate and start ok!\r\n");
	/* 创建一个开关检测任务 ,负责用户任务*/
	xTaskCreate(motor_task, "motor_task", 1024 *3, NULL, 3, NULL);// 

	}

extern void Led_Scan(void *arg);
esp_timer_create_args_t fw_timer =

{

.callback = &Led_Scan,// 矩阵LED 灯回调函数

.arg = NULL, //参数

.name = "fw_timer" //定时器名称

};

//矩阵LED控制函数  ,原理简图
/*       LED0   LED1  LED2  LED3  LED4  LED5
V1    
V0  
*/ 
 void Led_Scan(void *arg)
{
	uint8_t colNum = 0;
	uint16_t i = 0;
	for (i = 0; i < ROW_MAX_NUM; i++)                     //reset row
		gpio_set_level(ROW_SCAN_TAB[rowNum], 0);
	ets_delay_us(35);
	rowNum++;
	if (rowNum >= ROW_MAX_NUM)                           //scan row
	{
		rowNum = 0;
	}
	gpio_set_level(ROW_SCAN_TAB[rowNum], 1);

	for (colNum = 0; colNum < COL_MAX_NUM; colNum++)      //open col
	{
		if (led_data[rowNum][colNum] != 0)
		{
			gpio_set_level(COL_SCAN_TAB[colNum], 1);  //LED 设置高，亮

		}
		else
		{
			gpio_set_level(COL_SCAN_TAB[colNum], 0);//LED 设置低，灭
		}
	}
}

**Comment by Alvin1Zhang** [comment] 2020-07-15 01:47
This is a duplicate of https://github.com/espressif/esp-idf/issues/5594, will close this one and track in https://github.com/espressif/esp-idf/issues/5594. @dgjeffrey123 Thanks for reporting, please help try to keep updating in one ticket, thanks.

**Closed by Alvin1Zhang** 2020-07-15 01:47 UTC
