### ISSUE TITLE
Problems about flashing speed (IDFGH-7099)

### ISSUE THREAD

**Issue by NostalgistL00** [espressif/esp-idf#8708] opened 2022-04-02 15:25 UTC
My idf version is ESP-IDF v5.0-dev-2332-ge498209ed2 
I use esp-idf in WSL,and there's a problem whenflashing.
After I build my project through idf.py build,and try to flash with idf.py -p /dev/ttyS10 -b 921600 flash, it fails and output this :
================Start==================
esptool.py esp32 -p /dev/ttyS10 -b 921600 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x1000 bootloader/bootloader.bin 0x10000 hello-world.bin 0x8000 partition_table/partition-table.bin
esptool.py v3.3-dev
Serial port /dev/ttyS10
Connecting......................................

A fatal error occurred: Failed to connect to ESP32: Wrong boot mode detected (0x13)! The chip needs to be in download mode.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
CMake Error at run_serial_tool.cmake:55 (message):
/home/nostalgistl00/.espressif/python_env/idf5.0_py3.8_env/bin/python;;/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed

make[3]: *** [CMakeFiles/flash.dir/build.make:57: CMakeFiles/flash] Error 1
make[2]: *** [CMakeFiles/Makefile2:1951: CMakeFiles/flash.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1958: CMakeFiles/flash.dir/rule] Error 2
make: *** [Makefile:203: flash] Error 2
make failed with exit code 2
================End==================

i think maybe the baudrate is too high,and i change baudrate as default,it still failed,and output  this :
================Start==================
hello-world.bin binary size 0x29270 bytes. Smallest app partition is 0x100000 bytes. 0xd6d90 bytes (84%) free.
[100%] Built target app_check_size
[100%] Built target app
esptool.py esp32 -p /dev/ttyS10 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x1000 bootloader/bootloader.bin 0x10000 hello-world.bin 0x8000 partition_table/partition-table.bin
esptool.py v3.3-dev
Serial port /dev/ttyS10
Connecting.....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 08:3a:f2:51:01:c8
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Traceback (most recent call last):
  File "/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py", line 5347, in <module>
    _main()
  File "/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py", line 5340, in _main
    main()
  File "/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py", line 4762, in main
    esp.flash_set_parameters(flash_size_bytes(args.flash_size))
  File "/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py", line 1048, in flash_set_parameters
    self.check_command("set SPI params", ESP32ROM.ESP_SPI_SET_PARAMS,
  File "/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py", line 495, in check_command
    val, data = self.command(op, data, chk, timeout=timeout)
  File "/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py", line 468, in command
    p = self.read()
  File "/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py", line 413, in read
    return next(self._slip_reader)
StopIteration
CMake Error at run_serial_tool.cmake:55 (message):

  /home/nostalgistl00/.espressif/python_env/idf5.0_py3.8_env/bin/python;;/mnt/e/esp-idf-Linux/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed

make[3]: *** [CMakeFiles/flash.dir/build.make:57: CMakeFiles/flash] Error 1
make[2]: *** [CMakeFiles/Makefile2:1951: CMakeFiles/flash.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1958: CMakeFiles/flash.dir/rule] Error 2
make: *** [Makefile:203: flash] Error 2
make failed with exit code 2
================End==================

i think it;s still too high ,then i try 115200 with idf.py -p /dev/ttyS10 -b 115200 flashm,and it works,but it;s too slow for me.Then I tried find solution in programming guide in build system,i try to use esptool.py,
and here it is :

 esptool.py -p /dev/ttyS10 -b 921600 --before default_reset --after hard_reset --chip esp32  write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x1000 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin 0x10000 build/hello-world.bin

and it works with high speed,but i don;t understand why i can not use idf.py to flash the chip with high baudrate but have to use this long command,is there any solution to this?
thanks! :)

**Comment by dobairoland** [comment] 2022-04-04 05:23
Hi @NostalgistL00,

The first error message:
```
A fatal error occurred: Failed to connect to ESP32: Wrong boot mode detected (0x13)! The chip needs to be in download mode.
```
means that the chip could not be reseted into bootloader mode. (https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/entering-bootloader.html). The issue could be caused if possibly by the reset sequence is not propageted properly between Windows and WSL. One of the solutions could be to hold down the Boot button (GPIO0) during flashing.

The second error seems to me a duplicate of https://github.com/espressif/esp-idf/issues/4008.

I see that the flash size is different in the working command. You can try to set the proper value in `idf.py menuconfig` of your project.

Beside these observations, I don't think there is any difference between invoking `idf.py flash` and directly `esptool.py`.

**Closed by dobairoland** 2022-04-04 05:23 UTC
Labels: Status: Opened
