### ISSUE TITLE
[E][WiFiGeneric.cpp:1438] hostByName(): DNS Failed for (There's a net in the back that can't be recovered) (IDFGH-11412)

### ISSUE THREAD

**Issue by hzhh110** [espressif/esp-idf#12550] opened 2023-11-09 07:46 UTC
### Is your feature request related to a problem?

The problem can be easily repeated when trying wifi(password error) and network cable connection, as long as the problem occurs, it is basically impossible to recover

#define ETH_TYPE ETH_PHY_LAN8720
ETH.begin(ETH_ADDR, ETH_POWER_PIN, ETH_MDC_PIN, ETH_MDIO_PIN, ETH_TYPE, ETH_CLK_MODE);

**Comment by hzhh110** [comment] 2023-11-09 08:09
The network cable of the Internet connection router, after unplugging, many routers will also appear after this cannot be restored

**Comment by kostaond** [comment] 2023-11-10 14:26
@hzhh110 hi, thanks for reporting potential issue. However, you didn't specify your development environment and versions. It looks like Arduino so it would probably be better to report at [Arduino ESP32 repo](https://github.com/espressif/arduino-esp32).

Please also consider to rephrase the steps how to reproduce the issue. I'm note sure if I fully understand it. It could be just simple bullets like:
* Connect Ethernet cable
* Disconnect Ethernet cable
* Repeat X times
* Observe error "XY"

**Comment by me-no-dev** [comment] 2023-11-10 18:13
@kostaond feel free to close this issue. The user has opened a few on our end too. His problem is that DNS servers are global for client interfaces.

**Closed** 2023-11-13 07:14 UTC
Labels: Type: Feature Request, Status: Opened
