### ISSUE TITLE
error ompile  spi_bus_lock.c  (IDFGH-3147)

### ISSUE THREAD

**Issue by wuppergit** [espressif/esp-idf#5164] opened 2020-04-21 15:52 UTC
Compilation of spi_bus_lock.c throws  error:

error: implicit declaration of function 'xSemaphoreCreateBinaryStatic'; did you mean 'xSemaphoreCreateBinary'? [-Werror=implicit-function-declaration]

     g_spi_lock_main_flash_dev->semphr = xSemaphoreCreateBinaryStatic(&main_flash_semphr);

/esp/esp-idf/components/driver/spi_bus_lock.c:822:39: warning: assignment to 'SemaphoreHandle_t' {aka 'void *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
     g_spi_lock_main_flash_dev->semphr = xSemaphoreCreateBinaryStatic(&main_flash_semphr);

Changing to xSemaphoreCreateBinary doesn't work

**Comment by AxelLin** [comment] 2020-04-21 23:27
This was reported 3 weeks ago: https://github.com/espressif/esp-idf/issues/5046

**Comment by Alvin1Zhang** [comment] 2020-04-22 02:05
@AxelLin Thanks for the notes. @wuppergit Thanks for reporting, since the issue is same with https://github.com/espressif/esp-idf/issues/5046, will close this ticket, please help follow up on https://github.com/espressif/esp-idf/issues/5046. Thanks.

**Closed by Alvin1Zhang** 2020-04-22 02:05 UTC

**Comment by wuppergit** [comment] 2020-04-22 09:03
Thank' for the respond. It''s working fine.

Axel Lin <notifications@github.com> schrieb am Mi., 22. Apr. 2020 01:27:
