### ISSUE TITLE
2 files generated with the same name in spiffs (IDFGH-6514)

### ISSUE THREAD

**Issue by MaazSk** [espressif/esp-idf#8166] opened 2021-12-29 16:02 UTC
## Environment

- Development Kit:      [ESP32-DevKit]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32|]
- IDF version (run ``git describe --tags`` to find it): v4.3
   
- Compiler version : xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
  
- Operating System:     [Linux]

- Using an IDE?: [VS Code]
- Power Supply:         [USB]

## Problem Description

I am not pretty sure how this happened but I was trying to create log files in my system and after running for a long time there are 2 log files with the same name and I am unable to unlink them or delete them. As far as I know, this should not happen if there is already a file with the name a new file with the same name should not be created.

The files are as below
![Screenshot from 2021-12-29 21-24-51](https://user-images.githubusercontent.com/45138540/147680350-d0ac5db7-535e-4a2f-a699-019e3b6342cd.png)
You can see log_file_1.txt twice.

I have packed the spiffs image using mkspiffs with the following command
`./mkspiffs -c test -d 5 -b 4096 -p 256 -s 786432 spiffs.bin`

Please let me know if any more information is required

**Comment by RathiSonika** [comment] 2024-02-26 08:24
This issue is being closed as it has been mentioned [here](https://github.com/pellepl/spiffs/issues/22#issuecomment-1013323433) that the problem is not present. Please feel free to reopen or create a new issue if you encounter this problem again.

**Closed by RathiSonika** 2024-02-26 08:24 UTC
Labels: Status: Selected for Development
