### ISSUE TITLE
SD Card write speeds considerably slower under 5.0.1 vs 4.4. (IDFGH-9592)

### ISSUE THREAD

**Issue by polin-AL** [espressif/esp-idf#10940] opened 2023-03-07 21:07 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I'm in the process of updating a project from IDF 4.4 to 5.0.1., and we've noticed a considerable drop in SD write speeds. I wrote up a test, using the the SDSPI SD Card example project as a base. Exact same code, see below, with the following results, using a PNY 128GB Class 10 SD Card, and an ESP32-PICO-V3-02:

- ESP IDF 4.4 = I (2712) SdCardSPI: Test writing 976 kB in 2100 ms (465.03kB/s)
- ESP IDF 5.0.1 = I (161682) SdCardSPI: Test writing 976 kB in 158910 ms (6.15kB/s)

*charstring.c is just #define BASESTRING1000 1000 character randomized string.

```#include <string.h>
#include <errno.h>
#include <sys/unistd.h>
#include <sys/stat.h>
#include "esp_vfs_fat.h"
#include "sdmmc_cmd.h"
#include "charstring.c"

static const char *TAG = "SdCardSPI";

#define MOUNT_POINT "/sdcard"

// Pin mapping

/* works */
#define PIN_NUM_MISO 12
#define PIN_NUM_MOSI 13
#define PIN_NUM_CLK  14
#define PIN_NUM_CS   15

#define SPI_DMA_CHAN 1

void app_main(void)
{  
    esp_err_t ret;
    esp_vfs_fat_sdmmc_mount_config_t mount_config = {
        .format_if_mount_failed = true,
        .max_files = 5,
        .allocation_unit_size = 16 * 1024
    };
    sdmmc_card_t *card;
    const char mount_point[] = MOUNT_POINT;
    ESP_LOGI(TAG, "Initializing SD card");

    ESP_LOGI(TAG, "Using SPI peripheral");

    sdmmc_host_t host = SDSPI_HOST_DEFAULT();
    host.slot = SPI3_HOST;
    spi_bus_config_t bus_cfg = {
        .mosi_io_num = PIN_NUM_MOSI,
        .miso_io_num = PIN_NUM_MISO,
        .sclk_io_num = PIN_NUM_CLK,
        .quadwp_io_num = -1,
        .quadhd_io_num = -1,
        .max_transfer_sz = 4000,
    };
    ret = spi_bus_initialize(host.slot, &bus_cfg, SPI_DMA_CHAN);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to initialize bus.");
        return;
    }

    sdspi_device_config_t slot_config = SDSPI_DEVICE_CONFIG_DEFAULT();
    slot_config.gpio_cs = PIN_NUM_CS;
    slot_config.host_id = host.slot;

    ESP_LOGI(TAG, "Mounting filesystem");
    ret = esp_vfs_fat_sdspi_mount(mount_point, &host, &slot_config, &mount_config, &card);

    if (ret != ESP_OK) {
        if (ret == ESP_FAIL) {
            ESP_LOGE(TAG, "Failed to mount filesystem. "
                     "If you want the card to be formatted, set the EXAMPLE_FORMAT_IF_MOUNT_FAILED menuconfig option.");
        } else {
            ESP_LOGE(TAG, "Failed to initialize the card (%s). "
                     "Make sure SD card lines have pull-up resistors in place.", esp_err_to_name(ret));
        }
        return;
    }
    ESP_LOGI(TAG, "Filesystem mounted");

    sdmmc_card_print_info(stdout, card);

    // First create a file.
    const char *file_hello = MOUNT_POINT"/hello.txt";

    ESP_LOGI(TAG, "Opening file %s", file_hello);
    FILE *f = fopen(file_hello, "w");
    if (f == NULL) {
        ESP_LOGE(TAG, "Failed to open file for writing, %s", strerror(errno));
        return;
    }
    fprintf(f, "Hello %s!\n", card->cid.name);
    fclose(f);
    ESP_LOGI(TAG, "Hello File written");

    const char *file_foo = MOUNT_POINT"/foo.txt";

    // Check if destination file exists before renaming
    struct stat st;
    if (stat(file_foo, &st) == 0) {
        // Delete it if it exists
        unlink(file_foo);
    }

    // Rename original file
    ESP_LOGI(TAG, "Renaming file %s to %s", file_hello, file_foo);
    if (rename(file_hello, file_foo) != 0) {
        ESP_LOGE(TAG, "Rename failed");
        return;
    }

    // Open renamed file for reading
    ESP_LOGI(TAG, "Reading file %s", file_foo);
    f = fopen(file_foo, "r");
    if (f == NULL) {
        ESP_LOGE(TAG, "Failed to open file for reading");
        return;
    }

    // Read a line from file
    char line[64];
    fgets(line, sizeof(line), f);
    fclose(f);

    // Strip newline
    char *pos = strchr(line, '\n');
    if (pos) {
        *pos = '\0';
    }
    ESP_LOGI(TAG, "Read from file: '%s'", line);

//#define BASESTR1000 "..."

    const char * file_test = MOUNT_POINT"/test.txt";
    FILE * test = fopen(file_test, "w");


    ESP_LOGI(TAG, "Start write test");
    TickType_t startTick = xTaskGetTickCount();

    int loopcount = 1000;
    for (int i = 0; i < loopcount; i++)
    {
        fwrite((const void *)BASESTR1000, strlen(BASESTR1000), 1, test);
    }
    TickType_t endTick = xTaskGetTickCount();
    ESP_LOGI(TAG, "Write complete, closing the file");
    fclose(test);

    uint32_t time_delta_ms  = pdTICKS_TO_MS(endTick - startTick);

    ESP_LOGI(TAG, "Test writing %d kB in %d ms (%.2fkB/s)",
        loopcount * strlen(BASESTR1000) / 1024, time_delta_ms, (double)loopcount * strlen(BASESTR1000) * 1000 / 1024 / time_delta_ms );

    // All done, unmount partition and disable SPI peripheral
    esp_vfs_fat_sdcard_unmount(mount_point, card);
    ESP_LOGI(TAG, "Card unmounted");

    //deinitialize the bus after all devices are removed
    spi_bus_free(host.slot);
}
```

**Comment by andrew-elder** [comment] 2023-03-07 21:09
Posting a note to follow responses.

**Comment by igrr** [comment] 2023-03-07 21:22
Possibly this is the same issue as https://github.com/espressif/esp-idf/issues/10493#issuecomment-1420561542?

**Comment by polin-AL** [comment] 2023-03-07 22:22
They seem to be related, but wondering why we need a hardware change between 4.4 and 5.0.1? Setting SDSPI_CS  to -1 and pulling the CS line low on the SD card did improve write times to what we were seeing on 4.4.

**Comment by igrr** [comment] 2023-03-08 08:31
I think in #10493 we didn't get to the bottom of this issue (https://github.com/espressif/esp-idf/issues/10493#issuecomment-1420816198), so that's still unknown, unfortunately. cc @adokitkat

**Comment by adokitkat** [comment] 2023-03-08 15:07
![PXL_20230308_145709752~2.jpg](https://user-images.githubusercontent.com/1345895/223747787-47afe7b9-3217-4ee6-871c-73691867abeb.jpg)

![PXL_20230308_145724329.jpg](https://user-images.githubusercontent.com/1345895/223747797-4a245b06-0989-45bf-95ff-bfea7e9626db.jpg)

Hi! I tried to reproduce the regression with your example code on both ESP32-WROVER-KIT and ESP32-DEVKIT-C with external card reader connected to VSPI pins (you can see it on attached pictures) but everything works for me the same on both IDF versions v4.4 and v5.0.1 - both getting to 311 kB/s on my 16GB HC1 U3 microSD card.

**Comment by andrew-elder** [comment] 2023-03-08 20:34
@adokitkat - thanks for the prompt testing and feedback. Annoying that you don't observe the same results.... The main developer on this is on vacation for a week, so responses to your suggestions will be delayed.

**Comment by polin-AL** [comment] 2023-03-16 15:46
@adokitkat Results with this change reverted https://github.com/espressif/esp-idf/pull/7710/files:
`I (3312) SdCardSPI: Test writing 976 kB in 2570 ms (379.99kB/s)`

This is an acceptable speed for our project, and feels much better when running our project code.

**Comment by andrew-elder** [comment] 2023-03-16 18:06
@adokitkat What are the net steps? We are trying to determine whether we need to fork our own version of esp-idf (we would prefer not to!).

**Comment by adokitkat** [comment] 2023-03-22 23:57
@andrew-elder @polin-AL Since the problem was identified we will look into how to solve the regression. We cannot just revert the commit causing this because it fixes another problem, so a new solution has to be found. I'll leave this issue open and you'll be notified here on the fix status and whenever it was merged to master. I'll try to get `ESP32-PICO-V3-02 SiP Module` you mentioned you were using as soon as possible because with board I currently have it was not possible for me to reproduce the issue.

**Comment by polin-AL** [comment] 2023-03-28 17:15
@adokitkat I've done three tests now, with 10k pullup resistors on CS, MISO, and CS&MISO. All three still result in a 6.16kB/s transfer speed. This is after I reverted the ESPIDF change I made [previously](https://github.com/espressif/esp-idf/issues/10940#issuecomment-1472229993).

**Comment by andrew-elder** [comment] 2023-03-28 17:57
@adokitkat - thank you for your continued efforts on this. Here is the schematic for the SD card part of the board we are testing on:
![image](https://user-images.githubusercontent.com/814195/228326640-3fd8f2d3-44a6-4c0b-b459-4b2e901071b7.png)
all SPI lines have pullups on them.

**Comment by adokitkat** [comment] 2023-03-28 20:56
Testing with your code example:

IDF v5.0/master (without any workaround) + correct pull-up MOSI resistor.
```
I (3734) SdCardSPI: Test writing 976 kB in 3200 ms (305.18kB/s)
```

IDF v5.0/master (without any workaround) + MOSI pulled down.
```
I (162894) SdCardSPI: Test writing 976 kB in 159380 ms (6.13kB/s)
```

This matches your results. I am not sure why, but your hardware wiring seems to be somehow not correct. Since I don't have your board sadly I am not able to do a further research. That's the conclusion I am getting right now. 

Please try your example on any other ESP32 devkit and SPI SD card adapter (like the one on the picture I sent) or on ESP32-WROVER-KIT which has microSD card reader on the PCB and see what results do you get. ESP32-WROVER-KIT also has it's schema available online.

**Comment by adokitkat** [comment] 2023-03-28 21:13
Since this change is braking some board designs I will propose adding a setting in Kconfig with which you will be able to disable the `poll_busy` in `sdspi_host_start_command`. Is this alright?

**Comment by andrew-elder** [comment] 2023-03-28 21:39
@adokitkat - sounds like a good solution to me. We'll see if we can also try one of the kits.

**Comment by andrew-elder** [comment] 2023-04-04 17:54
> In meantime (and maybe even as a overall solution to your issue) I would advise, that is if you only have the SD card connected to the SPI line and nothing else, to set CS in IDF to -1 as unused and set the CS GPIO pin to low, so the SD card will be active the whole time.

Yes, we can try that.

> May I ask you what board are you using? Is it purchasable somewhere? Maybe I could get it so I can test on it.

Sorry, it is custom hardware that is not available for purchase. Are there other particular tests you would like us to do on our hardware? We might be able to set up some sort of call if you wanted to run specific tests.

**Comment by adokitkat** [comment] 2023-04-05 12:20
Could you try to add this line before the `esp_vfs_fat_sdspi_mount` call (IDF v5.0+ code without the CS == -1 workaround)?

`gpio_pullup_en(GPIO_NUM_19);` (change the number to number of GPIO pin you use as MISO)

I tried to simulate the incorrect schematics by externally connecting MISO to 1MOhm pull-down resistor, which resulted in slowdown you're seeing and then I added the `gpio_pullup_en` function to enable internal pull-up resistor which restored the IO speeds again. If this works for you too then it's better solution than the previous workaround.

**Comment by polin-AL** [comment] 2023-04-05 15:35
@adokitkat,

With `gpio_pullup_en(PIN_NUM_MISO)` I got the following:
`I (162172) SdCardSPI: Test writing 976 kB in 158800 ms (6.15kB/s)`

But with the CS pin set to -1, and pulled low, we are getting a much better:
`I (2952) SdCardSPI: Test writing 976 kB in 2360 ms (413.80kB/s)`

**Comment by polin-AL** [comment] 2023-04-05 17:52
There is a bit of a mixup here, we do have custom hardware for this project, but before that was created we were using a ESP32-PICO-V3-02 board. That's what I've been doing all the testing with for this issue, not our custom hardware.

**Comment by adokitkat** [comment] 2023-04-13 09:02
If you are alright with using the CS pin workaround, then I will close this issue since we could not reproduce the issue on correctly wired and set hardware. Thank you for participating! Feel free to reopen if there is a problem.

**Closed by adokitkat** 2023-04-13 09:02 UTC
Labels: Awaiting Response, Status: Reviewing

**Comment by italocjs** [comment] 2025-07-18 01:45
Hello, i'm currently updating from ESP-IDF 4.4.7 to 5.4.2 and noticed a extremely slow write / read too, attempting to use 
```
But with the CS pin set to -1, and pulled low, we are getting a much better:
I (2952) SdCardSPI: Test writing 976 kB in 2360 ms (413.80kB/s)
```
It does not recognize the card,  currently the sdcard is connected without any hardware pullups/pulldown (as the previous idf did not require it).

Has there been any development on this?  any tips? help is greatly appreciates, i'm currently getting ~0.13MB max of write speed and 0.06MB max of read. 

Tried solution 1 (add internal pullup, no effect)
```
I (00:00:03.093) SDCARD: Writing 128 chunks of 512 bytes each
I (00:00:19.641) SDCARD: V2 WRITE PERFORMANCE: 65536 bytes in 15888 ms = 4124 bytes/sec (4.03 KB/s, 0.00 MB/s)
I (00:00:19.642) SDCARD: V2 Write test completed, starting read performance test
I (00:00:30.220) SDCARD: V2 READ PERFORMANCE: 65536 bytes in 10488 ms = 6248 bytes/sec (6.10 KB/s, 0.01 MB/s)
```

Tried solution 2 (disable CS), card no longer detected
```
I (00:00:00.208) SDCARD: SPI host configuration: slot=1, max_freq_khz=20000
I (00:00:00.215) SDCARD: SPI bus configuration: MOSI=13, MISO=12, SCK=14, CS=15
I (00:00:00.224) SDCARD: SPI bus initialized successfully
I (00:00:00.229) SDCARD: Using CS workaround (gpio_cs = GPIO_NUM_NC)
I (00:00:00.236) SDCARD: Mounting filesystem...
E (00:00:00.443) sdmmc_sd: sdmmc_init_sd_if_cond: send_if_cond (1) returned 0x108
E (00:00:00.444) vfs_fat_sdmmc: sdmmc_card_init failed (0x108).
E (00:00:00.447) SDCARD: Failed to mount filesystem. Error: ESP_ERR_INVALID_RESPONSE
```

Tried pullup on MISO and MOSI, no effect
```
I (00:00:19.634) SDCARD: V2 WRITE PERFORMANCE: 65536 bytes in 15881 ms = 4126 bytes/sec (4.03 KB/s, 0.00 MB/s)
I (00:00:19.635) SDCARD: V2 Write test completed, starting read performance test
I (00:00:30.208) SDCARD: V2 READ PERFORMANCE: 65536 bytes in 10483 ms = 6251 bytes/sec (6.10 KB/s, 0.01 MB/s)
I (00:00:30.209) SDCARD: V2 Speed test completed successfully
```
