### ISSUE TITLE
Can't connect to WiFi with space in ssid (IDFGH-5611)

### ISSUE THREAD

**Issue by hoatenhu** [espressif/esp-idf#7331] opened 2021-07-27 08:53 UTC
Hi everyone, can you help me with this problem:
- I use softAP provisioning example
- I can't connect with ssid when it has space
- I try another version but it doesn't work
- But It can connect with ssid have no space
**1. When ssis has space:**
![1](https://user-images.githubusercontent.com/84147184/127125671-f0660903-f094-4ee2-91be-4f54574817ef.jpeg)
![1 1](https://user-images.githubusercontent.com/84147184/127125684-6767180a-db7c-43f1-8727-17d8afd79759.jpeg)

https://user-images.githubusercontent.com/84147184/127125709-ddeffc70-b258-4161-b3ba-c2cc923a9cd0.mp4
![1 5](https://user-images.githubusercontent.com/84147184/127125817-0e017100-a87b-401a-9a23-b764ce09ccbd.jpeg)

**2. When no space**
![2](https://user-images.githubusercontent.com/84147184/127125829-983aae75-3cbe-4e94-a0d1-ff091bb58419.jpeg)
![2 2](https://user-images.githubusercontent.com/84147184/127125842-c7018249-2b58-4c3e-9974-fba9e9ced14a.jpeg)

**Comment by ESP-YJM** [comment] 2021-07-28 06:14
@hoatenhu Could you please offer your IDF version you used. I can't reproduce your issue.

**Comment by hoatenhu** [comment] 2021-07-28 07:02
Hi,
I tried IDF 4.1, 4.2, 4.3, also checkout remote/origin/release 4.1(4.2, 4.3 ) in git, and it doesn't work.
Now I'm using 4.2
![image](https://user-images.githubusercontent.com/84147184/127278628-5dc78cce-b421-464a-be95-160765b65460.png)

**Comment by hoatenhu** [comment] 2021-07-28 07:10
I am using esp32 Wrover, does this have any effect on this error?

**Comment by ESP-YJM** [comment] 2021-07-28 07:23
I think you can run wifi sta example to test it.

**Comment by hoatenhu** [comment] 2021-07-28 09:16
This is when I run wifi sta example:
![image](https://user-images.githubusercontent.com/84147184/127297155-de2d7e82-6bb6-4403-9674-ccb4eafedd01.png)

**Comment by hoatenhu** [comment] 2021-07-28 09:20
And when without space:
![image](https://user-images.githubusercontent.com/84147184/127297669-7ca166cb-af9f-4ad9-a3dc-164d78288907.png)

**Comment by ESP-YJM** [comment] 2021-07-28 09:22
@hoatenhu Is ssid `te` and `Y Nhi` used the same router AP？

**Comment by hoatenhu** [comment] 2021-07-28 09:25
yepp, I also try with ssid: `te_1` and it has the same error with ssid: `Y Nhi`

**Comment by ESP-YJM** [comment] 2021-07-28 09:29
@hoatenhu I think this ssid is ok to connect. Please check your AP wifi channel, need in 1-13 and only support 2.4G.

**Comment by hoatenhu** [comment] 2021-07-28 11:24
It still error

![image](https://user-images.githubusercontent.com/84147184/127314382-0d1cf2ee-2bf1-455a-b3ad-494ef0ca4ce8.png)

**Comment by ESP-YJM** [comment] 2021-07-28 11:36
@hoatenhu It's ok for me with same ssid and password. Or can you erase your flash and re-flash fw to test? Or capture wifi packet.
![Screenshot from 2021-07-28 19-33-27](https://user-images.githubusercontent.com/83155693/127315858-08d307e3-4fce-4d21-b6d4-15c160785861.png)

**Comment by hoatenhu** [comment] 2021-07-28 14:00
It works with passwords of fewer than 13 characters, what if I want the password to have more characters?
![image](https://user-images.githubusercontent.com/84147184/127334811-041a2f23-d3dc-44c7-8e26-9b951f1bde32.png)

**Comment by AxelLin** [comment] 2021-07-29 01:03
> It works with passwords of fewer than 13 characters, what if I want the password to have more characters?

I don't get it.
This does not match https://github.com/espressif/esp-idf/issues/7331#issuecomment-888232386 which shows faiure with passoword:10031998 (obviously less than 13 characters)
So what was changed to make it work?

**Comment by hoatenhu** [comment] 2021-07-29 01:19
I checked out v4.3, therefore https://github.com/espressif/esp-idf/issues/7331#issuecomment-888232386  work with less 13 characters

**Comment by ESP-YJM** [comment] 2021-07-29 02:22
@hoatenhu I also use tag v4.2 version. And it's ok for space ssid and more than 13 characters password.

**Comment by hoatenhu** [comment] 2021-07-29 02:58
So why I can connect with password `123456789012`, and not connect with password `1234567890123`, I can't understand, I use v4.3 now
![image](https://user-images.githubusercontent.com/84147184/127424602-8754f714-a893-4ac7-a528-25922798f2dd.png)

**Comment by ESP-YJM** [comment] 2021-07-29 03:01
@hoatenhu Do you have another AP router or mobile hotspot? You can change it and test.

**Comment by hoatenhu** [comment] 2021-07-29 03:07
but why I can't connect with this password `thanhtuyennhuy`, I use v4.3 now
![image](https://user-images.githubusercontent.com/84147184/127425327-b2f84310-9e6e-4306-a279-7cbe4164b6ec.png)

**Comment by AxelLin** [comment] 2021-07-29 03:10
> but why I can't connect with this password `thanhtuyennhuy`, I use v4.3 now

Please modify the example code to print disconnect reason when connect the AP fail.

**Comment by hoatenhu** [comment] 2021-07-29 03:20
Can you help me how to modify it? I don't know where
![image](https://user-images.githubusercontent.com/84147184/127426409-1677658f-2e03-4688-88bc-1f9a4cf339cc.png)

**Comment by hoatenhu** [comment] 2021-07-29 03:40
with pass `thanhtuyen` it works, If I add 1 more character, it won't work, ex `thanhtuyenn`, `thanhtuyennh`, ..
![image](https://user-images.githubusercontent.com/84147184/127427906-9f4d517f-270a-4e80-9d5f-87d6a0727a68.png)

**Comment by ESP-YJM** [comment] 2021-07-29 03:46
@hoatenhu  You can follow this to print wifi connect error reason. https://github.com/espressif/esp-idf/blob/master/components/wifi_provisioning/src/manager.c#L864 . Besides, do you try my suggestion https://github.com/espressif/esp-idf/issues/7331#issuecomment-888762203 to test?

**Comment by hoatenhu** [comment] 2021-07-29 04:27
![image](https://user-images.githubusercontent.com/84147184/127429745-1ac887b3-843b-466f-a5ef-2fe620f02c27.png)
![image](https://user-images.githubusercontent.com/84147184/127431519-9c39d228-15de-4ab6-ba28-9210ef9464d8.png)

**Comment by hoatenhu** [comment] 2021-07-29 04:30
here is if I add `6` in password

![image](https://user-images.githubusercontent.com/84147184/127431781-a2c3b94f-efd8-4ff8-9939-320b36115211.png)

**Comment by hoatenhu** [comment] 2021-07-29 04:37
![image](https://user-images.githubusercontent.com/84147184/127432244-716ad75b-9f28-4569-ad64-98dcb82e825c.png)
![9086257f216cd6328f7d](https://user-images.githubusercontent.com/84147184/127432398-4321b69a-2c7b-41ee-94e2-3eae1a3070b3.jpg)

**Comment by AxelLin** [comment] 2021-07-29 04:42
@hoatenhu 

Can you share the brand / model of this AP?
Also share the AP setting screenshot if possible.

**Comment by hoatenhu** [comment] 2021-07-29 04:57
I use mobile hotspot of my Window laptop for esp now
and this is wifi I want esp to connect to( my home wifi)
![image](https://user-images.githubusercontent.com/84147184/127433966-2ab59c7d-648e-45be-b6e5-9cd21948f3ac.png)

**Comment by ESP-YJM** [comment] 2021-07-29 06:08
@hoatenhu WIFI connection error reason 2 is auth fail, maybe password is mismatch. You can use another device to connect AP.

**Comment by hoatenhu** [comment] 2021-07-29 07:33
and what about this error
![image](https://user-images.githubusercontent.com/84147184/127450755-3d5a4c2a-c46b-4a24-b7c5-fa6a2eed31d8.png)

**Comment by ESP-YJM** [comment] 2021-07-29 07:57
@hoatenhu You can find reason in this file. https://github.com/espressif/esp-idf/blob/master/components/esp_wifi/include/esp_wifi_types.h#L99

**Comment by hoatenhu** [comment] 2021-07-29 08:37
ok, thank you so much for helping me, I think the problem is my AP router

**Comment by ESP-YJM** [comment] 2021-07-29 08:41
Ok, please help close this issue if no other problem.

**Comment by hoatenhu** [comment] 2021-07-29 08:42
ok, bye

**Closed** 2021-07-29 08:42 UTC
Labels: Status: Opened
