### ISSUE TITLE
WiFi stack can freeze if CONFIG_ESP32_WIFI_RX_BA_WIN > CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM (IDFGH-1383)

### ISSUE THREAD

**Issue by ssilverman** [espressif/esp-idf#3663] opened 2019-06-20 05:27 UTC
Suggest you change the issue to this:

> WiFi stack can freeze if CONFIG_ESP32_WIFI_RX_BA_WIN > CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM.
> 
> Tested on esp-idf v3.2
> 
> This configuration should be prevented or checked and an error thrown.

_Originally posted by @negativekelvin in https://github.com/espressif/esp-idf/issues/3646#issuecomment-503832957_

**Comment by ssilverman** [comment] 2019-06-20 05:29
See also: https://github.com/espressif/arduino-esp32/issues/2899

**Comment by r1dd1ck** [comment] 2019-06-20 17:57
Well, are you sure it's this?
 
Because the `iperf` example uses:
`WIFI_STATIC_RX_BUFFER_NUM=16 `
`WIFI_RX_BA_WIN=32`

and it does **not** "freeze" :neutral_face:

**Comment by negativekelvin** [comment] 2019-06-20 21:06
Well it solves the problem reported here but maybe only happens "under certain conditions" so needs more constraints from wifi stack developers

**Comment by r1dd1ck** [comment] 2019-06-20 21:34
Yes, I certainly agree that changing the values "fixes" the reported issue :thumbsup: 

But what I was pointing at is, whether the supplied conditional really is the **underlying cause** of the freezing stack, because it is in direct conflict with the `iperf` example defaults (which doesn't seem to show the symptoms). 

Other than that, all is fine :slightly_smiling_face:

**Comment by ssilverman** [comment] 2019-09-26 22:12
This still happens in the v1.0.3 Arduino core: https://github.com/espressif/arduino-esp32/issues/3287

**Comment by ssilverman** [comment] 2019-09-26 22:46
For those following along, the stack now fails to receive more packets than defined by CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM. Doing some spelunking for the word `dynamic_rx_buf_num` (the consumer of this define, as found with a simple grep) led me to `tools/sdk/lib/libesp32.a`, that's why I think the issue is in `esp-idf` as opposed to just in the Arduino core.

**Comment by espxiehang** [comment] 2019-11-14 06:15
@ssilverman hi,I use your script to send upd packets, but I didn't reproduce the issue.
Can you give me an easy to reproduce method and your log?

**Comment by ssilverman** [comment] 2019-11-14 22:36
When I filed this and related issues, this was the behaviour. However, the later Arduino releases seem to fix the problem. I haven’t dived in, but if you use settings from 1.0.2 (I think? See the issues in that repo that link to this one.), then you’ll see this behaviour. I realize this repo isn’t Arduino, and I haven’t explored much in the non-Arduino space of the esp-idf repo, but I think you’ll find the behaviour by using the settings mentioned in those Arduino versions.

**Comment by negativekelvin** [comment] 2019-11-14 23:34
I think this can be closed with https://github.com/espressif/esp-idf/commit/dd26caf7799a7414596d71d1bc4ee39634480a62#diff-fdc67a5904b65c3885aad20459aa1cef

**Comment by ssilverman** [comment] 2019-11-14 23:36
@negativekelvin was the source of this problem found?

**Comment by negativekelvin** [comment] 2019-11-15 00:12
Yes, enforce restrictions on the value of CONFIG_ESP32_WIFI_RX_BA_WIN per the commit.  The other issues are all outside the scope of esp-idf code so I think you can close this.

**Comment by ssilverman** [comment] 2019-11-15 00:34
Right, but I meant: why does not meeting those conditions cause the problem? Is there a deeper problem somewhere? Should a comment in the code that uses these values make note of a fault potential? I’m just suggesting another commit that addresses that problem or at least makes a note of it somewhere. Other than that, I can certainly close this if you’re saying it’s fixed.

**Closed** 2019-11-15 00:36 UTC

**Comment by negativekelvin** [comment] 2019-11-15 00:50
The actual conditions in the commit are 

`(CONFIG_ESP32_WIFI_RX_BA_WIN ≤ CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM) && (CONFIG_ESP32_WIFI_RX_BA_WIN ≤ 2 * CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM)`

so iperf is not in violation

**Comment by espxiehang** [comment] 2019-11-15 02:45
Yes, its rules are defined in “components/esp_wifi/src/wifi_init.c”
