### ISSUE TITLE
froze after 30 mins using esp_log_set_vprintf() and udp socket (IDFGH-34)

### ISSUE THREAD

**Issue by 0BackDoor1** [espressif/esp-idf#1246] opened 2017-11-08 14:10 UTC
Hi,
I'm facing a strange issue, I wrote a simple project that use esp_log_set_vprintf() to redirect logs to a remote server through an udp socket, but after 30 minutes logs stops (even connected directly via serial port),  the board freeze every time after 30mins without any error or warning.
Little note: the freeze doesn't occur if I comment the line with sendto() (lwip library).
I already checked the amout of free memory and there is a lot of memory available when freeze occurs.
All suggestions idea are welcome

**Comment by FayeY** [comment] 2017-11-14 11:50
Could you provide your test code?

**Comment by 0BackDoor1** [comment] 2017-11-17 13:24
I tried to simplify as much as possibile

**main.c**
```c
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "wifi_manager.h"
#include "bscore.h"
#include <string.h>

static const char *TAG = "<main>";

void app_main()
{
	ESP_ERROR_CHECK( nvs_flash_init() );
	wifi_manager_init();
	bs_core_init();
	ESP_LOGI(TAG, "System started");
}
```


**bscore.c**
```c
#include "bscore.h"

#include <string.h>
#include <ctype.h>
#include <inttypes.h>

#include "esp_log.h"
#include "esp_bt_device.h"

#include "sdkconfig.h"

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"

//Include Component Headers
#include "remote_log.h"
#include "wifi_manager.h"

static const char *TAG = "<BSCORE>";

typedef enum
{
  FSM_INIT_WIFI,
  FSM_WAIT_CHECK_FW_UPDATE
} fsm_bs_core_status_e;

static fsm_bs_core_status_e current_status = FSM_INIT_WIFI;

void print_fsm_bs_core_status(fsm_bs_core_status_e status)
{
  switch(status)
  {
    case FSM_INIT_WIFI:
    {
      ESP_LOGW(TAG,"FSM_INIT_WIFI");
      break;
    }
    case FSM_WAIT_CHECK_FW_UPDATE:
    {
      ESP_LOGW(TAG,"FSM_WAIT_CHECK_FW_UPDATE");
      break;
    }
  }
}

/*
 * Task functions (main FSM)
 */
static void task_bs_core(void *pvParameters)
{
  while(true)
  {
    print_fsm_bs_core_status(current_status);
    switch( current_status )
    {
      case FSM_INIT_WIFI:
      {
        if(wifi_station_connected())
        {
          //Activate logs to udp
          int result = remote_log_init(CONFIG_REMOTE_UDP_URL, CONFIG_REMOTE_UDP_PORT);
          if(result != 0)
          {
            ESP_LOGE(TAG,"remote_log_init error, result:%i",result);
          }
          else
          {
            remote_log_set_identifier("AB:CD:EF:GH:IL:MN",17);
          }

          current_status = FSM_WAIT_CHECK_FW_UPDATE;
        }
        else
        {
          ESP_LOGE(TAG,"No connection available!");
        }
        break;
      }

      case FSM_WAIT_CHECK_FW_UPDATE:
      {
        ESP_LOGW(TAG,"Waiting for freeze...");
        break;
      }
    }

    vTaskDelay(BS_CORE_TASK_DELAY / portTICK_PERIOD_MS);
  }
}

/**
 * Init App module
 */  
void bs_core_init()
{
  ESP_LOGI(TAG,"Component init");

  // Launch main task
  xTaskCreate(task_bs_core, "bscoreTask", 2048, NULL, tskIDLE_PRIORITY + 2, NULL);
  ESP_LOGI(TAG,"Component init done");
}
```


**wifi_manager.c**
```c

#include "sdkconfig.h"

#include <string.h>
#include "wifi_manager.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_event_loop.h"
#include "tcpip_adapter.h"
#include "lwip/ip_addr.h"
#include "lwip/dns.h"
#include "apps/dhcpserver.h"
#include "apps/dhcpserver_options.h"

#include "lwip/inet.h"
#include "lwip/ip4_addr.h"

#include "freertos/event_groups.h"
#include "esp_log.h"

// List of event group bits
#define WIFI_EVENT_CONNECTED    BIT0
#define WIFI_EVENT_CONNECTING   BIT1

// Signal 
static EventGroupHandle_t wifi_event_group;

static wifi_mode_t current_working_mode;
static const char* TAG = "<WifiManager>";
#define WIFI_SSID "ssid_of_my_wifi"
#define WIFI_PSW "psw_of_my_wifi"

static esp_err_t event_handler(void *ctx, system_event_t *event)
{
  switch(event->event_id)
  {
    case SYSTEM_EVENT_STA_START:
    xEventGroupSetBits(wifi_event_group, WIFI_EVENT_CONNECTING);
    esp_wifi_connect();
    break;
    case SYSTEM_EVENT_STA_GOT_IP:
    xEventGroupSetBits(wifi_event_group, WIFI_EVENT_CONNECTED);
    break;
    case SYSTEM_EVENT_STA_DISCONNECTED:
    xEventGroupClearBits(wifi_event_group, WIFI_EVENT_CONNECTING);
    xEventGroupClearBits(wifi_event_group, WIFI_EVENT_CONNECTED);
          //ESP_LOGI(TAG,"Station disconnected to AP");
    
          // For performance reasons we launch connect immediately
    if (current_working_mode == WIFI_MODE_STA)
    {
      xEventGroupSetBits(wifi_event_group, WIFI_EVENT_CONNECTING);
      esp_wifi_connect();
    }
    break;
    case SYSTEM_EVENT_STA_CONNECTED:
    ESP_LOGI(TAG,"Station connected to AP");
    break;
    case SYSTEM_EVENT_STA_AUTHMODE_CHANGE:
    break;

    default:
    ESP_LOGD(TAG,"Wifi event: %i", event->event_id);
    break;
  }
  
  return ESP_OK;
}

/*
 * Main init function
 */
void wifi_manager_init()
{
  current_working_mode = WIFI_MODE_STA;

  tcpip_adapter_init();
  wifi_event_group = xEventGroupCreate();
  ESP_ERROR_CHECK( esp_event_loop_init(event_handler, NULL) );
  wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
  ESP_ERROR_CHECK( esp_wifi_init(&cfg) );
  wifi_country_t wifi_country = {
    .cc = "EU",
    .schan = 1,
    .nchan = 13,
    .policy = WIFI_COUNTRY_POLICY_AUTO,
  };
  ESP_ERROR_CHECK( esp_wifi_set_country(&wifi_country) );
  ESP_ERROR_CHECK( esp_wifi_set_storage(WIFI_STORAGE_RAM) );
  wifi_config_t wifi_config = {
    .sta = {
      .ssid = WIFI_SSID,
      .password = WIFI_PSW,
    },
  };
  ESP_LOGI(TAG, "Setting WiFi configuration SSID %s...", wifi_config.sta.ssid);
  ESP_ERROR_CHECK( esp_wifi_set_mode(WIFI_MODE_STA) );
  ESP_ERROR_CHECK( esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config) );
  ESP_ERROR_CHECK( esp_wifi_start() );
  
  ESP_LOGD(TAG, "Starting WIFI peripheral");
}

bool wifi_station_connected()
{
  uint32_t bits;
  if (current_working_mode != WIFI_MODE_STA && current_working_mode != WIFI_MODE_APSTA) 
  {
    return false;
  }

  bits = xEventGroupGetBits(wifi_event_group);
  return (bits & WIFI_EVENT_CONNECTED) ? true : false;
}
```


**remote_log.c**
```c
#include "remote_log.h"
#include <string.h>
#include "esp_system.h"
#include "esp_log.h"

#include "lwip/err.h"
#include "lwip/sockets.h"
#include "lwip/sys.h"
#include "lwip/netdb.h"
#include "lwip/dns.h"

static int fd;
static struct sockaddr_in serveraddr;
static uint8_t buf[REMOTE_LOG_SINGLE_LINE_MAX_LEN];
static char *board_identifier;
static uint8_t board_identifier_len = 0;
static const char *TAG = "<UDP_LOG>";

static const char *error_buffer_small = "err1\n\0";
static const char *error_missing_id = "err2\n\0";

static const char null_terminator_string = '\0';
static const uint8_t null_terminator_string_len = 1;

void remote_log_set_identifier(char *id_to_use, uint8_t id_len)
{
  if(id_len <= (REMOTE_LOG_SINGLE_LINE_MAX_LEN-(1+null_terminator_string_len)) ) //Is buff large enough? (1 for new line char and 1 for null terminator string)
  {
    board_identifier = id_to_use;
    board_identifier_len = id_len;

    //Set idenfitier at the beginning of the buffer-log
    memcpy(&buf[0],board_identifier,board_identifier_len);
  }
  else
  {
    ESP_LOGE(TAG,"remote_log_set_identifier fail, buf size is smaller than %i",id_len);
  }
}

static int hook_send_log_to_udp_vprintf( const char *log_format, va_list arguments_list )
{
  static uint32_t buff_pointer;
  static uint8_t max_space_for_content;

  if(board_identifier_len <= (REMOTE_LOG_SINGLE_LINE_MAX_LEN-(1+null_terminator_string_len)) ) //Is buff large enough? (1 for new line char and 1 for null terminator string)
  {
    //Remote log without identifier has no sense, so it must be set
    if(board_identifier_len > 0)
    {
      //Start to the end of identifier
      buff_pointer = board_identifier_len;

      max_space_for_content = REMOTE_LOG_SINGLE_LINE_MAX_LEN - (board_identifier_len+null_terminator_string_len);

      //Then add log string
      buff_pointer += vsnprintf((char*)&buf[buff_pointer], max_space_for_content, log_format, arguments_list);

      //Resize the pointer if vsnprintf goes too forward
      if(buff_pointer > (board_identifier_len+max_space_for_content))
      {
        buff_pointer = REMOTE_LOG_SINGLE_LINE_MAX_LEN;//board_identifier_len+max_space_for_content;
        // printf("|buff_pointer resized to:%i|\n",buff_pointer);
        buf[REMOTE_LOG_SINGLE_LINE_MAX_LEN-2] = '\n';
        buf[REMOTE_LOG_SINGLE_LINE_MAX_LEN-1] = '\0';
      }

      //printf("%s\n", buf);
      
      sendto(fd, buf, buff_pointer, 0, (struct sockaddr *)&serveraddr, sizeof(serveraddr));
    }
    else
    {
      sendto(fd, error_missing_id, strlen(error_missing_id), 0, (struct sockaddr *)&serveraddr, sizeof(serveraddr));
    }
  }
  else
  {
    sendto(fd, error_buffer_small, strlen(error_buffer_small), 0, (struct sockaddr *)&serveraddr, sizeof(serveraddr));
  }
  return vprintf(log_format, arguments_list);
}

int remote_log_init(const char *ipaddr, unsigned long port )
{
  ESP_LOGI(TAG, "initializing udp logging...");
  if( (fd = socket(AF_INET, SOCK_DGRAM, 0)) < 0 )
  {
   ESP_LOGE(TAG, "Cannot open socket!");
   return -1;
 }

 uint32_t ip_addr_bytes;
 inet_aton(ipaddr, &ip_addr_bytes);
 ESP_LOGI(TAG, "Logging to 0x%x", ip_addr_bytes);

 memset( &serveraddr, 0, sizeof(serveraddr) );
 serveraddr.sin_family = AF_INET;
 serveraddr.sin_port = htons( port );
 serveraddr.sin_addr.s_addr = ip_addr_bytes;

 esp_log_set_vprintf(hook_send_log_to_udp_vprintf);

 return 0;
}

void remote_log_free()
{
  esp_log_set_vprintf(vprintf);
  close( fd );
}
```

**Comment by 0BackDoor1** [comment] 2017-11-17 14:50
UPDATE: using a brand new sdkconfig the issue disappeared, I'm going to compare two version to catch what generate the freeze

**Comment by 0BackDoor1** [comment] 2017-11-22 08:33
Good morning,
@FayeY the issue disappear switching to log level "info", the issue occurs with level "verbose", I can work to make the code up here as small as possible if needed

**Comment by liuzfesp** [comment] 2017-11-26 04:30
Hi @0BackDoor1 we will check this issue and update you.

**Comment by liuzfesp** [comment] 2017-11-26 04:32
@0BackDoor1 maybe you need to add some return value check in sendto because it may return error, and add some recoverable code for specific error.

**Comment by imotion-software** [comment] 2017-12-04 17:21
Hi @liuzfesp,

we're facing a very similar issue. We're using DevKitC board with a custom firmware. If we redirect log to UDP we got board frozen after exactly 30 minutes with log set to "Verbose".

Reduce verbosity will simply postpone the issue.

I don't think it's related to the quantity of logs in output because it always freezes at exactly 30 minutes, not one second less and no second more even though we change log outputs and quantity!

It's absolutely weird because in order to recover board we have to power cycle it. 
Watchdogs are not working at all.

**Comment by liuzfesp** [comment] 2017-12-05 02:08
Got @imotion-software , @zhangyanjiaoesp will investigate this issue.

**Comment by zhangyanjiaoesp** [comment] 2017-12-07 07:05
@0BackDoor1 @imotion-software 
I have tested as you said, and I got board frozen after exactly 1 hour with log set to "Verbose".
According to my log, I'm it's the time for the DHCP client to renew the lease. The analysis is as follows:

- DHCP client call `udp_sento_if()` in `dhcp_renew().` 

- When receiving the ack of the DHCP server,  `tcpip_adapter_dhcp_cb()` will be called in `tcpip_task`,
 `ESP_LOG(TAG,“if%d dhcpc cb”, tcpip_if)` wiil be executed, then `sendto()` will be called. This causes `tcpip_task` send mbox to itself, and then wait for a sem to be given.

- `vprintf_task` call `sendto()`,  send mbox to `tcpip_task`,  wait for a sem to be given, but the  `tcpip_task` is waiting for a sem too, so it will not run the `udp_sendto()`, then the board will froze.

To solve this problem, I think we can add an `if` statement to judge whether the current task is tcpip_task, if it is, we should not redirect log to  `sendto()` function. Like follows:
> char task_name[16];
  char *cur_task = pcTaskGetTaskName(xTaskGetCurrentTaskHandle());
  strncpy(task_name, cur_task, 16);
  task_name[15] = 0;        
  if (strncmp(task_name, "tiT", 16) == 0) {
      vprintf(log_format,arguments_list);
  }  

> 

I have tested for this solution, it woeks well.

**Comment by zhangyanjiaoesp** [comment] 2017-12-07 07:14
I have added  some return value check in sendto, and have added `if` statement in `hook_send_log_to_udp_vprintf`
> int get_socket_error_code(int socket) 
{   
  int result;
  u32_t optlen = sizeof(int);
  if(getsockopt(socket, SOL_SOCKET, SO_ERROR, &result, &optlen) == -1) {
    printf("getsockopt failed");
    return -1;
  }
  return result;
}
int show_socket_error_reason(int socket)
{
  int err = get_socket_error_code(socket);
  printf("socket error %d %s", err, strerror(err));
  return err;
}
static int hook_send_log_to_udp_vprintf( const char *log_format, va_list arguments_list )
{
  static uint32_t buff_pointer;
  static uint8_t max_space_for_content;
  int len;
  char task_name[16];
  char *cur_task = pcTaskGetTaskName(xTaskGetCurrentTaskHandle());
  strncpy(task_name, cur_task, 16);
  task_name[15] = 0;        
  if (strncmp(task_name, "tiT", 16) == 0) {
      vprintf(log_format,arguments_list);
  } 
  else 
  {
    if(board_identifier_len <= (REMOTE_LOG_SINGLE_LINE_MAX_LEN-(1+null_terminator_string_len)) ) //Is buff large enough? (1 for new line char and 1 for null terminator string)
    {
      //Remote log without identifier has no sense, so it must be set
      if(board_identifier_len > 0)
      {
        //Start to the end of identifier
        buff_pointer = board_identifier_len;
        max_space_for_content = REMOTE_LOG_SINGLE_LINE_MAX_LEN - (board_identifier_len+null_terminator_string_len);
        //Then add log string
        buff_pointer += vsnprintf((char*)&buf[buff_pointer], max_space_for_content, log_format, arguments_list);
        //Resize the pointer if vsnprintf goes too forward
        if(buff_pointer > (board_identifier_len+max_space_for_content))
        {
          buff_pointer = REMOTE_LOG_SINGLE_LINE_MAX_LEN;//board_identifier_len+max_space_for_content;
          // printf("|buff_pointer resized to:%i|\n",buff_pointer);
          buf[REMOTE_LOG_SINGLE_LINE_MAX_LEN-2] = '\n';
          buf[REMOTE_LOG_SINGLE_LINE_MAX_LEN-1] = '\0';
        }
        //printf("%s\n", buf);      
        len = sendto(fd, buf, buff_pointer, 0, (struct sockaddr *)&serveraddr, sizeof(serveraddr));
        if (len < 0)
	{
	  show_socket_error_reason(mysocket);
	}
      }
      else
      {
        len = sendto(fd, error_missing_id, strlen(error_missing_id), 0, (struct sockaddr *)&serveraddr, sizeof(serveraddr));
        if (len < 0)
	{
	  show_socket_error_reason(mysocket);
	}
      }
    }
    else
    {
      len = sendto(fd, error_buffer_small, strlen(error_buffer_small), 0, (struct sockaddr *)&serveraddr, sizeof(serveraddr));
      if (len < 0)
	{
	  show_socket_error_reason(mysocket);
	}
    }
  }
  return vprintf(log_format, arguments_list);
}

**Comment by imotion-software** [comment] 2017-12-09 15:47
Hi @zhangyanjiaoesp, it sounds great.
I will test it and let you know.

Why doesn't watchdog reset the board in this situation?

**Comment by igrr** [comment] 2017-12-09 16:08
@imotion-software do you have task watchdog enabled, and is some task other than Idle registered with the task watchdog?

**Comment by imotion-software** [comment] 2017-12-13 09:08
@igrr, we have default settings for watchdog, so nothing registered but idle task.

@zhangyanjiaoesp I checked and tried your fix. I can confirm you that problem was related to a print within TCP/IP task. Just skipping sendto for "tiT" task fix the issue.

In the meantime, we turned a board on yesterday evening and start collecting remote logs.
After exactly 10.000 seconds, on our remote log we got this:

`I (9997925) wifi: bcn_timout,ap_probe_send_start`

From that moment on, board could not connect to WiFi AP anymore. This morning I catch the serial port logs and they report continuously a strange reason 201 while connecting to AP:

```
D (55888100) event: SYSTEM_EVENT_STA_DISCONNECTED, ssid:WifiSSID, ssid_len:16, bssid:00:00:00:00:00:00, reason:201.
V (55888101) event: enter default callback.
D (55888105) tcpip_adapter: check: local, if=0 fn=0x4011df4c
.
D (55888110) tcpip_adapter: if0 start ip lost tmr: enter.
D (55888116) tcpip_adapter: if0 start ip lost tmr: no need start because netif=0x3ffeabb4 interval=120 ip=0.
D (55888126) tcpip_adapter: call api in lwip: ret=0x0, give sem.
D (55888132) tcpip_adapter: check: remote, if=0 fn=0x4011df4c
.
V (55888138) event: exit default callback.

```

Some important notes:
- WiFi AP is fully working and we have tens of other devices connected and working (some of them are ESP8266, connected and fully working since 1 year ago!)
- It's weird to get bcn_timout after exactly 10000 seconds. It sounds like a problem related to ESP32 firmware and not the AP
- In our application we use both WiFi e BLE together, so maybe it's a matter of coordination between those 2 peripherals
- Restarting board (not with a power cycle but simply using EN input), ESP did immediately connect to AP successfully

**Comment by igrr** [comment] 2017-12-13 09:36
> we have default settings for watchdog, so nothing registered but idle task.

That does explain why the watchdog does not restart the system in this case.

**Comment by 0BackDoor1** [comment] 2017-12-19 09:45
@zhangyanjiaoesp thank you, it worked even on my case

**Comment by avrmp** [comment] 2019-01-07 00:49
So 

> > we have default settings for watchdog, so nothing registered but idle task.
> 
> That does explain why the watchdog does not restart the system in this case.

Even with the task watchdog enabled, it still won't reset. Also this solution is not working for me!

**Comment by suda-morris** [comment] 2019-01-31 02:39
Hi @avrmp Would you please post your issue here with more detailed information?

**Comment by liuzfesp** [comment] 2020-03-12 02:33
@avrmp feel free to open a new issue if you still encounter the `watchdog not trigger issue`, I would like to close this issue since we have no way to replicate it.

**Comment by Alvin1Zhang** [comment] 2020-03-12 02:41
@avrmp Thanks for reporting.

**Closed by Alvin1Zhang** 2020-03-12 02:41 UTC

**Comment by mriksman** [comment] 2020-05-01 10:19
> char task_name[16];
> char *cur_task = pcTaskGetTaskName(xTaskGetCurrentTaskHandle());
> strncpy(task_name, cur_task, 16);
> task_name[15] = 0;
> if (strncmp(task_name, "tiT", 16) == 0) {
> vprintf(log_format,arguments_list);
> }

Amazing. After all this time, this post solved my issue. I spent a day on this baffled as to why `sendto` was the issue. I'm using it on the ESP8266 with `esp_log_set_putchar`
```c
int udp_logging_putchar( int chr )
{
    size_t len = strlen(buf);
    buf[len] = chr;
    buf[len + 1] = '\0';

    if (chr == '\n') {
        char task_name[16];
        char *cur_task = pcTaskGetTaskName(xTaskGetCurrentTaskHandle());
        strncpy(task_name, cur_task, 16);
        task_name[15] = 0;
        if (strncmp(task_name, "tiT", 16) != 0) {

            if (udp_log_fd >= 0)
            {
                sendto(udp_log_fd, buf, len+1, 0, (struct sockaddr *)&udp_log_socket, sizeof(udp_log_socket));
            }
        // 'clear' string
        buf[0] = '\0';
        }
    }
	return old_function( chr );
}
```
