### ISSUE TITLE
Build esp-idf-template with eclipse, Cann't find sdkconfig.h

### ISSUE THREAD

**Issue by AnalogLamb** [espressif/esp-idf#32] opened 2016-09-29 08:57 UTC
@projectgus 

There is two errors:

First, cfg = WIFI_INIT_CONFIG_DEFAULT();  //Syntax Error
Second, cannot find sdkconfig.h

![cannot_find_sdkconfig_h](https://cloud.githubusercontent.com/assets/7963385/18947452/bb9bffd4-8665-11e6-972b-0f281612bb0c.jpg)

**Comment by projectgus** [comment] 2016-10-03 22:58
Hi @AnalogLamb,

Thanks for reporting this issue. There is a problem opening esp-idf projects in Eclipse on Windows right now. #17 describes the issue as well - the build succeeds but Eclipse fails to find all the header directories parsing the build output, so it reports these kind of errors.

You can work around the issue for now by editing the "Include directories" for the project, as mentioned in the other issue. But we're working on a fix now.

I'm going to close this issue as a duplicate of #17, but please Subscribe to the other issue for updates to the bug.

Thanks,

Angus

**Closed by projectgus** 2016-10-03 22:58 UTC
Labels: duplicate
