### ISSUE TITLE
Update PlatformIO to latest (4.4 as of writing) (IDFGH-6723)

### ISSUE THREAD

**Issue by rbray89** [espressif/esp-idf#8352] opened 2022-02-04 18:11 UTC
https://registry.platformio.org/tools/platformio/framework-espidf should be update to the latest release of esp-idf (4.4 as of writing)

**Comment by negativekelvin** [comment] 2022-02-04 22:19
If you notice the owner of that package is platformio so I don't think espressif can update it

**Comment by rbray89** [comment] 2022-02-04 23:04
@negativekelvin I filed a ticket here as well, after looking for a long time to find a more appropriate place to file: https://github.com/platformio/platformio-registry/issues/7

**Comment by Jason2866** [comment] 2022-02-06 19:11
Afaik Submitting packages to platformio registry is moved from platformio to espressif.
(Same as for the toolchains). So requesting here seems the right place.
@pedrominatel  is this correct for idf releases?

**Comment by igrr** [comment] 2022-02-06 20:13
@Jason2866 I don't think so... @me-no-dev does have a way of uploading the toolchain packages (they show up in `espressif` namespace in platformio registry), however other packages (openocd-esp32, platform-espressif32) are under `platformio` namespace in platformio registry, so AFAIK we can't update them directly.

**Comment by Jason2866** [comment] 2022-02-06 22:07
@igrr There is no restriction in uploading. If you upload the package it will be usable under ownership `espressif`. Older packages are still under the ownership `platformio`.
Same as it is for the toolchains. Old ones are still under the ownership of platformio.
So @me-no-dev or anyone who is a member in the platformio team account can upload packages in platformio registry (as owner espressif).

**Comment by igrr** [comment] 2022-02-07 00:38
@Jason2866 Right, but then the resulting package would appear at https://registry.platformio.org/tools/espressif/framework-espidf and not https://registry.platformio.org/tools/platformio/framework-espidf, which I think is what the issue reporter is asking for?

**Comment by Jason2866** [comment] 2022-02-07 10:32
@igrr Since the newer toolchains are already with the ownership `espressif` t would be imho no problem to have all "other" from espressif in platformio registry.
For the platformio maintained framework it is just a change in the  [platform.json](https://github.com/platformio/platform-espressif32/blob/develop/platform.json) of the owner. I think Platformio crew would be grateful if the have less package pack work

**Comment by igrr** [comment] 2022-04-05 21:33
@Jason2866 sorry for the late response. I have confirmed with PlatformIO folks that Espressif can perform updates of tools and libraries in PIO registry. Updates of development frameworks is a different matter which requires a contract with PIO. We are in the process of sorting out the details.

**Comment by VojtechBartoska** [comment] 2024-08-22 13:46
I am closing this ticket as expired. Original discussion was already answered. Thanks for understanding.

**Closed by VojtechBartoska** 2024-08-22 13:46 UTC
Labels: Type: Feature Request, Status: Opened
