### ISSUE TITLE
WIFI/BT(BLE) Simultaneously? (IDFGH-7146)

### ISSUE THREAD

**Issue by bini2007** [espressif/esp-idf#8749] opened 2022-04-08 01:42 UTC
I'm working on a project that uses both Wifi (specifically the http_client component) as well as BLE.

They both seem to work great separately.

However, once Wifi establishes a connection and starts working (a small http request every second or so), the BLE feels starved. It takes a very long time to get connected, reads take in the order of seconds, and I often get disconnected.

Any idea what could cause this behavior?

 

Either I must be doing something wrong, or there's an issue with the stack.
Is there an example that does WIFI and BLE at the same time? Is it expected to work fine?

 

I guess,

the problem is that they share a radio; in other words, while the ESP32 is sending/receiving a BT packet, it cannot listen or send a WiFi packet.

Thanks,

**Comment by xiongweichao** [comment] 2022-04-11 02:03
Hi @bini2007 

Please refer to this [coexistence document](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/coexist.html). If this issue still exists, please provide the idf commit id and the demo (include sdkconfig) that reproduces the issue.

Thanks

**Comment by xiongweichao** [comment] 2022-04-12 02:05
Hi @bini2007 

Please provide the `.elf`  file for us to debug.

Thanks

**Comment by xiongweichao** [comment] 2022-04-12 02:06
Hi @bini2007 

Please provide the `.elf`  file for us to debug.

Thanks

**Comment by bini2007** [comment] 2022-04-12 03:30
the elf file can be downloaded in the link [https://github.com/bini2007/esp32-elf-debug/blob/main/esp32-welle.elf](https://github.com/bini2007/esp32-elf-debug/blob/main/esp32-welle.elf)

**Comment by bini2007** [comment] 2022-04-15 02:25
@[xiongweichao](https://github.com/xiongweichao)

We wonder how the debugging is going well using elf file.

**Comment by bini2007** [comment] 2022-04-18 03:50
We debugged using JTAG debugger on vscode.
So we captured such a following screen shot, however we don't know how to fix it.

![ble-con1-화면 캡처 2022-04-18 112836](https://user-images.githubusercontent.com/94033981/163751360-09288f68-f002-44a7-8c0a-e1ade0ecce74.png)

The PC shows below codes in IDF source:
void* malloc(size_t size)
{
    return heap_caps_malloc_default(size);  <--- The problem point when connection to server(slave) device with ble.
}


Then any advice!

**Comment by ESP-Marius** [comment] 2023-04-26 09:15
Sorry for the delayed follow-up on this one.

If we look at the backtrace we can see that the crash seems when we try to take a heap lock to do a malloc. The lock seems to point to random value 0x0000ff08, instead of a writeable memory area. So we get a store-prohibited. 

Typically this is due to memory corruption, something overwrite this heap allocated lock. For some general suggestion on how to debug these errors you can see [heap-corruption-detection](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html#heap-corruption-detection).

Closing this issue for now as it is quite old, but feel free to reopen it again if you are still experiencing problems.

**Closed** 2023-05-24 03:03 UTC
Labels: Status: Done, Resolution: Cannot Reproduce
