### ISSUE TITLE
[TW#18311] Bluetooth transmission problem

### ISSUE THREAD

**Issue by wangweidaai** [espressif/esp-idf#1562] opened 2018-01-30 00:45 UTC
use a2dp_source example，When you turn off the bluetooth headset, esp32 reports the error and restarts the program.

**Comment by Weijian-Espressif** [comment] 2018-02-11 08:07
@blueMoodBHD please help review the issue.

**Comment by blueMoodBHD** [comment] 2018-03-05 07:34
@wangweidaai Because I did not reproduce the problem, can you provide the relevant log? Thanks

**Comment by FayeY** [comment] 2018-03-22 06:26
Closing as can't reproduce. Please reopen if the issue persists and you can supply more details. Thanks.

**Closed by FayeY** 2018-03-22 06:26 UTC
