### ISSUE TITLE
WiFi error: Guru Meditation Error: Core 1 panic'ed (IllegalInstruction) (IDFGH-3932)

### ISSUE THREAD

**Issue by jarcos-al** [espressif/esp-idf#5822] opened 2020-09-03 10:31 UTC
Hello everyone. ;)  I am Jorge and I'm new on this forum.

Currently, I'm developing a firmware in a ESP32 module for create a custom hub.

I have an ESP32-Wrover-E module (16MB spi flash) and I have an issue with WiFi that i can't fix.
I'm using ESP-IDF  v4.3-dev, SPI speed: 40 MHz and SPI Mode: DIO.

The problem reported by the IDF Serial Monitor is this when the WiFi has been connected to an AP for a while:

""Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x4013f504: 04606502 0000f01d ad004136
Core  1 register dump:
PC      : 0x4013f508  PS      : 0x00060130  A0      : 0x00040020  A1      : 0x3ffc1f90  
A2      : 0x3ffdd1a8  A3      : 0x00001770  A4      : 0x00000000  A5      : 0x3ffb1a68  
A6      : 0x3ffb6460  A7      : 0x00000001  A8      : 0x8013f508  A9      : 0x3ffc1f70  
A10     : 0x3ffdd1a8  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x005b8d80  
A14     : 0x3ffb6460  A15     : 0x3ffb5a50  SAR     : 0x00000018  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x4012c180  LEND    : 0x4012c1ab  LCOUNT  : 0x00000007  

Backtrace:0x4013f505:0x3ffc1f90 0x0004001d:0x3ffc1fb0 |<-CORRUPTED

ELF file SHA256: 4c36298654fdb336

Rebooting...""

I have tried other ESP32 modules (wrover b in a ESP32-Wrover-Kit v4.1 and ESP32-WROOM-32 in ESP32- Devkit-C) and others power suply and dc regulators for discard a power suply issue.
I have also put capacitors of 2200 uf value to the 3.3 v in pin.

The error tends to appear randomly at runtime, so it is impossible for me to debug it. :? 

Can anyone help me to fix this problem?

Thanks in advance.

## Environment

- Development Kit:      [ESP32-Wrover-Kit]
- Kit version (for WroverKit/PicoKit/DevKitC): [v4]
- Module or chip used:  [ESP32-WROVER-B]
- IDF version (run ``git describe --tags`` to find it):
    

v4.3-dev-771-gc77c4ccf6-dirty
- Build System:         [CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r2) 8.2.0
- Operating System:   [Linux]
- Using an IDE?: [Yes (Eclipse)]
- Power Supply:         [external 3.3V]

## Debug Logs

```
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7116
load:0x40078000,len:13852
ho 0 tail 12 room 4
load:0x40080400,len:3952
entry 0x40080678
I (31) boot: ESP-IDF v4.3-dev-771-gc77c4ccf6-dirty 2nd stage bootloader
I (31) boot: compile time 15:11:03
I (32) boot: chip revision: 3
I (36) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (43) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (52) boot.esp32: SPI Flash Size : 4MB
I (57) boot: Enabling RNG early entropy source...
I (62) boot: Partition Table:
I (66) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (88) boot:  2 factory          factory app      00 00 00010000 00100000
I (95) boot: End of partition table
I (99) boot_comm: chip revision: 3, min. application chip revision: 0
I (107) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x28258 (164440) map
I (178) esp_image: segment 1: paddr=0x00038280 vaddr=0x3ffb0000 size=0x03bc4 ( 15300) load
I (185) esp_image: segment 2: paddr=0x0003be4c vaddr=0x40080000 size=0x00404 (  1028) load
I (185) esp_image: segment 3: paddr=0x0003c258 vaddr=0x40080404 size=0x03dc0 ( 15808) load
I (201) esp_image: segment 4: paddr=0x00040020 vaddr=0x400d0020 size=0xa41a0 (672160) map
I (459) esp_image: segment 5: paddr=0x000e41c8 vaddr=0x400841c4 size=0x149c0 ( 84416) load
I (496) esp_image: segment 6: paddr=0x000f8b90 vaddr=0x400c0000 size=0x00064 (   100) load
I (509) boot: Loaded app from partition at offset 0x10000
I (509) boot: Disabling RNG early entropy source...
I (521) cpu_start: Pro cpu up.
I (521) cpu_start: Starting app cpu, entry point is 0x40081620
I (506) cpu_start: App cpu up.
I (537) cpu_start: Pro cpu start user code
I (537) cpu_start: Application information:
I (537) cpu_start: Project name:     miniHUB
I (542) cpu_start: App version:      a2c9f55-dirty
I (548) cpu_start: Compile time:     Sep  2 2020 15:55:27
I (554) cpu_start: ELF file SHA256:  4c36298654fdb336...
I (560) cpu_start: ESP-IDF:          v4.3-dev-771-gc77c4ccf6-dirty
I (567) heap_init: Initializing. RAM available for dynamic allocation:
I (574) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (580) heap_init: At 3FFB97F8 len 00026808 (154 KiB): DRAM
I (586) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (593) heap_init: At 3FFE4350 len 00013CB0 (79 KiB): D/IRAM
I (599) heap_init: At 40098B84 len 0000747C (29 KiB): IRAM
I (606) spi_flash: detected chip: gd
I (610) spi_flash: flash io: dio
W (613) spi_flash: Detected size(16384k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
I (628) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (752) wifi:wifi driver task: 3ffc21e8, prio:23, stack:6656, core=1
I (00:00:00.087) system_api: Base MAC address is not set
I (00:00:00.088) system_api: read default base MAC address from EFUSE
I (782) wifi:wifi firmware version: 9c89486
I (782) wifi:wifi certification version: v7.0
I (782) wifi:config NVS flash: enabled
I (782) wifi:config nano formating: disabled
I (782) wifi:Init data frame dynamic rx buffer num: 64
I (792) wifi:Init management frame dynamic rx buffer num: 64
I (792) wifi:Init management short buffer num: 32
I (802) wifi:Init dynamic tx buffer num: 64
I (802) wifi:Init static rx buffer size: 1600
I (802) wifi:Init static rx buffer num: 16
I (812) wifi:Init dynamic rx buffer num: 64
I (912) phy: phy_version: 4350, 18c5e94, Jul 27 2020, 21:04:07, 0, 0
I (912) wifi:mode : null
I (912) wifi:Set ps type: 1

I (00:00:00.252) uart: queue free spaces: 20
CPU0 reset reason: E (00:00:00.255) RESET_REASON:: SW_CPU_RESET
CPU1 reset reason: E (00:00:00.261) RESET_REASON:: SW_CPU_RESET
I (00:00:00.267) MQTTS: [APP] Free memory: 174248 bytes

Type 'help' to get the list of commands.
Use UP/DOWN arrows to navigate through command history.
Press TAB when typing command name to auto-complete.

 ==================================================
 |          Welcome to MiniHUB console!           |
 |                                                |
 |  1. Print 'help' to gain overview of commands  |
 |  2. Configure device to station or soft-AP     |
 |  3. Setup WiFi connection                      |
 |  4. Connect to MQTT                                    |
 |                                                |
 ================================================
Reading ap_list from NVS ... 
The flash reading has been done successfully
                                                                                                                                                    
I (1092) wifi:mode : sta (10:52:1c:87:29:d8)
I (00:00:00.435) WiFi: WiFi ready
MiniHUB> I (00:00:02.485) WiFi: [pruebas][rssi=-50]
I (00:00:02.487) WiFi: sta scan done
I (00:00:02.488) WiFi: 1 AP's scanned

I (00:00:02.501) RECONNECT: SSID pruebas found
I (3182) wifi:Set ps type: 1

I (3302) wifi:new:<1,0>, old:<1,1>, ap:<255,255>, sta:<1,0>, prof:1
I (4082) wifi:state: init -> auth (b0)
I (4092) wifi:state: auth -> assoc (0)
I (4092) wifi:state: assoc -> run (10)
I (4102) wifi:connected with pruebas, aid = 3, channel 1, BW20, bssid = f0:9f:c2:f1:ea:0b
I (4102) wifi:security: WPA2-PSK, phy: bgn, rssi: -48
I (4112) wifi:pm start, type: 1
I (4182) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (00:00:05.576) esp_netif_handlers: sta ip: 192.168.2.190, mask: 255.255.252.0, gw: 192.168.1.1

I (00:00:18.486) MQTTS: Other event id:7
I (00:00:20.309) MQTTS: MQTT_EVENT_CONNECTED
I (00:00:20.311) MQTTS: Connected to MQTT server
I (00:00:20.316) MQTTS: publish, msg_id=0
I (00:00:20.322) MQTTS: MQTT_EVENT_DATA

**(Minutes later...)**

Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x4013f504: 04606502 0000f01d ad004136
Core  1 register dump:
PC      : 0x4013f508  PS      : 0x00060d30  A0      : 0x00040020  A1      : 0x3ffc1f90  
A2      : 0x3ffdd1a4  A3      : 0x00001770  A4      : 0x00000000  A5      : 0x3ffb1a68  
A6      : 0x3ffb6460  A7      : 0x00000001  A8      : 0x8013f508  A9      : 0x3ffc1f70  
A10     : 0x3ffdd1a4  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x005b8d80  
A14     : 0x3ffb6460  A15     : 0x3ffb5a50  SAR     : 0x00000018  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x4012c180  LEND    : 0x4012c1ab  LCOUNT  : 0x00000007  

Backtrace:0x4013f505:0x3ffc1f90 0x0004001d:0x3ffc1fb0 |<-CORRUPTED


ELF file SHA256: 4c36298654fdb336

Rebooting...
```

## Other items if possible

- [x] sdkconfig file (attach the sdkconfig file from your project folder)
[attachments.zip](https://github.com/espressif/esp-idf/files/5167897/attachments.zip)

**Comment by liuzfesp** [comment] 2020-09-03 13:22
Hi @jarcos-al please help to attach the *.elf file here and then I can analyze the backtrace of the crashing. You can find the *.elf file under the project/build dir, e.g. the iperf.elf is located under $IDF_PATH/examples/wifi/iperf/build. 

Also notified that the *.elf file should be the one which is generated at the same time as the *.bin file that triggers the crashing. If you project is re-compile, then you may need take following steps to reproduce it:

- Re-build the project, and keep the *.elf/*.bin
- Reproduce the crashing and attach the log and *.elf here

**Comment by igrr** [comment] 2020-09-03 15:36
Judging by the symptoms (IllegalInstruction with A0 register containing 0x40020), this seems to be the same issue as https://github.com/espressif/esp-idf/issues/5758 — the fix for it is in review and should be merged soon.

**Comment by jarcos-al** [comment] 2020-09-04 07:29
@igrr, I confirm, the issue is due to Heap tracing in mode 'Standalone'. I have desactivated this option in the sdkconfig and the problem has not reappeared.
Thanks for the support!

**Closed** 2020-09-04 10:32 UTC
