### ISSUE TITLE
erase-otadata failed (IDFGH-7254)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#8843] opened 2022-04-26 21:28 UTC
Master branch, just updated.
```
Executing action: erase-otadata
Serial port /dev/ttyUSB0
Connecting...
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting...
Detecting chip type... ESP32
Running ninja in directory /home/chegewara/esp/master/examples/get-started/hello_world/build
Executing "ninja erase-otadata"...
ninja: error: unknown target 'erase-otadata'
ninja failed with exit code 1
```

Thanks

**Comment by dobairoland** [comment] 2022-04-27 09:13
Hi @chegewara. Are you running this in the unmodified `get-started/hello_world` example? Ota commands should not work there because there is no OTA partition defined in that project. 

But unfortunately, there is another issue which would you get for an OTA project. We try to fix this soon. The `master` branch is affected. v4.4 should work fine. I'm sorry for the inconvenience.

**Comment by KaeLL** [comment] 2022-04-27 16:31
> there is another issue which would you get for an OTA project. We try to fix this soon. The master branch is affected. 

@dobairoland could you link or detail the issue?

**Comment by dobairoland** [comment] 2022-04-27 16:53
It is not tracked on github. We've noticed that issuing for example `idf.py erase-otadata` prints only a couple of lines but nothing happens. I need to investigate more. I'll link the fix here and keep open this one until then.

**Comment by dobairoland** [comment] 2022-05-20 12:23
The fix is in progress. It should make into v5.0. No released versions are affected. The issue is present only in the master branch.

**Closed** 2022-05-29 00:42 UTC
Labels: Status: Done, Resolution: Done
