### ISSUE TITLE
Ch340/41 usb driver for esp32 s3 Any one help me out on this? (IDFGH-8156)

### ISSUE THREAD

**Issue by THEDSP** [espressif/esp-idf#9652] opened 2022-08-27 05:16 UTC
### Is your feature request related to a problem?

I just trying to communicate with device which has ch340/41 usb chip i want to esp32 s3 to make communicate with it as host 

- i already try esp-idf usb host cdc lib but it does not work the descriptor read is working but how to set up for device ch340 in simple word to write the driver for ch340 i trying to replicate the ftdi driver given by the esp but i cant make it working so there is any one who help me out on this.

**Comment by AristarchosOfSamos** [comment] 2022-08-28 15:17
-> [[https://github.com/espressif/esp-idf/issues/8951#issuecomment-1177577056](url)](https://github.com/espressif/esp-idf/issues/8951#issuecomment-1177577056)

**Comment by tore-espressif** [comment] 2022-08-29 05:22
Hello @THEDSP ,
As @AristarchosOfSamos pointed out, this is a duplicate of https://github.com/espressif/esp-idf/issues/8951 you can find link to CH34x driver there.

The reason why we didn't merge it to `master` branch of esp-idf is that we don't want to add device drivers into the esp-idf, but rather have separate projects for drivers such as this (although, we got a little delayed with this plan).

**Comment by THEDSP** [comment] 2022-08-30 11:14
thanks a lot I checked it out but i can not compile it succusses fully can  you help me on this tore

**Comment by THEDSP** [comment] 2022-08-30 11:36
> Hello @THEDSP , As @AristarchosOfSamos pointed out, this is a duplicate of #8951 you can find link to CH34x driver there.
> 
> The reason why we didn't merge it to `master` branch of esp-idf is that we don't want to add device drivers into the esp-idf, but rather have separate projects for drivers such as this (although, we got a little delayed with this plan).

i can't compile this please help me out on this

**Comment by tore-espressif** [comment] 2022-08-31 16:26
From the log I can see that `cdc_acm_host.h` header file is included correctly, but `cdc_acm_host.c` is not compiled.

Navigate to your project root and `usb_host_cdc_acm` component to your project. run :
```
 idf.py add-dependency usb_host_cdc_acm
```

This will add the dependency to your `main` component. If you need to add the dependency to another_componenet run
```
 idf.py add-dependency usb_host_cdc_acm --component another_component
 ```

**Comment by THEDSP** [comment] 2022-09-01 07:07
hello 

> From the log I can see that `cdc_acm_host.h` header file is included correctly, but `cdc_acm_host.c` is not compiled.
> 
> Navigate to your project root and `usb_host_cdc_acm` component to your project. run :
> 
> ```
>  idf.py add-dependency usb_host_cdc_acm
> ```
> 
> This will add the dependency to your `main` component. If you need to add the dependency to another_componenet run
> 
> ```
>  idf.py add-dependency usb_host_cdc_acm --component another_component
> ```

Hello sir thanks 
Now i successfully compiled the code and attach usb to it But first the program is stuck at Opening CH340 device
and after time device rebooted .
I further debug it so I found out the PID of my ch341 is 5512 instead of 5522 mentioned in .hpp file so I changed it to my PID
now the code will stuck at Setting up line coding so what we can do to work it properly.

**Comment by tore-espressif** [comment] 2022-09-01 07:29
@THEDSP PID 0x5512 means that your CH341 is programmed for 'EPP/MEM/I2C mode, EPP/I2C adapter'.

The driver that I gave you is for 'UART' mode. Unfortunately, I don't have this device, so I can't help you much.

What you can do is to capture USB communication between the device and USB Host (PC), on Windows you can use Wireshark. 
And then replicate the communication with ESP, by modifing the CH340 UART driver

Regards, Tomas

**Comment by THEDSP** [comment] 2022-09-01 07:57
can you mailed me in personal I have some thing urgent to discuss with you?

**Comment by THEDSP** [comment] 2022-09-01 09:29
I will try to work on as you said and let you updated on that and if you contact me on mail we can discus more in details

**Comment by THEDSP** [comment] 2022-09-01 14:01
i found linux driver for ch341 for epp i2c mode so how can we port them in to the esp.
https://github.com/zoobab/ch341-parport/tree/master/CH341PAR_LINUX
where to start any hint ?

**Comment by THEDSP** [comment] 2022-09-07 07:06
Hello any update on this?

**Comment by THEDSP** [comment] 2022-09-07 07:10
Can you guide me for raw fiction to communicate with the usb host

**Comment by THEDSP** [comment] 2022-09-07 07:10
how to set up packet brrequest and so on

**Comment by tore-espressif** [comment] 2022-12-06 08:08
CH34x driver released https://components.espressif.com/components/espressif/usb_host_ch34x_vcp

The example will be updated soon

**Closed** 2022-12-13 07:45 UTC
Labels: Type: Feature Request, Status: Reviewing

**Comment by chegewara** [comment] 2023-02-25 04:42
Hi @tore-espressif 
i see this note in component:
`Limited implementation only. The vendor does not provide full specification.`
I just found this piece of code and i believe it may help to reverse engineer CH341 and to improve espressif driver.:
https://github.com/openwch/ch583/blob/main/EVT/EXAM/USB/Device/COM/src/Main.c#L562-L588

I hope this help in future.

**Comment by tore-espressif** [comment] 2023-03-08 07:05
Hi @chegewara ,
Thank your for the link! Yes, most of the current driver is reverse-engineered from similar sources.

We are trying to define boundaries for support of these 3rd party components, ATM we provide the support only if more users are asking about the same feature. In case of CH341 it seems that the basic TX/RX support is enough for most usecases :)
