### ISSUE TITLE
ESP32 without PSRAM Wifi connection (IDFGH-10951)

### ISSUE THREAD

**Issue by alberk8** [espressif/esp-idf#12143] opened 2023-08-27 00:25 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

I have ESP32 Rev3 with IDF 4.4.5.   If I compile firmware with PSRAM enabled and deployed onto a hardware without PSRAM then wifi will not connect.  Is there a way to get that to work?

```
CONFIG_ESP32_REV_MIN_3=y
CONFIG_ESP32_SPIRAM_SUPPORT=y
CONFIG_ESP32_DEFAULT_CPU_FREQ_240=y
CONFIG_SPIRAM_BOOT_INIT=y
CONFIG_SPIRAM_IGNORE_NOTFOUND=y
CONFIG_SPIRAM_USE_MEMMAP=n
CONFIG_SPIRAM_USE_CAPS_ALLOC=n
CONFIG_SPIRAM_USE_MALLOC=y
CONFIG_SPIRAM_TYPE_AUTO=y
CONFIG_SPIRAM_TYPE_ESPPSRAM32=n
CONFIG_SPIRAM_TYPE_ESPPSRAM64=n
CONFIG_SPIRAM_SIZE=-1
CONFIG_SPIRAM_SPEED_40M=y
```

**Comment by alberk8** [comment] 2023-09-19 05:48
Hi,
Can someone confirm this?  Thank you.

**Comment by jimmo** [comment] 2023-11-09 01:01
We're seeing this too. (Duplicate of https://github.com/espressif/esp-idf/issues/11971)

**Comment by mhdong** [comment] 2024-03-22 07:54
Hi @alberk8 
please refer https://github.com/nanoframework/nf-interpreter/pull/2837
Issue solved with https://github.com/espressif/esp-idf/commit/f37448cddb395939d2a168fdd86dbb0cd868fc59

**Comment by Sherry616** [comment] 2024-04-24 03:23
Thanks for reporting, we will close this issue. Feel free to reopen if have more updates. 
Thanks for using our Espressif product!

**Closed by Sherry616** 2024-04-24 03:23 UTC
Labels: Awaiting Response, Status: Reviewing
