### ISSUE TITLE
[esp32 C3 rev1] wifi build error (IDFGH-6277)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#7946] opened 2021-11-22 01:16 UTC
esp-idf: 4a011f318377ab717b9dc459019c1055602c93ff
board: esp32 C3 rev1

```
/home/chegewara/.espressif/tools/riscv32-esp-elf/esp-2021r2-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /home/chegewara/esp/master/components/esp_phy/lib/esp32c3/libphy.a(phy_chip_v7.o): in function `phy_get_romfunc_addr':
(.text.phy_get_romfunc_addr+0x1a): undefined reference to `rom_temp_to_power'
```
For minimum `rev1` it fail to build, for `rev3` it is ok (i didnt test other rev versions).

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/7577603/sdkconfig.txt)
Thanks

**Comment by xueyunfei998** [comment] 2021-11-22 03:59
hi @chegewara 

Which example do you use to make compilation errors? I'll try to reproduce this problem locally

**Comment by chegewara** [comment] 2021-11-22 04:10
It is my custom code with C++ class. Code works good with S3, can be build with C3 rev3, but fail to build with C3 rev1.
I am guessing it should fail with any espressif example.

It was my "faul", because i thought i have C3 rev1, when in fact i do have C3 rev2, but that is not changing the fact i cant build app.

**Comment by xueyunfei998** [comment] 2021-11-22 06:41
hi @chegewara 
If the problem is solved, you can close the problem. Thanks

**Comment by chegewara** [comment] 2021-11-22 06:45
I dont know if problem is solved, wifi app still does not build for C3 rev1.

**Comment by xueyunfei998** [comment] 2021-11-22 07:47
hi @chegewara 
I suggest you use it directly C3 rev3.
There may be some problems with C3 Rev1. C3 Rev3 has been fixed

**Comment by chegewara** [comment] 2021-11-22 07:50
i can do that, but what will do someone with C3 rev1?

I am not asking for suggestion, but reporting problem with build wifi app.

**Comment by chegewara** [comment] 2021-11-22 19:45
To make it easier to reproduce:
https://github.com/espressif/esp-idf/tree/master/examples/wifi/scan
esp-idf: App "scan" version: v5.0-dev-329-g4a011f3183
```
/home/chegewara/.espressif/tools/riscv32-esp-elf/esp-2021r2-8.4.0/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/8.4.0/../../../../riscv32-esp-elf/bin/ld: /home/chegewara/esp/master/components/esp_phy/lib/esp32c3/libphy.a(phy_chip_v7.o): in function `phy_get_romfunc_addr':
(.text.phy_get_romfunc_addr+0x1a): undefined reference to `rom_temp_to_power'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```
[sdkconfig.rev1.txt](https://github.com/espressif/esp-idf/files/7583904/sdkconfig.txt)
[sdkconfig.rev2.txt](https://github.com/espressif/esp-idf/files/7583923/sdkconfig.rev2.txt)

Just to make sure i tried to build for esp32C3 rev2 and also failed with the same error, so:
- severity: BUG
- importance: high 
- additional steps: better test case maybe??

**Comment by xueyunfei998** [comment] 2021-11-23 08:12
hi @chegewara 
I compile this example with that commit id you provide, esp-idf: App "scan" version: v5.0-dev-329-g4a011f3183

https://github.com/espressif/esp-idf/tree/master/examples/wifi/scan

My compilation here can pass.

You can follow the following steps:

idf.py set-target esp32c3

idf.py build

![c374153f-0835-42af-b88c-2d9faa9cf769](https://user-images.githubusercontent.com/52622915/142989498-a9da7a56-1448-4871-b111-2f549bc8d2cc.jpg)

**Comment by chegewara** [comment] 2021-11-23 08:18
Yes, it pass for C3 rev3, which is default settings. Like i said, it fail for C3 rev1 and rev2.

**Comment by 0xjakob** [comment] 2021-11-24 02:17
@chegewara confirmed, with **Chip revision 2** there's a linker error. I'll take a look at it.

**Comment by 0xjakob** [comment] 2021-11-24 02:53
`rom_temp_to_power` is provided in the [revision 3 linker script](https://github.com/espressif/esp-idf/blob/master/components/esp_rom/esp32c3/ld/esp32c3.rom.eco3.ld#L30). But for some reason, it's not provided in the [revision <3 linker script](https://github.com/espressif/esp-idf/blob/master/components/esp_rom/esp32c3/ld/esp32c3.rom.ld#L1899). 

`rom_temp_to_power` is required by `libphy.a` but not provided on revision < 3, because of the linker script.
In revision 3, `rom_temp_to_power` is provided by the rom code.

I'll pass it to the relevant colleagues, since I'm not familiar with libphy.a.

**Comment by chegewara** [comment] 2021-11-24 02:55
Not a problem, as long as it can be solved.

Thanks

**Comment by xueyunfei998** [comment] 2021-11-25 02:53
hi @chegewara 

After our internal discussion, at present, rev1 rev2 and idf have stopped maintenance, so it is recommended to use rev3 directly.

**Comment by AxelLin** [comment] 2021-11-25 03:21
> hi @chegewara
> 
> After our internal discussion, at present, rev1 rev2 and idf have stopped maintenance, so it is recommended to use rev3 directly.

So you are asking people to throw away the rev1,rev2 devices and buy a new one with rev3?

**Comment by chegewara** [comment] 2021-11-25 03:24
Thanks a lot for letting us know we are not important to get fix, again, and by "us" i mean all people who were stupid enough to buy espressif boards earlier.
Now we have wifi featured boards without wifi support. 
Since its not an issue to espressif i am closing it.

**Comment by chegewara** [comment] 2021-11-25 04:00
PS in that case i am suggesting to remove minimum revision select option from menuconfig, to not make us confused.

**Comment by TianaESP** [comment] 2021-11-25 04:02
Hi @AxelLin @chegewara, sorry for letting you have such a bad experience on this. Please let me have a brief clarification. 
As far as I know, we sent rev1 and rev2 to customers mainly for pre-study and evaluation, even we know we will have further updates on silicons(like rev3) at that time. We value customers' feedback, so we want to share with you although they are “uncompleted” or "limited". However, we recommend customers build MP products with the rev3, which is better and shares the largest marketing. from my knowledge, rev3 is the only version we produce now. 
If you are using rev1 and rev2 for MP, of course, we will keep supporting you with your questions. But, if it is possible for you to switch to rev3, we would be grateful. 
Thanks for your suggestions wrt removing minimum revision select option from menuconfig. If you have any questions or concerns. Please feel free to ask.
Tiana

**Comment by chegewara** [comment] 2021-11-25 04:09
That sounds reasonable, but is not actually full story.
I bought my 5 C3 from mouser and i believe there are hundreds or even thousands C3 boards sold on mouser, maybe also digkey and/or amazon. Sure, i can switch to rev3 as i am "lucky" enough and i have 2 C3 as a sample from espressif, but i still have 5 rev2 which are crap now. 
I can live with that, because i am earning enough on esp32 programming to buy new boards, but this is bug in closed wifi driver and we dont even cant fix it in forked repo.

**Comment by Jason2866** [comment] 2021-11-25 21:53
@chegewara have you tried to uncomment in [file](https://github.com/espressif/esp-idf/blob/master/components/esp_rom/esp32c3/ld/esp32c3.rom.ld#L1899)

**Comment by AxelLin** [comment] 2021-12-23 09:43
> hi @chegewara
> 
> After our internal discussion, at present, rev1 rev2 and idf have stopped maintenance, so it is recommended to use rev3 directly.

@xueyunfei998 @0xjakob 

I'm surprised that I hit this issue on v4.3.2.
If you don't want to support older h/w rev in master tree, that's fine.
But this is a **breaking** change, AFAICT, it should not happen on stable branches.

**Comment by denruss** [comment] 2021-12-28 07:34
I have the same problem, already have a solution?

**Comment by NHellFire** [comment] 2022-01-06 10:06
> @chegewara have you tried to uncomment in [file](https://github.com/espressif/esp-idf/blob/master/components/esp_rom/esp32c3/ld/esp32c3.rom.ld#L1899) [27ddbf5#diff-56ec23fe68028a0ce77e0eb47e28216ebb0c9f87cd1fbffe1df4e1c21abdf5ab](https://github.com/espressif/esp-idf/commit/27ddbf5fccb6122238c84e333fa5f50d25b6dd89#diff-56ec23fe68028a0ce77e0eb47e28216ebb0c9f87cd1fbffe1df4e1c21abdf5ab) Looks like not an dramatic issue when back again. Btw. I have a effected board too, which was NOT sold as development board...

I can confirm that reverting the edits to esp32c3.rom.ld makes WiFi functional on my rev2 sample.

**Comment by Seenov** [comment] 2022-01-10 20:11
The suggestion of using rev 3 is only practical if Espressif identifies the revisions of the chips in the part numbers and replaces the rev2 that were sold to customers. I have 2 Dev kits that have rev 3 parts ordered at the same time as qty 78 ESP32-C3-WROOM-02-N4 that are revision 2 (unknown to me at the time). I have another full reel of 500 pieces that have the same part number.  The Espressif factory label on the reel does not seem to identify the revision number. There is no information on the revision of the chips on the Mouser website
![IMG_3335](https://user-images.githubusercontent.com/4084840/148832512-2c7bd7db-15be-46e6-9237-adf399f19905.jpg)
.

**Comment by StanzaW** [comment] 2022-01-12 06:31
Hi Seeno, sorry. Please get in touch with our sales team sales@espressif.com. Our staff will help check the version of this whole reel and provide after-sales service, including changing them to v3 if they are v2.

**Comment by Seenov** [comment] 2022-01-12 18:16
Hi, this resolves the issue for the 500 pieces, but I have 2 other orders, one of 78 that are rev 2 and one of 178 that I will test shortly. Please keep the issue open. Thank you

**Comment by StanzaW** [comment] 2022-01-13 03:26
Hi Seenov, please get in touch with our sales team at sales@espressif.com and provide your contact address. Our staff will arrange rev 3 modules for you. There are a small amount of rev 2 modules on the market. We have decided not to provide further support for them.   Sorry.

**Comment by Seenov** [comment] 2022-01-13 20:31
Thanks, great customer service, I am impressed!

**Comment by pic16f887** [comment] 2022-01-26 11:13
With such "good" support for you products I am not sure that should use ESP32 C3 because my dev board is useless with up to date toolchain and usually sellers can't answer which revision of SoC is on the board.

**Comment by Seenov** [comment] 2022-01-26 16:06
Hello pic16f887, I think that reading the QRCode on the SoC, may produce info to determine the rev or the manufacture date. Ask Espressif about it. Here is a picture of the SoC on my rev 3 dev board. It was shipped from Mouser July 16th, 2021.
Good luck.
![Image-1](https://user-images.githubusercontent.com/4084840/151200136-0505c04c-17ad-4288-b837-b822cff8b5fb.jpg)
k

**Comment by AxelLin** [comment] 2022-02-23 06:23
https://docs.espressif.com/projects/espressif-esp-faq/en/latest/commercial-faq/index.html#how-can-i-tell-if-an-espressif-module-is-in-mass-production-or-an-npi-product

**Comment by vikeyfox** [comment] 2022-03-18 02:10
遇到了同样的问题，至少得给条活路吧，要不然买的几十片样片就报废了

**Comment by Jason2866** [comment] 2022-03-18 10:15
@vikeyfox as workaround you can use this [file](https://github.com/tasmota/esp-idf/blob/v4.4_dev/components/esp_rom/esp32c3/ld/esp32c3.rom.ld) and replace the orig. one.

**Comment by vikeyfox** [comment] 2022-03-19 03:41
> 



> @vikeyfox作为解决方法，您可以使用此[文件](https://github.com/tasmota/esp-idf/blob/v4.4_dev/components/esp_rom/esp32c3/ld/esp32c3.rom.ld)并替换原始文件。一。

OH,thankyou,I'll try

**Comment by brianlinuxing** [comment] 2022-11-29 18:03
I am very late to this, but I've got these errors with my Rev. 1 too.

My understanding is that is to fix this, in the short term, it is to adjust the esp32c3.rom.ld file?

Does anyone have a copy of the file that will work with ESP-IDF v4.4?

I tried following then link from @Jason2866 but it’s vanished, is there another one that is good?

Thanks in advance :)

**Comment by Jason2866** [comment] 2022-11-29 18:43
It is [here](https://github.com/tasmota/esp-idf/blob/Tasmota/v4.4/components/esp_rom/esp32c3/ld/esp32c3.rom.ld)

**Comment by brianlinuxing** [comment] 2022-12-03 15:59
Thank you so much @Jason2866 :)

**Comment by 0xjakob** [comment] 2023-02-28 11:30
We are closing this issue now. If you happen to have this very problem (old ESP32-C3 HW revision that is not supported by current IDF version), please contact sales as indicated above.

**Closed by 0xjakob** 2023-02-28 11:30 UTC
Labels: Status: Opened
