### ISSUE TITLE
portMAX_DELAY not leading to xStreamBufferReceive() waiting indefinitely (IDFGH-7239)

### ISSUE THREAD

**Issue by EN20M** [espressif/esp-idf#8833] opened 2022-04-25 15:08 UTC
## Problem Description

As stated in the [documentation ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos.html#_CPPv420xStreamBufferReceive20StreamBufferHandle_tPv6size_t10TickType_t) setting `xTicksToWait` to `portMAX_DELAY` should result in `xStreamBufferReceive` blocking untill the number of bytes set by `xTriggerLevel` is reached.

This works fine for me untill I try to pass a stream longer than ~113 bytes received from an UART clocked at 9.6k baud. The bytes get transmitted with gaps inbitween adding up to about 397ms for the 113 bytes. Anything longer than that and the `xStreamBufferReceive` returns priore to reaching the trigger level.

I suspect somthing similar to [this](https://github.com/aws/amazon-freertos/issues/1837) from another repository but it does not seem to be resolved.

**Comment by dereks-igor** [comment] 2022-04-29 22:10
You can test if it's the issue you linked to by defining this macro in your build (this is a workaround for the race condition):

```
	#define sbSEND_COMPLETED( pxStreamBuffer )											\
		vTaskSuspendAll();																\
		{																				\
			if( ( pxStreamBuffer )->xTaskWaitingToReceive != NULL && 						\
  			  prvBytesInBuffer( pxStreamBuffer ) >= pxStreamBuffer->xTriggerLevelBytes) \
			{																			\
				( void ) xTaskNotify( ( pxStreamBuffer )->xTaskWaitingToReceive,		\
									  ( uint32_t ) 0,									\
									  eNoAction );										\
				( pxStreamBuffer )->xTaskWaitingToReceive = NULL;						\
			}																			\
		}																				\
		( void ) xTaskResumeAll();
```

If adding that resolves the symptom, then it's the same root cause.

**Comment by moefear85** [comment] 2022-07-10 14:18
how much is actually returned, and what value is xTriggerLevel?

**Comment by EN20M** [comment] 2022-07-10 15:53
I'll have a look at that tomorrow and get you those numbers as soon as possible

**Comment by ESP-Marius** [comment] 2022-07-12 06:07
@EN20M Did some tests but wasn't able to replicate this.

Any chance you can share a simple example that can reproduce this issue?

If not then some more info might help us trace down what's happening:
* Like @moefear85 mentioned already: what is `xTriggerLevel` set to and how many bytes do receive return when it times out?
* Which IDF commit are you basing your project on?

**Comment by EN20M** [comment] 2022-07-12 07:49
in case you are interested heres the uart config:
```
void uart_init(void)
{
   const uart_config_t uart_config = {
       .baud_rate = 9600,
       .data_bits = UART_DATA_8_BITS,
       .parity = UART_PARITY_EVEN,
       .stop_bits = UART_STOP_BITS_1,
       .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,
       .source_clk = UART_SCLK_APB,
   };
   uart_driver_install(UART_NUM_1, RX_BUF_SIZE * 2, 0, 0, NULL, 0);
   uart_param_config(UART_NUM_1, &uart_config);
   uart_set_pin(UART_NUM_1, TXD_PIN, RXD_PIN, UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE);
}
```

**Comment by ESP-Marius** [comment] 2022-07-14 04:51
@EN20M As far as I know `xStreamBufferReceive` will only block until triggerLevel _if_ the message buffer is empty when you call the function. If there is e.g. 10 bytes there then it will return 10 bytes immediately, no matter what the trigger level is.

**Comment by moefear85** [comment] 2022-07-14 06:55
and triggerlevel is designed to be called in high frequency to delimit messages? i don't think that works because it assumes no data loss. one it happens, sender & reciever become desynchronized.

 i use magic strings and c++ string-search & size fields. ideally uart-break should have been usable, but that is currently broken. i also tried base64 encoding. but all seem to lead to alot of loss under load, when for example, there are several freertos timers running and messages are forwarded to/from wifi.

which is the best method? i wonder now how modbus does it.

**Comment by EN20M** [comment] 2022-07-14 08:16
@ESP-Marius That fits perfectly to the behaviour that I am seeing. As you can see I had to wrap the call in a loop running untill the desired amont of bytes got received so I'll now treat my workaround as my solution.

I don't really understand why one would want `xStreamBufferReceive` to return before triggerLevel is reached but if it is like that it would be nice if its behaviour is documented like that.

Thanks for the help. If it is acually intended bahaviour than it looks like this issue can be closed.

**Comment by ESP-Marius** [comment] 2022-07-15 01:20
@EN20M Closing this one then.

I agree that the upstream freeRTOS docs do a poor job of emphasizing this, I also missed it initially and only noticed after reading the code itself.

**Closed by ESP-Marius** 2022-07-15 01:20 UTC
Labels: Status: In Progress
