### ISSUE TITLE
[TW#20346] rtc_module.c compile error

### ISSUE THREAD

**Issue by fxzengfrank** [espressif/esp-idf#1841] opened 2018-04-09 11:07 UTC
while make all

CC build/driver/rtc_module.o
/esp-idf/components/driver/./rtc_module.c: In function 'adc_convert':
/esp-idf/components/driver/./rtc_module.c:1245:12: error: 'adc_value' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     return adc_value;
            ^
cc1: some warnings being treated as errors
make[1]: *** [rtc_module.o] Error 1
make: *** [component-driver-build] Error 2

**Comment by moraleja39** [comment] 2018-04-11 19:45
Until it gets fixed, you can compile by setting "Assertion level" to anything but "Disabled" under "Compiler options".
IE. the -DNDEBUG seems to be the cause to the compilation error.

**Comment by panfeng-espressif** [comment] 2018-04-16 09:51
Hello fxzengfrank,
Would you mind sharing your commit id of ESP-IDF?
Is it a demo code or your own project?
Thanks

**Comment by mahavirj** [comment] 2018-04-17 05:18
@fxzengfrank Thanks for reporting this. Fix for this is in progress, should be merged soon.

**Closed** 2018-04-19 11:15 UTC
