### ISSUE TITLE
Unable to install IDF on Raspberry Pi W (IDFGH-11873)

### ISSUE THREAD

**Issue by sidreco214** [espressif/esp-idf#12959] opened 2024-01-11 06:37 UTC
### Is your feature request related to a problem?

```console
sudo apt update
sudo apt install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
mkdir esp
cd esp
git clone --recursive https://github.com/espressif/esp-idf.git
cd esp-idf
./install.sh
Detecting the Python interpreter
Checking "python3" ...
Python 3.11.2
"python3" has been detected
Checking Python compatibility
Installing ESP-IDF tools
Traceback (most recent call last):
  File "/home/rasp-find/esp/esp-idf/tools/idf_tools.py", line 207, in <module>
    CURRENT_PLATFORM = parse_platform_arg(PYTHON_PLATFORM)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rasp-find/esp/esp-idf/tools/idf_tools.py", line 202, in parse_platform_arg
    fatal(f'unknown platform: {platform}')
    ^^^^^
NameError: name 'fatal' is not defined
```

### Describe the solution you'd like.

When I install IDF on Raspberry Pi W, I met this problem. I used Raspberry Pi OS Lite

Release date: December 11th 2023
System: 32-bit
Kernel version: 6.1
Debian version: 12 (bookworm)

### Describe alternatives you've considered.

.

### Additional context.

Please consider adding this platform.

**Comment by dobairoland** [comment] 2024-01-11 10:46
This is probably a duplicate of https://github.com/espressif/esp-idf/issues/12865.

Can you please try what I've suggested in https://github.com/espressif/esp-idf/issues/12865#issuecomment-1870209177?

**Closed** 2024-02-28 12:45 UTC
Labels: Type: Feature Request, Status: Done, Resolution: NA
