### ISSUE TITLE
Abort in coex_init in ESP-IDF 4.1-beta2 (IDFGH-3467)

### ISSUE THREAD

**Issue by CrowdedFuzzball** [espressif/esp-idf#5427] opened 2020-06-10 12:42 UTC
Hello there!

During Wi-Fi start in client mode, after BLE starts working in peripheral mode (Nimble) abort occurs.

When software coexistence switched off in sdkconfig everything is ok.
As far as I understand, this is some kind of bug.

[sdkconfig.zip](https://github.com/espressif/esp-idf/files/4758480/sdkconfig.zip)
Backtrace: 0x40094e70:0x3ffd1490 0x40095221:0x3ffd14b0 0x4016a6aa:0x3ffd14d0 0x400d4fd5:0x3ffd14f0 0x400d5239:0x3ffd1520 0x40176374:0x3ffd1560 0x4017643d:0x3ffd1580 0x401766c2:0x3ffd15a0 0x4017357e:0x3ffd15c0 0x4018b37a:0x3ffd15e0
0x40094e70: invoke_abort at .../esp-idf/components/esp32/panic.c:1590x40095221: abort at .../esp-idf/components/esp32/panic.c:174
0x4016a6aa: coex_init at ??:?
0x400d4fd5: esp_phy_rf_init at .../esp-idf/components/esp_wifi/src/phy_init.c:269
0x400d5239: esp_phy_load_cal_and_init at .../esp-idf/components/esp_wifi/src/phy_init.c:747
0x40176374: wifi_rf_phy_enable at ??:?
0x4017643d: wifi_hw_start at ??:?
0x401766c2: wifi_start_process at ??:?
0x4017357e: ieee80211_ioctl_process at ??:?
0x4018b37a: ppTask at ??:?

**Comment by francescolavra** [comment] 2020-08-03 17:48
For the record, the issue is present in ESP-IDF v4.0.1 as well. Relevant log snippet:
```
I (1260) wifi:wifi driver task: 3ffda244, prio:23, stack:6656, core=1
I (1270) wifi:wifi firmware version: aa5336b
I (1270) wifi:config NVS flash: enabled
I (1270) wifi:config nano formating: disabled
I (1270) wifi:Init dynamic tx buffer num: 32
I (1270) wifi:Init data frame dynamic rx buffer num: 32
I (1280) wifi:Init management frame dynamic rx buffer num: 32
I (1280) wifi:Init management short buffer num: 32
I (1290) wifi:Init static rx buffer size: 1600
I (1290) wifi:Init static rx buffer num: 10
I (1300) wifi:Init dynamic rx buffer num: 32
I (1310) wifi:Set ps type: 0

abort() was called at PC 0x400f36f2 on core 1

ELF file SHA256: 33ef24acd6fe3ee2

Backtrace: 0x4008e76c:0x3ffda060 0x4008eb45:0x3ffda080 0x400f36f2:0x3ffda0a0 0x400d2758:0x3ffda0c0 0x400d28fc:0x3ffda0f0 0x400dd6c4:0x3ffda120 0x400dd78d:0x3ffda140 0x400dda1e:0x3ffda160 0x400da90a:0x3ffda180 0x4009a552:0x3ffda1a0

Rebooting...
```
```
Decoding stack results
0x4008e76c: invoke_abort at /usr/src/esp-idf/components/esp32/panic.c line 157
0x4008eb45: abort at /usr/src/esp-idf/components/esp32/panic.c line 172
0x400d2758: esp_phy_rf_init at /usr/src/esp-idf/components/esp_wifi/src/phy_init.c line 239
0x400d28fc: esp_phy_load_cal_and_init at /usr/src/esp-idf/components/esp_wifi/src/phy_init.c line 711
```
The issue does not show up when software control of WiFi/Bluetooth coexistence is disabled in the SDK config.

**Comment by Alvin1Zhang** [comment] 2020-08-04 01:04
Thanks for reporting and updates, really sorry for slow turnaround, we will look into.

**Comment by redradist** [comment] 2020-10-11 12:51
@thecashit @Alvin1Zhang @francescolavra I have faced the same issue
During enabled Software control WiFi/Ble coexisting when my phone tries to connect to device error occures:
```console
LE connection complete. handle=0 role=1 paddrtype=1 addr=6d.77.b5.d5.54.40 local_rpa=0.0.0.0.0.0 peer_rpa=0.0.0.0.0.0 itvl=39 latency=0 spvn_tmo=500 mca=1
0x40 0x54 0xd5 0xb5 0x77 0x6d
connection established; status=0 handle=0 our_ota_addr_type=0 our_ota_addr=30:ae:a4:dd:9b:ee our_id_addr_type=0 our_id_addr=30:ae:a4:dd:9b:ee peer_ota_addr_type=1 peer_ota_addr=6d:77:b5:d5:54:40 peer_id_addr_type=1 peer_id_addr=6d:77:b5:d5:54:40 conn_itvl=39 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0007 len=0
0x07 0x20 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x7 status=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x17 0x02 0x01 0x06 0x03 0x03 0x11 0x18 0x0c 0x09 0x73 0x74 0x75 0x66 0x66 0x2d 0x65 0x73 0x70 0x33 0x32 0x02 0x0a 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0006 len=15
0x06 0x20 0x0f 0x30 0x00 0x60 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x6 status=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x01
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0016 len=2
0x16 0x20 0x02 0x00 0x00
Command Status: status=0 cmd_pkts=5 ocf=0x16 ogf=0x8
LE Remote Used Features. handle=0 feat=ff 00 00 00 00 00 00 00
LE Remote Connection Parameter Request. handle=0 min_itvl=6 max_itvl=6 latency=0 timeout=500
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0020 len=14
0x20 0x20 0x0e 0x00 0x00 0x06 0x00 0x06 0x00 0x00 0x00 0xf4 0x01 0x00 0x00 0x00 0x00
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x20 status=0
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x10 0x01 0x00 0xff 0xff 0x00 0x28
rxed att command: read group type req; conn=0 start_handle=0x0001 end_handle=0xffff
txed att command: read group type rsp; conn=0 length=6
host tx hci data; handle=0 length=24
ble_hs_hci_acl_tx(): 0x00 0x00 0x18 0x00 0x14 0x00 0x04 0x00 0x11 0x06 0x01 0x00 0x05 0x00 0x00 0x18 0x06 0x00 0x09 0x00 0x01 0x18 0x0a 0x00 0x0e 0x00 0x00 0x18
D (10445) CurrentSensor: count >= 1000: _voltage = 78mV


D (10449) NimBleGattChar: Connection handle: 0, Value handle: 24
GATT procedure initiated: notify; att_handle=24
txed att command: notify req; conn=0 handle=0x0018
host tx hci data; handle=0 length=15
ble_hs_hci_acl_tx(): 0x00 0x00 0x0f 0x00 0x0b 0x00 0x04 0x00 0x1b 0x18 0x00 0x4e 0x00 0x00 0x00 0x00 0x00 0x00 0x00
Number of Completed Packets: num_handles=1
handle:0 pkts:1
ble_hs_hci_evt_acl_process(): conn_handle=0 pb=2 len=11 data=0x07 0x00 0x04 0x00 0x10 0x0f 0x00 0xff 0xff 0x00 0x28
rxed att command: read group type req; conn=0 start_handle=0x000f end_handle=0xffff
Guru Meditation Error: Core 0 panic'ed (LoadProhibited). Exception was unhandled.

Core 0 register dump:
PC : 0x4018fb33 PS : 0x00060530 A0 : 0x800e8b6b A1 : 0x3ffe2e80
A2 : 0x00000000 A3 : 0x00000000 A4 : 0x00000000 A5 : 0x3ffdbb90
A6 : 0x00000000 A7 : 0x00000000 A8 : 0x800ebe80 A9 : 0x3ffe2e80
A10 : 0x3ffdbb90 A11 : 0x00000000 A12 : 0x3ffdbba8 A13 : 0x00000000
A14 : 0x00000000 A15 : 0x00000000 SAR : 0x00000008 EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000 LBEG : 0x4000c349 LEND : 0x4000c36b LCOUNT : 0xffffffff

Backtrace:0x4018fb30:0x3ffe2e80 0x400e8b68:0x3ffe2ea0 0x400ed82e:0x3ffe2ec0 0x400edc01:0x3ffe2f00 0x400ede12:0x3ffe2f30 0x400edefe:0x3ffe2f80 0x400eec33:0x3ffe2ff0 0x400e2645:0x3ffe3040 0x400e1b7e:0x3ffe3070 0x400e107d:0x3ffe30a0 0x400e108f:0x3ffe30c0 0x400ebc82:0x3ffe30e0 0x400d9712:0x3ffe3100 0x4008e741:0x3ffe3120
```

I have also mentioned this issue in the forum https://www.esp32.com/viewtopic.php?f=13&t=6707&start=50 and https://www.esp32.com/viewtopic.php?f=20&t=7450

@Alvin1Zhang When it will be fixed ? Is there any update on this issue ?

**Comment by redradist** [comment] 2020-10-11 18:09
@Alvin1Zhang In 4.2-beta2 I do not see crash and seems like Ble and WiFi works simultaneously, but service discovery does not work and I cannot know available services on device

**Comment by blueMoods** [comment] 2020-10-12 09:22
Hello @thecashit @francescolavra , In coex, we should enable Wi-FI power save mode, and it seems like that you have close it with `esp_wifi_set_ps(WIFI_PS_NONE);`. Please make sure that Wi-FI power save mode is enabled and test again. Thanks.

**Comment by blueMoods** [comment] 2020-10-12 09:26
Hello @redchenjs, your issue seems like different, could you please provide you `.elf` file?

**Comment by redchenjs** [comment] 2020-10-12 09:41
😅Oops!

**Comment by redradist** [comment] 2020-10-12 11:43
> 
> 
> Hello @redchenjs, your issue seems like different, could you please provide you `.elf` file?

@blueMoods Unfortunately I cannot provide the .elf currently ... just try WiFi joinSta and Ble with all coex options enabled

**Comment by redradist** [comment] 2020-10-12 11:44
> 
> 
> Hello @thecashit @francescolavra , In coex, we should enable Wi-FI power save mode, and it seems like that you have close it with `esp_wifi_set_ps(WIFI_PS_NONE);`. Please make sure that Wi-FI power save mode is enabled and test again. Thanks.

@blueMoods What option should be ? `esp_wifi_set_ps(WIFI_PS_MAX);` ?

**Comment by blueMoods** [comment] 2020-10-12 13:36
> > Hello @thecashit @francescolavra , In coex, we should enable Wi-FI power save mode, and it seems like that you have close it with `esp_wifi_set_ps(WIFI_PS_NONE);`. Please make sure that Wi-FI power save mode is enabled and test again. Thanks.
> 
> @blueMoods What option should be ? `esp_wifi_set_ps(WIFI_PS_MAX);` is it proper value ?

`WIFI_PS_MIN_MODEM` and `WIFI_PS_MAX_MODEM` are both OK.

**Comment by redradist** [comment] 2020-10-12 16:20
> > > Hello @thecashit @francescolavra , In coex, we should enable Wi-FI power save mode, and it seems like that you have close it with `esp_wifi_set_ps(WIFI_PS_NONE);`. Please make sure that Wi-FI power save mode is enabled and test again. Thanks.
> > 
> > 
> > @blueMoods What option should be ? `esp_wifi_set_ps(WIFI_PS_MAX);` is it proper value ?
> 
> `WIFI_PS_MIN_MODEM` and `WIFI_PS_MAX_MODEM` are both OK.

@blueMoods Okay, I will try but last time when I tried these values it does not work for me. Bluetooth discovery did not work at that time

**Comment by redradist** [comment] 2020-10-12 17:19
> > > Hello @thecashit @francescolavra , In coex, we should enable Wi-FI power save mode, and it seems like that you have close it with `esp_wifi_set_ps(WIFI_PS_NONE);`. Please make sure that Wi-FI power save mode is enabled and test again. Thanks.
> > 
> > 
> > @blueMoods What option should be ? `esp_wifi_set_ps(WIFI_PS_MAX);` is it proper value ?
> 
> `WIFI_PS_MIN_MODEM` and `WIFI_PS_MAX_MODEM` are both OK.

@blueMoods I've checked, I've already have enabled `esp_wifi_set_ps(WIFI_PS_MAX);` on join STA, but service discovery does not work ... When I remove join STA code, service discovery works

**Comment by cyberman54** [comment] 2021-03-06 14:58
I can confirm this issue, happening if BLE and WiFi operate in coex mode, but **does not happen if BLE stacked is unused**.

```
15:39:40.223 > [I][main.cpp:438] setup(): Starting Wifi...
15:39:40.257 > abort() was called at PC 0x40171cb6 on core 0
15:39:41.022 >
15:39:41.022 > ELF file SHA256: 0000000000000000
15:39:41.022 >
15:39:41.022 > Backtrace: 0x400956b8:0x3ffe1060 0x40095931:0x3ffe1080 0x40171cb6:0x3ffe10a0 0x4017838c:0x3ffe10c0 0x401785ea:0x3ffe10f0 0x401874ec:0x3ffe1120 
0x401875b9:0x3ffe1140 0x4018760b:0x3ffe1160 0x40184742:0x3ffe1190 0x401b6202:0x3ffe11b0 0x4009698a:0x3ffe11e0
15:39:41.022 >   #0  0x400956b8:0x3ffe1060 in invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
15:39:41.022 >   #1  0x40095931:0x3ffe1080 in abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715
15:39:41.022 >   #2  0x40171cb6:0x3ffe10a0 in coex_init at ??:?
15:39:41.022 >   #3  0x4017838c:0x3ffe10c0 in esp_phy_rf_init at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/phy_init.c:524
15:39:41.022 >   #4  0x401785ea:0x3ffe10f0 in esp_phy_load_cal_and_init at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/phy_init.c:673
15:39:41.022 >   #5  0x401874ec:0x3ffe1120 in wifi_rf_phy_enable at ??:?
15:39:41.022 >   #6  0x401875b9:0x3ffe1140 in wifi_hw_start at ??:?
15:39:41.022 >   #7  0x4018760b:0x3ffe1160 in wifi_set_promis_process at ??:?
15:39:41.022 >   #8  0x40184742:0x3ffe1190 in ieee80211_ioctl_process at ??:?
15:39:41.022 >   #9  0x401b6202:0x3ffe11b0 in ppTask at ??:?
15:39:41.022 >   #10 0x4009698a:0x3ffe11e0 in vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
15:39:41.022 >
15:39:41.022 > Rebooting...
```

**Comment by geza-pycom** [comment] 2021-11-17 18:01
Hello!
I experience the same isse on esp-idf v4.2.2, calling esp_wifi_set_ps(WIFI_PS_MIN_MODEM) does not solve/hide the issue.
Are there any solution for this crash ? When CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE is disabled, the crash does not happen, however based on https://docs.espressif.com/projects/espressif-esp-faq/en/latest/software-framework/coexistence.html it is advised to enable it, isn't it ?

**Comment by blueMoodBHD** [comment] 2023-06-28 13:21
> avoids this issue, so could be used as workaround - but i assume lowering power on wifi will have side effects

@cyberman54 `esp_wifi_set_ps(WIFI_PS_MIN_MODEM)` is used to set Wi-Fi power save mode, instead of  lowering power.

**Closed** 2023-10-26 10:37 UTC
Labels: Awaiting Response
