### ISSUE TITLE
USB Vendor Specific class (IDFGH-13801)

### ISSUE THREAD

**Issue by maaamcube** [espressif/esp-idf#14658] opened 2024-10-01 14:50 UTC
### Is your feature request related to a problem?

Hello everyone,
I checked the Esp idf USB Host Library and i didn't find that Vendor Specific USB class is supported, can it be added ? (i need to connect my Stm32 device Vendor Specific USB to send it through wifi)
Thanks.

### Describe the solution you'd like.

Ideally, the Esp idf USB Host Library support Vendor Specific USB so i can send multiple hubs and vendor specific usb devices through wifi.

**Comment by tore-espressif** [comment] 2024-10-02 07:21
Hello @maaamcube , thank you for the request.

We don't plan to implement Vendor specific class driver because, each vendor specific device is different and requires custom driver that can handle all its features, so it must be custom made for a specific device.

If your device uses standard BULK IN/OUT endpoints, you can use our [CDC-ACM driver](https://components.espressif.com/components/espressif/usb_host_cdc_acm/versions/2.0.4)

Could you also please clarify what do you mean by 'send multiple hubs and vendor specific usb devices through wifi'?

**Comment by maaamcube** [comment] 2024-10-02 07:25
Hello @tore-espressif,
Thanks for your reply.
On my PCB, I have 3 hubs, each hub has an Stm32 usb device vendor specific
![image](https://github.com/user-attachments/assets/f7e918d6-de4d-46ac-8a34-f08024d74f7a)

**Comment by tore-espressif** [comment] 2024-10-02 09:46
Duplicate of https://github.com/espressif/esp-idf/issues/13307

The HUB support will be added, but we can't help with this very custom design

**Closed by tore-espressif** 2024-10-02 09:46 UTC
Labels: Type: Feature Request, Status: Opened

**Comment by chegewara** [comment] 2024-11-07 05:49
https://github.com/espressif/esp-dev-kits/tree/master/esp32-s3-usb-bridge/examples/usb_wireless_bridge

**Comment by maaamcube** [comment] 2024-11-07 08:01
> https://github.com/espressif/esp-dev-kits/tree/master/esp32-s3-usb-bridge/examples/usb_wireless_bridge

there is no option with usb between the Esp32 and the MCU
