### ISSUE TITLE
modbus master 是否可以支持传入的参数来设置停止位的功能 (IDFGH-4119)

### ISSUE THREAD

**Issue by zjykymt** [espressif/esp-idf#5986] opened 2020-10-16 02:39 UTC
你好，

components\freemodbus\port\portserial_m.c：xMBMasterPortSerialInit() 中串口的参数配置项停止位是默认为1的，是否可以支持传入参数来设置呢？或者说这个串口的stopbits参数配置与否都没啥影响呢？

>uart_config_t xUartConfig = 
{
        .baud_rate = ulBaudRate,
        .data_bits = ucData,
        .parity = ucParity,
        .stop_bits = UART_STOP_BITS_1,
        .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,
        .rx_flow_ctrl_thresh = 2,
        .source_clk = UART_SCLK_APB,
    };

**Comment by alisitsyn** [comment] 2020-10-20 13:33
Hello zjykymt,

The extra stop bit can be a useful way to add a little extra receive processing time, especially at high baud rates and/or using software driven UART, where time is required to process the received byte. However the devices today have hardware driven UARTs and are fast enough, work at even higher baud rates without the need of an extra stop bit. The one stop bit configuration is usually enough for most of device UARTs and do not cause any issues. Do you have any issues communication between devices in your infrastructure due to fixed stop bit config?

If you have very strong opinion about two stop bit configuration it can be added to Modbus configuration and propagated to Modbus serial code initialization function.

**Comment by zjykymt** [comment] 2020-10-21 07:10
Hi alisitsyn, thanks for your reply.

Under the test there is no problem with the communication at 115200bps.

**Comment by zjykymt** [comment] 2020-10-21 07:19
In addition, I want to describe another modbus communication problem that I tested here.

ESP-IDF version: 4.1

I have configured the following two configurations: **Place UART ISR function into IRAM** or **Place timer interrupt handler into IRAM**
![image](https://user-images.githubusercontent.com/9928032/96685717-19071b00-13b0-11eb-8d9a-ee79b26e2a4a.png)

But when the program calls **esp_partition_write** or **esp_partition_erase_range** function, 
the following two read errors will still occur when the Master modbus command is sent at this time：

> MB_CONTROLLER_MASTER: mbc_master_send_request(131): SERIAL master send request failure error=(0x107) (ESP_ERR_TIMEOUT).<br>
> MB_CONTROLLER_MASTER: mbc_master_send_request(131): SERIAL master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).

**Comment by alisitsyn** [comment] 2020-10-23 08:06
@zjykymt,

What are the priority of the tasks which doing the partition erase and write?
I would recommend to change the priority of modbus tasks (CONFIG_FMB_PORT_TASK_PRIO) to be higher.
The modbus master uses polling approach to process input packets and reads FIFO byte by byte. 
This may cause the errors you showed. In this case possible solution is just retry the modbus write/read request.

This is known issue related to coexistence of Wi-Fi and flash functionality with modbus.
The fixes for the v4.1 as well for other branches are ready but not merged yet. You could test the patch below to apply the fixes. The modbus v4.1 with these patches works significantly better and allows avoiding most of the problems but reading errors are still possible in your application in some conditions (priority of the tasks which do intensive work related to Wi-Fi and flash access). In this case the only retry will help.
Please disable the CONFIG_MB_TIMER_PORT_ENABLED option after applying patch to allow longer delays during modbus packet processing due to periodical suspend of its tasks.

[freemodbus_backport_latest_fixes_v41.zip](https://github.com/espressif/esp-idf/files/5428126/freemodbus_backport_latest_fixes_v41.zip)

Please let me know the results. Thanks.

**Comment by zjykymt** [comment] 2020-10-28 02:16
Hi alisitsyn，

I use xTaskCreate to create application tasks, all tasks have a priority of 2, and the modbus serial task priority is 10.
![image](https://user-images.githubusercontent.com/9928032/97380495-21a4a780-1902-11eb-9d6b-7e9750ddc77d.png)

After I apply the patch and set CONFIG_MB_TIMER_PORT_ENABLED to disable, the modbus read/write errors still occur but **the chances have been reduced**(ESP_ERR_TIMEOUT error no longer appears).

> After **esp_partition_erase_range**: 
> E (381754) MB_PORT_COMMON: vMBMasterRunResRelease(172): vMBMasterRunResRelease: resource release failure.

> After **esp_partition_write**: 
> E (637180) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).

The general logic of my code is: tell the modem to use HTTP GET to obtain a file of 1M size. After the modem is downloaded, use UART (115200bps) to transmit to the ESP32, and every 256 bytes received by the ESP32 are stored in the flash (of course, before downloading the flash has been erased). While downloading, read 6 consecutive modbus times as a complete implementation, and execute a complete implementation every 5 seconds

This patch seems to have some optimization effects, but I don’t quite understand that MODBUS_UART_ISR runs in RAM. 
The uart received FIFO is also in RAM, will the flash operation cause the MODBUS_UART_ISR insertion of the FIFO to fail?

Due to the development plan of my own project, I am sorry that I can only simply test and provide not very specific information.
When the development of my project reaches a certain level, I will try to understand the reasons for the above modbus uart tx/rx and flash r/w/erase errors in ESP-IDF.

Thanks.

**Comment by alisitsyn** [comment] 2020-10-29 15:10
Hi @zjykymt,

Thank you for thest results. I will investigate the issues related to using esp_partition_erase_range(). I guess it is due to constraints of current Modbus architecture. I am trying to reproduce and check solution for this. This will take some time.  As a workaround I can propose to do retries of modbus read/write requests if the error returned:

```
err == ESP_ERR_TIMEOUT;
for (int retry = 0; (retry < MB_MAX_RETRY) && (err != ESP_OK); retry++) {
    err = mbc_master_get_parameter(cid, (char*)param_descriptor->param_key, 
                                                    (uint8_t*)&value, &type);
}
```

**Comment by JavierSVE** [comment] 2020-12-11 12:36
I have the same problem with the freemodbus master component.
My application consists of a web server via a wifi access point with an embedded web page that allows updating the esp32 firmware via OTA, and a connection with a slave device via modbus.
For the OTA update firmware I use the native APIs provided by app_update component (esp_ota_write).
To avoid the error=(0x108) (ESP_ERR_INVALID_RESPONSE) during the firmware update I deactivate the communications via modbus and when the update is completed I perform a software reset (esp_restart()).
My problem is that after resetting the esp32 the modbus component is corrupted and all the requests fail with the "E (637180) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE)".
The only solution at the moment is to try a hardware reset with the EN pin.
I am developing the application with version 4.2 of the esp-idf.
Does alisitsyn have a freemodbus component patch for this version?
The esp_restart function does not reset the peripherals (except for WiFi, BT, UART0, SPI1, and legacy timers) but my modbus connection use the UART2.
Is there a software reset that does reset all the peripherals?

**Comment by alisitsyn** [comment] 2020-12-11 16:12
@JavierSVE,

The modbus actually was not designed to work with OTA update and there are things that might prevent to work properly. But in your case the modbus is restarted after update. It is interesting case and need more investigation to fix this issue. I do have the patch for v4.2 version to fix most of known issues. Please apply patch below to check if it fixes the issue.

[0001_backport_latest_fixes_v42.diff](https://github.com/espressif/esp-idf/files/5680191/0001_backport_latest_fixes_v42.diff.log)

I will try to reproduce your issue in my environment and will connect you then. Would appreciate if you can send the example to reproduce.
Thanks.

**Comment by JavierSVE** [comment] 2020-12-14 08:38
alisitsyn thank you very much for your quick response.
To reproduce this problem you can use the versamodule's example "ESP-OTA-Webserver" and add a task to it with a modbus master that interrogates a slave vía UART2:
[https://github.com/versamodule/ESP32-OTA-Webserver](url)
Now I'm going to test the patch for version 4.2 of esp-if.

**Comment by JavierSVE** [comment] 2020-12-14 10:28
I have applied the patch provided by alisitsyn to esp-idf v4.2 and the problem of the modbus master after the esp_restart continues.
This is the trace log.
First the ESP32 start from the ota_0 (at offset 0x10000). All run ok. So I run a firmware update from the embedded web and the esp_restart runs.
Now esp32 starts from partition ota_1 (at offset 0x380000) but when the vMasterTask task starts to interrogate the slave via modbus, error=(0x108) (ESP_ERR_INVALID_RESPONSE) appears forever.

`ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7132
load:0x40078000,len:13696
load:0x40080400,len:4000
entry 0x40080688
I (28) boot: ESP-IDF v4.2-dev-1995-g636b964c8-dirty 2nd stage bootloader
I (28) boot: compile time 10:37:10
I (29) boot: chip revision: 1
I (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (40) boot.esp32: SPI Speed      : 40MHz
I (45) boot.esp32: SPI Mode       : DIO
I (49) boot.esp32: SPI Flash Size : 8MB
I (54) boot: Enabling RNG early entropy source...
I (59) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 ota_0            OTA app          00 10 00010000 00370000
I (100) boot:  4 ota_1            OTA app          00 11 00380000 00370000
I (107) boot:  5 storage          Unknown data     01 82 006f0000 00100000
I (115) boot: End of partition table
I (119) boot_comm: chip revision: 1, min. application chip revision: 0
I (126) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x3fe9c (261788) map
I (235) esp_image: segment 1: paddr=0x0004fec4 vaddr=0x3ffb0000 size=0x00154 (   340) load
I (236) esp_image: segment 2: paddr=0x00050020 vaddr=0x400d0020 size=0x9e66c (648812) map
I (489) esp_image: segment 3: paddr=0x000ee694 vaddr=0x3ffb0154 size=0x03d58 ( 15704) load
I (496) esp_image: segment 4: paddr=0x000f23f4 vaddr=0x40080000 size=0x00404 (  1028) load
I (496) esp_image: segment 5: paddr=0x000f2800 vaddr=0x40080404 size=0x17ea8 ( 97960) load
I (560) boot: Loaded app from partition at offset 0x10000
I (560) boot: Disabling RNG early entropy source...
I (560) cpu_start: Pro cpu up.
I (564) cpu_start: Application information:
I (569) cpu_start: Project name:     SAF840DU_WS
I (574) cpu_start: App version:      e4163eb-dirty
I (580) cpu_start: Compile time:     Dec 14 2020 10:59:25
I (586) cpu_start: ELF file SHA256:  93a8fe4335f060bf...
I (592) cpu_start: ESP-IDF:          v4.2-dev-1995-g636b964c8-dirty
I (599) cpu_start: Starting app cpu, entry point is 0x40081a94
I (0) cpu_start: App cpu up.
I (609) heap_init: Initializing. RAM available for dynamic allocation:
I (616) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (622) heap_init: At 3FFBAA20 len 000255E0 (149 KiB): DRAM
I (628) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (635) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (641) heap_init: At 400982AC len 00007D54 (31 KiB): IRAM
I (647) cpu_start: Pro cpu start user code
I (665) spi_flash: detected chip: gd
I (666) spi_flash: flash io: dio
I (666) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (729) MAIN: Press the switch to run...
I (731) uart: queue free spaces: 20


esp32 (I (1805) wifi_setup: starting tcpip adapter
/spiffs) > I (1807) wifi_setup: setting gateway IP
I (1808) wifi_setup: starting DHCPS adapter
I (1810) wifi_setup: starting event loop
I (1815) wifi_setup: initializing WiFi
I (1821) wifi:wifi driver task: 3ffcdfd4, prio:23, stack:6656, core=0
I (1825) system_api: Base MAC address is not set
I (1830) system_api: read default base MAC address from EFUSE
I (1852) wifi:wifi firmware version: 9f3395e
I (1852) wifi:wifi certification version: v7.0
I (1852) wifi:config NVS flash: enabled
I (1853) wifi:config nano formating: disabled
I (1857) wifi:Init data frame dynamic rx buffer num: 32
I (1862) wifi:Init management frame dynamic rx buffer num: 32
I (1867) wifi:Init management short buffer num: 32
I (1872) wifi:Init dynamic tx buffer num: 32
I (1876) wifi:Init static rx buffer size: 1600
I (1880) wifi:Init static rx buffer num: 16
I (1884) wifi:Init dynamic rx buffer num: 32
I (3668) phy: phy_version: 4182, f1ba940, Jun  4 2020, 19:40:07, 0, 0
I (3669) wifi:mode : softAP (24:0a:c4:b8:e6:f9)
I (3673) wifi:Total power save buffer number: 16
I (3674) wifi:Init max length of beacon: 752/752
I (3677) wifi:Init max length of beacon: 752/752
I (3682) wifi_setup: WiFi set up!
I (3683) wifi_event_handler: Access Point Started
I (3691) server_handle_task: task starting
I (3692) server_task: server listening
I (3700) count_task: starting task
I (24170) wifi:new:<1,1>, old:<1,1>, ap:<1,1>, sta:<255,255>, prof:1
I (24171) wifi:station: d0:37:45:ab:b1:e3 join, AID=1, bgn, 40U
I (24185) wifi_event_handler: station d0:37:45:ab:b1:e3 join, AID=1
I (25228) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.123.2
I (36890) server_task: new client
I (36891) http_server: reading from client...
I (36891) http_server: read from client
I (36893) http_server: Sending /
I (36895) server_task: new client
I (36907) http_server: reading from client...
I (37032) http_server: read from client
I (37033) http_server: Sending /root.css
I (37037) server_task: new client
I (37037) http_server: reading from client...
I (37039) server_task: new client
I (37041) http_server: read from client
I (37048) http_server: Sending /jquery.js
I (37125) http_server: reading from client...
I (37126) http_server: read from client
I (37126) http_server: Sending /root.js
I (37225) server_task: new client
I (37226) http_server: reading from client...
I (37228) http_server: read from client
I (37229) http_server: Sending menu.png
I (37397) server_task: new client
I (37397) http_server: reading from client...
I (37398) http_server: read from client
I (37400) http_server: Requesting websocket on /
I (37408) websocket_callback: client 0 connected!
I (137300) parseReceivedJson: received binary chunk (251 to go) of size 4096:
I (142753) OTA: Writing to partition subtype 17 at offset 0x380000
I (142766) sendFirmwareJsonAck: (to client: 0) NEXT:
I (142767) websocket_callback: PD_FIRMWARE_CHUNK with length 5500:
I (142790) parseReceivedJson: received binary chunk (250 to go) of size 4096:
I (142791) OTA: Writing to partition subtype 17 at offset 0x380000
I (142806) sendFirmwareJsonAck: (to client: 0) NEXT:
I (142806) websocket_callback: PD_FIRMWARE_CHUNK with length 5500:
I (142825) parseReceivedJson: received binary chunk (249 to go) of size 4096:
I (142826) OTA: Writing to partition subtype 17 at offset 0x380000
I (142842) sendFirmwareJsonAck: (to client: 0) NEXT:
I (142842) websocket_callback: PD_FIRMWARE_CHUNK with length 5500:
I (142861) parseReceivedJson: received binary chunk (248 to go) of size 4096:
I (142861) OTA: Writing to partition subtype 17 at offset 0x380000
I (142877) sendFirmwareJsonAck: (to client: 0) NEXT:
I (142877) websocket_callback: PD_FIRMWARE_CHUNK with length 5500:
I (142893) parseReceivedJson: received binary chunk (247 to go) of size 4096:
I (142893) OTA: Writing to partition subtype 17 at offset 0x380000
I (142909) sendFirmwareJsonAck: (to client: 0) NEXT:
I (142909) websocket_callback: PD_FIRMWARE_CHUNK with length 5500:
I (142923) parseReceivedJson: received binary chunk (246 to go) of size 4096:
I (142923) OTA: Writing to partition subtype 17 at offset 0x380000
I (142940) sendFirmwareJsonAck: (to client: 0) NEXT:
I (142941) websocket_callback: PD_FIRMWARE_CHUNK with length 5500:
I (142956) parseReceivedJson: received binary chunk (245 to go) of size 4096:
I (142956) OTA: Writing to partition subtype 17 at offset 0x380000
I (142972) sendFirmwareJsonAck: (to client: 0) NEXT:

# Continue with the rest of the pieces ....

I (150594) websocket_callback: PD_FIRMWARE_CHUNK with length 5498:
I (150609) parseReceivedJson: received binary chunk (3 to go) of size 4096:
I (150609) OTA: Writing to partition subtype 17 at offset 0x380000
I (150625) sendFirmwareJsonAck: (to client: 0) NEXT:
I (150625) websocket_callback: PD_FIRMWARE_CHUNK with length 5498:
I (150639) parseReceivedJson: received binary chunk (2 to go) of size 4096:
I (150640) OTA: Writing to partition subtype 17 at offset 0x380000
I (150656) sendFirmwareJsonAck: (to client: 0) NEXT:
I (150657) websocket_callback: PD_FIRMWARE_CHUNK with length 5498:
I (150665) parseReceivedJson: received binary chunk (1 to go) of size 1744:
I (150667) OTA: Writing to partition subtype 17 at offset 0x380000
I (150679) esp_image: segment 0: paddr=0x00380020 vaddr=0x3f400020 size=0x3fe9c (261788) map
I (150755) esp_image: segment 1: paddr=0x003bfec4 vaddr=0x3ffb0000 size=0x00154 (   340)
I (150756) esp_image: segment 2: paddr=0x003c0020 vaddr=0x400d0020 size=0x9e66c (648812) map
I (150942) esp_image: segment 3: paddr=0x0045e694 vaddr=0x3ffb0154 size=0x03d58 ( 15704)
I (150948) esp_image: segment 4: paddr=0x004623f4 vaddr=0x40080000 size=0x00404 (  1028)
I (150950) esp_image: segment 5: paddr=0x00462800 vaddr=0x40080404 size=0x17ea8 ( 97960)
I (150987) esp_image: segment 0: paddr=0x00380020 vaddr=0x3f400020 size=0x3fe9c (261788) map
I (151060) esp_image: segment 1: paddr=0x003bfec4 vaddr=0x3ffb0000 size=0x00154 (   340)
I (151062) esp_image: segment 2: paddr=0x003c0020 vaddr=0x400d0020 size=0x9e66c (648812) map
I (151246) esp_image: segment 3: paddr=0x0045e694 vaddr=0x3ffb0154 size=0x03d58 ( 15704)
I (151252) esp_image: segment 4: paddr=0x004623f4 vaddr=0x40080000 size=0x00404 (  1028)
I (151254) esp_image: segment 5: paddr=0x00462800 vaddr=0x40080404 size=0x17ea8 ( 97960)
I (151312) OTA: Next boot partition subtype 17 at offset 0x380000
I (151315) sendFirmwareJsonAck: (to client: 0) OK:
I (151316) parseReceivedJson: Reboot Commad, Restarting ...
I (153320) wifi:station: d0:37:45:ab:b1:e3 leave, AID = 1, bss_flags is 134243, bss:0x3ffde05c
I (153322) wifi:new:<1,0>, old:<1,1>, ap:<1,1>, sta:<255,255>, prof:1
I (153327) wifi_event_handler: Unregistered event=3
I (153330) wifi_event_handler: station d0:37:45:ab:b1:e3 leave, AID=1
I (153338) wifi_event_handler: Access Point Stopped
I (153376) wifi:flush txq
I (153376) wifi:stop sw txq
I (153378) wifi:lmac stop hw txq
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7132
load:0x40078000,len:13696
load:0x40080400,len:4000
entry 0x40080688
I (29) boot: ESP-IDF v4.2-dev-1995-g636b964c8-dirty 2nd stage bootloader
I (29) boot: compile time 10:37:10
I (30) boot: chip revision: 1
I (34) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (41) boot.esp32: SPI Speed      : 40MHz
I (46) boot.esp32: SPI Mode       : DIO
I (50) boot.esp32: SPI Flash Size : 8MB
I (55) boot: Enabling RNG early entropy source...
I (60) boot: Partition Table:
I (64) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (78) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (86) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (93) boot:  3 ota_0            OTA app          00 10 00010000 00370000
I (101) boot:  4 ota_1            OTA app          00 11 00380000 00370000
I (108) boot:  5 storage          Unknown data     01 82 006f0000 00100000
I (116) boot: End of partition table
I (120) boot_comm: chip revision: 1, min. application chip revision: 0
I (127) esp_image: segment 0: paddr=0x00380020 vaddr=0x3f400020 size=0x3fe9c (261788) map
I (236) esp_image: segment 1: paddr=0x003bfec4 vaddr=0x3ffb0000 size=0x00154 (   340) load
I (237) esp_image: segment 2: paddr=0x003c0020 vaddr=0x400d0020 size=0x9e66c (648812) map
I (490) esp_image: segment 3: paddr=0x0045e694 vaddr=0x3ffb0154 size=0x03d58 ( 15704) load
I (497) esp_image: segment 4: paddr=0x004623f4 vaddr=0x40080000 size=0x00404 (  1028) load
I (497) esp_image: segment 5: paddr=0x00462800 vaddr=0x40080404 size=0x17ea8 ( 97960) load
I (561) boot: Loaded app from partition at offset 0x380000
I (561) boot: Disabling RNG early entropy source...
I (562) cpu_start: Pro cpu up.
I (565) cpu_start: Application information:
I (570) cpu_start: Project name:     SAF840DU_WS
I (575) cpu_start: App version:      e4163eb-dirty
I (581) cpu_start: Compile time:     Dec 14 2020 10:59:25
I (587) cpu_start: ELF file SHA256:  93a8fe4335f060bf...
I (593) cpu_start: ESP-IDF:          v4.2-dev-1995-g636b964c8-dirty
I (600) cpu_start: Starting app cpu, entry point is 0x40081a94
I (592) cpu_start: App cpu up.
I (610) heap_init: Initializing. RAM available for dynamic allocation:
I (617) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (623) heap_init: At 3FFBAA20 len 000255E0 (149 KiB): DRAM
I (629) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (636) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (642) heap_init: At 400982AC len 00007D54 (31 KiB): IRAM
I (648) cpu_start: Pro cpu start user code
I (667) spi_flash: detected chip: gd
I (667) spi_flash: flash io: dio
I (667) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (730) MAIN: Press the switch to run...
I (732) uart: queue free spaces: 20

esp32 (I (1806) wifi_setup: starting tcpip adapter
/spiffs) > I (1808) wifi_setup: setting gateway IP
I (1809) wifi_setup: starting DHCPS adapter
I (1811) wifi_setup: starting event loop
I (1816) wifi_setup: initializing WiFi
I (1822) wifi:wifi driver task: 3ffcdfd4, prio:23, stack:6656, core=0
I (1826) system_api: Base MAC address is not set
I (1831) system_api: read default base MAC address from EFUSE
I (1853) wifi:wifi firmware version: 9f3395e
I (1853) wifi:wifi certification version: v7.0
I (1853) wifi:config NVS flash: enabled
I (1854) wifi:config nano formating: disabled
I (1858) wifi:Init data frame dynamic rx buffer num: 32
I (1863) wifi:Init management frame dynamic rx buffer num: 32
I (1868) wifi:Init management short buffer num: 32
I (1873) wifi:Init dynamic tx buffer num: 32
I (1877) wifi:Init static rx buffer size: 1600
I (1881) wifi:Init static rx buffer num: 16
I (1885) wifi:Init dynamic rx buffer num: 32
I (3668) phy: phy_version: 4182, f1ba940, Jun  4 2020, 19:40:07, 0, 0
I (3670) wifi:mode : softAP (24:0a:c4:b8:e6:f9)
I (3674) wifi:Total power save buffer number: 16
I (3674) wifi:Init max length of beacon: 752/752
I (3678) wifi:Init max length of beacon: 752/752
I (3683) wifi_setup: WiFi set up!
I (3684) wifi_event_handler: Access Point Started
I (3692) server_task: server listening
I (3696) count_task: starting task
I (3696) server_handle_task: task starting
E (6866) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (6868) MASTER: ComandRequest (0x4) an invalid response from slave.
I (6968) wifi:new:<1,1>, old:<1,1>, ap:<1,1>, sta:<255,255>, prof:1
I (6969) wifi:station: d0:37:45:ab:b1:e3 join, AID=1, bgn, 40U
I (6980) wifi_event_handler: station d0:37:45:ab:b1:e3 join, AID=1
I (6988) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.123.2
E (8866) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (8868) MASTER: ComandRequest (0x1) an invalid response from slave.
E (8949) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (8950) MASTER: ComandRequest (0x3) an invalid response from slave.
E (9214) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (9215) MASTER: ComandRequest (0x3) an invalid response from slave.
E (9349) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (9350) MASTER: ComandRequest (0x4) an invalid response from slave.
E (9619) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (9620) MASTER: ComandRequest (0x4) an invalid response from slave.
E (10816) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (10818) MASTER: ComandRequest (0x1) an invalid response from slave.
E (10890) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (10891) MASTER: ComandRequest (0x3) an invalid response from slave.
E (11154) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (11155) MASTER: ComandRequest (0x3) an invalid response from slave.
E (11289) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (11290) MASTER: ComandRequest (0x4) an invalid response from slave.
E (11556) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (11557) MASTER: ComandRequest (0x4) an invalid response from slave.
E (12853) MB_CONTROLLER_MASTER: mbc_master_send_request(131): Master send request failure error=(0x108) (ESP_ERR_INVALID_RESPONSE).
E (12854) MASTER: ComandRequest (0x1) an invalid response from slave.

# For ever ....
`

**Comment by JavierSVE** [comment] 2020-12-14 12:01
After applying the second proposed patch that corrects some fixes for esp_restart() to address the incorrect reset of UART1/2 tx/rx fifo, now everything works correctly.

Thank you very much.

**Comment by alisitsyn** [comment] 2020-12-14 13:27
@JavierSVE,

I was able to reproduce the issue with my simple modbus master example and OTA update through web with the result almost the same as yours (had timeout modbus errors instead of invalid response). Then it was possible to fix the issue applying patch below. The UART2 is able to work correctly after this and I do not have issues.

[0002_driver_fix_uart_module_reset_issue.diff](https://github.com/espressif/esp-idf/files/5688973/0002_driver_fix_uart_module_reset_issue.diff.log)

**Closed** 2021-06-08 04:52 UTC
Labels: Type: Feature Request
