### ISSUE TITLE
Esp32 failed to send one to many using espnow protocol (IDFGH-7410)

### ISSUE THREAD

**Issue by xiezhoubin** [espressif/esp-idf#8988] opened 2022-05-19 19:49 UTC
Board
ESP32

Device Description
ESP32 Dev Module

Hardware Configuration
none

Version
v2.0.3

IDE Name
arduino+vscode

Operating System
win11

Flash frequency
80

PSRAM enabled
no

Upload speed
921600

Description
https://randomnerdtutorials.com/esp-now-one-to-many-esp32-esp8266/

The host can only send data to the first slave, but cannot send data to the second slave. Once sent, "internal error" will appear.Save different versions of the platform at the same time. Version 1.0.6 can be used, but versions 2.0.1, 2.0.2 and 2.0.3 cannot be used.

![image](https://user-images.githubusercontent.com/75734559/169390627-c1a42662-b366-461e-80f0-eb767b01e432.png)
![image](https://user-images.githubusercontent.com/75734559/169390678-12cda42c-756b-4ab3-820d-7bf8f4185802.png)
![image](https://user-images.githubusercontent.com/75734559/169390721-d388d789-1dcd-4ae2-9274-66c37da7a5f3.png)

Sketch：

/*********
  Rui Santos
  Complete project details at https://RandomNerdTutorials.com/esp-now-one-to-many-esp32-esp8266/
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files.
  
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
*********/

#include <esp_now.h>
#include <WiFi.h>

// REPLACE WITH YOUR ESP RECEIVER'S MAC ADDRESS
uint8_t broadcastAddress1[] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
uint8_t broadcastAddress2[] = {0xFF, , , , , };
uint8_t broadcastAddress3[] = {0xFF, , , , , };

typedef struct test_struct {
  int x;
  int y;
} test_struct;

test_struct test;

esp_now_peer_info_t peerInfo;

// callback when data is sent
void OnDataSent(const uint8_t *mac_addr, esp_now_send_status_t status) {
  char macStr[18];
  Serial.print("Packet to: ");
  // Copies the sender mac address to a string
  snprintf(macStr, sizeof(macStr), "%02x:%02x:%02x:%02x:%02x:%02x",
           mac_addr[0], mac_addr[1], mac_addr[2], mac_addr[3], mac_addr[4], mac_addr[5]);
  Serial.print(macStr);
  Serial.print(" send status:\t");
  Serial.println(status == ESP_NOW_SEND_SUCCESS ? "Delivery Success" : "Delivery Fail");
}
 
void setup() {
  Serial.begin(115200);
 
  WiFi.mode(WIFI_STA);
 
  if (esp_now_init() != ESP_OK) {
    Serial.println("Error initializing ESP-NOW");
    return;
  }
  
  esp_now_register_send_cb(OnDataSent);
   
  // register peer
  peerInfo.channel = 0;  
  peerInfo.encrypt = false;
  // register first peer  
  memcpy(peerInfo.peer_addr, broadcastAddress1, 6);
  if (esp_now_add_peer(&peerInfo) != ESP_OK){
    Serial.println("Failed to add peer");
    return;
  }
  // register second peer  
  memcpy(peerInfo.peer_addr, broadcastAddress2, 6);
  if (esp_now_add_peer(&peerInfo) != ESP_OK){
    Serial.println("Failed to add peer");
    return;
  }
  /// register third peer
  memcpy(peerInfo.peer_addr, broadcastAddress3, 6);
  if (esp_now_add_peer(&peerInfo) != ESP_OK){
    Serial.println("Failed to add peer");
    return;
  }
}
 
void loop() {
  test.x = random(0,20);
  test.y = random(0,20);
 
  esp_err_t result = esp_now_send(0, (uint8_t *) &test, sizeof(test_struct));
   
  if (result == ESP_OK) {
    Serial.println("Sent with success");
  }
  else {
    Serial.println("Error sending the data");
  }
  delay(2000);
}

**Comment by Alvin1Zhang** [comment] 2022-05-20 01:21
Close as duplicate of https://github.com/espressif/esp-idf/issues/8992

**Closed** 2022-05-20 01:21 UTC
Labels: Status: Opened

**Comment by SuGlider** [comment] 2022-07-27 22:53
Check solution in:
https://github.com/espressif/esp-idf/issues/8992#issuecomment-1197443125
https://github.com/espressif/esp-idf/issues/8992#issuecomment-1197446232
