### ISSUE TITLE
Python environment setting problem during toolchain installation (IDFGH-8489)

### ISSUE THREAD

**Issue by Zeni241** [espressif/esp-idf#9947] opened 2022-10-10 12:19 UTC
I have downloaded esp-idf v4.4.2 and installing toolchain manually (after setting the environment ‎variables). ‎
I tried many times running install.ps1, but in the end I get the error :‎

_Setting up Python environment
usage: idf_tools.py [-h] [--quiet] [--non-interactive] [--tools-json TOOLS_JSON] [--idf-path IDF_PATH]‎
‎                    {list,check,export,install,download,install-python-env} ...‎
**idf_tools.py: error: unrecognized arguments: --features=‎**_

I think following line in script “install.ps1” is giving problem. ‎
_‎"$IDF_PATH/tools/idf_tools.py install-python-env --features=${FEATURES}"_

Also I observed that install.ps1 in ver4.4.2 is different than previous versions.‎

This is the output I get:
_D:\IDF442>$Env:IDF_TOOLS_PATH= "d:\IDFTchain442"‎
D:\IDF442>$Env:IDF_TOOLS_PATH
D:\IDF442>./install.ps1‎
Installing ESP-IDF tools
Current system platform: win64‎
Selected targets are: esp32c3, esp32h2, esp32s3, esp32, esp32s2‎
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, cmake, ‎openocd-esp32, ninja, idf-exe, ccache, dfu-util
Skipping xtensa-esp32-elf@esp-2021r2-patch3-8.4.0 (already installed)‎
Skipping xtensa-esp32s2-elf@esp-2021r2-patch3-8.4.0 (already installed)‎
Skipping xtensa-esp32s3-elf@esp-2021r2-patch3-8.4.0 (already installed)‎
Skipping riscv32-esp-elf@esp-2021r2-patch3-8.4.0 (already installed)‎
Skipping esp32ulp-elf@2.28.51-esp-20191205 (already installed)‎
Skipping esp32s2ulp-elf@2.28.51-esp-20191205 (already installed)‎
Skipping cmake@3.23.1 (already installed)‎
Skipping openocd-esp32@v0.11.0-esp32-20220411 (already installed)‎
Skipping ninja@1.10.2 (already installed)‎
Skipping idf-exe@1.0.3 (already installed)‎
Skipping ccache@4.3 (already installed)‎
Skipping dfu-util@0.9 (already installed)‎
Setting up Python environment
usage: idf_tools.py [-h] [--quiet] [--non-interactive] [--tools-json TOOLS_JSON] [--idf-path IDF_PATH]‎
‎                    {list,check,export,install,download,install-python-env} ...‎
idf_tools.py: error: unrecognized arguments: --features=‎_

**Comment by dobairoland** [comment] 2022-10-10 13:56
It looks like this is duplicate of https://github.com/espressif/esp-idf/issues/9616 and https://github.com/espressif/esp-idf/issues/9556.

https://github.com/espressif/esp-idf/commit/a1f03817975d29fc332e81d0420859bb8677053e will be part of v4.4.3 and released soon. You can apply this fix until then to work around the issue.

**Closed by dobairoland** 2022-10-10 13:56 UTC
Labels: Status: Opened
