### ISSUE TITLE
Add support for ethernet PHY with integrated switch like KSZ8463 (IDFGH-1845)

### ISSUE THREAD

**Issue by joa77** [espressif/esp-idf#4054] opened 2019-09-11 15:06 UTC
I would be great to have support for ethernet PHYs with integrated switch. For example the Microchip KSZ8463.
So you can daisy chain your devices together, with no need for a seperate switch

**Comment by suda-morris** [comment] 2019-09-18 09:28
Hi @joa77 
I would say it's an amazing idea to have such a feature, we will take that into consideration. 

But I'm sorry maybe it's not a high priority to implement such a feature.

**Comment by joa77** [comment] 2019-09-19 07:40
Thanks for your support. I will then wait until some switch phy is integrated

**Comment by kostaond** [comment] 2021-07-14 05:49
Duplicate to #6488. Check it for current activity.

**Comment by Alvin1Zhang** [comment] 2021-07-30 06:15
Close as duplicate of https://github.com/espressif/esp-idf/issues/6488

**Closed by Alvin1Zhang** 2021-07-30 06:15 UTC
