### ISSUE TITLE
Unable to restart Advertising after NimBLE reset event occurred. (IDFGH-2956)

### ISSUE THREAD

**Issue by tmsalidor** [espressif/esp-idf#4989] opened 2020-03-25 14:08 UTC
## Environment

- Development Kit:      [none]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version: v3.3.1
- Build System:         [Make]
- Compiler version: 1.22.0-80-g6c4433a
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

We are using NimBLE stack with esp-idf version 3.3.1. It runs BLE server and is connected from iOS or Android application. It starts advertising after power-up, stops when connected and restarts when disconnected. It works normally well but we noticed an issue. When NimBle stack signals reset event during Advertising, it's unable to restart adverting after it anyway.

### Expected Behavior
The handling of reset event is noted in link below.
http://mynewt.apache.org/v1_7_0/network/ble_setup/ble_sync_cb.html
When Nimble detects something wrong, it signals reset event callback and reset controller.
Nimble stack re-syncs with controller and signals sync event callback.
Our code can start advertising after reception of sync event.

### Actual Behavior
Nimble signals reset event callback and then signals sync event callback after a while.
Our code requests to start advertising, but it gets error response 2 (BLE_HS_EALREADY). It looks already advertising working, but not actually.

### Steps to reproduce

1. Power up and initialize NimBLE stack.
2. Our code receives sync event from NimBLE then starts advertising by ble_gap_adv_start() API.
3. Connected by iOS or Android application. Do some processes.
4. Our code calls esp_ota_begin() API, and it sometimes causes erroneous disconnection of BLE (known behavior in issue https://github.com/espressif/esp-idf/issues/3551). Our code receives GAP disconnection event therefore restart advertising by ble_gap_adv_start() API.
5. Sometimes NimBLE reset event appears. Sync event also appears after a while then our code starts advertising by ble_gap_adv_start() API, but it fails.

### Code to reproduce this issue
Almost derived from esp-idf/components/examples/bluetooth/nimble/bleprph/main/main.c.

<details>
<summary>Code</summary>

```
void nm_ble_on_sync(void)
{
    int rc;

    /* Figure out address to use while advertising (no privacy for now) */
    rc = ble_hs_id_infer_auto(0, &s_own_addr_type);
    if (rc != 0) {
        ESP_LOGE(TAG, "error determining address type; rc=%d", rc);
        assert(false);
        return;
    }

    /* Printing ADDR */
    uint8_t addr_val[6] = {0};
    rc = ble_hs_id_copy_addr(s_own_addr_type, addr_val, NULL);
    if (rc != 0) {
        ESP_LOGE(TAG, "error determining address type; rc=%d", rc);
        assert(false);
        return;
    }

    ESP_LOGI(TAG, "BLE mac address: %02X:%02X:%02X:%02X:%02X:%02X",
    addr_val[0], addr_val[1], addr_val[2], addr_val[3], addr_val[4], addr_val[5]);

    rc = bleprph_advertise();
    if (rc) {
        ESP_LOGE(TAG, "bleprph_advertise fail: %d", rc);

    }
}

static void nim_on_reset(int reason)
{
    ESP_LOGI(TAG, "nim_on_reset() started");
    MODLOG_DFLT(ERROR, "Resetting state; reason=%d\n", reason);
}

static void nim_on_sync(void)
{
    ESP_LOGI(TAG, "%s:%d", __FUNCTION__, __LINE__);
    int rc;

    /* Make sure we have proper identity address set (public preferred) */
    rc = ble_hs_util_ensure_addr(0);
    assert(rc == 0);

    nm_ble_on_sync();
}

void nim_host_task(void *param)
{
    ESP_LOGI(TAG, "BLE Host Task Started");
    /* This function will return only when nimble_port_stop() is executed */
    nimble_port_run();

    nimble_port_freertos_deinit();
}

void nim_init(void)
{
    int rc;

    ESP_ERROR_CHECK(esp_nimble_hci_and_controller_init());

    nimble_port_init();
    /* Configure the host. */
    ble_hs_cfg.reset_cb = nim_on_reset;
    ble_hs_cfg.sync_cb = nim_on_sync;
    // ble_hs_cfg.gatts_register_cb = gatt_svr_register_cb;
    ble_hs_cfg.store_status_cb = ble_store_util_status_rr;

    ble_svc_gap_init();
    ble_svc_gatt_init();

    rc = ble_gatts_count_cfg(NM_GATT_SVR_SVCS);
    assert(rc == 0);

    rc = ble_gatts_add_svcs(NM_GATT_SVR_SVCS);
    assert(rc == 0);

    /* Set the default device name. */
    rc = ble_svc_gap_device_name_set(app_hostname());
    assert(rc == 0);

    /* XXX Need to have template for store */
    ble_store_config_init();

    nimble_port_freertos_init(nim_host_task);
}
```

</details>

## Debug Logs

<details>
<summary>Failure log</summary>

```
Disconnection Complete: status=0 handle=0 reason=8
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0007 len=0
0x07 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x7 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x17 0x02 0x01 0x06 0x03 0x03 0xff 0xff 0x0c 0x09 0x52 0x65 0x6d 0x6f 0x2d 0x38 0x31 0x46 0x42 0x45 0x43 0x02 0x0a 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0 
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0006 len=15
0x06 0x20 0x0f 0x30 0x00 0x60 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x6 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x01 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=0 
I (71469) NIM_COMMON: nim_on_reset() started
Resetting state; reason=12
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0003 len=0
0x03 0x0c 0x00 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x3 status=0 
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0001 len=0
0x01 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x1 status=0 hci_ver=8 hci_rev=782 lmp_ver=8 mfrg=96 lmp_subver=782
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0003 len=0
0x03 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x3 status=0 supp_feat=0x877bffdbfecdeebf
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0001 len=8
0x01 0x0c 0x08 0x90 0x80 0x00 0x02 0x00 0x80 0x00 0x20 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x1 status=0 
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0063 len=8
0x63 0x0c 0x08 0x00 0x00 0x80 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x63 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0001 len=8
0x01 0x20 0x08 0x7f 0x06 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x1 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0002 len=0
0x02 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x2 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0003 len=0
0x03 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x3 status=0 
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0009 len=0
0x09 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x9 status=0 bd_addr=c8:2b:96:81:fb:ee
looking up peer sec; 
I (71599) NIM_COMMON: nim_on_sync:39
I (71599) nm-bt: BLE mac address: EE:FB:81:96:2B:C8
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0007 len=0
0x07 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x7 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x17 0x02 0x01 0x06 0x03 0x03 0xff 0xff 0x0c 0x09 0x52 0x65 0x6d 0x6f 0x2d 0x38 0x31 0x46 0x42 0x45 0x43 0x02 0x0a 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0 
error enabling advertisement; rc=2
bleprph_advertise fail: 2
```

</details>

## Other items if possible

We tried to bypass the situation somehow. We called ble_gap_adv_stop() to terminate advertising before calling ble_gap_adv_start(), but it gets another error return 524 (BLE_ERR_CMD_DISALLOWED).

<details>
<summary>Failure log 2</summary>

```
Disconnection Complete: status=0 handle=0 reason=8
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0007 len=0
0x07 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x7 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x17 0x02 0x01 0x06 0x03 0x03 0xff 0xff 0x0c 0x09 0x52 0x65 0x6d 0x6f 0x2d 0x38 0x31 0x46 0x41 0x38 0x34 0x02 0x0a 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0 
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0006 len=15
0x06 0x20 0x0f 0x30 0x00 0x60 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x6 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x01 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=0 
I (54306) NIM_COMMON: nim_on_reset() started
Resetting state; reason=12
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0003 len=0
0x03 0x0c 0x00 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x3 status=0 
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0001 len=0
0x01 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x1 status=0 hci_ver=8 hci_rev=782 lmp_ver=8 mfrg=96 lmp_subver=782
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0003 len=0
0x03 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x3 status=0 supp_feat=0x877bffdbfecdeebf
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0001 len=8
0x01 0x0c 0x08 0x90 0x80 0x00 0x02 0x00 0x80 0x00 0x20 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x1 status=0 
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0063 len=8
0x63 0x0c 0x08 0x00 0x00 0x80 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x63 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0001 len=8
0x01 0x20 0x08 0x7f 0x06 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x1 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0002 len=0
0x02 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x2 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0003 len=0
0x03 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x3 status=0 
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0009 len=0
0x09 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x9 status=0 bd_addr=c8:2b:96:81:fa:86
looking up peer sec; 
I (54436) NIM_COMMON: nim_on_sync:42
GAP procedure initiated: stop advertising.
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=12 
W (54456) NIM_COMMON: ble_gap_adv_stop fail: 524
I (54456) nm-bt: BLE mac address: 86:FA:81:96:2B:C8
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0007 len=0
0x07 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x7 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x17 0x02 0x01 0x06 0x03 0x03 0xff 0xff 0x0c 0x09 0x52 0x65 0x6d 0x6f 0x2d 0x38 0x31 0x46 0x41 0x38 0x34 0x02 0x0a 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0 
E (54496) nm-bt: error enabling advertisement; rc=2
E (54506) nm-bt: bleprph_advertise fail: 2
```

</details>

We guessed this is because of mismatch of state recognition between BLE controller and host and searched available API to recover it, but nothing likely found. The flag ble_gap_slave[0].op looks causing ble_gap_adv_start() returns error 2 (BLE_HS_EALREADY). We modified esp-idf to allow direct call to ble_gap_slave_reset_state() API and used it just before to call ble_gap_adv_start(). With this try start advertising was accepted.

<details>
<summary>Success log</summary>

```
Disconnection Complete: status=0 handle=0 reason=8
D (54717) nm-bt: bleprph_gap_event:110
D (54717) nm-bt: event->type: 14
D (54727) nm-bt: subscribe event; conn_handle=0 attr_handle=8 reason=2 prevn=0 curn=0 previ=1 curi=0

D (54727) nm-bt: xSemaphoreTake bleprph_gap_event:253
D (54737) nm-bt: xSemaphoreGive bleprph_gap_event:260
D (54747) nm-bt: bleprph_gap_event:110
D (54747) nm-bt: event->type: 14
D (54747) nm-bt: subscribe event; conn_handle=0 attr_handle=14 reason=2 prevn=1 curn=0 previ=0 curi=0

D (54757) nm-bt: xSemaphoreTake bleprph_gap_event:253
D (54767) nm-bt: xSemaphoreGive bleprph_gap_event:260
D (54767) nm-bt: bleprph_gap_event:110
D (54777) nm-bt: event->type: 1
I (54777) nm-bt: blufi session disconnect
D (54777) nm-bt: xSemaphoreTake bleprph_gap_event:172
D (54787) nm-bt: xSemaphoreGive bleprph_gap_event:216
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0007 len=0
0x07 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x7 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x17 0x02 0x01 0x06 0x03 0x03 0xff 0xff 0x0c 0x09 0x52 0x65 0x6d 0x6f 0x2d 0x38 0x31 0x46 0x41 0x38 0x34 0x02 0x0a 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0 
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0006 len=15
0x06 0x20 0x0f 0x30 0x00 0x60 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x6 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x01 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=0 
I (54867) NIM_COMMON: nim_on_reset() started
Resetting state; reason=12
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0003 len=0
0x03 0x0c 0x00 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x3 status=0 
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0001 len=0
0x01 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x1 status=0 hci_ver=8 hci_rev=782 lmp_ver=8 mfrg=96 lmp_subver=782
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0003 len=0
0x03 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x3 status=0 supp_feat=0x877bffdbfecdeebf
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0001 len=8
0x01 0x0c 0x08 0x90 0x80 0x00 0x02 0x00 0x80 0x00 0x20 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x1 status=0 
ble_hs_hci_cmd_send: ogf=0x03 ocf=0x0063 len=8
0x63 0x0c 0x08 0x00 0x00 0x80 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x3 ocf=0x63 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0001 len=8
0x01 0x20 0x08 0x7f 0x06 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x1 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0002 len=0
0x02 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x2 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0003 len=0
0x03 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x3 status=0 
ble_hs_hci_cmd_send: ogf=0x04 ocf=0x0009 len=0
0x09 0x10 0x00 
Command complete: cmd_pkts=5 ogf=0x4 ocf=0x9 status=0 bd_addr=c8:2b:96:81:fa:86
looking up peer sec; 
I (54987) NIM_COMMON: nim_on_sync:43
I (54997) nm-bt: BLE mac address: 86:FA:81:96:2B:C8
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0007 len=0
0x07 0x20 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x7 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0008 len=32
0x08 0x20 0x20 0x17 0x02 0x01 0x06 0x03 0x03 0xff 0xff 0x0c 0x09 0x52 0x65 0x6d 0x6f 0x2d 0x38 0x31 0x46 0x41 0x38 0x34 0x02 0x0a 0x03 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x8 status=0 
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x0006 len=15
0x06 0x20 0x0f 0x30 0x00 0x60 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x07 0x00 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0x6 status=0 
ble_hs_hci_cmd_send: ogf=0x08 ocf=0x000a len=1
0x0a 0x20 0x01 0x01 
Command complete: cmd_pkts=5 ogf=0x8 ocf=0xa status=0 
```

</details>

With above results, we guess current esp-idf (or NimBLE stack) is missing some necessary clean-up process in NimBLE host layer at NimBLE controller reset event.

**Comment by dhrishi** [comment] 2020-03-26 03:40
@tmsalidor Thanks for reporting the issue. We are already working on making NimBLE stack behave correctly after reset and have raised an upstream request, see here: https://github.com/apache/mynewt-nimble/pull/777

Once that is reviewed and integrated, we will include the same in esp-nimble as well.

**Comment by tmsalidor** [comment] 2020-03-27 14:59
@dhrishi Thanks for your comment. I got the cause and fix is already in progress.

**Comment by prasad-alatkar** [comment] 2020-05-21 05:13
Hi @tmsalidor Can you please confirm if the issue is resolved with latest `release/v3.3` ?  Reference commit on IDF `release/v3.3`: aad04405.

**Comment by tmsalidor** [comment] 2020-05-30 03:41
Hello @prasad-alatkar, I checked the latest commit of release/v3.3 and confirmed it's resolved. Thanks a lot.

**Comment by dhrishi** [comment] 2020-05-30 04:52
@tmsalidor Great! Can you please close this issue?

**Closed** 2020-05-30 08:07 UTC
