### ISSUE TITLE
GPIO 36, 39, 34, 35 are not configuring properly as UART Rx pin (IDFGH-689)

### ISSUE THREAD

**Issue by PranavD10** [espressif/esp-idf#3141] opened 2019-03-07 13:26 UTC
I am using ESP32 development board and want to use the any of the GPIO pins 36, 39, 34, 35 as a UART Rx pin. 
I use uart_select_example.c to check whether they work properly or not.
I found that when I configure pin 36 as Rx the pin 36 and 39 both are susceptible and causes reception.
Same thing happen with 34 and 35.
What could be the reason that the other pin also causes the reception...??

**Comment by koobest** [comment] 2019-03-18 02:52
Hi, @PranavD10
Has this problem been solved? I don't quite understand the issue you described. Can you please tell me how can I reproduce this issue and what is the phenomenon?

thanks!!

**Comment by koobest** [comment] 2019-04-01 01:55
Hi, @PranavD10
Can you please share your progress here :-).
thanks !!

**Comment by Alvin1Zhang** [comment] 2019-05-16 10:02
@PranavD10 Thanks for reporting the issue. Will close the issue for now due to lack of details. Feel free to reopen and please please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md). Thanks.

**Closed by Alvin1Zhang** 2019-05-16 10:02 UTC

**Comment by KonstantinKondrashov** [comment] 2019-05-16 11:26
I think this issue the same as [this](https://github.com/espressif/esp-idf/issues/3141). If you consider that it is not the same please give us more information about your issue. Thanks.

**Comment by Mr-HaleYa** [comment] 2020-11-20 03:44
I think this may be why. it looks like they are connected internally 
![image](https://user-images.githubusercontent.com/42821995/99755408-f435be80-2aa7-11eb-9fc1-cee3e135005e.png)
