### ISSUE TITLE
USB slave continuous restart issue (IDFGH-11344)

### ISSUE THREAD

**Issue by Firmware-beginner** [espressif/esp-idf#12492] opened 2023-10-31 08:54 UTC
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I'm using TI's MSP430F5XXX microcontroller(USB slave) with inbuilt USB stack and TI's custom VID PID, 
USB slave is connected to ESP32S3(USB host). I'm using ESP-IDF 5.1 CMD for build, flash and monitor.
I'm facing issues opening the slave device using usb host cdc_acm_vcp example, the issue is that the
device keeps on restarting. I am not able to understand why device is restarting.

The LOGS of the device is given below : 

I (329) main_task: Calling app_main()
I (329) VCP example: Installing USB Host
I (369) VCP example: Installing CDC-ACM driver
I (369) VCP example: Opening any VCP device...
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x4200a330  PS      : 0x00060530  A0      : 0x8200a8f2  A1      : 0x3fc98f30
0x4200a330: cdc_acm_transfers_allocate at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_cdc_acm/cdc_acm_host.c:625

A2      : 0x3fc9d190  A3      : 0x3fc9d3cc  A4      : 0x00000000  A5      : 0x00000200
A6      : 0x00000000  A7      : 0x00000200  A8      : 0x42009fc0  A9      : 0x3fc98f10
0x42009fc0: in_xfer_cb at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_cdc_acm/cdc_acm_host.c:1009

A10     : 0x00000000  A11     : 0x00000000  A12     : 0x3fc9d19c  A13     : 0x3fc9d300
A14     : 0xb33fffff  A15     : 0xb33fffff  SAR     : 0x0000001a  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000002  LBEG    : 0x400570e8  LEND    : 0x400570f3  LCOUNT  : 0x00000000
0x400570e8: memset in ROM

0x400570f3: memset in ROM

Backtrace: 0x4200a32d:0x3fc98f30 0x4200a8ef:0x3fc98f90 0x42009a51:0x3fc98fe0 0x4200893d:0x3fc99030 0x42008969:0x3fc99050 0x42009ba2:0x3fc99070 0x4200905d:0x3fc990e0 0x42027b8b:0x3fc99150 0x4037c611:0x3fc99180
0x4200a32d: cdc_acm_transfers_allocate at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_cdc_acm/cdc_acm_host.c:624

0x4200a8ef: cdc_acm_host_open_vendor_specific at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_cdc_acm/cdc_acm_host.c:859 (discriminator 6)

0x42009a51: CdcAcmDevice::open_vendor_specific(unsigned short, unsigned short, unsigned char, cdc_acm_host_device_config_t const*) at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_cdc_acm/include/usb/cdc_acm_host.h:317
 (inlined by) esp_usb::FT23x::FT23x(unsigned short, cdc_acm_host_device_config_t const*, unsigned char) at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_ftdi_vcp/usb_host_ftdi_vcp.cpp:43

0x4200893d: esp_usb::VCP::register_driver<esp_usb::FT23x>()::{lambda(unsigned short, cdc_acm_host_device_config_t const*, unsigned char)#1}::operator()(unsigned short, cdc_acm_host_device_config_t const*, unsigned char) const at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_vcp/include/usb/vcp.hpp:52

0x42008969: esp_usb::VCP::register_driver<esp_usb::FT23x>()::{lambda(unsigned short, cdc_acm_host_device_config_t const*, unsigned char)#1}::_FUN(unsigned short, cdc_acm_host_device_config_t const*, unsigned char) at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_vcp/include/usb/vcp.hpp:51

0x42009ba2: esp_usb::VCP::open(cdc_acm_host_device_config_t const*, unsigned char) at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/managed_components/espressif__usb_host_vcp/usb_host_vcp.cpp:72

0x4200905d: app_main at D:/esp-idf-master/esp-idf-master/examples/peripherals/usb/host/cdc/code_test/main/cdc_acm_vcp_example_main.cpp:188

0x42027b8b: main_task at C:/Espressif0/frameworks/esp-idf-v5.1-4/components/freertos/app_startup.c:208 (discriminator 13)

0x4037c611: vPortTaskWrapper at C:/Espressif0/frameworks/esp-idf-v5.1-4/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:162

ELF file SHA256: 144e3f568d52c6ea

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x4037579c
0x4037579c: esp_restart_noos_dig at C:/Espressif0/frameworks/esp-idf-v5.1-4/components/esp_system/port/esp_system_chip.c:57 (discriminator 1)

**Comment by tore-espressif** [comment] 2023-11-07 09:28
Closing as duplicate of https://github.com/espressif/esp-idf/issues/12503

**Closed by tore-espressif** 2023-11-07 09:28 UTC
Labels: Status: In Progress
