### ISSUE TITLE
[RMT]some remote controllers not working (IDFGH-1204)

### ISSUE THREAD

**Issue by keesus** [espressif/esp-idf#3509] opened 2019-05-21 05:50 UTC
## Environment

- Development Kit:  ESP32-Wrover-Kit
- Module or chip used: ESP32-WROVER-B
- Build System: CMake

i'm using [ESP32_IR_Remote.c](https://github.com/Darryl-Scott/ESP32-RMT-Library-IR-code-RAW).

I can copy IR raw datas from some remote controllers and save it and transmit it as well.

But for some remote controllers it reads raw data fine but when transmit it doesn't perform.

I found some points to make an adjustment here, 

  rmt_config_t config;
  config.rmt_mode = RMT_MODE_RX;
  config.channel = (rmt_channel_t)rmtport;
  config.gpio_num = (gpio_num_t)gpionum;
  gpio_pullup_en((gpio_num_t)gpionum);
  config.mem_block_num = 7; //how many memory blocks 64 x N (0-7)
  config.rx_config.filter_en = 1;
  config.rx_config.filter_ticks_thresh = 100; // 80000000/100 -> 800000 / 100 = 8000  = 125us
  config.rx_config.idle_threshold = TICK_10_US * 100 * 20; // originally TICK_10_US * 100 * 20
  config.clk_div = CLK_DIV;
  ESP_ERROR_CHECK(rmt_config(&config));
  ESP_ERROR_CHECK(rmt_driver_install(config.channel, 5000, 0));
  rmt_get_ringbuf_handle(config.channel, &ringBuf);
  rmt_rx_start(config.channel, 1);

and I tried some values but nothing changed.

Can anybody help me out ?

**Comment by negativekelvin** [comment] 2019-05-21 09:44
You should move this issue to the third party code repo or post in the forum.  I don't think this is directly related to esp-idf code.

It can depend on the protocol the remote uses https://globalcache.zendesk.com/hc/en-us/articles/114094165172-Tech-Tip-IR-Control-with-RC6-coded-IR-signals or the carrier frequency expected by the receiving device.

**Comment by koobest** [comment] 2019-05-21 13:22
Hi, @keesus
The information you provided can not help us debug this issue. Can you provide RMT signal waveforms?

thanks !!

**Comment by keesus** [comment] 2019-05-29 07:40
@koobest Hi, I copied by receiver and the data would be [8850,4650,400,750,400,750,400,1850,400,750,400,750,400,700,400,750,400,700,400,1850,400,1850,400,750,400,1850,400,1850,400,1850,400,1850,400,1850,400,750,400,750,400,1850,400,750,400,750,400,750,400,1850,400,1850,400,1850,400,1850,400,750,400,1850,400,1850,400,1850,400,750,400,750,400]

after I transmit the data to some air conditioner, nothing happens.
what makes me confused is it's working well to other air conditioner, TV , other devices.
I researched many IR related documents but still have no idea.

**Comment by negativekelvin** [comment] 2019-05-29 10:04
It does look like basic nec code.  What is make and model of a/c?

**Comment by keesus** [comment] 2019-05-29 10:59
@negativekelvin 

Hi there.

it says TCL air conditiner.

**Comment by koobest** [comment] 2019-07-19 06:53
Hi, @keesus
Have you solved this issue? 

> after I transmit the data to some air conditioner, nothing happens.what makes me confused is it's working well to other air conditioner, TV , other devices.I researched many IR related documents but still have no idea

You mean when you send this sequence with ESP32, it is works to some devices, but not for other devices?

Is this problem caused by the incorrect carrier frequency? Or the accepted data is wrong, so the data sent is wrong?

thanks !!

**Comment by Alvin1Zhang** [comment] 2019-08-12 02:48
@keesus Thanks for reporting the issue, will close this issue due to short of feedback, please feel free to reopen the issue if it still exists. Thanks.

**Closed by Alvin1Zhang** 2019-08-12 02:48 UTC
