### ISSUE TITLE
FreeRTOS pvTimerGetTimerID()

### ISSUE THREAD

**Issue by forthlightning** [espressif/esp-idf#376] opened 2017-02-23 23:48 UTC
Hi, I have a repo [here](https://github.com/forthlightning/freertos_timer_test), in which I am trying to encode 2 pieces of information in the ID field of a timer. 

In the same function, at [this](https://github.com/forthlightning/freertos_timer_test/blob/master/main/include/FOO.h#L69) point in my code, the parameters are pulled from the ID field and printed successfully. As configured the serial output is this:
```
constructor, meter_id: 1, read_type: 1
constructor, meter_id: 2, read_type: 1
```
Once we leave scope and are in another task [this](https://github.com/forthlightning/freertos_timer_test/blob/master/main/main.cpp#L39) print statement shows up like so:
```
callback, meter_id: 184, type: 64
callback, meter_id: 184, type: 64
```

Even with two instances of FOO class, the print statement is the same. If I change the string name of the timer [here](https://github.com/forthlightning/freertos_timer_test/blob/master/main/include/FOO.h#L60), sometimes the "meter_id" field changes.

I have tried two methods to access the return value of the pvTimerGetTimerID() function. [Pointer way](https://github.com/forthlightning/freertos_timer_test/blob/master/main/main.cpp#L31) and [memcpy way](https://github.com/forthlightning/freertos_timer_test/blob/master/main/main.cpp#L36), both of which give the same result above.

Goin' crazy over here, is this expected behavior??? Maybe a scoping issue? 

For reference: Looking at this [freertos docs page](http://www.freertos.org/FreeRTOS-timers-pvTimerGetTimerID.html).
Also notably missing is [vTimerSetTimerID()](http://www.freertos.org/FreeRTOS-timers-vTimerSetTimerID.html)

**Comment by barronbarnett** [comment] 2017-02-24 01:48
You're setting the token_ptr on the stack at run time. You're lucky in that the pointer retains the correct information on the stack since you're main thread merely sleeps.

Since this is done on the stack you will only ever see the values from FOO(2) because the initialization of FOO(2) overwrote the values on the stack of F00(1) during initialization. 

Moving the declaration of sdm_read_token my_token; into the private section of the struct will cause this to persist.

To Espressif, you can close this as it's not a bug within pvTimerGetTimerID().

**Closed** 2017-02-24 07:44 UTC
