### ISSUE TITLE
windows10 cmake build error (IDFGH-535)

### ISSUE THREAD

**Issue by dtboy1995** [espressif/esp-idf#2888] opened 2018-12-27 03:40 UTC
- windows 10
- idf version 3.1.1

```log
D:\esp\hello_world>idf.py build
Running ninja in directory D:\esp\hello_world\build
Executing "ninja all"...
[1/4] Generating hello-world.bin
FAILED: hello-world.bin
cmd.exe /C "cd /D D:\esp\hello_world\build && C:\Users\dtboy\.platformio\python27\python.exe D:/msys32/home/dtboy/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 elf2image --flash_mode dio --flash_freq 40m --flash_size 2MB -o hello-world.bin hello-world.elf"
Traceback (most recent call last):
  File "D:/msys32/home/dtboy/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 35, in <module>
    import serial.tools.list_ports as list_ports
ImportError: No module named serial.tools.list_ports
[2/4] Performing build step for 'bootloader'
FAILED: bootloader-prefix/src/bootloader-stamp/bootloader-build bootloader/bootloader.elf bootloader/bootloader.bin bootloader/bootloader.map
cmd.exe /C "cd /D D:\esp\hello_world\build\bootloader && "D:\Program Files\CMake\bin\cmake.exe" --build ."
[1/1] Generating bootloader.bin
FAILED: bootloader.bin
cmd.exe /C "cd /D D:\esp\hello_world\build\bootloader && C:\Users\dtboy\.platformio\python27\python.exe D:/msys32/home/dtboy/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 elf2image --flash_mode dio --flash_freq 40m --flash_size 2MB -o bootloader.bin bootloader.elf"
Traceback (most recent call last):
  File "D:/msys32/home/dtboy/esp/esp-idf/components/esptool_py/esptool/esptool.py", line 35, in <module>
    import serial.tools.list_ports as list_ports
ImportError: No module named serial.tools.list_ports
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```
------
```cmd
pip install pyserial
Requirement already satisfied: pyserial in d:\python27\lib\site-packages
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by dobairoland** [comment] 2018-12-27 07:42
Hello @dtboy1995!

Please try to run `C:\Users\dtboy\.platformio\python27\python.exe -m pip install pyserial`. If that doesn't help you then please post here the output of `C:\Users\dtboy\.platformio\python27\python.exe -m pip show pyserial`

**Comment by dtboy1995** [comment] 2018-12-27 07:52
@dobairoland be deeply grateful. it works well

**Comment by dtboy1995** [comment] 2018-12-27 07:55
@dobairoland Thank you, I would like to ask you a question, my python environment variable is set to D:\Python27, why the path will be changed to C:\Users\dtboy\. Platformio \Python27 \ after using idf.py?

**Comment by dtboy1995** [comment] 2018-12-28 08:36
@dobairoland 
Sorry for not replying in time
This is a screenshot
<img width="342" alt="default" src="https://user-images.githubusercontent.com/19227547/50508880-acc27580-0abe-11e9-9ed9-e25a239fc60d.PNG">

**Comment by dobairoland** [comment] 2019-01-02 15:00
Hello @dtboy1995.

Yes, you are right. It seems that `esptool` was invoked with a different Python interpreter than `idf.py` was invoked with. However, I wasn't able to find the root cause, therefore, I reopened the issue to help track this as TODO.

**Comment by dtboy1995** [comment] 2019-01-03 01:32
thanks a lot @dobairoland

**Comment by projectgus** [comment] 2019-03-28 03:32
Hi @dtboy1995 & @dcm684w ,

Thanks for being patient while someone got back to you about this.

The root cause for this issue was fixed in commit d0b2d5ec95113fc7c9ec17787e16d30afb8aebf5. In some cases, the default interpreter registered in Windows for ".py" files was being used to execute a Python script instead of the correct interpreter.

In @dtboy1995's case, it looks like the python.exe in the `.platformio` directory was registered as the interpreter for .py files, but this was not the interpreter that was used to run idf.py.

If you update to the latest master branch, the same Python interpreter should be used throughout. Please leave another comment if that's not the case, and we'll reopen.

**Closed by projectgus** 2019-03-28 03:32 UTC

**Comment by projectgus** [comment] 2019-03-28 03:36
@dtboy1995 Oops, I missed you were using the 3.1.1 release. This hasn't been backported to v3.1 yet, but it will be. Will update this issue when that fix is merged.

**Comment by dtboy1995** [comment] 2019-03-28 03:38
@projectgus, thank you very much for your hard work.

**Comment by projectgus** [comment] 2019-03-29 05:47
@dtboy1995 Actually there's something a bit odd here, the error you got matches a fix we made in master branch but that bug was never in the 3.1 release branch (the bug was introduced after we had created the 3.1 release branch).

There are two possibilities:

1. This error has a different root cause
2 You were using master branch when you reported the issue, not the 3.1.1 release.

Could you please double check for me?

**Comment by dtboy1995** [comment] 2019-03-29 06:04
@projectgus I am very sorry, after that I used the Ubuntu system

**Comment by projectgus** [comment] 2019-03-29 06:07
@dtboy1995 No problems. Glad you found a workaround.

@dcm684w If you're still experiencing this bug, please let us know your IDF version and we can reopen the issue.
