### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled. (IDFGH-12617)

### ISSUE THREAD

**Issue by sRubyy** [espressif/esp-idf#13614] opened 2024-04-15 20:41 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x40089fe8  PS      : 0x00060530  A0      : 0x800dd8f4  A1      : 0x3ffd8cf0  
A2      : 0x00000000  A3      : 0x3ffb2330  A4      : 0x00000800  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x00000004  
A10     : 0x3ffb5e68  A11     : 0x80000001  A12     : 0x80091180  A13     : 0x3ffd8be0  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000016  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x40089fe4  LEND    : 0x40089ffa  LCOUNT  : 0x0000007f  

Backtrace: 0x40089fe5:0x3ffd8cf0 0x400dd8f1:0x3ffd8d00 0x400d464b:0x3ffd8d40

Decoding stack results
0x400dd8f1: i2s_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/driver/i2s.c line 2283
0x400d464b: i2s_rec(void*) at C:\Users\yokfr\OneDrive\Documents\Arduino\MonitorRec/MonitorRec.ino line 352

This problem occurred when my recording task was created a second time but it worked fine the first time that it was created.

I'm working with ESP32-WROOM-32E on an Arduini IDE.

**Comment by igrr** [comment] 2024-05-10 13:37
Hi @sRubyy,

To understand the register dump, please take a look at this document: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html#loadprohibited-storeprohibited. In this case, `StoreProhibited` exception with `EXCVADDR: 0x00000000` indicates that the program has tried writing something to a NULL pointer. Please check your code and make sure you are not passing a NULL pointer argument to `i2s_read` in `MonitorRec.ino line 352`.
Perhaps when you create the task the second time, memory allocation fails and the buffer you are using is NULL.

I'll close the issue since it doesn't look like a bug on ESP-IDF side. If you think the issue is in ESP-IDF, please try to narrow it down to a smaller sample program you can share with us.

**Closed by igrr** 2024-05-10 13:37 UTC
Labels: Status: Opened
