### ISSUE TITLE
idf.py menuconfig failed "cmake failed with exit code 3221225725" (IDFGH-3090)

### ISSUE THREAD

**Issue by javfernandez** [espressif/esp-idf#5111] opened 2020-04-13 15:03 UTC
Hi everybody I have a problem while executing the idf.py menuconfig:
Operation system:Windows 10.
Python Version: Python  3.7.2
The command is: >idf.py --port COM10 -C ./hello_world -v menuconfig
And I get 
Checking Python dependencies...
Python requirements from C:\Users\USUARIO\Desktop\esp-idf\requirements.txt are satisfied.
Executing action: menuconfig
Running cmake in directory c:\users\usuario\desktop\esp-idf\hello_world\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized -DCCACHE_ENABLE=0 c:\users\usuario\desktop\esp-idf\hello_world"...
Warn about uninitialized values.
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
-- mconf-idf version mconf-v4.6.0.0-idf-20190628-win32
-- IDF_TARGET not set, using default target: esp32
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe
-- Check for working CXX compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project version: v4.0-dirty
-- Building ESP-IDF components for target esp32
cmake failed with exit code 3221225725

What Im doing wrong
Thanks

**Comment by Alvin1Zhang** [comment] 2020-04-14 01:47
@javfernandez Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, and etc. would help us debug further. Thanks.

**Comment by renzbagaporo** [comment] 2020-04-14 02:59
Hi @javfernandez, I cannot seem to reproduce this issue on my Windows machine. What version of CMake do you have?

Also, can you test executing the command on the actual example directory (minus `-C ./hello_world ` of course)

**Comment by dobairoland** [comment] 2020-04-14 07:45
Neither could I reproduce. Even the `-C` option works for me as it should be in the v4.0 branch.

This is suspicious:
> Project version: v4.0-dirty

Please examine the output of `git status`, clean uncommitted changes and update the submodules.

**Comment by javfernandez** [comment] 2020-04-14 13:29
I executed from de example directory as @renzbagaporo suggested. I get the following output:
C:\Users\USUARIO\Desktop\esp-idf\hello_world>idf.py --port COM10 -v menuconfig
Checking Python dependencies...
Python requirements from C:\Users\USUARIO\Desktop\esp-idf\requirements.txt are satisfied.
Executing action: menuconfig
Running cmake in directory c:\users\usuario\desktop\esp-idf\hello_world\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized -DCCACHE_ENABLE=0 c:\users\usuario\desktop\esp-idf\hello_world"...
Warn about uninitialized values.
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
-- mconf-idf version mconf-v4.6.0.0-idf-20190628-win32
-- IDF_TARGET not set, using default target: esp32
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 8.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe
-- Check for working CXX compiler: C:/Users/USUARIO/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project version: v4.0-dirty
-- Building ESP-IDF components for target esp32
Traceback (most recent call last):
  File "C:/Users/USUARIO/Desktop/esp-idf/tools/kconfig_new/confgen.py", line 571, in <module>
    main()
  File "C:/Users/USUARIO/Desktop/esp-idf/tools/kconfig_new/confgen.py", line 282, in main
    output_function(deprecated_options, config, temp_file)
  File "C:/Users/USUARIO/Desktop/esp-idf/tools/kconfig_new/confgen.py", line 298, in write_config
    deprecated_options.append_config(config, filename)
  File "C:/Users/USUARIO/Desktop/esp-idf/tools/kconfig_new/confgen.py", line 156, in append_config
    with open(path_output, 'a') as f_o:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\USUARIO\\AppData\\Local\\Temp\\confgen_tmp5033pqq0'
CMake Error at C:/Users/USUARIO/Desktop/esp-idf/tools/cmake/kconfig.cmake:208 (message):
  Failed to run confgen.py
  (C:\Users\USUARIO\.espressif\python_env\idf4.0_py3.7_env\Scripts\python.exe;C:/Users/USUARIO/Desktop/esp-idf/tools/kconfig_new/confgen.py;--kconfig;C:/Users/USUARIO/Desktop/esp-idf/Kconfig;--sdkconfig-rename;C:/Users/USUARIO/Desktop/esp-idf/sdkconfig.rename;--config;C:/Users/USUARIO/Desktop/esp-idf/hello_world/sdkconfig;--env-file;C:/Users/USUARIO/Desktop/esp-idf/hello_world/build/config.env).
  Error 1
Call Stack (most recent call first):
  C:/Users/USUARIO/Desktop/esp-idf/tools/cmake/build.cmake:441 (__kconfig_generate_config)
  C:/Users/USUARIO/Desktop/esp-idf/tools/cmake/project.cmake:337 (idf_build_process)
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/USUARIO/Desktop/esp-idf/hello_world/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1

cd

**Comment by renzbagaporo** [comment] 2020-04-20 03:29
This seems to be a different error entirely @javfernandez. I'm inclined to be suspicious of the possible modifications as @dobairoland mentioned:

```
Project version: v4.0-dirty
```

I second his suggestion of:

```
Please examine the output of git status, clean uncommitted changes and update the submodules.
```

and trying again...

**Comment by renzbagaporo** [comment] 2020-04-22 04:38
Any updates @javfernandez ?

**Comment by javfernandez** [comment] 2020-04-22 11:23
Hi, Im gonna try what @renzbagaporo suggestedd. I see there is a lot of uncommited changes in the repository and I want to try to update the repository

**Comment by javfernandez** [comment] 2020-04-24 12:14
Well, I made it work, I had to dischard all changes and updates all submodules
Thanks for all!

**Comment by renzbagaporo** [comment] 2020-04-26 07:42
Thanks for the update @javfernandez. Please close the issue if this is no longer an issue. Thanks!

**Closed** 2020-04-26 15:09 UTC

**Comment by rkashish75** [comment] 2022-09-23 17:11
https://github.com/renzbagaporo how to do the following?
Please examine the output of git status, clean uncommitted changes and update the submodules.

**Comment by rkashish75** [comment] 2022-09-23 17:17
I get the following when i install esp-at

PS C:\Espressif\frameworks\esp-idf-v4.4\esp\esp-at> python build.py install
Ready to install ESP-IDF prerequisites..
Windows Installer Download has already installed all prerequisites.
Ready to install ESP-AT prerequisites..
Requirement already satisfied: setuptools>=21 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 4)) (51.3.3)
Requirement already satisfied: cryptography<35,>=2.1.4 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 9)) (3.4.8)
Requirement already satisfied: pyyaml in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 10)) (6.0)
Requirement already satisfied: xlrd in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 11)) (2.0.1)
Collecting pycryptodome==3.15.0
  Downloading pycryptodome-3.15.0-cp35-abi3-win_amd64.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 965.8 kB/s eta 0:00:00
Collecting idf-component-manager==1.1.4
  Downloading idf_component_manager-1.1.4-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: contextlib2>0.6.0 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (21.6.0)
Requirement already satisfied: schema in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.7.5)
Requirement already satisfied: requests-toolbelt in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.9.1)
Requirement already satisfied: requests<3 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (2.27.1)
Requirement already satisfied: future in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.18.2)
Requirement already satisfied: click>=8.0.0 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (8.0.4)
Requirement already satisfied: colorama in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.4.4)
Requirement already satisfied: tqdm<5 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (4.63.0)
Requirement already satisfied: six in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (1.16.0)
Requirement already satisfied: cffi>=1.12 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from cryptography<35,>=2.1.4->-r requirements.txt (line 9)) (1.15.0)
Requirement already satisfied: pycparser in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from cffi>=1.12->cryptography<35,>=2.1.4->-r requirements.txt (line 9)) (2.21)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (2021.10.8)
Installing collected packages: pycryptodome, idf-component-manager
  Attempting uninstall: idf-component-manager
    Found existing installation: idf-component-manager 1.0.1
    Uninstalling idf-component-manager-1.0.1:
      Successfully uninstalled idf-component-manager-1.0.1
Successfully installed idf-component-manager-1.1.4 pycryptodome-3.15.0

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Platform name:
1. PLATFORM_ESP32
2. PLATFORM_ESP32C3
3. PLATFORM_ESP32C2
choose(range[1,3]):1

Module name:
1. WROOM-32
2. WROVER-32
3. PICO-D4
4. SOLO-1
5. MINI-1 (description: ESP32-U4WDH chip inside)
6. ESP32-SDIO
7. ESP32-D2WD (description: 2MB flash, No OTA)
8. ESP32_QCLOUD (description: QCLOUD TX:17 RX:16)
choose(range[1,8]):1

Enable silence mode to remove some logs and reduce the firmware size?
0. No
1. Yes
choose(range[0,1]):1
Platform name:ESP32     Module name:WROOM-32    Silence:1
Cloning into submodule:"esp-idf" from "https://github.com/espressif/esp-idf.git" (This may take time)..
Cloning into 'esp-idf'...
remote: Enumerating objects: 378620, done.
remote: Counting objects: 100% (3897/3897), done.
remote: Compressing objects: 100% (1623/1623), done.
remote: Total 378620 (delta 2291), reused 3679 (delta 2130), pack-reused 374723
Receiving objects: 100% (378620/378620), 206.50 MiB | 1.76 MiB/s, done.
Resolving deltas: 100% (279073/279073), done.
Updating files: 100% (8478/8478), done.
Submodule 'components/asio/asio' (https://github.com/espressif/asio.git) registered for path 'components/asio/asio'
Submodule 'components/bootloader/subproject/components/micro-ecc/micro-ecc' (https://github.com/kmackay/micro-ecc.git) registered for path 'components/bootloader/subproject/components/micro-ecc/micro-ecc'
Submodule 'components/bt/controller/lib_esp32' (https://github.com/espressif/esp32-bt-lib.git) registered for path 'components/bt/controller/lib_esp32'
Submodule 'components/bt/controller/lib_esp32c3_family' (https://github.com/espressif/esp32c3-bt-lib.git) registered for path 'components/bt/controller/lib_esp32c3_family'
Submodule 'components/bt/host/nimble/nimble' (https://github.com/espressif/esp-nimble.git) registered for path 'components/bt/host/nimble/nimble'
Submodule 'components/cbor/tinycbor' (https://github.com/intel/tinycbor.git) registered for path 'components/cbor/tinycbor'
Submodule 'components/cmock/CMock' (https://github.com/ThrowTheSwitch/CMock.git) registered for path 'components/cmock/CMock'
Submodule 'components/coap/libcoap' (https://github.com/obgm/libcoap.git) registered for path 'components/coap/libcoap'
Submodule 'components/esp_wifi/lib' (https://github.com/espressif/esp32-wifi-lib.git) registered for path 'components/esp_wifi/lib'
Submodule 'components/esptool_py/esptool' (https://github.com/espressif/esptool.git) registered for path 'components/esptool_py/esptool'
Submodule 'components/expat/expat' (https://github.com/libexpat/libexpat.git) registered for path 'components/expat/expat'
Submodule 'components/json/cJSON' (https://github.com/DaveGamble/cJSON.git) registered for path 'components/json/cJSON'
Submodule 'components/libsodium/libsodium' (https://github.com/jedisct1/libsodium.git) registered for path 'components/libsodium/libsodium'
Submodule 'components/lwip/lwip' (https://github.com/espressif/esp-lwip.git) registered for path 'components/lwip/lwip'
Submodule 'components/mbedtls/mbedtls' (https://github.com/espressif/mbedtls.git) registered for path 'components/mbedtls/mbedtls'
Submodule 'components/mqtt/esp-mqtt' (https://github.com/espressif/esp-mqtt.git) registered for path 'components/mqtt/esp-mqtt'
Submodule 'components/nghttp/nghttp2' (https://github.com/nghttp2/nghttp2.git) registered for path 'components/nghttp/nghttp2'
Submodule 'components/protobuf-c/protobuf-c' (https://github.com/protobuf-c/protobuf-c.git) registered for path 'components/protobuf-c/protobuf-c'
Submodule 'components/spiffs/spiffs' (https://github.com/pellepl/spiffs.git) registered for path 'components/spiffs/spiffs'
Submodule 'components/tinyusb/tinyusb' (https://github.com/espressif/tinyusb.git) registered for path 'components/tinyusb/tinyusb'
Submodule 'components/unity/unity' (https://github.com/ThrowTheSwitch/Unity.git) registered for path 'components/unity/unity'
Submodule 'examples/build_system/cmake/import_lib/main/lib/tinyxml2' (https://github.com/leethomason/tinyxml2.git) registered for path 'examples/build_system/cmake/import_lib/main/lib/tinyxml2'
Submodule 'examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib' (https://github.com/espressif/esp-cryptoauthlib.git) registered for path 'examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib'
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/asio/asio'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/bootloader/subproject/components/micro-ecc/micro-ecc'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/bt/controller/lib_esp32'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/bt/controller/lib_esp32c3_family'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/bt/host/nimble/nimble'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/cbor/tinycbor'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/cmock/CMock'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/coap/libcoap'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/esp_wifi/lib'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/esptool_py/esptool'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/expat/expat'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/json/cJSON'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/libsodium/libsodium'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/lwip/lwip'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/mbedtls/mbedtls'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/mqtt/esp-mqtt'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/nghttp/nghttp2'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/protobuf-c/protobuf-c'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/spiffs/spiffs'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/tinyusb/tinyusb'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/unity/unity'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/examples/build_system/cmake/import_lib/main/lib/tinyxml2'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib'...
Submodule path 'components/asio/asio': checked out 'f31694c9f1746ba189a4bcae2e34db15135ddb22'
Submodule path 'components/bootloader/subproject/components/micro-ecc/micro-ecc': checked out 'd037ec89546fad14b5c4d5456c2e23a71e554966'
Submodule path 'components/bt/controller/lib_esp32': checked out 'c98341759b2c152c58878db6daf22d153a75fda4'
Submodule path 'components/bt/controller/lib_esp32c3_family': checked out '30725989d4ba6393363d3310b945c2b8518c7c8e'
Submodule path 'components/bt/host/nimble/nimble': checked out 'acd6e0cea6c5cce732feb27e155e9c5d288030c8'
Submodule path 'components/cbor/tinycbor': checked out '085ca40781f7c39febe6d14fb7e5cba342e1804b'
Submodule path 'components/cmock/CMock': checked out 'eeecc49ce8af123cf8ad40efdb9673e37b56230f'
Submodule 'vendor/c_exception' (https://github.com/throwtheswitch/cexception.git) registered for path 'components/cmock/CMock/vendor/c_exception'
Submodule 'vendor/unity' (https://github.com/throwtheswitch/unity.git) registered for path 'components/cmock/CMock/vendor/unity'
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/cmock/CMock/vendor/c_exception'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/cmock/CMock/vendor/unity'...
Submodule path 'components/cmock/CMock/vendor/c_exception': checked out '71b47be7c950f1bf5f7e5303779fa99a16224bb6'
Submodule path 'components/cmock/CMock/vendor/unity': checked out 'cf949f45ca6d172a177b00da21310607b97bc7a7'
Submodule path 'components/coap/libcoap': checked out '98954eb30a2e728e172a6cd29430ae5bc999b585'
Submodule 'ext/tinydtls' (https://github.com/eclipse/tinydtls.git) registered for path 'components/coap/libcoap/ext/tinydtls'
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/coap/libcoap/ext/tinydtls'...
Submodule path 'components/coap/libcoap/ext/tinydtls': checked out '7f8c86e501e690301630029fa9bae22424adf618'
Submodule path 'components/esp_wifi/lib': checked out '3417df55828856c1deda1edc3078baa532069e03'
Submodule path 'components/esptool_py/esptool': checked out 'e53efcf84ceb6fac315ccb1348d6950ac33af309'
Submodule path 'components/expat/expat': checked out '57c7da69b78e3698e112a6b5da19d5109b8232d1'
Submodule path 'components/json/cJSON': checked out 'd348621ca93571343a56862df7de4ff3bc9b5667'
Submodule path 'components/libsodium/libsodium': checked out '4f5e89fa84ce1d178a6765b8b46f2b6f91216677'
Submodule path 'components/lwip/lwip': checked out '76303df2386902e0d7873be4217f1d9d1b50f982'
Submodule path 'components/mbedtls/mbedtls': checked out '89da85968417ce4a163b7275cb22f159995c271d'
Submodule path 'components/mqtt/esp-mqtt': checked out '27eb4726067465c5c67d4ecdca5ddccd26f02580'
Submodule path 'components/nghttp/nghttp2': checked out '8f7b008b158e12de0e58247afd170f127dbb6456'
Submodule 'third-party/mruby' (https://github.com/mruby/mruby) registered for path 'components/nghttp/nghttp2/third-party/mruby'
Submodule 'third-party/neverbleed' (https://github.com/tatsuhiro-t/neverbleed.git) registered for path 'components/nghttp/nghttp2/third-party/neverbleed'
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/nghttp/nghttp2/third-party/mruby'...
Cloning into 'C:/Espressif/frameworks/esp-idf-v4.4/esp/esp-at/esp-idf/components/nghttp/nghttp2/third-party/neverbleed'...
Submodule path 'components/nghttp/nghttp2/third-party/mruby': checked out '7c91efc1ffda769a5f1a872c646c82b00698f1b8'
Submodule path 'components/nghttp/nghttp2/third-party/neverbleed': checked out 'b967ca054f48a36f82d8fcdd32e54ec5144f2751'
Submodule path 'components/protobuf-c/protobuf-c': checked out 'dac1a65feac4ad72f612aab99f487056fbcf5c1a'
Submodule path 'components/spiffs/spiffs': checked out 'f5e26c4e933189593a71c6b82cda381a7b21e41c'
Submodule path 'components/tinyusb/tinyusb': checked out '334e95fac52a607150157ae5199a19e11f843982'
Submodule path 'components/unity/unity': checked out '7d2bf62b7e6afaf38153041a9d53c21aeeca9a25'
Submodule path 'examples/build_system/cmake/import_lib/main/lib/tinyxml2': checked out '7e8e249990ec491ec15990cf95b6d871a66cf64a'
Submodule path 'examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib': checked out 'bb672b0437485fc7420add178299631692b15ac3'
Synchronizing submodule:"esp-idf" from "https://github.com/espressif/esp-idf.git" (This may take time)..
old commit: 5666813ce0b2b37a3765dcc7f2b284ec19902c0a
checkout commit: 588436db47da792736dade1c21fcbf2c879456a4
From https://github.com/espressif/esp-idf
 * branch                  release/v4.3 -> FETCH_HEAD
Already up to date.
Submodule path 'components/bt/controller/lib_esp32': checked out 'b877f7e1fc98dccfcf4dbf31f215c5cb44ec3f0d'
Submodule path 'components/bt/controller/lib_esp32c3_family': checked out 'fa1c19100651dd9528ae551892d7de9598810b12'
Submodule path 'components/bt/host/nimble/nimble': checked out '1dc1ec6e76b0ab3bf93cc9f1ff7a2a09141e7c61'
Submodule path 'components/esp_wifi/lib': checked out 'b0069fb607ec41ad872f0deaf3a9bdbbb4018dbb'
Submodule path 'components/esptool_py/esptool': checked out '56a7660834de16a9e550114befb8932c73af2261'
Submodule path 'components/mbedtls/mbedtls': checked out '8b0e35f2ad477fcc2a267cf434528024b8499085'
Submodule path 'components/mqtt/esp-mqtt': checked out '985078affa8a2d2b56b87c8e6455252850f895c6'
submodules check completed for updates.
Ready to set up ESP-IDF tools..
ERROR: This script was called from a virtual environment, can not create a virtual environment again
A fatal error occurred: set up ESP-IDF python-env failed
PS C:\Espressif\frameworks\esp-idf-v4.4\esp\esp-at> build.py install
build.py : The term 'build.py' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ build.py install
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (build.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command build.py was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\build.py". See "get-help about_Command_Precedence" for more details.
PS C:\Espressif\frameworks\esp-idf-v4.4\esp\esp-at> .\build.py install
Ready to install ESP-IDF prerequisites..
Windows Installer Download has already installed all prerequisites.
Ready to install ESP-AT prerequisites..
Requirement already satisfied: setuptools>=21 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 4)) (51.3.3)
Requirement already satisfied: cryptography<35,>=2.1.4 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 9)) (3.4.8)
Requirement already satisfied: pyyaml in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 10)) (6.0)
Requirement already satisfied: xlrd in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 11)) (2.0.1)
Requirement already satisfied: pycryptodome==3.15.0 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 12)) (3.15.0)
Requirement already satisfied: idf-component-manager==1.1.4 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from -r requirements.txt (line 13)) (1.1.4)
Requirement already satisfied: schema in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.7.5)
Requirement already satisfied: six in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (1.16.0)
Requirement already satisfied: requests-toolbelt in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.9.1)
Requirement already satisfied: future in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.18.2)
Requirement already satisfied: colorama in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (0.4.4)
Requirement already satisfied: tqdm<5 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (4.63.0)
Requirement already satisfied: requests<3 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (2.27.1)
Requirement already satisfied: click>=8.0.0 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (8.0.4)
Requirement already satisfied: contextlib2>0.6.0 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager==1.1.4->-r requirements.txt (line 13)) (21.6.0)
Requirement already satisfied: cffi>=1.12 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from cryptography<35,>=2.1.4->-r requirements.txt (line 9)) (1.15.0)
Requirement already satisfied: pycparser in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from cffi>=1.12->cryptography<35,>=2.1.4->-r requirements.txt (line 9)) (2.21)
Requirement already satisfied: certifi>=2017.4.17 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests<3->idf-component-manager==1.1.4->-r requirements.txt (line 13)) (2.0.12)

[notice] A new release of pip available: 22.1.2 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Platform name:ESP32     Module name:WROOM-32    Silence:1
submodules check completed for updates.
Ready to set up ESP-IDF tools..
ERROR: This script was called from a virtual environment, can not create a virtual environment again
A fatal error occurred: set up ESP-IDF python-env failed

**Comment by rkashish75** [comment] 2022-09-30 10:16
@renzbagaporo Pls see if you can help with the issues I'm facing with esp32

**Comment by dobairoland** [comment] 2022-09-30 10:36
@rkashish75 You can report issues for ESP-AT at https://github.com/espressif/esp-at.
