### ISSUE TITLE
AWS Fleet Provisioning support with ESP-IDF (IDFGH-6559)

### ISSUE THREAD

**Issue by venkateshgr-ayla** [espressif/esp-idf#8203] opened 2022-01-07 06:25 UTC
Hi,

I am trying to setup ESP-IDF to do AWS Fleet Provisioning using CSR, I don't find any source or support for this on ESP32. Can you help me in finding it for me? What is the procedure to set this up and the complete process.
Even if you have a beta version also should be fine for me.

Thanks,
GR.Venkatesh

**Comment by Alvin1Zhang** [comment] 2022-01-10 05:58
@venkateshgr-ayla Thanks for reporting, this is a duplicate of https://github.com/espressif/esp-aws-iot/issues/85, will close this one and let us track in https://github.com/espressif/esp-aws-iot/issues/85.

**Closed by Alvin1Zhang** 2022-01-10 05:58 UTC
Labels: Type: Feature Request, Status: Opened
