### ISSUE TITLE
SMTP Example not Working (IDFGH-10311)

### ISSUE THREAD

**Issue by Vaibhavarde67** [espressif/esp-idf#11571] opened 2023-06-01 13:02 UTC
I used the smtp example in esp-idf to send mail and I was able to send email using Gmail server but when i tried same code for other smtp server it was not working. I have disabled the CA certificate validation still it is not working with other than Gmail sntp server.  After some modification in code I was able to see the e-mail in sent folder still it is not getting transferred to receiver

**Comment by nopnop2002** [comment] 2023-06-27 03:26
https://github.com/espressif/esp-idf/issues/7250

**Comment by Alvin1Zhang** [comment] 2024-04-01 06:04
Thanks for reporting, seems this is duplicate of https://github.com/espressif/esp-idf/issues/7250, please help follow updates there, thanks.

**Closed by Alvin1Zhang** 2024-04-01 06:04 UTC
Labels: Status: Opened
