### ISSUE TITLE
ESP32c3 BLE RPA (Privay) Address doesn't change (IDFGH-9564)

### ISSUE THREAD

**Issue by braiden** [espressif/esp-idf#10915] opened 2023-03-05 15:43 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev-3778-g370e250072

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32c3

### Power Supply used.

USB

### What is the expected behavior?

When advertising with an RPA addr type my ota ADDR should be a random rotating RPA addr.

### What is the actual behavior?

The advertising address has the fixed value `7e:1e:1e:79:4f:f7`. I've verified this is the physically transmitted address with [nrf sniffer](https://www.nordicsemi.com/Products/Development-tools/nrf-sniffer-for-bluetooth-le)

`7e:1e:1e:79:4f:f7` is an RPA with a constant prand rand part of `1e:1e:1e` concatenated hash of `ah(irk, 7e:1e:1e) == 79:4f:f7`. Which makes sense based on irk setup [here](https://github.com/espressif/esp-nimble/blob/nimble-1.3.0-idf/nimble/host/src/ble_hs_pvcy.c#L31).

Why is rand part always the same? Why doesn't it change. Nimble calls `BLE_HCI_OCF_LE_SET_RPA_TMO` [here](https://github.com/espressif/esp-nimble/blob/nimble-1.3.0-idf/nimble/host/src/ble_hs_pvcy.c#L182) to setup 15 minute ttl.

### Steps to reproduce.

1. `examples/bluetooth/nimble/bleprph`
2. set-target esp32c3
3. main/main.c line 197; `ble_gap_adv_start(BLE_OWN_ADDR_RPA_PUBLIC_DEFAULT`...
4. Observe the ADV_IND addr is `7e:1e:1e:79:4f:f7`

I've mostly tested with undirected `ext_adv`, but had no luck with any configuration (adv or directed).

Does the ESP32c3 actually support controller based RPA generated addresses? Am i somehow supposed to seed `prand`?

### Debug Logs.

```
Frame 1894: 58 bytes on wire (464 bits), 58 bytes captured (464 bits) on interface /tmp/wireshark_extcap_-dev-ttyACM1, id 0
Nordic BLE Sniffer
Bluetooth Low Energy Link Layer
    Access Address: 
    Packet Header: 0x2060 (PDU Type: ADV_IND, ChSel: #2, TxAdd: Random)
        .... 0000 = PDU Type: 0x0 ADV_IND
        ...0 .... = Reserved: 0
        ..1. .... = Channel Selection Algorithm: #2
        .1.. .... = Tx Address: Random
        0... .... = Reserved: 0
        Length: 32
    Advertising Address: 7e:1e:1e:79:4f:f7 (7e:1e:1e:79:4f:f7)
    Advertising Data
        Flags
        16-bit Service Class UUIDs
        Device Name: nimble-bleprph
        Tx Power Level
    CRC: 0x9acc59
```

**Comment by chegewara** [comment] 2023-03-05 23:55
From few years ago, on bluedroid stack, i remember you can set only `PUBLIC` or `PRIVATE` own address. You cant tell host you want it to be `RPA` or `STATIC`, because in `LL` packet there is only `TxAdd` bit flag, which means private or public.

**Comment by braiden** [comment] 2023-03-06 01:03
I don't think that can be case? When with privacy extensions enabled TxAdd=0 implies RPA? The physically captured broadcast package is absolutely and RPA address (i computed the address hash manually to verify).

_The Link Layer may use resolvable private addresses or non-resolvable private
addresses for the advertiser’s device address (AdvA field) when entering the
Advertising State and using connectable and scannable undirected events._

*BLUETOOTH CORE SPECIFICATION Version 5.4 | Vol 4, Part E, 7.8.5 LE Set Advertising Parameters command* provides 4 options for own address.

**Comment by chegewara** [comment] 2023-03-06 01:10
1. `TxAdd = 0` - means public address
2. I had to recolect what was the problem; well, beside of setting this value in bludroid i also had to call this function `esp_ble_gap_config_local_privacy()`
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gap_ble.html#_CPPv432esp_ble_gap_config_local_privacyb

Im not sure if similar function is used in nimble thou.

**Comment by braiden** [comment] 2023-03-06 01:26
Thanks for the suggestion. I'll take look. I'm assuming `esp_ble_gap_config_local_privacy` implies host mode privacy, but I'm specifically looking for controller based privacy on the esp32c3.

**Comment by braiden** [comment] 2023-03-06 01:56
Traced that bluedriod code path. It essentially does `HCI_LE_Set_Address_Resolution_-Enable`. The analogous call in NimBLE happens in  `ble_hs_pvcy_set_our_irk` → `ble_host_rpa_enabled`. I've already made sure this is happening. :(. Thanks for the tip though. I'm a a bluedroid user will find this thread.

**Comment by braiden** [comment] 2023-03-10 02:07
Since the controller is a binary blob I really need espressif's help for a fix.

- I've verified nimble enables address resolution, sets a timer for address rotation, and adds the correct irk to resolve list. 
- I've verified the controller generates a valid a valid RPA address with a correctly computed hash.

... but as I mention the RPA is neither random nor changes.

Vol 6, Part B, 6.1:

_The Link Layer shall set a timer determined by the Host. A new resolvable
private address shall be generated when the timer expires. If the Link Layer is
reset, a new resolvable private address shall be generated and the timer
started with any value in the allowed range._

As a terrible hack I've called `r_lld_rpa_renew()` symbol exported by the linker and implemented in rom(?), and have had some success getting RPA address to change, but this is clearly the wrong path.

**Comment by braiden** [comment] 2023-03-10 19:43
Most recent findings: three bugs one of them mine:

1. Most importantly: The RPA address changes only when advertising starts. After restarting adverting every 30 seconds the RPA began to rotate. I'm not able to decipher the BLE spec well enough to know for sure this is working-as-intended, but its at least good enough.
2. However the RPA rotates every 15 minutes ignoring `CONFIG_BT_NIMBLE_RPA_TIMEOUT` even though a timeout is set: `ble_hs_pvcy_ensure_started()` →  `ble_hs_pvcy_set_addr_timeout()` → `BLE_HCI_OCF_LE_SET_RPA_TMO`. Controller Bug?
3. The _random_ address always starts with a non-random fixed value. Controller Bug?

Oh, and I also alluded to the fact that nimble uses a hard coded IRK. I'd expect this will causing boning to more than one privacy enabled ESP device. More of a nimble issue, but I'll mention in here for anyone finding this thread. See micro-python for workaround to that issue. https://github.com/micropython/micropython/blob/cacc96d98c2a70dc7e5194331ea70746c39746ec/extmod/nimble/modbluetooth_nimble.c#L281

**Comment by braiden** [comment] 2023-03-12 20:37
> 2. However the RPA rotates every 15 minutes ignoring CONFIG_BT_NIMBLE_RPA_TIMEOUT even though a timeout is set: ble_hs_pvcy_ensure_started() → ble_hs_pvcy_set_addr_timeout() → BLE_HCI_OCF_LE_SET_RPA_TMO. Controller Bug?

Manually sending *HCI_LE_Set_Resolvable_Private_Address_-Timeout* (Vol 4, Pt E, 7.8.45) in the sync callback fixes this. Unclear why. NimBLE calls this too. Maybe something to do with order of the commands being issued (e.g. must enable resolve list first)? So could be either a NimBLE bug or a controller bug?

**Comment by devcexx** [comment] 2023-06-11 11:50
Hi,

This thread was the only result in Google after copy pasting the MAC address I was getting on my two ESP32-S3 devices (with different manufacturers and form factors), while advertising using Controller-based RPA Public MAC address with NimBLE. I'm glad that I'm not the only one having the same issue.

@braiden the workaround you've published for the ESP32 is just for host-based privacy right? Unfortunately, my use-case requires controller-based privacy since I'm using the whitelist feature, which doesn't work with host-based privacy.

So, I can see this issue while enabling GAP advertising with the following line: 

```C
rc = ble_gap_adv_start(BLE_OWN_ADDR_RPA_PUBLIC_DEFAULT, NULL, BLE_HS_FOREVER,
			 &adv_params, rfble_gap_event, NULL);
```

This is making the MAC address to be set on my two devices to `7e:1e:1e:79:4f:f7`. The resolution of the peer's RPA works perfectly though. I'm not very familiar with NimBLE stack nor Bluetooth in general, so I'm not sure if there's anything else that I need to do to setup the controller for using RPA or this is indeed a controller/host stack bug. Any guidance is appreciated.

**Comment by braiden** [comment] 2023-06-11 12:56
I'm using device based privacy.  I may not have updated the bug with my latest findings:

Do not use `ble_gap_adv_start` with `BLE_HS_FOREVER`. Instead I restart advertisement ever 5 minutes. After this change, the device will rotate the address every 15 minutes. Remaining issues are:

1. The initial address is always 7e:1e:1e:79:4f:f7, but a new random address will be assigned in ~15 minutes.
2. The API to change the timeout to something shorter than 15 minutes didn't work.

**Comment by devcexx** [comment] 2023-06-11 13:38
This is reproducible on my side while using Controller-based privacy. Restarting the advertisement every 5 minutes, after 15 minutes the device will start advertising a new RPA address, but the initial address is always 7e:1e:1e:79:4f:f7. For my case changing the setting `BT_NIMBLE_RPA_TIMEOUT` won't have any effect because it is only applicable to host-based privacy.

**Comment by achugbGL** [comment] 2023-09-16 22:47
We are seeing this issue on our ESP32-C3 devices as well with the same initial address: 7e:1e:1e:79:4f:f7.

**Comment by zhp0406** [comment] 2023-09-18 03:59
thanks for report the problem,you can set RPA timeout with menuconfig:
(Top) → Component config → Bluetooth → NimBLE Options ->(5) RPA timeout in seconds

**Comment by zhp0406** [comment] 2023-09-18 04:04
@achugbGL @devcexx 
This is an issue (with the same initial address). could you please specify how this issue affects your usage? We will fix it ASAP.

**Comment by zhp0406** [comment] 2023-09-18 04:31
> @zhp0406, thanks for looking into this. Like @braiden mentioned above, the RPA timeout setting seems to be getting ignored for some reason. Regarding the initial address issue, the biggest problem for us is that when multiple devices using our firmware boot around the same time, they have conflicting addresses.

sorry for that,it will take some time for us to solve the issue(The initial address is always 7e:1e:1e:79:4f:f7). In the meantime, to avoid affecting your usage, you can set a different Identity Resolving Key (IRK) for each device. This way, the addresses will be different during the first initialization.
Note:
You can use the API **int ble_hs_pvcy_set_our_irk(const uint8_t *irk)** to set the IRK for each device.

**Comment by achugbGL** [comment] 2023-09-19 00:03
Thank you! Appreciate your attention to this issue

**Comment by rahult-github** [comment] 2023-10-30 06:47
Hi @achugbGL ,

The attached patch has a change to generate a new IRK for each device on boot without the need for user to call any API. Please help check if it works for you. The patch should go in $IDF_PATH/components/bt/host/nimble/nimble path.

[0001-Added-change-to-generate-unique-IRK-based-on-chip-ma.txt](https://github.com/espressif/esp-idf/files/13201630/0001-Added-change-to-generate-unique-IRK-based-on-chip-ma.txt)

**Comment by Indastri** [comment] 2023-12-07 11:42
Since there is no response from the user, closing the issue, if there will be any questions or issues feel free to reopen or create a new issue. Cheers.

**Closed by Indastri** 2023-12-07 11:42 UTC
Labels: Type: Bug, Status: Done, Resolution: NA

**Comment by achugbGL** [comment] 2025-03-19 00:03
Hi there. Sorry for missing this and for re-opening it. We had implemented our own IRK generation & storage method and I'm looking to migrate to the stock IDF implementation. One question I had was regarding how to reset the stored IRK and force generation of a new random IRK. Thanks!

**Comment by esp-zhp** [comment] 2025-03-19 03:03
@achugbGL 
We have modified the random number generation method so that prand is truly random each time, ensuring that the address is also random.
see：
BLUETOOTH CORE SPECIFICATION Version 5.4 | Vol 6, Part B page 2680

![Image](https://github.com/user-attachments/assets/52124225-6194-4193-845c-fbc4b5cc9e6d)

**Comment by achugbGL** [comment] 2025-03-19 03:54
Hi. Sorry, I should have been more clear. It seems like the ESP on boot/initializing BLE checks to see if there is an IRK in NVS and if not it generates a random IRK and saves it to NVS. I would like to be able to reset the saved IRK with a new random IRK so that previously bonded devices cannot track the device.

**Comment by esp-zhp** [comment] 2025-03-19 04:02
@achugbGL 
This is a new issue. Please create a separate issue to keep this one organized; otherwise, it may become confusing.  

Regarding your question, you can try enabling the configuration option **BT_BLE_SMP_ID_RESET_ENABLE** to see if it meets your requirements.  

See:  
**(Top) → Component config → Bluetooth → Bluedroid Options → Bluetooth Low Energy → Include BLE security module (SMP)**  
[ ] Reset device identity when all bonding records are deleted.

**Comment by achugbGL** [comment] 2025-03-19 04:11
Sorry, I thought it might be a quick question about the functionality that was added to resolve this issue. I can make a new one. 

I did see that config option but it seemed like that one was specific to Bluedroid where as this is for NimBLE

**Comment by rahult-github** [comment] 2025-03-19 04:51
> I did see that config option but it seemed like that one was specific to Bluedroid where as this is for NimBLE 

For NimBLE:

(Top) → Component config → Bluetooth → NimBLE Options
[ ] Reset device identity when all bonding records are deleted

**Comment by achugbGL** [comment] 2025-03-19 05:04
Thank you!
