### ISSUE TITLE
Http Async not working when streaming it finishes the stream then terminates the connection.... (IDFGH-11555)

### ISSUE THREAD

**Issue by ThatBigPrint** [espressif/esp-idf#12676] opened 2023-11-27 09:47 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi guys I have spent weeks on this! 

So far I have managed to bodge a persistent connection without async... but I wish to be able to have a open connection accepting server-side events (this is currently working kind of.... but it gets the first initial data then closes the connection then re-opens it....) when then I want to be able to send to the same connection this is my code 

`void sse_stream_task(void *pvParameters)
{
    start_config = true;
    char *buffer = malloc(MAX_HTTP_RECV_BUFFER + 1);
    if (buffer == NULL)
    {
        ESP_LOGE(TAG, "Cannot malloc http receive buffer");
        return;
    }

    char full_url[256];

    // snprintf(full_url, sizeof(full_url), "%s%s?auth=%s", FIREBASE_HOST, FIREBASE_PATH, FIREBASE_AUTH);
    snprintf(full_url, sizeof(full_url), "%s/%s%s.json?auth=%s", FIREBASE_HOST, rvd_data_str, FIREBASE_PATH, FIREBASE_AUTH);

    ESP_LOGI(TAG, "Connecting to Firebase URL: %s", full_url);

    esp_http_client_config_t config = {
        .url = full_url,
        //.url = "https://postman-echo.com/get",
        .crt_bundle_attach = esp_crt_bundle_attach,
        .event_handler = _http_event_handler,
        //.timeout_ms = 1000,
        //.is_async = true,
        //.user_data = buffer,
    };
    esp_http_client_handle_t client = esp_http_client_init(&config);
    esp_http_client_set_header(client, "Accept", "text/event-stream");
    esp_err_t err;
    if ((err = esp_http_client_open(client, 0)) != ESP_OK)
    {
        ESP_LOGE(TAG, "Failed to open HTTP connection: %s", esp_err_to_name(err));
        // start_config = false;
        // free(buffer);
        //   continue;
    }

    int content_length = esp_http_client_fetch_headers(client);
    int total_read_len = 0;
    int read_len = 0;
    if (total_read_len < content_length && content_length <= MAX_HTTP_RECV_BUFFER)
    {
        read_len = esp_http_client_read(client, buffer, content_length);
        if (read_len <= 0)
        {
            ESP_LOGE(TAG, "Error read data");
        }
        buffer[read_len] = 0;
        ESP_LOGI(TAG, "read_len = %d", read_len);
    }

    while (http_connected)
    {

        esp_http_client_read(client, buffer, MAX_HTTP_RECV_BUFFER);

        vTaskDelay(10 / portTICK_PERIOD_MS);
    }

    start_config = false;

    ESP_LOGE(TAG, "http lost coms canceling");
    esp_http_client_close(client);
    esp_http_client_cleanup(client);
    free(buffer);
    vTaskDelete(NULL);
}`

am I missing something fundamental here I've tried setting the timeout and .is_async etc 

it varifies the certificate and grabs the first data but it then closes the connection even though it's supposed to stay open also tried the keep alive etc... i have used the http perform as well as per the main http client example to no avail it just drops out? and repeats ?

**Comment by hmalpani** [comment] 2023-12-05 06:44
Hello @ThatBigPrint 

If I understand correctly, you want your program to stay in `while (http_connected)` loop. I think you have not set the `http_connected` to true and thus it call `esp_http_client_close`. Please let me know if my understanding of the problem is incorrect. Also in that case, can you provide the minimal application to reproduce this?

Thanks!

**Comment by hmalpani** [comment] 2023-12-20 12:01
Closing this issue. Please feel free to reopen if you have more updates.

**Closed by hmalpani** 2023-12-20 12:01 UTC
Labels: Status: In Progress, Awaiting Response
