### ISSUE TITLE
Make flash fails after upgrading to 4.2-dev (IDFGH-3083)

### ISSUE THREAD

**Issue by tuupola** [espressif/esp-idf#5104] opened 2020-04-12 08:35 UTC
## Environment

- Development Kit:      [none]
- Module or chip used:  [ESP32-PICO-D4]
- IDF version: v4.2-dev-1097-g2e14149bf
- Build System:         [Make]
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2020r1) 8.2.0
- Operating System:     [macOS]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

After updating to  4.2-dev `make flash` fails with the following error.

```
$ make flash
...
serial.serialutil.SerialException: [Errno 2] could not open port "/dev/cu.usbserial-C54ABFCA45": [Errno 2] No such file or directory: '"/dev/cu.usbserial-C54ABFCA45"'
make: *** [flash] Error 1
```

Culprit is this commit: https://github.com/espressif/esp-idf/commit/862fa815ff1ff79481ef113a9af7d9092e6f3583  which causes hyphens to be part of the port name. Reverting the commit makes problem go away.

As a sidenote this seems to concern all serial operations.

```
$ make monitor
...
SerialException: [Errno 2] could not open port "/dev/cu.usbserial-C54ABFCA45": [Errno 2] No such file or directory: '"/dev/cu.usbserial-C54ABFCA45"'
```

**Comment by fpgamaster** [comment] 2020-04-12 13:55
Same here. It seems idf.py monitor to work.

**Comment by Alvin1Zhang** [comment] 2020-04-12 14:02
@tuupola Thanks for reporting and the investigation, we will look into. Thanks.

**Comment by projectgus** [comment] 2020-04-15 05:45
Hi @tuupola ,

Thanks for reporting this. I've just replied to issue #5124 and then realised this is the same root cause, but I'll link to the comment on the other issue rather than copy-pasting it:
https://github.com/espressif/esp-idf/issues/5124#issuecomment-613828807

A fix is in review and both issues will be updated when it's merged.

Angus

**Closed** 2020-04-24 08:43 UTC
