### ISSUE TITLE
[TW#23625] system restart while disable the BLE interface

### ISSUE THREAD

**Issue by NOA-Vernon** [espressif/esp-idf#2077] opened 2018-06-19 10:23 UTC
## Environment

- Development Kit:      [ESP32-WROOM]
- Kit version (for WroverKit/PicoKit/DevKitC): [ v3]
- Core (if using chip or module): [ESP32-WROOM-32U]
- IDF version (ESP-IDF v3.1-dev-961-ga255622-dirty.): 
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:		[Make]
- Operating System:		[Ubuntu]
- Power Supply:         [Battery]

## Problem Description

system always restart while going to disable function.

### Expected Behavior
I want to switch on and off the BLE and WIFI interface normally without unexpected system restart.

### Actual Behavior
system always restart while going to disable function. following is the log from uart

[0;31mE (115126) BT: L2CA_RemoveFixedChnl()  CID: 0x0004  BDA: 30aea484486e not connected[0m
[0;31mE (115126) BT: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0016[0m
[0;31mE (115126) BT: bta_gattc_conn_cback() - cif=4 connected=0 conn_id=4 reason=0x0016[0m
[0;31mE (115136) BT: bta_gattc_conn_cback() - cif=5 connected=0 conn_id=5 reason=0x0016[0m
[0;31mE (115146) BT: bta_gattc_conn_cback() - cif=6 connected=0 conn_id=6 reason=0x0016[0m
[0;31mE (115156) BT: bta_gattc_deregister Deregister Failedm unknown client cif[0m
[0;32mI (115166) GATTS_DEMO: ESP_GATTS_DISCONNECT_EVT[0m
[0;32mI (115756) GATTC_MULTIPLE_DEMO: update connetion params status = 0, min_int = 0, max_int = 0,conn_int = 6,latency = 0, timeout = 500[0m
[0;32mI (115956) GATTC_MULTIPLE_DEMO: update connetion params status = 0, min_int = 0, max_int = 0,conn_int = 32,latency = 0, timeout = 500[0m
[0;32mI (116206) GATTC_MULTIPLE_DEMO:  esp_bluedroid_disable() ok[0m
/home/esp8266/esp/esp-idf/components/freertos/queue.c:1441 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x4008ff61 on core 0

Backtrace: 0x40093494:0x3ffb3390 0x4009366b:0x3ffb33b0 0x4008ff61:0x3ffb33d0 0x400edb15:0x3ffb3410 0x40129382:0x3ffb3430 0x40136005:0x3ffb3450 0x4013d43d:0x3ffb3470 0x401369de:0x3ffb3490 0x4001791d:0x3ffb34b0 0x40136f7d:0x3ffb34d0 0x4013716e:0x3ffb3510 0x400188f5:0x3ffb3540 0x4004d13e:0x3ffb3580 0x4013c55d:0x3ffb35d0 0x4013ac0b:0x3ffb35f0 0x401396e2:0x3ffb3640 0x40019d11:0x3ffb3680 0x40055b4d:0x3ffb36a0 0x401364a7:0x3ffb36c0 0x4013650f:0x3ffb36e0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5656
load:0x40078000,len:0
ho 12 tail 0 room 4
load:0x40078000,len:14868
entry 0x40078628
[0;32mI (30) boot: ESP-IDF v3.1-dev-961-ga255622-dirty 2nd stage bootloader[0m
[0;32mI (30) boot: compile time 14:05:36[0m
[0;32mI (32) boot: Enabling RNG early entropy source...[0m
[0;32mI (37) boot: SPI Speed      : 40MHz[0m
[0;32mI (41) boot: SPI Mode       : DIO[0m
[0;32mI (45) boot: SPI Flash Size : 16MB[0m
[0;32mI (49) boot: Partition Table:[0m
[0;32mI (53) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (60) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (68) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (75) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (83) boot:  3 factory          factory app      00 00 00010000 00200000[0m
[0;32mI (90) boot:  4 ota_0            OTA app          00 10 00210000 00200000[0m
[0;32mI (97) boot:  5 ota_1            OTA app          00 11 00410000 00200000[0m
[0;32mI (105) boot: End of partition table[0m
[0;32mI (109) boot: Defaulting to factory image[0m
[0;32mI (114) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x80d84 (527748) map[0m
[0;32mI (308) esp_image: segment 1: paddr=0x00090dac vaddr=0x3ffc0000 size=0x05cf4 ( 23796) load[0m
[0;32mI (317) esp_image: segment 2: paddr=0x00096aa8 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (318) esp_image: segment 3: paddr=0x00096eb0 vaddr=0x40080400 size=0x09160 ( 37216) load[0m
[0;32mI (341) esp_image: segment 4: paddr=0x000a0018 vaddr=0x400d0018 size=0x11c230 (1163824) map[0m
[0;32mI (749) esp_image: segment 5: paddr=0x001bc250 vaddr=0x40089560 size=0x0d61c ( 54812) load[0m
[0;32mI (772) esp_image: segment 6: paddr=0x001c9874 vaddr=0x400c0000 size=0x00000 (     0) load[0m
[0;32mI (786) boot: Loaded app from partition at offset 0x10000[0m

### Steps to repropduce

1. call the below function ble_if_close() and  ble_if_open() several times, it will cause system restart.

### Code to reproduce this issue

following is the segment code that disable the BLE function.

int ble_if_close(void){
ret = esp_ble_gatts_app_unregister(gl_profile_tab_s[PROFILE_A_APP_ID].gatts_if);
    if (ret){
        ESP_LOGE(GATTS_TAG, "gatts app unregister error, error code = %x", ret);
        return ret;
    }
    ret = esp_ble_gatts_app_unregister(gl_profile_tab_s[PROFILE_B_APP_ID].gatts_if);
    if (ret){
        ESP_LOGE(GATTS_TAG, "gatts app unregister error, error code = %x", ret);
        return ret;
    }
	//vTaskDelay(100 / portTICK_RATE_MS);
	if( esp_bluedroid_disable() == ESP_OK ){
		ESP_LOGI(GATTC_TAG," esp_bluedroid_disable() ok");
	}else{
		ESP_LOGI(GATTC_TAG," esp_bluedroid_disable() nok");
	}	
	//vTaskDelay(100 / portTICK_RATE_MS);		
	if( esp_bluedroid_deinit() == ESP_OK ){
		ESP_LOGI(GATTC_TAG," esp_bluedroid_deinit() ok");
	}else{
		ESP_LOGI(GATTC_TAG," esp_bluedroid_deinit() nok");
	}
	//vTaskDelay(100 / portTICK_RATE_MS);
	if( esp_bt_controller_disable() == ESP_OK ){
		ESP_LOGI(GATTC_TAG," esp_bt_controller_disable() ok");
	}else{
		ESP_LOGI(GATTC_TAG," esp_bt_controller_disable() nok");
	}
	//vTaskDelay(100 / portTICK_RATE_MS);
	if( esp_bt_controller_deinit() == ESP_OK ){
		ESP_LOGI(GATTC_TAG," esp_bt_controller_deinit() ok");
	}else{
		ESP_LOGI(GATTC_TAG," esp_bt_controller_deinit() nok");
	}
}

following is the segment code that re-enable the BLE function.

int ble_if_open(void){
ESP_ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT));

    esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();

    ret = esp_bt_controller_init(&bt_cfg);
    if (ret) {
        ESP_LOGE(GATTC_TAG, "%s initialize controller failed\n", __func__);
        return ret;
    }

    ret = esp_bt_controller_enable(ESP_BT_MODE_BLE);
    if (ret) {
        ESP_LOGE(GATTC_TAG, "%s enable controller failed\n", __func__);
        return ret;
    }

    ret = esp_bluedroid_init();
    if (ret) {
        ESP_LOGE(GATTC_TAG, "%s init bluetooth failed\n", __func__);
        return ret;
    }

    ret = esp_bluedroid_enable();
    if (ret) {
        ESP_LOGE(GATTC_TAG, "%s enable bluetooth failed\n", __func__);
        return ret;
    }

    //register the  callback function to the gap module
    ret = esp_ble_gap_register_callback(esp_gap_cb);
    if (ret){
        ESP_LOGE(GATTC_TAG, "gap register error, error code = %x", ret);
        return ret;
    }
	
	//----------------for ble peripheral----------------
	ret = esp_ble_gatts_register_callback(gatts_event_handler);
    if (ret){
        ESP_LOGE(GATTS_TAG, "gatts register error, error code = %x", ret);
        return ret;
    }
    ret = esp_ble_gatts_app_register(PROFILE_A_APP_ID);
    if (ret){
        ESP_LOGE(GATTS_TAG, "gatts app register error, error code = %x", ret);
        return ret;
    }
    ret = esp_ble_gatts_app_register(PROFILE_B_APP_ID);
    if (ret){
        ESP_LOGE(GATTS_TAG, "gatts app register error, error code = %x", ret);
        return ret;
    }
    esp_err_t local_mtu_ret = esp_ble_gatt_set_local_mtu(500);
    if (local_mtu_ret){
        ESP_LOGE(GATTS_TAG, "set local  MTU failed, error code = %x", local_mtu_ret);
    }
}

**Comment by Weijian-Espressif** [comment] 2018-07-09 06:55
@NOA-Vernon please modify ESP_ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT)); -> esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT);

This function only needs to be called once

**Comment by NOA-Vernon** [comment] 2018-07-09 07:03
@Weijian-Espressif Yes, I called the esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT); just for only one time,  restart the ble I did not called this function, and it caused the system restart, but it is not every time caused system restart, it happened sometimes.

**Comment by Weijian-Espressif** [comment] 2018-07-09 07:07
@NOA-Vernon OK, I will try to reproduce the issue.

**Comment by Weijian-Espressif** [comment] 2018-07-09 11:19
@NOA-Vernon OK, I test your code about 4 hours. The issue is not reproduced in master, maybe it have be fixed in the latest IDF.  Can you update to the latest IDF and try?

**Comment by NOA-Vernon** [comment] 2018-07-10 01:29
@Weijian-Espressif Yes, I used the latest IDF(v3.2), I'm sorry that my description is not so clear.  I turn on or off the BLE while WIFI is on and connected to a AP, can you try to turn on the WIFI and connnect to a AP and test it again,  it sometimes happened. I don't know what might caused the following issue.

/home/esp8266/esp/esp-idf/components/freertos/queue.c:1441 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x4008ff61 on core 0

**Comment by Weijian-Espressif** [comment] 2018-07-10 02:43
Hi @NOA-Vernon  I test your BLE code without WIFI, it is not reproduced until today 10:36. Maybe it is bug of wifi or coexist. Can you provide your elf file and Backtrace code ?

**Comment by Weijian-Espressif** [comment] 2018-07-10 02:46
please refer https://docs.espressif.com/projects/esp-idf/en/latest/get-started/idf-monitor.html?highlight=xtensa-esp32-elf-addr2line ,    **Automatically Decoding Addresses**

**Comment by NOA-Vernon** [comment] 2018-07-11 11:15
@Weijian-Espressif  thank you for your reply, so sorry for that I could not provide the elf file for you as it was the project from the company, but I used the xtensa-esp32-elf-addr2line command to decode the addresses, please see the following segment.

esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x40093494
0x40093494: _frxt_int_exit at /home/esp8266/esp/esp-idf/components/freertos/portasm.S:177
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3390
0x3ffb3390: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x4009366b
0x4009366b: _xt_context_restore at /home/esp8266/esp/esp-idf/components/freertos/xtensa_context.S:292
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb33b0
0x3ffb33b0: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x4008ff61
0x4008ff61: write_txrate_power_offset at /home/cff/gittree/chip7.1_phy/chip_7.1/board_code/app_test/pp/phy/phy_chip_v7_cal.c:2443 (discriminator 1)
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb33d0
0x3ffb33d0: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb33d0 0x400edb15
0x3ffb33d0: ?? ??:0
0x400edb15: esp_ble_gatts_add_char at /home/esp8266/esp/esp-idf/components/bt/bluedroid/api/esp_gatts_api.c:346
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3410 0x40129382
0x3ffb3410: ?? ??:0
0x40129382: bta_gatts_set_attr_value at /home/esp8266/esp/esp-idf/components/bt/bluedroid/bta/gatt/bta_gatts_act.c:514
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3430 0x40136005
0x3ffb3430: ?? ??:0
0x40136005: adc1_hall_enable at /home/esp8266/esp/esp-idf/components/driver/rtc_module.c:1896
 (inlined by) adc1_get_raw at /home/esp8266/esp/esp-idf/components/driver/rtc_module.c:1494
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3450 0x4013d43d
0x3ffb3450: ?? ??:0
0x4013d43d: esp_wifi_internal_reg_rxcb at ??:?
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3470 0x401369de
0x3ffb3470: ?? ??:0
0x401369de: start_command_write_blocks at /home/esp8266/esp/esp-idf/components/driver/sdspi_host.c:818
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3490 0x4001791d
0x3ffb3490: ?? ??:0
0x4001791d: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb34b0 0x40136f7d
0x3ffb34b0: ?? ??:0
0x40136f7d: sdspi_host_init_slot at /home/esp8266/esp/esp-idf/components/driver/sdspi_host.c:267
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb34d0 0x4013716e
0x3ffb34d0: ?? ??:0
0x4013716e: sdspi_host_do_transaction at /home/esp8266/esp/esp-idf/components/driver/sdspi_transaction.c:110 (discriminator 2)
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3510 0x400188f5
0x3ffb3510: ?? ??:0
0x400188f5: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3540 0x4004d13e
0x3ffb3540: ?? ??:0
0x4004d13e: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3580 0x4013c55d
0x3ffb3580: ?? ??:0
0x4013c55d: wifi_osi_funcs_register at ??:?
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb35d0 0x4013ac0b
0x3ffb35d0: ?? ??:0
0x4013ac0b: spicommon_bus_initialize_io at /home/esp8266/esp/esp-idf/components/driver/spi_common.c:323
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb35f0 0x401396e2
0x3ffb35f0: ?? ??:0
0x401396e2: uart_set_pin at /home/esp8266/esp/esp-idf/components/driver/uart.c:1116
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3640 0x40019d11
0x3ffb3640: ?? ??:0
0x40019d11: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb3680 0x40055b4d
0x3ffb3680: ?? ??:0
0x40055b4d: ?? ??:0
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb36a0 0x401364a7
0x3ffb36a0: ?? ??:0
0x401364a7: card_missing at /home/esp8266/esp/esp-idf/components/driver/sdspi_host.c:98
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb36c0 0x4013650f
0x3ffb36c0: ?? ??:0
0x4013650f: go_idle_clockout at /home/esp8266/esp/esp-idf/components/driver/sdspi_host.c:182
esp8266@esp8266-VirtualBox:~/Share/tauokery5$ xtensa-esp32-elf-addr2line -pfiaC -e build/tauokery5.elf 0x3ffb36e0
0x3ffb36e0: ?? ??:0

**Comment by Weijian-Espressif** [comment] 2018-07-16 07:11
@NOA-Vernon I will fix it as soon as possible

**Comment by FayeY** [comment] 2018-08-06 03:17
This issue should have been fixed, please have a try. And feel free to reopen if the issue persists. Thanks.

**Closed by FayeY** 2018-08-06 03:17 UTC
