### ISSUE TITLE
tx power adv

### ISSUE THREAD

**Issue by netanbi** [espressif/esp-idf#9781] opened 2022-09-14 05:57 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi Espressif engineer ,
i work with the example of "gatts_demo" -ble
board: evk esp32-c3-devkitm-1

I succeed in changing the tx power with the func but if I see with NRF app what is the advertisement of the tx power is always 9dbm
even if change the to 18dbm or 0 dBm and with my spectrum analyzer I verify that it's really transforming the power tx but in the app I always see 9dm
thanks

**Comment by mahavirj** [comment] 2022-09-19 07:09
Seems duplicate of https://github.com/espressif/esp-idf/issues/9780

**Closed by mahavirj** 2022-09-19 07:09 UTC
