### ISSUE TITLE
CMakeLists.txt Question (IDFGH-11958)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#13036] opened 2024-01-23 06:25 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Why does this Work: 

```
idf_build_get_property(target IDF_TARGET)

set(srcs)
set(includes)
set(priv_requires)

if(CONFIG_IDF_TARGET_ESP32S3)
    list(APPEND srcs "usb_ncm.c")
    list(APPEND includes ".")
    list(APPEND priv_requires esp_tinyusb tinyusb)
endif()


idf_component_register(SRCS ${srcs}
                       INCLUDE_DIRS ${includes}
                       REQUIRES esp_netif
                       PRIV_REQUIRES ${priv_requires}
                       )
```

but this not: 

```
idf_build_get_property(target IDF_TARGET)

set(srcs)
set(includes)
set(requires)
set(priv_requires)

if(CONFIG_IDF_TARGET_ESP32S3)
    list(APPEND srcs "usb_ncm.c")
    list(APPEND includes ".")
    list(APPEND requires esp_netif)
    list(APPEND priv_requires esp_tinyusb tinyusb)
endif()


idf_component_register(SRCS ${srcs}
                       INCLUDE_DIRS ${includes}
                       REQUIRES ${requires}
                       PRIV_REQUIRES ${priv_requires}
                       )
```

the later one gives an Error: 

```
: fatal error: esp_netif.h: No such file or directory
```

**Comment by fhrbata** [comment] 2024-01-23 10:21
Hello @diplfranzhoepfinger 

I believe this is by design.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#component-requirements

> The values of REQUIRES and PRIV_REQUIRES should not depend on any configuration choices (CONFIG_xxx macros). This is because requirements are expanded before the configuration is loaded. Other component variables (like include paths or source files) can depend on configuration choices.

HTH

**Comment by igrr** [comment] 2024-01-23 10:34
(You can, however, use the `target` variable which you have already initialized — just replace `if(CONFIG_IDF_TARGET_ESP32S3)` with `if(target STREQUAL esp32s3)`)

**Comment by KonstantinKondrashov** [comment] 2024-01-24 07:42
Hi @diplfranzhoepfinger!
I close it, here is a summary:
- Avoid using CONFIG_xxx macros for REQUIRES and PRIV_REQUIRES.
- You can use `if(target STREQUAL esp32s3)` for example.

**Closed by KonstantinKondrashov** 2024-01-24 07:42 UTC
Labels: Status: Opened
