### ISSUE TITLE
(macos) idf.py build fails - cannot find 'In archive' in libxtensa.a dump (IDFGH-9032)

### ISSUE THREAD

**Issue by Coobik** [espressif/esp-idf#10440] opened 2022-12-25 16:03 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev-2509-gcfef24863f

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I expect "idf.py build" to run without errors

### What is the actual behavior?

cloned esp-idf and followed the manual
created a dummy project
tried to build it with "idf.py build"
- build fails on esp-idf/tools/ldgen/ldgen/entity.py", in add_sections_info with error: Expected 'In archive', found end of text

### Steps to reproduce.

run "idf.py build" in a project directory

### Build or installation Logs.

```plain
Traceback (most recent call last):
  File "/Users/USER/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/pyparsing/core.py", line 817, in _parseNoCache
    loc, tokens = self.parseImpl(instring, pre_loc, doActions)
  File "/Users/USER/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/pyparsing/core.py", line 2337, in parseImpl
    if instring[loc] == self.firstMatchChar and instring.startswith(
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USER/projects/esp/esp-idf/tools/ldgen/ldgen/entity.py", line 157, in add_sections_info
    results = parser.parseString(first_line, parseAll=True)
  File "/Users/USER/.espressif/python_env/idf5.1_py3.10_env/lib/python3.10/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected 'In archive', found end of text  (at char 1), (line:2, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USER/projects/esp/esp-idf/tools/ldgen/ldgen.py", line 175, in <module>
    main()
  File "/Users/USER/projects/esp/esp-idf/tools/ldgen/ldgen.py", line 133, in main
    sections_infos.add_sections_info(dump)
  File "/Users/USER/projects/esp/esp-idf/tools/ldgen/ldgen/entity.py", line 159, in add_sections_info
    raise ParseException('Parsing sections info for library ' + sections_info_dump.name + ' failed. ' + p.msg)
pyparsing.exceptions.ParseException: Parsing sections info for library /my-project/build/esp-idf/xtensa/libxtensa.a failed. Expected 'In archive'  (at char 0), (line:1, col:1)
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```

### More Information.

i use macos big sur 11.7.2 on intel mac
--
tried to debug this issue a little

- esp-idf/tools/ldgen/ldgen.py - main():
dump = StringIO(subprocess.check_output([objdump, '-h', library], env=new_env).decode())
dump.name = library
sections_infos.add_sections_info(dump)

- esp-idf/tools/ldgen/ldgen/entity.py - def add_sections_info(self, sections_info_dump):
first_line = sections_info_dump.readline()
archive_path = (Literal('In archive').suppress() +
                        White().suppress() +
                        # trim the colon and line ending characters from archive_path
                        rest_of_line.set_results_name('archive_path').set_parse_action(
                            lambda s, loc, toks: s.rstrip(':\n\r ')))

results = parser.parseString(first_line, parseAll=True)  # exception here

--
process fails on the lib: /my-project/build/esp-idf/xtensa/libxtensa.a

i have dumped the whole stringio buffer (sections_info_dump):

/my-project/build/esp-idf/xtensa/libxtensa.a(eri.c.obj):	file format elf32-unknown

Sections:
Idx Name                Size     VMA      Type
  0                     00000000 00000000
  1 .text               00000000 00000000 TEXT
  2 .data               00000000 00000000 DATA
  3 .bss                00000000 00000000 BSS
  4 .text.eri_read      00000008 00000000 TEXT
  5 .text.eri_write     00000008 00000000 TEXT
  6 .debug_frame        00000040 00000000
  7 .rela.debug_frame   00000084 00000000
  8 .debug_info         000000f6 00000000
  9 .rela.debug_info    00000168 00000000
 10 .debug_abbrev       000000aa 00000000
 11 .debug_loc          0000003a 00000000
 12 .rela.debug_loc     00000048 00000000
 13 .debug_aranges      00000028 00000000
 14 .rela.debug_aranges 0000003c 00000000
 15 .debug_ranges       00000018 00000000
 16 .rela.debug_ranges  00000030 00000000
 17 .debug_line         000001ce 00000000
 18 .rela.debug_line    00000090 00000000
 19 .debug_str          000001c5 00000000
 20 .comment            00000027 00000000
 21 .xtensa.info        00000038 00000000
 22 .xt.prop            00000048 00000000
 23 .rela.xt.prop       00000048 00000000
 24 .symtab             00000140 00000000
 25 .strtab             0000001a 00000000
 26 .shstrtab           000000f3 00000000

/my-project/build/esp-idf/xtensa/libxtensa.a(xt_trax.c.obj):	file format elf32-unknown

Sections:
Idx Name                                               Size     VMA      Type
  0                                                    00000000 00000000
  1 .literal._xt_trax_start_trace                      00000018 00000000 TEXT
  2 .rela.literal._xt_trax_start_trace                 00000018 00000000
  3 .literal.xt_trax_trace_is_active                   00000008 00000000 TEXT
  4 .rela.literal.xt_trax_trace_is_active              0000000c 00000000
  5 .literal.xt_trax_start_trace_instructions          00000004 00000000 TEXT
  6 .rela.literal.xt_trax_start_trace_instructions     0000000c 00000000
  7 .literal.xt_trax_start_trace_words                 00000004 00000000 TEXT
  8 .rela.literal.xt_trax_start_trace_words            0000000c 00000000
  9 .literal.xt_trax_trigger_traceend_after_delay      00000018 00000000 TEXT
 10 .rela.literal.xt_trax_trigger_traceend_after_delay 00000030 00000000
 11 .text                                              00000000 00000000 TEXT
 12 .data                                              00000000 00000000 DATA
 13 .bss                                               00000000 00000000 BSS
 14 .text._xt_trax_start_trace                         00000026 00000000 TEXT
 15 .rela.text._xt_trax_start_trace                    00000078 00000000
 16 .text.xt_trax_trace_is_active                      00000011 00000000 TEXT
 17 .rela.text.xt_trax_trace_is_active                 00000024 00000000
 18 .text.xt_trax_start_trace_instructions             0000000e 00000000 TEXT
 19 .rela.text.xt_trax_start_trace_instructions        00000018 00000000
 20 .text.xt_trax_start_trace_words                    0000000e 00000000 TEXT
 21 .rela.text.xt_trax_start_trace_words               00000018 00000000
 22 .text.xt_trax_trigger_traceend_after_delay         00000032 00000000 TEXT
 23 .rela.text.xt_trax_trigger_traceend_after_delay    00000078 00000000
 24 .debug_frame                                       00000088 00000000
 25 .rela.debug_frame                                  00000138 00000000
 26 .debug_info                                        00000227 00000000
 27 .rela.debug_info                                   00000270 00000000
 28 .debug_abbrev                                      0000011b 00000000
 29 .debug_loc                                         0000004c 00000000
 30 .rela.debug_loc                                    00000060 00000000
 31 .debug_aranges                                     00000040 00000000
 32 .rela.debug_aranges                                00000084 00000000
 33 .debug_ranges                                      00000030 00000000
 34 .rela.debug_ranges                                 00000078 00000000
 35 .debug_line                                        000002d6 00000000
 36 .rela.debug_line                                   000001a4 00000000
 37 .debug_str                                         00000276 00000000
 38 .comment                                           00000027 00000000
 39 .xtensa.info                                       00000038 00000000
 40 .xt.lit                                            00000028 00000000
 41 .rela.xt.lit                                       0000003c 00000000
 42 .xt.prop                                           00000108 00000000
 43 .rela.xt.prop                                      00000108 00000000
 44 .symtab                                            00000220 00000000
 45 .strtab                                            000000ab 00000000
 46 .shstrtab                                          00000278 00000000

/my-project/build/esp-idf/xtensa/libxtensa.a(xtensa_intr.c.obj):	file format elf32-unknown

Sections:
Idx Name                                   Size     VMA      Type
  0                                        00000000 00000000
  1 .iram1.0.literal                       00000008 00000000 TEXT
  2 .rela.iram1.0.literal                  00000018 00000000
  3 .literal.xt_set_exception_handler      00000008 00000000 TEXT
  4 .rela.literal.xt_set_exception_handler 00000018 00000000
  5 .literal.xt_int_has_handler            00000008 00000000 TEXT
  6 .rela.literal.xt_int_has_handler       00000018 00000000
  7 .literal.xt_set_interrupt_handler      0000000c 00000000 TEXT
  8 .rela.literal.xt_set_interrupt_handler 00000024 00000000
  9 .text                                  00000000 00000000 TEXT
 10 .data                                  00000000 00000000 DATA
 11 .bss                                   00000000 00000000 BSS
 12 .rodata.str1.4                         00000023 00000000 DATA
 13 .iram1.0                               00000016 00000000 TEXT
 14 .rela.iram1.0                          00000024 00000000
 15 .text.xt_set_exception_handler         00000046 00000000 TEXT
 16 .rela.text.xt_set_exception_handler    00000084 00000000
 17 .text.xt_int_has_handler               0000001d 00000000 TEXT
 18 .rela.text.xt_int_has_handler          00000018 00000000
 19 .text.xt_set_interrupt_handler         0000004e 00000000 TEXT
 20 .rela.text.xt_set_interrupt_handler    00000090 00000000
 21 .debug_frame                           00000070 00000000
 22 .rela.debug_frame                      000000fc 00000000
 23 .debug_info                            00000590 00000000
 24 .rela.debug_info                       0000051c 00000000
 25 .debug_abbrev                          0000025a 00000000
 26 .debug_loc                             00000223 00000000
 27 .rela.debug_loc                        00000318 00000000
 28 .debug_aranges                         00000038 00000000
 29 .rela.debug_aranges                    0000006c 00000000
 30 .debug_ranges                          00000028 00000000
 31 .rela.debug_ranges                     00000060 00000000
 32 .debug_line                            000006b2 00000000
 33 .rela.debug_line                       000004d4 00000000
 34 .debug_str                             00000349 00000000
 35 .comment                               00000027 00000000
 36 .xtensa.info                           00000038 00000000
 37 .xt.lit                                00000020 00000000
 38 .rela.xt.lit                           00000030 00000000
 39 .xt.prop                               00000180 00000000
 40 .rela.xt.prop                          00000180 00000000
 41 .symtab                                00000230 00000000
 42 .strtab                                000000c8 00000000
 43 .shstrtab                              000001e9 00000000

/my-project/build/esp-idf/xtensa/libxtensa.a(xtensa_intr_asm.S.obj):	file format elf32-unknown

Sections:
Idx Name                Size     VMA      Type
  0                     00000000 00000000
  1 .text               00000033 00000000 TEXT
  2 .data               00000400 00000000 DATA
  3 .rela.data          00000900 00000000
  4 .bss                00000000 00000000 BSS
  5 .xtensa.info        00000038 00000000
  6 .debug_line         000000e6 00000000
  7 .rela.debug_line    000000f0 00000000
  8 .debug_info         00000023 00000000
  9 .rela.debug_info    00000048 00000000
 10 .debug_abbrev       00000014 00000000
 11 .debug_aranges      00000020 00000000
 12 .rela.debug_aranges 00000024 00000000
 13 .debug_str          00000083 00000000
 14 .xt.prop            00000054 00000000
 15 .rela.xt.prop       00000054 00000000
 16 .symtab             00000550 00000000
 17 .strtab             0000034a 00000000
 18 .shstrtab           0000009b 00000000

--
there is no trace of the words "In archive" in the dump, neither in the first line (it is blank) nor in the whole dump

**Comment by Coobik** [comment] 2022-12-25 16:31
run command manually to see there are no words "In archive" in output
/usr/bin/objdump -h /my-project-path/build/esp-idf/xtensa/libxtensa.a

**Comment by Coobik** [comment] 2022-12-25 17:01
it looks like the problem is the difference in behaviour between macos objdump (/usr/bin/objdump) and the one in linux. they have very different output.

on macos, we can install binutils with homebrew: brew install binutils
then linux version of objdump is available under /usr/local/opt/binutils/bin
so we can run it
/usr/local/opt/binutils/bin/objdump -h /my-prohect-path/build/esp-idf/xtensa/libxtensa.a
and observe the output - the first line is indeed:
In archive /my-project-path/build/esp-idf/xtensa/libxtensa.a:

so the tool chain for macos should include linux version of objdump to get the "In archive" line

PS
i don't understand why do we need objdump to read this line because it's just filepath which is already known

**Comment by Coobik** [comment] 2022-12-25 21:12
for some (yet unknown) reason
/Users/USER/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-objdump
is not picked up by build scripts (even after . ./export.sh is run), so macos default objdump is used

**Comment by Coobik** [comment] 2022-12-25 22:24
tried to put --objdump "xtensa-esp32-elf-objdump" into /Users/USER/projects/esp/esp-idf/tools/cmake/ldgen.cmake explicitly (instead of using CMAKE_OBJDUMP which is always "/usr/bin/objdump" for unknown reason), so that ldgen step is passed,

then got the following error:
/Users/USER/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/11.2.0/../../../../xtensa-esp32-elf/bin/ld: warning: cannot find entry symbol call_start_cpu0; not setting start address

/Users/USER/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/11.2.0/../../../../xtensa-esp32-elf/bin/ld: /Users/USER/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/11.2.0/../../../../xtensa-esp32-elf/lib/no-rtti/libnosys.a(sbrk.o):(.literal+0x4): undefined reference to `end'

**Comment by igrr** [comment] 2022-12-26 06:53
Hi @Coobik, sorry that the project build didn't work as expected. To help us troubleshoot this, could you please attach the `CMakeCache.txt` file found inside `build` directory? Then remove the `build` directory, run `idf.py build` again, and attach the entire build log you get.

**Comment by Coobik** [comment] 2022-12-28 14:40
hi!
i don't know what is happening, but today i have tried with reverted ldgen.cmake,
i've put back --objdump "${CMAKE_OBJDUMP}" instead of explicit xtensa-esp32-elf-objdump
and it looks like now it picks up the correct objdump (xtensa-esp32-elf-objdump)
maybe that was a magic of reboot

but aside from that, it's not clear why objdump is required, because i've logged the results
and the lib paths and the first lines from the output of xtensa-esp32-elf-objdump are the same

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/xtensa/libxtensa.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/xtensa/libxtensa.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_ringbuf/libesp_ringbuf.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_ringbuf/libesp_ringbuf.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/efuse/libefuse.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/efuse/libefuse.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/driver/libdriver.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/driver/libdriver.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_pm/libesp_pm.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_pm/libesp_pm.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/mbedtls/libmbedtls.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/mbedtls/libmbedtls.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_app_format/libesp_app_format.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_app_format/libesp_app_format.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/bootloader_support/libbootloader_support.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/bootloader_support/libbootloader_support.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_partition/libesp_partition.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_partition/libesp_partition.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/app_update/libapp_update.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/app_update/libapp_update.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/spi_flash/libspi_flash.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/spi_flash/libspi_flash.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/pthread/libpthread.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/pthread/libpthread.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_system/libesp_system.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_system/libesp_system.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_rom/libesp_rom.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_rom/libesp_rom.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/hal/libhal.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/hal/libhal.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/log/liblog.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/log/liblog.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/heap/libheap.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/heap/libheap.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/soc/libsoc.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/soc/libsoc.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_hw_support/libesp_hw_support.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_hw_support/libesp_hw_support.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/freertos/libfreertos.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/freertos/libfreertos.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/newlib/libnewlib.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/newlib/libnewlib.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/cxx/libcxx.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/cxx/libcxx.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_common/libesp_common.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_common/libesp_common.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_timer/libesp_timer.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_timer/libesp_timer.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/app_trace/libapp_trace.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/app_trace/libapp_trace.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_event/libesp_event.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_event/libesp_event.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/nvs_flash/libnvs_flash.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/nvs_flash/libnvs_flash.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_phy/libesp_phy.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_phy/libesp_phy.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/vfs/libvfs.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/vfs/libvfs.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/lwip/liblwip.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/lwip/liblwip.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_netif/libesp_netif.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_netif/libesp_netif.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/wpa_supplicant/libwpa_supplicant.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/wpa_supplicant/libwpa_supplicant.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_wifi/libesp_wifi.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_wifi/libesp_wifi.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/unity/libunity.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/unity/libunity.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/cmock/libcmock.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/cmock/libcmock.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/console/libconsole.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/console/libconsole.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/http_parser/libhttp_parser.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/http_parser/libhttp_parser.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp-tls/libesp-tls.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp-tls/libesp-tls.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_adc/libesp_adc.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_adc/libesp_adc.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_eth/libesp_eth.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_eth/libesp_eth.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_gdbstub/libesp_gdbstub.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_gdbstub/libesp_gdbstub.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_hid/libesp_hid.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_hid/libesp_hid.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/tcp_transport/libtcp_transport.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/tcp_transport/libtcp_transport.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_http_client/libesp_http_client.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_http_client/libesp_http_client.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_http_server/libesp_http_server.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_http_server/libesp_http_server.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_https_ota/libesp_https_ota.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_https_ota/libesp_https_ota.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_lcd/libesp_lcd.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_lcd/libesp_lcd.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/protobuf-c/libprotobuf-c.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/protobuf-c/libprotobuf-c.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/protocomm/libprotocomm.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/protocomm/libprotocomm.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_local_ctrl/libesp_local_ctrl.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/esp_local_ctrl/libesp_local_ctrl.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/espcoredump/libespcoredump.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/espcoredump/libespcoredump.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/wear_levelling/libwear_levelling.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/wear_levelling/libwear_levelling.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/sdmmc/libsdmmc.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/sdmmc/libsdmmc.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/fatfs/libfatfs.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/fatfs/libfatfs.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/json/libjson.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/json/libjson.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/mqtt/libmqtt.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/mqtt/libmqtt.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/perfmon/libperfmon.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/perfmon/libperfmon.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/spiffs/libspiffs.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/spiffs/libspiffs.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/ulp/libulp.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/ulp/libulp.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/wifi_provisioning/libwifi_provisioning.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/wifi_provisioning/libwifi_provisioning.a:

lib:                   /Users/USER/projects/esp/friwave32n/build/esp-idf/main/libmain.a
first_line: In archive /Users/USER/projects/esp/friwave32n/build/esp-idf/main/libmain.a:

**Comment by Coobik** [comment] 2022-12-28 14:53
the second problem "cannot find entry symbol call_start_cpu0" and "undefined reference to `end'" - it is now also gone, but there came another one - undefined reference to `app_main'

I've looked around and it seems that now as defined in esp-idf/tools/cmake/project.cmake, the source directory of a project must be named "main".
but i have used platformio (vscode plugin, latest update) to create a project, and it has created source directory as "src".
after i renamed the directory to "main" this dummy project is now buildable by idf.py build

but not platformio itself, struggle continues...

**Comment by Coobik** [comment] 2022-12-28 15:55
so for platformio to be compatible with idf.py build and recognize main directory instead of src, we need to to put

[platformio]
src_dir = ./main

into platformio.ini

**Comment by igrr** [comment] 2022-12-30 07:42
Given that you have solved the issue on your side and that we were unable to reproduce it, I'll close the issue. If it happens again, please re-open it and attach the files I have mentioned in https://github.com/espressif/esp-idf/issues/10440#issuecomment-1364939905.

**Closed by igrr** 2022-12-30 07:42 UTC
Labels: Type: Bug, Status: Opened

**Comment by Ou7law007** [comment] 2023-01-02 14:43
Same error on Mac. Not using platformio

```
pyparsing.exceptions.ParseException: Parsing sections info for library /path/build/esp-idf/xtensa/libxtensa.a failed. Expected 'In archive'  (at char 0), (line:1, col:1)
```
The file is not empty

**Comment by Coobik** [comment] 2023-01-02 15:07
> Same error on Mac. Not using platformio
> 
> ```
> pyparsing.exceptions.ParseException: Parsing sections info for library /path/build/esp-idf/xtensa/libxtensa.a failed. Expected 'In archive'  (at char 0), (line:1, col:1)
> ```
> 
> The file is not empty

you need to make sure that xtensa-esp32-elf-objdump is used and not the system objdump.
also put all the paths that are exported by export.sh to your PATH
