### ISSUE TITLE
stdatomic builtin functions are not multi-core safe for target pointer in external RAM (IDFGH-9385)

### ISSUE THREAD

**Issue by vvasiu** [espressif/esp-idf#10759] opened 2023-02-13 15:22 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.3.2

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

ESP32-WROVER-KIT

### Power Supply used.

USB

### What is the expected behavior?

We've been using atomic builtin functions from stdatomic.h and noticed that they are not multi-core safe in certain cases.

Example code
```
#include <stdatomic.h>
volatile static int i;
volatile static int j;

void foo(){
    __atomic_exchange_n(&i, &j);
}
```
The following cmd line: `c:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -S test.c`, produces the dissasembly as below, so the __atomic_exchange_n is inlined:
```
foo:
	entry	sp, 32
	mov.n	a7, sp
	l32r	a8, .LC0
	l32r	a3, .LC1
	memw
	l32i.n	a2, a3, 0
.L2:
	mov.n	a4, a2
	mov.n	a2, a8
	wsr	a4, SCOMPARE1
	s32c1i	a2, a3, 0
	sub	a6, a2, a4
	movi.n	a5, 1
	movi.n	a4, 0
	moveqz	a4, a5, a6
	beqz.n	a4, .L2
	nop.n
	retw.n
```

Reading about the Xtensa ISA, the native instructions `wsr` and `s32c1i` are used to perform an atomic compare and set, in a way that is multi-core safe.
However, we noticed that when the target pointer is in external RAM, and a race condition happens, this atomic compare and set is not functional.

Analyzing further we found some comments in later updates of the esp-idf => https://github.com/espressif/esp-idf/blob/9092b9396605908d6c3f4bfc24c7a56abebdb141/components/esp_hw_support/cpu.c#L915

So it seems that for external RAM, the stdatomic builtin functions can't work and we must use APIs provided by esp-idf.

Questions:
- Can you confirm this analysis?
- Is there any plan to upgrade the toolchain libraries in a way that stdatomic will be multi-core safe?

### What is the actual behavior?

stdatomic builtin functions are not multi-core safe for target pointer in external RAM

### Steps to reproduce.

1. Dissasemble a call to `__atomic_exchange_n` function and analyze the result

**Comment by igrr** [comment] 2023-02-13 15:29
This is probably a duplicate of https://github.com/espressif/esp-idf/issues/4635.

**Closed** 2023-02-13 15:41 UTC
Labels: Type: Bug, Status: Done, Resolution: Duplicate
