### ISSUE TITLE
about Timers and relaunching (IDFGH-12883)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#13845] opened 2024-05-24 05:11 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

using this: 

https://github.com/diplfranzhoepfinger/esp_timer_example

it is the Example: 

https://github.com/espressif/esp-idf-cxx/blob/main/examples/esp_timer_cxx/main/esp_timer_example.cpp

and modify it like this: 

```
        timer.start(chrono::microseconds(200 * 1000));
        this_thread::sleep_for(std::chrono::milliseconds(550));
        timer.start(chrono::microseconds(200 * 1000));
```

and it works, the Timer can be started 2 times. 

but in another Application i get this: 

Exception with error: 259 ESP_ERR_INVALID_STATE
ESP_ERR_INVALID_STATE if the timer is already running

**Comment by igrr** [comment] 2024-05-24 12:23
> and it works, the Timer can be started 2 times.

I think it makes sense, because the timer is first started for 200 ms, so after a 550 ms delay, it is not running. Hence, we can start it again without getting an error.

If you want to start an already-running timer, you first need to call esp_timer_stop to cancel it.

**Comment by diplfranzhoepfinger** [comment] 2024-05-24 12:57
this is my Error. 

i wanted to test a Timer started 2 times which is still running.

**Comment by Dazza0** [comment] 2024-05-28 07:34
@diplfranzhoepfinger Closing this issue as it's not a bug. ESP Timer start APIs are designed to return `ESP_ERR_INVALID_STATE` if the timer is already running.

**Closed** 2024-05-28 07:34 UTC
Labels: Status: Opened
