### ISSUE TITLE
Error compiling latest master branch. (IDFGH-2885)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#4931] opened 2020-03-13 21:47 UTC
Git describe: v4.2-dev-674-g640c7c510

```
In file included from esp_idf/test_master/esp-idf/components/bt/controller/bt.c:38:
esp_idf/test_master/esp-idf/components/bt/controller/bt.c: In function 'esp_bt_controller_mem_release':
esp_idf/test_master/esp-idf/components/log/include/esp_log.h:322:47: error: 'mem_start' may be used uninitialized in this function [-Werror=maybe-uninitialized]
         else if (level==ESP_LOG_DEBUG )     { esp_log_write(ESP_LOG_DEBUG,      tag, LOG_FORMAT(D, format), esp_log_timestamp(), tag, ##__VA_ARGS__); } \
                                               ^~~~~~~~~~~~~
esp_idf/test_master/esp-idf/components/bt/controller/bt.c:975:14: note: 'mem_start' was declared here
     intptr_t mem_start, mem_end;
```

**Comment by dobairoland** [comment] 2020-03-14 06:54
This looks like a duplicate of https://github.com/espressif/esp-idf/issues/4918.

**Comment by KaeLL** [comment] 2020-03-14 13:49
it is. You may close it, then.

**Comment by Alvin1Zhang** [comment] 2020-03-16 07:15
@KaeLL Thanks for reporting, let us track in https://github.com/espressif/esp-idf/issues/4918, thanks.

**Closed by Alvin1Zhang** 2020-03-16 07:15 UTC
