### ISSUE TITLE
xTaskAbortDelay is missing

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#1746] opened 2018-03-20 00:29 UTC
I have seen that xTaskAbortDelay() is not available.
Would be nice e.g. to cancel a select which has no timeout.
At the moment I use a select with timeout and a task notification as workaround.

**Comment by negativekelvin** [comment] 2018-03-20 01:00
https://github.com/espressif/esp-idf/issues/1453

**Comment by igrr** [comment] 2018-03-20 11:15
As @negativekelvin mentioned above, this looks like a duplicate of #1453. Please follow the link to that issue and click "Subscribe" button to receive future updates.

**Closed by igrr** 2018-03-20 11:15 UTC
