### ISSUE TITLE
Error uploading Filesystem image (IDFGH-8864)

### ISSUE THREAD

**Issue by jrHernandezSio** [espressif/esp-idf#10289] opened 2022-12-01 11:35 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

**ENVIRONMENT:**
espressif32@3.3.2 -> framework-espidf @ 3.40300.0 (4.3.0)
espressif32@5.2.0 ->framework-espidf @ 3.40402.0 (4.4.2) (also tried with this and same result)
ESPTOOL               -> tool-esptoolpy @ 1.40201.0 (4.2.1)

**DESCRIPTION:**
I am trying to setup a file into a SPIFFS partition in my ESP32-4MB, but I am finding some inconsistency.

After uploading the image file spiffs.bin with file included  the file is not there when botting the EPS32.
I have noticed the address for SPIFFS partition is not the same as the addres provided at runtime.

Partitions.csv :
```
# Name,   Type, SubType, Offset,  Size, Flags
# Note: if you have increased the bootloader size, make sure to update the offsets to avoid overlap
reserved, data, 0xfe,     0x9000,   16k
otadata,  data, ota,      0xd000,   8k     
phy_init, data, phy,      0xf000,   4k                   
ota_0,    app,  ota_0,    0x10000,  1780k 
ota_1,    app,  ota_1,    ,         1780k
coredump, data, coredump, ,         64K 
nvs,      data, nvs,      ,         128K
storage,  data, spiffs,   ,         256K
```

Flashing spiffs.bin ...
```
Building SPIFFS image from 'data' directory to .pio\build\esp32dev\spiffs.bin
/config.txt
Looking for upload port...
Auto-detected: COM8
Uploading .pio\build\esp32dev\spiffs.bin
esptool.py v3.1
Serial port COM8
Connecting........_
Chip is ESP32-D0WD (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 98:f4:ab:89:6a:a0
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x003ba000 to 0x003f9fff...
Compressed 262144 bytes to 948...
Writing at 0x003ba000... (100 %)
Wrote 262144 bytes (948 compressed) at 0x003ba000 in 1.4 seconds (effective 1543.7 kbit/s)...
Hash of data verified.
```

ADDRESS for flashing tool -> **0x003ba000**

Booting....
```
-DEBUG-: [Thu Jan  1 00:00:02 1970] Partition size: total: 233681, used: 0
-DEBUG-: [Thu Jan  1 00:00:02 1970] Failed to open cfg file
-DEBUG-: [Thu Jan  1 00:00:02 1970] WR new file
-DEBUG-: [Thu Jan  1 00:00:02 1970] Failed to open cfg file
-DEBUG-: [Thu Jan  1 00:00:02 1970] FILE (/spiffs/config.json) : Total (bytes): 0
....
repartition > Boot partition  -> partition label: ota_0 type: 0 subtype: 16     address:      10000     size:    1822720
repartition > OTA 0           -> partition label: ota_0 type: 0 subtype: 16     address:      10000     size:    1822720
repartition > OTA 1           -> partition label: ota_1 type: 0 subtype: 17     address:     1D0000     size:    1822720
repartition > NVS             -> partition label: nvs   type: 1 subtype: 2      address:     39D000     size:     131072
repartition > SPIFFS  -> partition label: storage       type: 1 subtype: 130    address:     3BD000     size:     262144
```
ADDRESS for ESP32 -> **0x3BD000**

After booting SPIFFS Partition is empty -> (Partition size: total: 233681, used: 0)

If I force the address to be **0x3BD000** in the partitions.csv everything works ok.
```
storage,  data, spiffs,   0x3BD000, 256K
```
Am I missing anything here?
I did this in the past with a 16MB device and worked ok.
Any clue, suggestion?

Regards, Ramon.

**Comment by igrr** [comment] 2022-12-02 10:09
This looks very similar to https://github.com/platformio/platform-espressif32/issues/627:

If we simply add all the partition sizes to 0x10000 to calculate the offset of `storage` partition, then we get:
0x10000 + (1780+1780+64+128)*1024 = 0x003ba000

which is exactly what the upload tool is printing. But it is incorrect, because app partition sizes need to be aligned to 16kB (on the ESP32, at least). Which as exactly the problem reported in that issue.

I'm not sure why you are getting this issue in Platformio 5.2.0, which seems to be the latest version and should have a fix for this issue. You can try adding some debugging logs to [this](https://github.com/platformio/platform-espressif32/blob/fee4b738f55d32a9bc0d0cf1f73be04ea4159968/builder/main.py#L134) code in platformio, i guess it is responsible for calculating the partition offsets. If you don't find the cause, I recommend opening a new issue at https://github.com/platformio/platform-espressif32/issues, attaching a simplified version of your project which can reproduce the issue.

(I'm closing the issue here since it doesn't seem to be related to ESP-IDF itself.)

**Closed by igrr** 2022-12-02 10:09 UTC
Labels: Status: Opened
