### ISSUE TITLE
Wrong type comparison in esp_ptr_in_drom() (IDFGH-10632)

### ISSUE THREAD

**Issue by josesimoes** [espressif/esp-idf#11865] opened 2023-07-13 12:26 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.5

### Operating System used.

Windows

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

Build should run succesfully.

### What is the actual behavior?

Build error comming from setting warning as error.

```
[build] E:/GitHub/esp-idf/components/soc/include/soc/soc_memory_types.h: In function 'bool esp_ptr_in_drom(const void*)':
[build] E:/GitHub/esp-idf/components/soc/include/soc/soc_memory_types.h:140:25: error: comparison of integer expressions of different signedness: 'intptr_t' {aka 'int'} and 'uint32_t' {aka 'unsigned int'} [-Werror=sign-compare]
[build]      return ((intptr_t)p >= drom_start_addr && (intptr_t)p < SOC_DROM_HIGH);
[build]              ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

### Steps to reproduce.

Build project with compiler options `-Wall` 

### More Information.

This can be fixed by changing the declaration of `drom_start_addr` from `uint32_t` to `int32_t`.
Alternatively the cast in line 140 could be changed to `(uintptr_t)`.

**Comment by igrr** [comment] 2023-07-13 16:55
I'll close this as duplicate of https://github.com/espressif/esp-idf/issues/11653. To get notifications about this issue, please click "subscribe" in the linked issue.

**Closed by igrr** 2023-07-13 16:55 UTC
Labels: Type: Bug, Status: Opened
