### ISSUE TITLE
Compiler error:  unknown type name '__gnuc_va_list' (IDFGH-12198)

### ISSUE THREAD

**Issue by JB-DX** [espressif/esp-idf#13252] opened 2024-02-24 14:50 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using ESP-IDF v5.1.2-dirty and getting this compiler error
```
c:\esp\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\xtensa-esp32-elf\sys-include\stdio.h:46:9: error: unknown type name '__gnuc_va_list'
   46 | typedef __gnuc_va_list va_list;

```
so __VALIST remains undefined and creates lots of further errors.

the referred section of stdio.h is this:
```
#if __POSIX_VISIBLE >= 200809 || __XSI_VISIBLE
#ifdef __GNUC__
#ifndef _VA_LIST_DEFINED
typedef __gnuc_va_list va_list;
#define _VA_LIST_DEFINED
#endif
#else /* !__GNUC__ */
#include <stdarg.h>
#endif
#endif /* __POSIX_VISIBLE >= 200809 || __XSI_VISIBLE */

```
any idea how to fix it?

**Comment by igrr** [comment] 2024-02-24 20:18
Could you please attach the complete build log (not just the last line)? This will help understand the condition which leads to this issue. Also please attach your sdkconfig file.

(In the future, kindly use 'Build time issue' issue template, it asks for information which we typically need to know to help with such kinds of issues.)

**Comment by JB-DX** [comment] 2024-02-25 00:20
Sorry I only now discovered that there is a  'Build time issue'

I attached both in a zip, since that file type is allowed
[build-log-and-sdkconfig.zip](https://github.com/espressif/esp-idf/files/14394842/build-log-and-sdkconfig.zip)

**Comment by dobairoland** [comment] 2024-02-26 07:07
I might be wrong but it looks to me that the the issue is coming from the `pjlib_neu` component where `stdarg.h` was not included. In that case, this cannot be fixed in ESP-IDF.

**Comment by andylinpersonal** [comment] 2024-02-26 07:54
Maybe you can try to rerun `install.sh` and ensure `esp-idf` have been checked out to the correct revision? `-dirty` means some uncommitted changes exist in your `esp-idf`’s repo. Some files may be modified accidentally.

**Comment by igrr** [comment] 2024-02-26 11:55
Looks like the issue happens because:
- pjlib provides a file called `stdarg.h`
- pjlib/include/pj/compat directory has been directly added to the compiler search path. So when the compiler sees `#include <stdarg.h>`, it doesn't include the toolchain-provided stdarg.h, it takes the one from pjlib/include/pj/compat.
- Therefore wherever there is an `#include <stdarg.h>`, it doesn't have any effect, and the va_list-related types are not defined.

I recommend checking your CMakeLists.txt file where you are adding pjlib library. Make sure you are not adding pjlib/include/pj/compat to the list of include directories. When pjlib source code needs to use the headers from `compat`, they always include them by full path, [like this](https://github.com/pjsip/pjproject/blob/b0be1706ea7e7334fb3f49f97d3f909d68c4ae64/pjlib/src/pj/errno.c#L23)

Currently you are including all these paths:
```
-IC:/projects/ESP/pjlib/components/pjlib_neu
-IC:/projects/ESP/pjlib/components/pjlib_neu/include
-IC:/projects/ESP/pjlib/components/pjlib_neu/include/pj
-IC:/projects/ESP/pjlib/components/pjlib_neu/include/pj/compat
-IC:/projects/ESP/pjlib/components/pjlib_neu/include/pj++
-IC:/projects/ESP/pjlib/components/pjlib_neu/src/pj
-IC:/projects/ESP/pjlib/components/pjlib_neu/src/pjlib-test
```
I think you need to remove at least include/pj/compat from the list, maybe some other ones as well — please check the include paths actually used when compiling pjlib on the host.

**Comment by JB-DX** [comment] 2024-02-26 23:00
Thank you very much for all your comments.
I was quite surprised that  folder pjlib_neu got included. My CMakeLists.txt does not specify it. It's just a folder with files that I did not want to loose. Apparently it gets included anyway. I have now moved it elsewhere and the problem is gone. Is there a way to specify that such temporary folders are not be included? 
I assumed that only files & folders specified in CMakeLists.txt would be used, apparently I was wrong.

**Comment by ESP-Marius** [comment] 2024-05-09 03:20
> I was quite surprised that folder pjlib_neu got included. My CMakeLists.txt does not specify it. It's just a folder with files that I did not want to loose. Apparently it gets included anyway. I have now moved it elsewhere and the problem is gone. Is there a way to specify that such temporary folders are not be included?

Hard to say without seeing your cmakefile, but typically cmake only include what you explicitly tells it to, so there shouldnt be a need to exclude anything.

I think we can consider this one closed now, as the original issue is resolved and there doesnt seem to be any IDF related issues.

**Closed by ESP-Marius** 2024-05-09 03:20 UTC
Labels: Status: Opened
