### ISSUE TITLE
esp_send_now aborts thread (IDFGH-12979)

### ISSUE THREAD

**Issue by kumado97** [espressif/esp-idf#13930] opened 2024-06-07 17:15 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

platformio core 6.1.15 - 3.4.4

### Espressif SoC revision.

esp32-s3-devkitc-1

### Operating System used.

Windows

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32-s3-devkitc-1

### Power Supply used.

USB

### What is the expected behavior?

Am using VSC with platformio Core 6.1.15  ·Home 3.4.4
Have a esp32 S3 woom (makerfabs S3 parallel TFT with Touch 3.5"
The code with esp_send_now did work some months ago 
classical onDatasent and  xtask create
Now it does work not anymore without changes in the code
WIFi ist not started and mode is WiFi_STA

### What is the actual behavior?

the esp_send_now is finished with a zero and the thread calling it aborts

also tried:  WiFi.useStaticBuffers(true);  // it will keep sdkconfig default for cache and static TX buffers in WiFi

### Steps to reproduce.

void OnDataSent(const uint8_t *mac_addr, esp_now_send_status_t status) 
{
  if (status == ESP_NOW_SEND_SUCCESS)
  {
    enow_success = "data sent";
  }
  else
  {
    enow_success = "nothing sent ";
  }
  Serial.print(enow_success);
  // Serial.printf(" - von: %02X:%02X:%02X:%02X:%02X:%02X  an Mac:%02X:%02X:%02X:%02X:%02X:%02X \n", th1_mac_addr[0],th1_mac_addr[1],th1_mac_addr[2],th1_mac_addr[3],th1_mac_addr[4],th1_mac_addr[5],mac_addr[0],mac_addr[1],mac_addr[2],mac_addr[3],mac_addr[4],mac_addr[5]);
}

/// assign outgoing data:
void assign_outgoingreadings(uint8_t nmc)
{ 
  wifi_second_chan_t b;
  uint8_t a;
  esp_wifi_get_channel(&a,&b);
  Serial.printf("Channel: set esp channel:%d - now_wifi_channel_th:%d - wifi_wahl:%d \r\n",a,now_wifi_channel_th, wifi_wahl);
    
  outgoingReadings.id = now_id;   
  outgoingReadings.now_ch = a;          // now channel zum Senden
  std::copy(th1_mac_addr, th1_mac_addr + 6, outgoingReadings.mac_addr);       // Mac_adresse des TH _senders
  outgoingReadings.nr = drun;   
  strcpy((char*)outgoingReadings.un_id,"ETH");   
  outgoingReadings.uxt = get_uxtime();         // ux time
  outgoingReadings.Trs = TR_soll;                 // TR_soll
  outgoingReadings.Tri = TR_ist;                 // TR_ist
    
  Serial.printf("id:%d - ch:%d  mac:%02x:%02x:%02x:%02x:%02x:%02x  -drun:%d -unid:%s - uxt:%l -TRs: %.1f - Tri:%.1f\n",outgoingReadings.id, outgoingReadings.now_ch,th1_mac_addr[0], th1_mac_addr[1], th1_mac_addr[2], th1_mac_addr[3], th1_mac_addr[4], th1_mac_addr[5],outgoingReadings.nr,outgoingReadings.un_id,outgoingReadings.uxt,outgoingReadings.Trs,outgoingReadings.Tri);
  Serial.printf("P#: pid_0  pid_1  pid2  Tv_rsp   Tvr_hst   Tvlidx  Trlidx  Thkidx  motstat   svstat  rg_alg  mot_rpm\r\n");
  
  // Serial.printf(" nmc:%d  pmc_s[1].mc_eth:%d  pmc_s[1].subnr_mc:%d\n",nmc,pmc_s[1].mc_eth,pmc_s[1].subnr_mc);
  if (nmc == 1 && pmc_s[1].mc_eth == 1 && pmc_s[1].subnr_mc == 1) // 1. Pumpe am Motor Controller 1
  {
    outgoingReadings.pid_1[0] = HKS[1].pid[0];    // P Wert Regler
    outgoingReadings.pid_1[1] = HKS[1].pid[1];    // I Wert Regler
    outgoingReadings.pid_1[2] = HKS[1].pid[2];    // D Wert Regler
    outgoingReadings.Tvr_spreiz_soll_1 = HKS[1].Tvr_spreiz;
    outgoingReadings.Tvr_hyst_soll_1 = HKS[1].Tvr_hyst;
    outgoingReadings.Tvl_idx_1 = HKS[1].Tsvl_idx;
    outgoingReadings.Trl_idx_1 = HKS[1].Tsrl_idx;
    outgoingReadings.Thk_idx_1 = HKS[1].Tshk_idx;
    outgoingReadings.mot_stat_soll_1 = HKS[1].mot_stat;
    outgoingReadings.sv_stat_soll_1 = HKS[1].sv_stat;
    outgoingReadings.rg_alg_soll_1 = HKS[1].rg_alg;
    outgoingReadings.mot_rpm_soll_1 = HKS[1].mot_rpm;
    Serial.printf("1:  %.1f    %.1f    %.1f    %.1f      %.1f        %d       %d       %d       %d         %d       %d       %d  \n",outgoingReadings.pid_1[0],outgoingReadings.pid_1[1],outgoingReadings.pid_1[2],outgoingReadings.Tvr_spreiz_soll_1,outgoingReadings.Tvr_hyst_soll_1,outgoingReadings.Tvl_idx_1,outgoingReadings.Trl_idx_1,outgoingReadings.Thk_idx_1,outgoingReadings.mot_stat_soll_1,outgoingReadings.sv_stat_soll_1,outgoingReadings.rg_alg_soll_1,outgoingReadings.mot_rpm_soll_1);
  }
}

// starts esp
void start_espnow()
{
  WiFi.disconnect();  // Abschalten vor Beginn now, sonst Quatsch beim Senden/Empfangen
  delay(100);
  
  WiFi.useStaticBuffers(true);  // it will keep sdkconfig default for cache and static TX buffers in WiFi
  WiFi.mode(WIFI_STA);  // Station mode (aka STA mode or Wi-Fi client mode). ESP32 connects to an access point.
  
  wifi_router_channel = WiFi.channel();
    
  esp32_mc_read = 1;   // Status für Daten gelesen vom Motorcontroller 0: Daten erhalten  - 1: keine Daten erhalten 
         
  Serial.printf("now_wifi_channel = %d\n",now_wifi_channel_th);
  // ESP_ERROR_CHECK(esp_wifi_set_channel(esp_ch,WIFI_SECOND_CHAN_NONE));
  if (esp_now_init() != ESP_OK) 
  { ESP.restart(); 
    return; 
  }

  ESP_ERROR_CHECK(esp_wifi_set_channel(now_wifi_channel_th,WIFI_SECOND_CHAN_NONE));

  peerInfo.channel = now_wifi_channel_th;    
  peerInfo.encrypt = false;
      
  memcpy(peerInfo.peer_addr, mc1_mac_addr, 6);
  if (esp_now_add_peer(&peerInfo) == ESP_OK)
    Serial.printf("# Peer mc1: %02X:%02X:%02X:%02X:%02X:%02X hinzugefügt\n", mc1_mac_addr[0],mc1_mac_addr[1],mc1_mac_addr[2],mc1_mac_addr[3],mc1_mac_addr[4],mc1_mac_addr[5]);
  else 
    Serial.printf("# peer mc1 nicht hinzugefügt \r\n");  
    
  if (anz_mc >= 2)    // number of controllers with data to be sent to
  {
    memcpy(peerInfo.peer_addr, mc2_mac_addr, 6);
      if (esp_now_add_peer(&peerInfo) == ESP_OK)
        Serial.printf("# Peer mc2: %02X:%02X:%02X:%02X:%02X:%02X hinzugefügt\n", mc2_mac_addr[0],mc2_mac_addr[1],mc2_mac_addr[2],mc2_mac_addr[3],mc2_mac_addr[4],mc2_mac_addr[5]);
      else 
        Serial.printf("# peer mc2 nicht hinzugefügt \r\n");
  }

  if (anz_mc >= 3)
  {
    memcpy(peerInfo.peer_addr, mc3_mac_addr, 6);
      if (esp_now_add_peer(&peerInfo) == ESP_OK)
        Serial.printf("# Peer mc3: %02X:%02X:%02X:%02X:%02X:%02X hinzugefügt\n", mc3_mac_addr[0],mc3_mac_addr[1],mc3_mac_addr[2],mc3_mac_addr[3],mc3_mac_addr[4],mc3_mac_addr[5]);
      else 
        Serial.printf("# peer mc3 nicht hinzugefügt \r\n");
  }

  esp_err_t regerr_send;
  regerr_send = esp_now_register_send_cb(OnDataSent);
  sp("regerr_send: ");
  Serial.println(regerr_send);

  // Register for a callback function that will be called when data is received
  esp_now_register_recv_cb(OnDataRecv);
  
  drun = 1;
    
  Serial.printf("ESP-NOW gestartet auf Kanal: %d \n",now_wifi_channel_th);
}

////////////////// now the function sending actually
void send_to_mc(void *pvParameters){  
  /// run as parallel task 
  
  while (1) 
  {
    if (espnow_active == true) 
    {
      esp_err_t result1,result2,result3;
      // An motor Controller 1 senden = mc1_mac_str
      // Serial.printf("mac1: %s - mac2:%s - mac3:%s\r\n",mc1_mac_str,mc2_mac_str,mc3_mac_str);
      sp("Send to:");
      printMac(mc1_mac_addr);
      spl("");

      assign_outgoingreadings(1);
            
      result1 = esp_now_send(mc1_mac_addr,(uint8_t *) &outgoingReadings,sizeof(outgoingReadings));

      Serial.printf("result  esp_now_send %d \n",result1);

      if (result1 == ESP_OK) 
      {
        Serial.printf("Run: %d - sent to MC 1 via NOW \n",drun);

        if (print_send_data)
        {
          Serial.printf("From:%d - drun: %d",outgoingReadings.id,outgoingReadings.nr);
          Serial.printf(" - Nr:1 - Mot_stat_1:%d - rg_alg_1:%d - rpm_1:%d - Nr:2 - Mot_stat_2:%d - rg_alg_2:%d - rpm_2:%d ",outgoingReadings.mot_stat_soll_1,outgoingReadings.rg_alg_soll_1,outgoingReadings.mot_rpm_soll_1,outgoingReadings.mot_stat_soll_2,outgoingReadings.rg_alg_soll_2,outgoingReadings.mot_rpm_soll_2);
           // Serial.printf(" - Nr:3 - Mot_stat_3:%d - rg_alg_3:%d - rpm_3:%d",,outgoingReadings.mot_stat_soll_3,outgoingReadings.rg_alg_soll_3,outgoingReadings.mot_rpm_soll_3);
          Serial.println("");
        }
      }
      else 
      {
        Serial.println("error sending to MC1");
      }
      
      if (anz_mc >= 2)
      {
        assign_outgoingreadings(2);
        result2 = esp_now_send(mc2_mac_addr, (uint8_t *) &outgoingReadings, sizeof(outgoingReadings));
        
        if (result2 == ESP_OK) 
        {
          Serial.printf(" - an MC 2 gesendet über NOW ");
          //spl("");
          if (print_send_data)
          {
            Serial.printf("Von:%d - drun: %d",outgoingReadings.id,outgoingReadings.nr);
            Serial.printf(" - Nr:1 - Mot_stat_1:%d - rg_alg_1:%d - rpm_1:%d - Nr:2 - Mot_stat_2:%d - rg_alg_2:%d - rpm_2:%d ",outgoingReadings.mot_stat_soll_1,outgoingReadings.rg_alg_soll_1,outgoingReadings.mot_rpm_soll_1,outgoingReadings.mot_stat_soll_2,outgoingReadings.rg_alg_soll_2,outgoingReadings.mot_rpm_soll_2);
            // Serial.printf(" - Nr:3 - Mot_stat_3:%d - rg_alg_3:%d - rpm_3:%d",,outgoingReadings.mot_stat_soll_3,outgoingReadings.rg_alg_soll_3,outgoingReadings.mot_rpm_soll_3);
            Serial.println("");
          }
        }
        else 
        {
          Serial.println("Fehler beim Senden an MC2");
        }
      }
      if (anz_mc >= 3)
      {
        assign_outgoingreadings(3);
        result2 = esp_now_send(mc3_mac_addr, (uint8_t *) &outgoingReadings, sizeof(outgoingReadings));
        
        if (result3 == ESP_OK) 
        {
          Serial.printf(" - an MC 3 gesendet über NOW ");
          //spl("");
          if (print_send_data)
          {
            Serial.printf("Von:%d - drun: %d",outgoingReadings.id,outgoingReadings.nr);
            Serial.printf(" - Nr:1 - Mot_stat_1:%d - rg_alg_1:%d - rpm_1:%d - Nr:2 - Mot_stat_2:%d - rg_alg_2:%d - rpm_2:%d",outgoingReadings.mot_stat_soll_1,outgoingReadings.rg_alg_soll_1,outgoingReadings.mot_rpm_soll_1,outgoingReadings.mot_stat_soll_2,outgoingReadings.rg_alg_soll_2,outgoingReadings.mot_rpm_soll_2);
            // Serial.printf(" - Nr:3 - Mot_stat_3:%d - rg_alg_3:%d - rpm_3:%d",,outgoingReadings.mot_stat_soll_3,outgoingReadings.rg_alg_soll_3,outgoingReadings.mot_rpm_soll_3);
            Serial.println("");
          }
        }
        else 
        {
          Serial.println("Fehler beim Senden an MC3");
        }
      }

    }
           
    //showing unsused stack for xtaskcreate actually is ca 2k
    
    vTaskDelay(40);
    unsigned int temp = uxTaskGetStackHighWaterMark(nullptr);
    printf(" - send_to_mc: Unused stack is %u \r\n", temp);
    
    delay (1000); // wait until next Write cycle
  
  }
} 

///////////// in the setup 
xTaskCreateUniversal(send_to_mc, "send_to_mc", 5024, NULL, 2, NULL, 0);   // Parallel task auf Core 0 (= WIFI/RF core)

### Debug Logs.

```plain
Datum;23.3.2024;17:24.45;
esp_now_channel;6;
TR_hyst;1.000000;
Bild_aus_min;5.000000;
anz_pp;2;
anz_mc;1;
pmc1;1;1;1;00:01:00:00:02:01;
pmc2;2;1;2;00:01:00:00:02:02;
pmc3;3;1;3;00:01:00:00:02:03;
pid1;0.100000;0.100000;0.100000;
pid2;0.200000;0.200000;0.200000;
pid3;0.300000;0.300000;0.300000;
dsx1;5;3;2;
dsx2;0;1;4;
dsx3;6;7;8; 17 Zeilen eingelesen
Wifi Scan durchführen - Bitte warten
1 Netzwerke gefunden:
Nr:1  - Name:Kuma-Dach  - RSSI:(-47)dB  - Kanal:11 - Encrypted: j
Ausgewähltes Netzwerk nach index: 0 - Channel für esp-now: 8
 - Check Time set: 01-01-1970  00:00:07 
  - Eigene Mac Adresse: 00:01:00:00:02:00 - WiFi Mac:48:27:E2:07:43:D0
now_wifi_channel = 8
# Peer mc1: 00:01:00:00:02:01 hinzugefügt
regerr_send: 0
ESP-NOW gestartet auf Kanal: 8
Touchscreen initialisiert
Senden an:00:01:00:00:02:01
Channel: set esp channel:8 - now_wifi_channel_th:8 - wifi_wahl:0
id:1 - ch:8  mac:00:01:00:00:02:00  -drun:1 -unid:ETH - uxt:TRs: 0.0 - Tri:21.0
P#: pid_0  pid_1  pid2  Tv_rsp   Tvr_hst   Tvlidx  Trlidx  Thkidx  motstat   svstat  rg_alg  mot_rpm
1:  0.1    0.1    0.1    2.0      1.0        5       3       2       0         0       2       60
2:  0.2    0.2    0.2    2.0      1.0        0       1       4       0         0       1       10
assign_outgoingreadings erledigt
Ergebnis esp_now_send 0
Lauf: 1 - an MC 1 gesendet über NOW Nix gesendet - send_to_mc: Unused stack is 2760 

abort() was called at PC 0x4209cc4b on core 1


Backtrace: 0x403782e2:0x3fceb150 0x4037e385:0x3fceb170 0x403842cd:0x3fceb190 0x4209cc4b:0x3fceb210 0x4209cc92:0x3fceb230 0x4208d7db:0x3fceb250 0x4208f7c7:0x3fceb270 0x4200aa27:0x3fceb290 0x42019929:0x3fceb2c0 0x4201a59f:0x3fcebe80 0x42025dc2:0x3fcebf40




ELF file SHA256: 9c092eaea38f8099

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xb (SPI_FAST_FLASH_BOOT)
Saved PC:0x40382d2f
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a80
entry 0x403c98d0
E (226) opi psram: PSRAM ID read error: 0x00000000, PSRAM chip not found or not supported, or wrong PSRAM line mode
E (226) spiram: SPI RAM enabled but initialization failed. Bailing out.
Start
Datum;23.3.2024;17:24.45;
esp_now_channel;6;
TR_hyst;1.000000;
Bild_aus_min;5.000000;
ssid;Kuma-Dach;
pwid;orte-jj1hb;
anz_pp;2;
anz_mc;1;
pmc1;1;1;1;00:01:00:00:02:01;
pmc2;2;1;2;00:01:00:00:02:02;
pmc3;3;1;3;00:01:00:00:02:03;
pid1;0.100000;0.100000;0.100000;
pid2;0.200000;0.200000;0.200000;
pid3;0.300000;0.300000;0.300000;
dsx1;5;3;2;
dsx2;0;1;4;
dsx3;6;7;8; 17 Zeilen eingelesen
Wifi Scan durchführen - Bitte warten
2 Netzwerke gefunden:
Nr:1  - Name:Kuma-Dach  - RSSI:(-50)dB  - Kanal:11 - Encrypted: j
Nr:2  - Name:$��?␟  - RSSI:(-96)dB  - Kanal:1 - Encrypted: j
Ausgewähltes Netzwerk nach index: 0 - Channel für esp-now: 1
 - Check Time set: 01-01-1970  00:00:07 
  - Eigene Mac Adresse: 00:01:00:00:02:00 - WiFi Mac:48:27:E2:07:43:D0
now_wifi_channel = 1
# Peer mc1: 00:01:00:00:02:01 hinzugefügt
regerr_send: 0
ESP-NOW gestartet auf Kanal: 1
Touchscreen initialisiert
Senden an:00:01:00:00:02:01
Channel: set esp channel:1 - now_wifi_channel_th:1 - wifi_wahl:0
id:1 - ch:1  mac:00:01:00:00:02:00  -drun:1 -unid:ETH - uxt:TRs: 0.0 - Tri:21.0
P#: pid_0  pid_1  pid2  Tv_rsp   Tvr_hst   Tvlidx  Trlidx  Thkidx  motstat   svstat  rg_alg  mot_rpm
1:  0.1    0.1    0.1    2.0      1.0        5       3       2       0         0       2       60
2:  0.2    0.2    0.2    2.0      1.0        0       1       4       0         0       1       10
assign_outgoingreadings erledigt
Ergebnis esp_now_send 0 
Lauf: 1 - an MC 1 gesendet über NOW Nix gesendet - send_to_mc: Unused stack is 2760 

abort() was called at PC 0x4209cc4b on core 1


Backtrace: 0x403782e2:0x3fceb150 0x4037e385:0x3fceb170 0x403842cd:0x3fceb190 0x4209cc4b:0x3fceb210 0x4209cc92:0x3fceb230 0x4208d7db:0x3fceb250 0x4208f7c7:0x3fceb270 0x4200aa27:0x3fceb290 0x42019929:0x3fceb2c0 0x4201a59f:0x3fcebe80 0x42025dc2:0x3fcebf40




ELF file SHA256: 9c092eaea38f8099

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xb (SPI_FAST_FLASH_BOOT)
Saved PC:0x40382d41
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a80
entry 0x403c98d0
E (226) opi psram: PSRAM ID read error: 0x00000000, PSRAM chip not found or not supported, or wrong PSRAM line mode
E (226) spiram: SPI RAM enabled but initialization failed. Bailing out.
Start
Datum;23.3.2024;17:24.45;
esp_now_channel;6;
TR_hyst;1.000000;
Bild_aus_min;5.000000;
ssid;Kuma-Dach;
pwid;orte-jj1hb;
anz_pp;2;
anz_mc;1;
pmc1;1;1;1;00:01:00:00:02:01;
pmc2;2;1;2;00:01:00:00:02:02;
pmc3;3;1;3;00:01:00:00:02:03;
pid1;0.100000;0.100000;0.100000;
pid2;0.200000;0.200000;0.200000;
pid3;0.300000;0.300000;0.300000;
dsx1;5;3;2;
dsx2;0;1;4;
dsx3;6;7;8; 17 Zeilen eingelesen
Wifi Scan durchführen - Bitte warten
1 Netzwerke gefunden:
Nr:1  - Name:Kuma-Dach  - RSSI:(-50)dB  - Kanal:11 - Encrypted: j
Ausgewähltes Netzwerk nach index: 0 - Channel für esp-now: 8
 - Check Time set: 01-01-1970  00:00:07 
  - Eigene Mac Adresse: 00:01:00:00:02:00 - WiFi Mac:48:27:E2:07:43:D0
now_wifi_channel = 8
# Peer mc1: 00:01:00:00:02:01 hinzugefügt
regerr_send: 0
ESP-NOW gestartet auf Kanal: 8
```

### More Information.

It has worked 6 months ago properly and now it doesn't !!!??????

**Comment by 0xjakob** [comment] 2024-06-10 07:55
@kumado97 I assume you mean `esp_now_send()`, instead of `esp_send_now()`, correct?

**Comment by kumado97** [comment] 2024-06-10 08:12
Yes,
but i solved it now. It would help extremely if you add code examples at the bottom of the reference chapters, e. g. how the code would change for the receive call back from core 2. to core 3.
kind regards
Kurt Orthmann

10.06.2024 09:55:57 0xjakob ***@***.***>:

**Comment by 0xjakob** [comment] 2024-06-11 07:59
@kumado97 Thanks for letting us know. We're working on improving our documentation and we do plan to introduce how-to sections for each area, which should help in your case.

If the problem is resolved, would you mind giving a brief feedback what solved the issue and close it? This helps other users with a similar issue and let's us easily keep track of issues that haven't been resolved, respectively.

**Comment by Sherry616** [comment] 2024-06-14 10:02
Thanks for reporting, we will close this issue. Feel free to reopen if have more updates. 
Thanks for using our Espressif product!

**Closed by Sherry616** 2024-06-14 10:02 UTC
Labels: Type: Bug, Status: Opened
