### ISSUE TITLE
install.ps1 has wrong arguments (IDFGH-8117)

### ISSUE THREAD

**Issue by josesimoes** [espressif/esp-idf#9616] opened 2022-08-23 15:35 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.2

### Operating System used.

Windows

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

PowerShell

### What is the expected behavior?

being able to execute install.ps1 successfully 

### What is the actual behavior?

fails when installing python

### Steps to reproduce.

run install.ps1

### Build or installation Logs.

```plain
Skipping idf-exe@1.0.3 (already installed)
Skipping ccache@4.3 (already installed)
Skipping dfu-util@0.9 (already installed)
Setting up Python environment
usage: idf_tools.py [-h] [--quiet] [--non-interactive] [--tools-json TOOLS_JSON] [--idf-path IDF_PATH]
                    {list,check,export,install,download,install-python-env} ...
idf_tools.py: error: unrecognized arguments: --features=
```

### More Information.

In line 16 of install.ps1 there is `--features=${FEATURES}` which is breaking the PS1 execution, if removed it executes OK.

**Comment by igrr** [comment] 2022-08-23 17:41
This looks like a duplicate of https://github.com/espressif/esp-idf/issues/9556.

**Closed** 2022-08-23 18:12 UTC
Labels: Type: Bug, Status: Opened
