### ISSUE TITLE
[TW#15438] Memory leak on  esp_wifi_start()-esp_wifi_stop() cycles

### ISSUE THREAD

**Issue by n0p** [espressif/esp-idf#1000] opened 2017-09-14 07:43 UTC
I am experimenting with cycling the wifi radio to conserve power and I've found that every loop it consumes 100bytes of heap memory.

This is the test code:
```
    for( ;; )
    {
        vTaskDelay(2000 / portTICK_PERIOD_MS);
        ESP_LOGI(TAG, "Dozing");
        esp_wifi_disconnect();
        esp_wifi_stop();
        ESP_LOGI(TAG, "Free memory: %d bytes", system_get_free_heap_size());
        
        vTaskDelay(2000 / portTICK_PERIOD_MS);
        ESP_LOGI(TAG, "Waking up");
        esp_wifi_start();
        esp_wifi_connect();
        ESP_LOGI(TAG, "Free memory: %d bytes", system_get_free_heap_size());
    }
```

**Comment by TimXia** [comment] 2017-10-12 09:15
@n0p It is caused by a bug of DHCP. It has been fixed and will be released in idf v3.0.

**Closed** 2017-10-23 08:03 UTC
