### ISSUE TITLE
Component dependency issue (IDFGH-6873)

### ISSUE THREAD

**Issue by svcguy** [espressif/esp-idf#8495] opened 2022-03-04 04:31 UTC
## Environment

- Development Kit:      **ESP32-S2 Kaluga**
- Kit version (for WroverKit/PicoKit/DevKitC):  **v1.3**
- Module or chip used:  **ESP32-S2 WROVER**
- IDF version (run ``git describe --tags`` to find it): **v4.4**
- Build System:         **idf.py**
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): **2021r2-patch2-8.4.0**
- Operating System:     **Windows**
- (Windows only) environment type: **ESP Command Prompt**
- Using an IDE?: **Yes VSCode (ESP-IDF VSCode extension 1.4.0)**
- Power Supply:        **N/A**

## Problem Description

Component Manager seems to have trouble with ^ and ~ notation

### Expected Behavior

Resolve dependencies

### Actual Behavior

Fails to resolve dependencies

### Steps to reproduce

```
PS C:\Users\svcgu\OneDrive\Documents\ESP32\ltc2488> idf.py add-dependency espressif/esp32_s2_kaluga_kit==0.0.4
Executing action: add-dependency
Created "c:\users\svcgu\onedrive\documents\esp32\ltc2488\main\idf_component.yml"
Successfully added dependency "espressif/esp32_s2_kaluga_kit==0.0.4" for component "main"
PS C:\Users\svcgu\OneDrive\Documents\ESP32\ltc2488> idf.py add-dependency lvgl/lvgl==8.2.0
Executing action: add-dependency
Successfully added dependency "lvgl/lvgl==8.2.0" for component "main"
PS C:\Users\svcgu\OneDrive\Documents\ESP32\ltc2488> idf.py reconfigure
Executing action: reconfigure
Running cmake in directory c:\users\svcgu\onedrive\documents\esp32\ltc2488\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 c:\users\svcgu\onedrive\documents\esp32\ltc2488"...
-- ccache will be used for faster recompilation
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32s2
Solving dependencies requirements
CMake Error at C:/Users/svcgu/esp/esp-idf/tools/cmake/build.cmake:455 (message):
  Traceback (most recent call last):

    File "runpy.py", line 194, in _run_module_as_main
    File "runpy.py", line 87, in _run_code
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\prepare_components\__main__.py", line 3, in <module>
      main()
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\prepare_components\prepare.py", line 110, in main
      args.func(args)
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\prepare_components\prepare.py", line 37, in prepare_dep_dirs
      ComponentManager(args.project_dir).prepare_dep_dirs(
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\core.py", line 325, in prepare_dep_dirs
      downloaded_component_paths = download_project_dependencies(
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\dependencies.py", line 36, in download_project_dependencies
      solution = solver.solve()
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\version_solver\version_solver.py", line 30, in solve
      result = self._solver.solve()
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\version_solver\mixology\version_solver.py", line 63, in solve
      if not self._run():
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\version_solver\mixology\version_solver.py", line 76, in _run
      self._propagate(next_package)
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\version_solver\mixology\version_solver.py", line 108, in _propagate
      root_cause = self._resolve_conflict(incompatibility)
    File "C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\idf_component_manager\version_solver\mixology\version_solver.py", line 282, in _resolve_conflict
      raise SolverFailure(incompatibility)

  idf_component_manager.version_solver.mixology.failure.SolverFailure:
  Because espressif/esp32_s2_kaluga_kit (0.0.4) depends on espressif/es8311
  (^0.0.2-alpha) which doesn't match any versions,
  espressif/esp32_s2_kaluga_kit is forbidden.

  So, because project depends on espressif/esp32_s2_kaluga_kit (==0.0.4),
  version solving failed.

Call Stack (most recent call first):
  C:/Users/svcgu/esp/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/svcgu/OneDrive/Documents/ESP32/ltc2488/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1
```

### Code to reproduce this issue

None - Build Issue

## Other items if possible

**ESP Doctor Command**

```---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.19043 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\PowerShell\7\;C:\Users\svcgu\AppData\Local\Microsoft\WindowsApps;C:\Users\svcgu\AppData\Local\Programs\Microsoft VS Code\bin;C:\ST\STM32Cube\STM32CubeProgrammer\bin; 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.65.0 
Visual Studio Code language en 
Visual Studio Code shell C:\Program Files\PowerShell\7\pwsh.exe 
ESP-IDF Extension version 1.4.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:\Users\svcgu\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) C:\Users\svcgu\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin;C:\Users\svcgu\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32s2-elf\bin;C:\Users\svcgu\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32s3-elf\bin;C:\Users\svcgu\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch2-8.4.0\riscv32-esp-elf\bin;C:\Users\svcgu\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Users\svcgu\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\svcgu\.espressif\tools\cmake\3.20.3\bin;C:\Users\svcgu\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin;C:\Users\svcgu\.espressif\tools\ninja\1.10.2;C:\Users\svcgu\.espressif\tools\idf-exe\1.0.3;C:\Users\svcgu\.espressif\tools\ccache\4.3\ccache-4.3-windows-64;C:\Users\svcgu\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:\\Users\\svcgu\\.espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) C:\Users\svcgu\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM6
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,target/esp32s2.cfg
ESP-IDF Tools Path (idf.toolsPath) C:\Users\svcgu\.espressif
Git Path (idf.gitPath) C:\Users\svcgu\.espressif\tools\idf-git\2.30.1\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to C:\Users\svcgu\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin: true
Access to C:\Users\svcgu\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32s2-elf\bin: true
Access to C:\Users\svcgu\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32s3-elf\bin: true
Access to C:\Users\svcgu\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch2-8.4.0\riscv32-esp-elf\bin: true
Access to C:\Users\svcgu\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin: true
Access to C:\Users\svcgu\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin: true
Access to C:\Users\svcgu\.espressif\tools\cmake\3.20.3\bin: true
Access to C:\Users\svcgu\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin: true
Access to C:\Users\svcgu\.espressif\tools\ninja\1.10.2: true
Access to C:\Users\svcgu\.espressif\tools\idf-exe\1.0.3: true
Access to C:\Users\svcgu\.espressif\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to C:\Users\svcgu\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 4.4
Python version 3.8.7
Python's pip version 20.3.3
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 3.1.9
Brotli version: 1.0.9
certifi version: 2021.10.8
cffi version: 1.15.0
charset-normalizer version: 2.0.12
click version: 8.0.4
colorama version: 0.4.4
construct version: 2.10.54
contextlib2 version: 21.6.0
cryptography version: 36.0.1
ecdsa version: 0.17.0
esp-windows-curses version: 0.1
Flask version: 0.12.5
Flask-Compress version: 1.11
Flask-SocketIO version: 2.9.6
future version: 0.18.2
gcovr version: 5.0
gdbgui version: 0.13.2.0
gevent version: 1.5.0
greenlet version: 1.1.2
idf-component-manager version: 1.0.1
idna version: 3.3
itsdangerous version: 2.1.0
Jinja2 version: 3.0.3
kconfiglib version: 13.7.1
lxml version: 4.8.0
MarkupSafe version: 2.1.0
pip version: 20.3.3
psutil version: 5.9.0
pycparser version: 2.21
pyelftools version: 0.28
pygdbmi version: 0.9.0.2
Pygments version: 2.11.2
pyparsing version: 2.3.1
pyserial version: 3.5
python-engineio version: 3.14.2
python-socketio version: 4.6.1
pywin32 version: 303
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.27.1
requests-toolbelt version: 0.9.1
schema version: 0.7.5
semantic-version version: 2.9.0
setuptools version: 60.9.3
six version: 1.16.0
tqdm version: 4.63.0
urllib3 version: 1.26.8
websocket-client version: 1.3.1
Werkzeug version: 0.16.1
wheel version: 0.36.2
windows-curses version: 2.3.0
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements from C:\Users\svcgu\esp\esp-idf\requirements.txt are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements from c:\Users\svcgu\.vscode\extensions\espressif.esp-idf-extension-1.4.0\requirements.txt are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements from c:\Users\svcgu\.vscode\extensions\espressif.esp-idf-extension-1.4.0\esp_debug_adapter\requirements.txt are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "C:\\Users\\svcgu\\.espressif\\tools\\xtensa-esp32s2-elf\\esp-2021r2-patch2-8.4.0\\xtensa-esp32s2-elf\\bin\\xtensa-esp32s2-elf-gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
} 
--------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by svcguy** [comment] 2022-03-04 04:38
Just noticed that the above set of dependencies will never resolve due to LVGL.  But the issue with the ```lvgl_esp32_drivers==0.0.4``` is the actual issue.  Revert that to ```lvgl_esp32_drivers==0.0.3``` and it will resolve
```Processing 7 dependencies:
[1/7] espressif/button (2.0.0)
[2/7] espressif/es8311 (1.0.0)
[3/7] espressif/esp32_s2_kaluga_kit (0.0.3)
[4/7] espressif/led_strip (1.1.0-alpha)
[5/7] idf (4.4.0)
[6/7] lvgl/lvgl (7.11.0)
[7/7] lvgl/lvgl_esp32_drivers (0.0.3)```

**Comment by kumekay** [comment] 2022-03-04 09:48
Hello @svcguy
Thank you 
Could you please also share the full content of your `idf_component.yml` file for `main` where you have the problem (and for other components in the `components` directory if you have any)?

**Comment by tore-espressif** [comment] 2022-03-04 13:56
@svcguy thank you for reporting.

Board Support Package (BSP) for Kaluga kit (both version 0.0.3 and 0.0.4) was one of our first trials with BSPs, so it uses already obsolete https://components.espressif.com/component/lvgl/lvgl_esp32_drivers, this package supports only LVGL v7. So when you define dependency on LVGL v8.2.0 it can't be resolved.

I'll update espressif/esp32_s2_kaluga_kit for LVGL v8 soon

**Comment by igrr** [comment] 2022-03-04 16:37
Just my 2c, it would be excellent if the error message reported by the component manager pointed at the root cause of this issue (`lvgl` incompatibility). Although I understand that version solving is a complex problem, so maybe it is too optimistic to require this...

**Comment by svcguy** [comment] 2022-03-04 17:49
Correct.  I realized that after posting.  The version of LVGL isn’t important to me right now.  Even removing LVGL as a dependency, it still fails (LVGL as a dependency isn’t necessary anyway since lvgl_esp32_drivers will pull LVGL in).  The issue is actually the es8311 dependency and I think the root issue is with the use of the ^ and ~ version specifiers.  It’s the only difference between the 0.0.3 and 0.0.4 versions.

And an update to LVGL v8 would be wonderful, thank you so much.  I’ll wait patiently :)

Sent from Mail for Windows

**Comment by kumekay** [comment] 2022-03-07 19:02
@svcguy Thank you for the issue, yes there is an with the solver and pre-release dependencies like `0.0.2-alpha`, we will check it

**Comment by kumekay** [comment] 2022-03-23 16:09
@svcguy The issue with caret was fixed in this commit https://github.com/espressif/idf-component-manager/commit/bede7f34e5cb329a2b7513252bba68173b0d36a0 however the package is not published on PyPI yet. 

If you want to try it now, you can install it into your ESP-IDF virtual env by running this command after export.ps1:

```
pip install git+https://github.com/espressif/idf-component-manager.git --upgrade

```

**Comment by Alvin1Zhang** [comment] 2022-04-19 09:10
Thanks for reporting, feel free to reopen.

**Closed by Alvin1Zhang** 2022-04-19 09:10 UTC
Labels: Status: Done, Resolution: Done
