### ISSUE TITLE
HTTP server problem (IDFGH-3874)

### ISSUE THREAD

**Issue by benas1989** [espressif/esp-idf#5775] opened 2020-08-22 08:24 UTC
## Environment

Development Kit:ESP32-Wrover-Kit
Kit version DevKitC
Module or chip used:ESP32-WROVER-B
IDF version: 4.2
Build System: idf.py
Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2020r2) 8.2.0
Operating System: macOS
Using an IDE?: Visual studio code
Power Supply: USB

## Problem Description

I am trying to create http server with websocket. I created a few endpoints. One for websocket connection and other to test HTTP GET POST requests.
But when I try to make GET or POST request it open new socket and does not close it. 
I have a limited amount of socket connections and and that is the problem.

### Expected Behavior
GET, POST request do not open new socket.

### Steps to reproduce

1. Create http server and add some endpoint (you can copy from my example)
2. Add callback functions
```CPP
        httpd_config_t config = HTTPD_DEFAULT_CONFIG();
        config.uri_match_fn = httpd_uri_match_wildcard;
        config.open_fn = on_open_socket;
        config.close_fn = on_close_socket;
```
```cpp
esp_err_t on_open_socket(httpd_handle_t hd, int sockfd)
{
    clients++;
    ESP_LOGI(TAG, "socket opened: %d", sockfd);
    ESP_LOGI(TAG, "Clients: %d", clients);
    return ESP_OK;
}

void on_close_socket(httpd_handle_t hd, int sockfd)
{
    ESP_LOGE(TAG, "socket closed: %d", sockfd);
    if (clients > 0)
    {
       clients--;
    }
    
    ESP_LOGE(TAG, "Clients: %d", clients);
}
```
3. Use postman to make request.

Here i make one GET request to endpoint '/'
```cpp
I (3022) WS HTTP SERVER: Server started.
I (15732) WS HTTP SERVER: socket opened: 57
I (15732) WS HTTP SERVER: Clients: 1
I (15732) WS HTTP SERVER: URL: /
```

### Code to reproduce this issue
https://gist.github.com/benas1989/6780d76f88d8d316b994996bc3b87f4b

**Comment by benas1989** [comment] 2020-09-08 12:18
Can anyone help?
Now i add httpd_sess_trigger_close function after sending data. But when i try load page from android phone
seems to work but somehow when it finishes loading the page opens 2 sockets and does not close them.


```cpp
I (2633) HTTP: Starting server on port: '80'
I (2633) HTTP: Registering URI handlers
I (2643) HTTP: Initializing spiffs
I (3033) HTTP: Server started.
I (7783) HTTP: New socket opened 51. Clients: 1
D (7783) HTTP: GET URL: /
I (7803) HTTP: Socket closed 51. Clients: 0
I (8513) HTTP: New socket opened 51. Clients: 1
D (8513) HTTP: GET URL: /style.css
I (8583) HTTP: New socket opened 52. Clients: 2
I (8583) HTTP: Socket closed 51. Clients: 1
D (8593) HTTP: GET URL: /index.js
I (8793) HTTP: Socket closed 52. Clients: 0
I (9023) HTTP: New socket opened 51. Clients: 1
I (9033) HTTP: New socket opened 52. Clients: 2
```

**Comment by shubhamkulkarni97** [comment] 2020-09-10 08:13
Hi @benas1989,

By default `lru_purge_enable` is set to false in `httpd_config_t`.
You can try enabling lru_purge by adding following line in http_server configuration:
```
config.lru_purge_enable = true;
```

When this option is enabled and no socket is available for new connection, `esp_http_server` will purge/close least recently used socket.

I think this will help in your use case.

Thanks,
Shubham

**Comment by benas1989** [comment] 2020-09-10 12:38
Thanks for the reply. I use websockets and don’t want to break all connections. Now I added one task to close socket if 5s timeout is reached and  if it is not a websocket connection.
https://gist.github.com/benas1989/cb455f3195d9fdd499d4e866b97cc9c7

After the change I wonder if this is the normal time it takes for the website to load? It takes about 500ms as you can see in the photo.

<img width="1052" alt="Screenshot 2020-09-10 at 15 21 52" src="https://user-images.githubusercontent.com/6152093/92729045-68523880-f37a-11ea-8bfc-4a849a510d93.png">

**Comment by benas1989** [comment] 2020-09-11 12:49
Ok :) Now i try Mongoose OS http server. He is very fast. Why is the esp-idf http server so slow?
<img width="706" alt="Screenshot 2020-09-11 at 15 46 41" src="https://user-images.githubusercontent.com/6152093/92927282-0b23b900-f446-11ea-9e81-f027d31c7b82.png">

**Comment by shubhamkulkarni97** [comment] 2020-09-17 11:01
To improve throughput, you can try changing some configurations in menuconfig as below:
```
 CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=16
 CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=64
 CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM=64
 CONFIG_ESP32_WIFI_TX_BA_WIN=32
 CONFIG_ESP32_WIFI_RX_BA_WIN=32
 CONFIG_LWIP_TCP_SND_BUF_DEFAULT=65534
 CONFIG_LWIP_TCP_WND_DEFAULT=65534
 CONFIG_LWIP_TCP_RECVMBOX_SIZE=64
 CONFIG_LWIP_UDP_RECVMBOX_SIZE=64
 CONFIG_LWIP_TCPIP_RECVMBOX_SIZE=64
```

Please note that these changes will also increase memory consumption.

**Comment by shubhamkulkarni97** [comment] 2020-10-01 09:25
@benas1989 Is your issue resolved?

**Comment by benas1989** [comment] 2020-10-04 14:37
I have changed, but nothing has changed since then. Only more memory is used :(

**Comment by Lisa999** [comment] 2020-11-30 18:27
I have the same issue, sockets are closed AFTER 150 seconds! So it's running out of sockets when doing concurrent requests, leading to these errors: 

> httpd_accept_conn: error in accept (23)

**Comment by lhespress** [comment] 2020-12-03 06:51
@benas1989 @Lisa999 

I think the reason is that the browser or Postman working in KeepAlive mode.

* The KeepAlive mode is used to keep client connect with server valid for long time to save the overhead of establishing/releasing connections.
* The non-Keepalive mode, each request/response client and server creates a new connection and disconnects immediately after completion.
* The KeepAlive is enabled by default in HTTP 1.1, you can add **"Connection: Close "** to your desired endpoint, so that each established connection is closed after completion.
* The Keep Alive is disabled by default in HTTP 1.0, you can add **”Connection: keep-alive “** to your desired endpoint, so that each connection will valid for long time.

You can reference the code as follows which copy from **esp-idf/examples/protocols/http_server/simple**:
```
/* An HTTP GET handler */
static esp_err_t hello_get_handler(httpd_req_t *req)
{
    char*  buf;
    size_t buf_len;

    /* Get header value string length and allocate memory for length + 1,
     * extra byte for null termination */
    buf_len = httpd_req_get_hdr_value_len(req, "Host") + 1;
    if (buf_len > 1) {
        buf = malloc(buf_len);
        /* Copy null terminated value string into buffer */
        if (httpd_req_get_hdr_value_str(req, "Host", buf, buf_len) == ESP_OK) {
            ESP_LOGI(TAG, "Found header => Host: %s", buf);
        }
        free(buf);
    }

    buf_len = httpd_req_get_hdr_value_len(req, "Test-Header-2") + 1;
    if (buf_len > 1) {
        buf = malloc(buf_len);
        if (httpd_req_get_hdr_value_str(req, "Test-Header-2", buf, buf_len) == ESP_OK) {
            ESP_LOGI(TAG, "Found header => Test-Header-2: %s", buf);
        }
        free(buf);
    }

    buf_len = httpd_req_get_hdr_value_len(req, "Test-Header-1") + 1;
    if (buf_len > 1) {
        buf = malloc(buf_len);
        if (httpd_req_get_hdr_value_str(req, "Test-Header-1", buf, buf_len) == ESP_OK) {
            ESP_LOGI(TAG, "Found header => Test-Header-1: %s", buf);
        }
        free(buf);
    }

    /* Read URL query string length and allocate memory for length + 1,
     * extra byte for null termination */
    buf_len = httpd_req_get_url_query_len(req) + 1;
    if (buf_len > 1) {
        buf = malloc(buf_len);
        if (httpd_req_get_url_query_str(req, buf, buf_len) == ESP_OK) {
            ESP_LOGI(TAG, "Found URL query => %s", buf);
            char param[32];
            /* Get value of expected key from query string */
            if (httpd_query_key_value(buf, "query1", param, sizeof(param)) == ESP_OK) {
                ESP_LOGI(TAG, "Found URL query parameter => query1=%s", param);
            }
            if (httpd_query_key_value(buf, "query3", param, sizeof(param)) == ESP_OK) {
                ESP_LOGI(TAG, "Found URL query parameter => query3=%s", param);
            }
            if (httpd_query_key_value(buf, "query2", param, sizeof(param)) == ESP_OK) {
                ESP_LOGI(TAG, "Found URL query parameter => query2=%s", param);
            }
        }
        free(buf);
    }

    /* Set some custom headers */
   httpd_resp_set_hdr(req, "Connection", "close");
   httpd_resp_set_hdr(req, "Connection", "Keep-Alive");

    /* Send response with custom headers and body set as the
     * string passed in user context*/
    const char* resp_str = (const char*) req->user_ctx;
    httpd_resp_send(req, resp_str, HTTPD_RESP_USE_STRLEN);

    /* After sending the HTTP response the old HTTP request
     * headers are lost. Check if HTTP request headers can be read now. */
    if (httpd_req_get_hdr_value_len(req, "Host") == 0) {
        ESP_LOGI(TAG, "Request headers lost");
    }
    return ESP_OK;
}

static const httpd_uri_t hello = {
    .uri       = "/hello",
    .method    = HTTP_GET,
    .handler   = hello_get_handler,
    /* Let's pass response string in user
     * context to demonstrate it's usage */
    .user_ctx  = "Hello World!"
};
```

**Comment by Lisa999** [comment] 2020-12-03 10:11
I've found a work-around, the problem is **not** on the browser side. Even closing the client browser still keeps the **server** socket occupied for about 150 seconds before releasing the socket.
The connection close isn't working because the client is closing the connection, but the server is not releasing the socket immediately so the server is running out of sockets fast.

The work-around:
`    httpd_resp_send(req, NULL, 0);
    httpd_sess_trigger_close(req->handle, httpd_req_to_sockfd(req));
`

**Comment by lhespress** [comment] 2020-12-03 11:30
@Lisa999 

I'm sorry for didn't describe it clearly. The reason is enable HTTP KeepAlive on the connection. It'll close the connection after completion when disable HTTP KeepAlive.

Disable HTTP KeepAlive:
```
httpd_resp_set_hdr(req, "Connection", "close");
```
Enable HTTP KeepAlive:
```
httpd_resp_set_hdr(req, "Connection", "Keep-Alive");
```

**Comment by Lisa999** [comment] 2020-12-03 12:45
I've tried this:
httpd_resp_set_hdr(req, "Connection", "close");
Didn't work. :-)

**Comment by boarchuz** [comment] 2020-12-03 13:17
Try returning ESP_FAIL from hello_get_handler. The server will close the connection if you return anything other than ESP_OK.

**Comment by Lisa999** [comment] 2020-12-03 16:13
My mistake! Connection close is working **IF** you put it **before** the send command:
httpd_resp_set_hdr(req, "Connection", "close");
httpd_resp_send(req, config, HTTPD_RESP_USE_STRLEN);

**Comment by HikerPan** [comment] 2020-12-16 03:43
Hello,
I meet the same problem.
Andy i try below config.
1. config.lru_purge_enable = true;
2. httpd_resp_set_hdr(req, "Connection", "close");
3. httpd_sess_trigger_close(req->handle, httpd_req_to_sockfd(req));
It works.
The most important is the lru_purge_enable.
Thanks All.

**Comment by lhespress** [comment] 2020-12-16 06:01
@Lisa999 @HikerPan If the issue has been fixed, could you close it? Thanks.

**Comment by Lisa999** [comment] 2020-12-16 19:48
I didn't open the issue, so i can't close it...

**Comment by Alvin1Zhang** [comment] 2020-12-17 01:48
@Lisa999 Thanks for the updates, currently we have a fix which is under internal reviewing, the issue will close automatically once the fix is available on GitHub. Thanks.

**Closed** 2020-12-31 11:31 UTC
