### ISSUE TITLE
esp.emac: no mem for receive buffer (IDFGH-8093)

### ISSUE THREAD

**Issue by SERIDJ** [espressif/esp-idf#9594] opened 2022-08-19 14:43 UTC

**Comment by king1688** [comment] 2022-08-22 19:50
I have the same problem when I complie and run the example under /ethernet/eth2ap examples code. if you got a solution, please let me know, thank you

**Comment by kostaond** [comment] 2022-09-01 06:30
Duplicate of #9308

**Closed** 2022-09-01 06:31 UTC
Labels: Status: Opened

**Comment by thiagohd** [comment] 2022-09-30 21:36
Same problem here.

**Comment by kostaond** [comment] 2022-10-31 11:28
Could you please check if [this WIP update](https://github.com/kostaond/esp-idf/tree/feature/emac_buff_optimization) helped to resolve your issue?
