### ISSUE TITLE
official esp_https_server dont work (IDFGH-13824)

### ISSUE THREAD

**Issue by sova32** [espressif/esp-idf#14675] opened 2024-10-05 16:07 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.4.0

### Espressif SoC revision.

Chip is ESP32-S3 (QFN56) (revision v0.2)

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

Waveshare esp32-S3-Pico

### Power Supply used.

USB

### What is the expected behavior?

worked example !!!
https://github.com/espressif/esp-idf/tree/v5.3.1/examples/protocols/https_server/simple

### What is the actual behavior?

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x2b (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce2810,len:0x1874
load:0x403c8700,len:0x4
load:0x403c8704,len:0xd20
load:0x403cb700,len:0x2ea4
entry 0x403c8928
I (27) boot: ESP-IDF v5.4-dev-3201-g46acfdce96 2nd stage bootloader
I (27) boot: compile time Sep 29 2024 19:09:38
I (27) boot: Multicore bootloader
I (32) boot: chip revision: v0.2
I (35) boot: efuse block revision: v1.3
I (40) boot.esp32s3: Boot SPI Speed : 80MHz
I (45) boot.esp32s3: SPI Mode       : DIO
I (49) boot.esp32s3: SPI Flash Size : 16MB
I (54) boot: Enabling RNG early entropy source...
I (60) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (78) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (93) boot:  3 factory          factory app      00 00 00010000 00200000
I (100) boot:  4 ota_0            OTA app          00 10 00210000 00200000
I (108) boot:  5 ota_1            OTA app          00 10 00410000 00200000
I (115) boot:  6 nvs_key          NVS keys         01 04 00610000 00001000
I (123) boot:  7 littleFS_ROOT    Unknown data     01 82 00611000 00100000
I (131) boot: End of partition table
I (135) boot: Defaulting to factory image
I (140) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=26c28h (158760) map
I (176) esp_image: segment 1: paddr=00036c50 vaddr=3fc99900 size=049e0h ( 18912) load
I (180) esp_image: segment 2: paddr=0003b638 vaddr=40374000 size=049e0h ( 18912) load
I (186) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=997b4h (628660) map
I (301) esp_image: segment 4: paddr=000d97dc vaddr=403789e0 size=10e38h ( 69176) load
I (321) esp_image: segment 5: paddr=000ea61c vaddr=600fe100 size=00018h (    24) load
I (330) boot: Loaded app from partition at offset 0x10000
I (330) boot: Disabling RNG early entropy source...
I (342) cpu_start: Multicore app
I (351) cpu_start: Pro cpu start user code
I (351) cpu_start: cpu freq: 160000000 Hz
I (352) app_init: Application information:
I (354) app_init: Project name:     filamentor_v2
I (360) app_init: App version:      1
I (364) app_init: Compile time:     Oct  5 2024 18:23:59
I (370) app_init: ELF file SHA256:  66d4994f4...
I (375) app_init: ESP-IDF:          v5.4-dev-3201-g46acfdce96
I (382) efuse_init: Min chip rev:     v0.0
I (387) efuse_init: Max chip rev:     v0.99 
I (392) efuse_init: Chip rev:         v0.2
I (396) heap_init: Initializing. RAM available for dynamic allocation:
I (404) heap_init: At 3FCA2058 len 000476B8 (285 KiB): RAM
I (410) heap_init: At 3FCE9710 len 00005724 (21 KiB): RAM
I (416) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (422) heap_init: At 600FE118 len 00001ED0 (7 KiB): RTCRAM
I (429) spi_flash: detected chip: winbond
I (433) spi_flash: flash io: dio
I (437) sleep_gpio: Configure to isolate all GPIO pins in sleep state
I (444) sleep_gpio: Enable automatic switching of GPIO sleep configuration
I (452) main_task: Started on CPU0
I (482) main_task: Calling app_main()
I (502) example_connect: Start example_connect.
I (502) pp: pp rom version: e7ae62f
I (502) net80211: net80211 rom version: e7ae62f
I (512) wifi:wifi driver task: 3fcac15c, prio:23, stack:6656, core=0
I (522) wifi:wifi firmware version: 643903f
I (522) wifi:wifi certification version: v7.0
I (522) wifi:config NVS flash: enabled
I (522) wifi:config nano formatting: disabled
I (532) wifi:Init data frame dynamic rx buffer num: 32
I (532) wifi:Init static rx mgmt buffer num: 5
I (532) wifi:Init management short buffer num: 32
I (542) wifi:Init dynamic tx buffer num: 32
I (542) wifi:Init static tx FG buffer num: 2
I (552) wifi:Init static rx buffer size: 1600
I (552) wifi:Init static rx buffer num: 10
I (552) wifi:Init dynamic rx buffer num: 32
I (562) wifi_init: rx ba win: 6
I (562) wifi_init: accept mbox: 6
I (572) wifi_init: tcpip mbox: 32
I (572) wifi_init: udp mbox: 6
I (572) wifi_init: tcp mbox: 6
I (582) wifi_init: tcp tx win: 5760
I (582) wifi_init: tcp rx win: 5760
I (592) wifi_init: tcp mss: 1440
I (592) wifi_init: WiFi IRAM OP enabled
I (592) wifi_init: WiFi RX IRAM OP enabled
I (602) phy_init: phy_version 680,a6008b2,Jun  4 2024,16:41:10
I (642) wifi:mode : sta (3c:84:27:e4:ec:40)
I (642) wifi:enable tsf
I (652) example_connect: Connecting to TP-LINK_720E...
W (652) wifi:Password length matches WPA2 standards, authmode threshold changes from OPEN to WPA2
I (652) example_connect: Waiting for IP(s)
I (3502) wifi:new:<10,2>, old:<1,0>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (3512) wifi:state: init -> auth (0xb0)
I (3512) wifi:state: auth -> assoc (0x0)
I (3522) wifi:state: assoc -> run (0x10)
I (6532) wifi:state: run -> init (0xf00)
I (6532) wifi:new:<10,0>, old:<10,2>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (6532) example_connect: Wi-Fi disconnected 15, trying to reconnect...
I (8952) example_connect: Wi-Fi disconnected 205, trying to reconnect...
I (11362) wifi:new:<10,2>, old:<10,0>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (11362) wifi:state: init -> auth (0xb0)
I (11362) wifi:state: auth -> assoc (0x0)
I (11372) wifi:state: assoc -> run (0x10)
I (14382) wifi:state: run -> init (0xf00)
I (14382) wifi:new:<10,0>, old:<10,2>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (14382) example_connect: Wi-Fi disconnected 15, trying to reconnect...
I (16792) example_connect: Wi-Fi disconnected 205, trying to reconnect...
I (19202) wifi:new:<10,2>, old:<10,0>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (19202) wifi:state: init -> auth (0xb0)
I (19212) wifi:state: auth -> assoc (0x0)
I (19212) wifi:state: assoc -> run (0x10)
I (22222) wifi:state: run -> init (0xf00)
I (22232) wifi:new:<10,0>, old:<10,2>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (22232) example_connect: Wi-Fi disconnected 15, trying to reconnect...
I (24642) example_connect: Wi-Fi disconnected 205, trying to reconnect...
I (27052) wifi:new:<10,2>, old:<10,0>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (27052) wifi:state: init -> auth (0xb0)
I (27062) wifi:state: auth -> assoc (0x0)
I (27062) wifi:state: assoc -> run (0x10)
I (30072) wifi:state: run -> init (0xf00)
I (30072) wifi:new:<10,0>, old:<10,2>, ap:<255,255>, sta:<10,2>, prof:1, snd_ch_cfg:0x0
I (30082) example_connect: WiFi Connect failed 7 times, stop reconnect.

assert failed: spinlock_acquire spinlock.h:142 (lock->count == 0)

Backtrace: 0x40375bd9:0x3fca5a50 0x4037c591:0x3fca5a70 0x4038480d:0x3fca5a90 0x4037d2b2:0x3fca5bb0 0x4037ce60:0x3fca5be0 0x4200b965:0x3fca5c20 0x4200bb80:0x3fca5c40 0x4200b3c7:0x3fca5de0 0x4200b1cd:0x3fca5e00 0x42098a0f:0x3fca5e20 0x4037d029:0x3fca5e50
--- 0x40375bd9: panic_abort at /home/vadiki/esp/esp-idf/components/esp_system/panic.c:454
0x4037c591: esp_system_abort at /home/vadiki/esp/esp-idf/components/esp_system/port/esp_system_chip.c:92
0x4038480d: __assert_func at /home/vadiki/esp/esp-idf/components/newlib/assert.c:80
0x4037d2b2: spinlock_acquire at /home/vadiki/esp/esp-idf/components/esp_hw_support/include/spinlock.h:142 (discriminator 1)
 (inlined by) xPortEnterCriticalTimeout at /home/vadiki/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:474 (discriminator 1)
0x4037ce60: vPortEnterCritical at /home/vadiki/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include/freertos/portmacro.h:567
 (inlined by) xQueueSemaphoreTake at /home/vadiki/esp/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1727
0x4200b965: example_wifi_sta_do_connect at /home/vadiki/esp/esp-idf/examples/common_components/protocol_examples_common/wifi_connect.c:174
0x4200bb80: example_wifi_connect at /home/vadiki/esp/esp-idf/examples/common_components/protocol_examples_common/wifi_connect.c:247
0x4200b3c7: example_connect at /home/vadiki/esp/esp-idf/examples/common_components/protocol_examples_common/connect.c:99
0x4200b1cd: app_main at /run/media/vadiki/250_GB_ST_1GB/projects/filamentor_v2/program/filamentor_v2/main/main.c:231
0x42098a0f: main_task at /home/vadiki/esp/esp-idf/components/freertos/app_startup.c:208
0x4037d029: vPortTaskWrapper at /home/vadiki/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134

ELF file SHA256: 66d4994f4

Rebooting...
���ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)
Saved PC:0x40375b18
--- 0x40375b18: esp_restart_noos at /home/vadiki/esp/esp-idf/components/esp_system/port/soc/esp32s3/system_internal.c:160

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce2810,len:0x1874
load:0x403c8700,len:0x4
load:0x403c8704,len:0xd20
load:0x403cb700,len:0x2ea4
entry 0x403c8928

### Steps to reproduce.

1. clone your official example
2. bulid and flash

**Comment by nileshkale123** [comment] 2024-10-07 08:06
Hello @sova32,

I attempted to reproduce the issue but did not encounter any errors during execution.

I recommend reviewing the relevant README file and ensuring that the Wi-Fi credentials match the ones configured on the system you're using to connect to the server.

Please feel free to reach out if the issue persists or if you need further assistance.

**Comment by nileshkale123** [comment] 2024-10-15 11:30
Hello @sova32 

Since we couldn't reproduce this issue on our end, I'm going to go ahead and close it.  If anything changes or new details pop up, feel free to reopen it!

**Closed by nileshkale123** 2024-10-15 11:30 UTC
Labels: Type: Bug, Status: Opened

**Comment by freddy916** [comment] 2025-05-13 09:38
I faced the same issue with the same error code. I faced this when my router went offline and ESP32 tried to reconnect 6 times. When it reconnects fails, it keeps restarting, and the same happens until it connects successfully.
