### ISSUE TITLE
BROWNOUTs reboot esp32c6 (IDFGH-9671)

### ISSUE THREAD

**Issue by RuslanSpartak** [espressif/esp-idf#11012] opened 2023-03-17 08:38 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

master

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32c6 module

### Power Supply used.

External 3.3V

### What is the expected behavior?

In sdkconfig I disable brownout detection. But I still see that  esp32c6 core still reboots because of brownout detection.

### What is the actual behavior?

Brownout reboot.

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by kayzen9** [comment] 2023-03-23 14:39
Same https://github.com/espressif/esp-idf/issues/11013 ??

**Comment by mahavirj** [comment] 2023-04-17 04:15
Duplicate of https://github.com/espressif/esp-idf/issues/11013, closing

**Closed by mahavirj** 2023-04-17 04:15 UTC
Labels: Type: Bug, Status: Opened
