### ISSUE TITLE
E (22) wifi: wifi_init_in_caller_task 712 ret=4353 (IDFGH-1172)

### ISSUE THREAD

**Issue by isharaux** [espressif/esp-idf#3485] opened 2019-05-16 05:31 UTC
Cant connect to WiFi using default arduino library #include <WiFi.h>
following error results...

`E (22) wifi: wifi_init_in_caller_task 712 ret=4353`

**Comment by liuzfesp** [comment] 2019-05-22 08:37
Hi @isharaux could you help to provide following info:

- IDF commit ID
- Steps to reproduce this issue

**Comment by liuzfesp** [comment] 2019-05-24 02:05
Hi @espxiehang please help.

**Comment by Alvin1Zhang** [comment] 2019-07-16 07:44
@isharaux Thanks for reporting the issue, will close the issue for now due to not enough details and little feedback. Feel free to reopen if your issue still happens. Thanks.

**Closed by Alvin1Zhang** 2019-07-16 07:44 UTC
