### ISSUE TITLE
Esp32 failed to send one to many using espnow protocol (IDFGH-7414)

### ISSUE THREAD

**Issue by xiezhoubin** [espressif/esp-idf#8992] opened 2022-05-18 15:31 UTC
### Board

ESP32

### Device Description

ESP32 Dev Module

### Hardware Configuration

none

### Version

v2.0.3

### IDE Name

arduino+vscode

### Operating System

win11

### Flash frequency

80

### PSRAM enabled

no

### Upload speed

921600

### Description

https://randomnerdtutorials.com/esp-now-one-to-many-esp32-esp8266/

![image](https://user-images.githubusercontent.com/75734559/169081586-afe0d6bf-431a-4df7-a70c-0e622cea8ede.png)

![image](https://user-images.githubusercontent.com/75734559/169081985-ae813289-3be1-4b6d-a18d-d53269a67f01.png)

![image](https://user-images.githubusercontent.com/75734559/169082111-05742020-7717-4879-accc-597708de68da.png)

### Sketch

```cpp
/*********
  Rui Santos
  Complete project details at https://RandomNerdTutorials.com/esp-now-one-to-many-esp32-esp8266/
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files.
  
  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
*********/

#include <esp_now.h>
#include <WiFi.h>

// REPLACE WITH YOUR ESP RECEIVER'S MAC ADDRESS
uint8_t broadcastAddress1[] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
uint8_t broadcastAddress2[] = {0xFF, , , , , };
uint8_t broadcastAddress3[] = {0xFF, , , , , };

typedef struct test_struct {
  int x;
  int y;
} test_struct;

test_struct test;

esp_now_peer_info_t peerInfo;

// callback when data is sent
void OnDataSent(const uint8_t *mac_addr, esp_now_send_status_t status) {
  char macStr[18];
  Serial.print("Packet to: ");
  // Copies the sender mac address to a string
  snprintf(macStr, sizeof(macStr), "%02x:%02x:%02x:%02x:%02x:%02x",
           mac_addr[0], mac_addr[1], mac_addr[2], mac_addr[3], mac_addr[4], mac_addr[5]);
  Serial.print(macStr);
  Serial.print(" send status:\t");
  Serial.println(status == ESP_NOW_SEND_SUCCESS ? "Delivery Success" : "Delivery Fail");
}
 
void setup() {
  Serial.begin(115200);
 
  WiFi.mode(WIFI_STA);
 
  if (esp_now_init() != ESP_OK) {
    Serial.println("Error initializing ESP-NOW");
    return;
  }
  
  esp_now_register_send_cb(OnDataSent);
   
  // register peer
  peerInfo.channel = 0;  
  peerInfo.encrypt = false;
  // register first peer  
  memcpy(peerInfo.peer_addr, broadcastAddress1, 6);
  if (esp_now_add_peer(&peerInfo) != ESP_OK){
    Serial.println("Failed to add peer");
    return;
  }
  // register second peer  
  memcpy(peerInfo.peer_addr, broadcastAddress2, 6);
  if (esp_now_add_peer(&peerInfo) != ESP_OK){
    Serial.println("Failed to add peer");
    return;
  }
  /// register third peer
  memcpy(peerInfo.peer_addr, broadcastAddress3, 6);
  if (esp_now_add_peer(&peerInfo) != ESP_OK){
    Serial.println("Failed to add peer");
    return;
  }
}
 
void loop() {
  test.x = random(0,20);
  test.y = random(0,20);
 
  esp_err_t result = esp_now_send(0, (uint8_t *) &test, sizeof(test_struct));
   
  if (result == ESP_OK) {
    Serial.println("Sent with success");
  }
  else {
    Serial.println("Error sending the data");
  }
  delay(2000);
}
```

### Debug Message

```plain
1
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by Alvin1Zhang** [comment] 2022-05-20 01:21
Seems this is duplicate of https://github.com/espressif/esp-idf/issues/8988, will close https://github.com/espressif/esp-idf/issues/8988 and track in this one. Thanks.

**Comment by zhangyanjiaoesp** [comment] 2022-06-01 08:20
@xiezhoubin I have tested with IDF v4.4.1 locally, ESP32 can send one two many using espnow protocol. 
The error `ESP_ERR_ESPNOW_INTERNAL` show that sending is fail, you can check whether your mac address is correct, or whether your ESP devices are in the same channel.

**Comment by xiezhoubin** [comment] 2022-06-01 08:26
> @xiezhoubin I have tested with IDF v4.4.1 locally, ESP32 can send one two many using espnow protocol. The error `ESP_ERR_ESPNOW_INTERNAL` show that sending is fail, you can check whether your mac address is correct, or whether your ESP devices are in the same channel.

I have checked it and there is no problem. The above Arduino sample code is used. I tried the same code. The package in version 1.0.6 can run normally, and the package in versions 2.0.1, 2.0.2 and 2.0.3 will report errors.

**Comment by e0v1a** [comment] 2022-06-02 10:46
I also encountered the same problem, in the same channel, between two fixed paired devices, this error will appear from time to time, sometimes it will appear every time, sometimes it will swipe the screen crazy, but even in this The communication does not seem to be affected when the error is reported and the screen is swiped (I use him to transmit stateless data, so it does not affect the occasional loss of a few)
And the internal error is a very vague expression that does not give any guidance (such as what is this problem related to? Send frequency? Interrupt?), which makes it impossible for developers to try to solve the problem

**Comment by zhangyanjiaoesp** [comment] 2022-06-07 07:28
@e0v1a @xiezhoubin This issue has been solved in IDF branch 5d95cd58b210523e68fb37e0fe23cd0331ff2585, will update it to Arduino as soon as possible.

**Comment by zhangyanjiaoesp** [comment] 2022-07-12 02:38
@xiezhoubin Have you updated the branch and have a test again?

**Comment by xiezhoubin** [comment] 2022-07-12 02:44
> @xiezhoubin Have you updated the branch and have a test again?

Is it version 2.0.4?

**Comment by zhangyanjiaoesp** [comment] 2022-07-12 03:02
> > @xiezhoubin Have you updated the branch and have a test again?
> 
> Is it version 2.0.4?

yes, please check whether your problem has been solved.

**Comment by xiezhoubin** [comment] 2022-07-12 03:54
The same code in the new version is compilation error.

Version 1.0.6 is OK.
![image](https://user-images.githubusercontent.com/75734559/178404945-70c1d3d7-d076-4c35-a63b-8428f30da0d1.png)

Compilation error of version 2.0.4.
![image](https://user-images.githubusercontent.com/75734559/178405218-e4604b4a-d219-4462-83ad-cb159efd11e7.png)

**Comment by xiezhoubin** [comment] 2022-07-12 04:32
The problem of compilation error reporting has been solved. Using memcpy requires adding (void*). But after running the code, it can't run, and the serial port output reports an error. There is no problem with the same code in version 1.0.6.
![image](https://user-images.githubusercontent.com/75734559/178408845-eb7ae3cd-eaa8-4116-ad65-733e2881d28f.png)

**Comment by xiezhoubin** [comment] 2022-07-12 04:43
Still not, version 2.0.4, in one to many transmission, will only be sent to the first.
It is recommended to refer to the link test below.
https://randomnerdtutorials.com/esp-now-one-to-many-esp32-esp8266/

**Comment by Espressif-liuuuu** [comment] 2022-07-20 08:14
hi @xiezhoubin, please try to call `esp_now_set_wake_window(65535)` after `esp_now_init()` for all of your esp_now rx devices to see if it could solve your problem. Thanks:)

**Comment by e0v1a** [comment] 2022-07-21 06:50
> hi @xiezhoubin, please try to call `esp_now_set_wake_window(65535)` after `esp_now_init()` for all of your esp_now rx devices to see if it could solve your problem. Thanks:)

It doesn't work, in a master-multiple-slave case, the broadcast data is always only received by the first slave device

**Comment by zhangyanjiaoesp** [comment] 2022-07-21 11:01
I have reproduced the problem locally, and will resolve it ASAP.

**Comment by zhangyanjiaoesp** [comment] 2022-07-27 09:03
@xiezhoubin To solve the problem, please change the code `cfg.cache_tx_buf_num = 1` to `cfg.cache_tx_buf_num = 16`
https://github.com/espressif/arduino-esp32/blob/4b64cde1022975cc8d72c41c500abb3d072762cf/libraries/WiFi/src/WiFiGeneric.cpp#L671
or just delete the code 

> 	if(!WiFiGenericClass::useStaticBuffers()) {
	    cfg.static_tx_buf_num = 0;
            cfg.dynamic_tx_buf_num = 32;
	    cfg.tx_buf_type = 1;
            cfg.cache_tx_buf_num = 1;  // can't be zero!
	    cfg.static_rx_buf_num = 4;
            cfg.dynamic_rx_buf_num = 32;
        }


We will add this change to the office Arduino code ASAP.

**Comment by SuGlider** [comment] 2022-07-27 22:35
@zhangyanjiaoesp @xiezhoubin

All you need to do is:

```c++
 void setup() {
   Serial.begin(115200);

   WiFi.useStaticBuffers(true);  // it will keep sdkconfig default for cache and static TX buffers in WiFi
   WiFi.mode(WIFI_STA);
   
   // .... your code
```

**Comment by SuGlider** [comment] 2022-07-27 22:38
``` WiFi.useStaticBuffers(true);``` will force Arduino to use deafult sdkconfig WiFi setup:

```
CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=8
CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=32
CONFIG_ESP32_WIFI_STATIC_TX_BUFFER=y
CONFIG_ESP32_WIFI_TX_BUFFER_TYPE=0
CONFIG_ESP32_WIFI_STATIC_TX_BUFFER_NUM=8
CONFIG_ESP32_WIFI_CACHE_TX_BUFFER_NUM=16
```

**Comment by Alvin1Zhang** [comment] 2022-08-03 03:14
https://github.com/espressif/arduino-esp32/pull/7044 has been merged, feel free to reopen.

**Closed** 2022-08-03 03:14 UTC
Labels: Status: In Progress, Status: Awaiting triage, Area: Libraries

**Comment by lebossejames** [comment] 2023-03-05 18:50
Hello,

I have same issue with ESP32-C3 with 2.0.7 library.
Can you help me please?

**Comment by zhangyanjiaoesp** [comment] 2023-03-06 02:11
@lebossejames Please create a new Github issue to describle your problem in details, thanks.
