### ISSUE TITLE
OTA not working with DOIT board.

### ISSUE THREAD

**Issue by blmhemu** [espressif/esp-idf#772] opened 2017-07-05 07:39 UTC
OTA shows the following errors:
![screen shot 2017-07-03 at 5 39 49 pm](https://user-images.githubusercontent.com/19410501/27854127-240f9d16-6183-11e7-82c5-73e9558b1051.png)

**Comment by projectgus** [comment] 2017-07-05 08:19
Thanks for reporting this. I believe this is a duplicate of #578, so I'm going to close it in favour of that issue (which I noticed you also commented on.)

**Closed by projectgus** 2017-07-05 08:19 UTC
