### ISSUE TITLE
[TW#17222] Low Power Amplifier

### ISSUE THREAD

**Issue by hberjanin** [espressif/esp-idf#1427] opened 2017-12-23 11:07 UTC
Hello, 
I will like to know when will be available the low noise amplifier: example code and schematics. Thanks in advance

**Comment by ginkgm** [comment] 2017-12-27 02:47
we're working on this, but it seems to be long before release.

are you sure your signal is in the range of +/- 2mV?

**Comment by hberjanin** [comment] 2017-12-27 16:34
It is lower than that level. it should be in uVolts.

**Comment by ginkgm** [comment] 2017-12-28 04:41
okay, in that case LNA would help.

**Comment by igrr** [comment] 2018-01-08 09:27
Closing as duplicate of https://github.com/espressif/esp-idf/issues/814.

**Closed by igrr** 2018-01-08 09:27 UTC
