### ISSUE TITLE
[TW#13568] Calling mbedtls_x509_crt_free twice sometimes causes crash.

### ISSUE THREAD

**Issue by Curclamas** [espressif/esp-idf#723] opened 2017-06-21 11:38 UTC
I have seen this issue on multiple occasions, especially in some arduino libs it may happen that ```mbedtls_x509_crt_free``` gets called twice in a row. Since there are multiple null checks I don't get why that crash is happening. Also it only happens on really rarer occasions. All my HTTPS-related tasks run pinned to core 1.

Crash log:
```
Guru Meditation Error of type LoadProhibited occurred on core  1. Exception was unhandled.
Register dump:
PC      : 0x40159c5c  PS      : 0x00060b30  A0      : 0x8013b41d  A1      : 0x3ffd6710
A2      : 0x3ffbe85c  A3      : 0x00000001  A4      : 0x3ffbe85c  A5      : 0x3f4108ec
A6      : 0x00000001  A7      : 0x3ffb1df8  A8      : 0x80159c16  A9      : 0x3ffd66f0
A10     : 0x00000000  A11     : 0x40082660  A12     : 0x3f418508  A13     : 0x00001bb3
A14     : 0x3f418d80  A15     : 0xffffffaf  SAR     : 0x00000004  EXCCAUSE: 0x0000001c
EXCVADDR: 0x0000000d  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0x00000000

Backtrace: 0x40159c5c:0x3ffd6710 0x4013b41d:0x3ffd6730 0x4013b13c:0x3ffd6750 0x4013b14e:0x3ffd6770 0x4013b165:0x3ffd6790 0x40138d49:0x3ffd67b0 0x401394e1:0x3ffd67e0 0x40139586:0x3ffd6820 0x4011f33f:0x3ffd6840 0x4011f450:0x3ffd68b0 0x4011f4c8:0x3ffd68e0
```

that translates to:

```
mbedtls_x509_crt_free
/home/ubuntu/workspace/esp/esp-idf/components/mbedtls/library/x509_crt.c:2350
_Z15stop_ssl_socketP17sslclient_contextPKcS2_S2_
/home/ubuntu/workspace/esp/logger-firmware/components/arduino/libraries/WiFiClientSecure/src/ssl_client.cpp:208
_ZN16WiFiClientSecure4stopEv
/home/ubuntu/workspace/esp/logger-firmware/components/arduino/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:196
_ZN16WiFiClientSecureD2Ev
/home/ubuntu/workspace/esp/logger-firmware/components/arduino/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:196
_ZN16WiFiClientSecureD0Ev
/home/ubuntu/workspace/esp/logger-firmware/components/arduino/libraries/WiFiClientSecure/src/WiFiClientSecure.cpp:196
_ZNSt10unique_ptrI10WiFiClientSt14default_deleteIS0_EED4Ev
/home/ubuntu/workspace/esp/logger-firmware/components/arduino/libraries/HTTPClient/src/HTTPClient.cpp:308
_ZN10HTTPClient11sendRequestEPKcPhj
/home/ubuntu/workspace/esp/logger-firmware/components/arduino/libraries/HTTPClient/src/HTTPClient.cpp:308
_ZN10HTTPClient3GETEv
/home/ubuntu/workspace/esp/logger-firmware/components/arduino/libraries/HTTPClient/src/HTTPClient.cpp:308
```

This is the particular line of code that seams to be failing (the last one):
```c++
        while( seq_cur != NULL )
        {
            seq_prv = seq_cur;
            seq_cur = seq_cur->next;
```

Surely this can be fixed "upstream" in the HTTPS-libs but I don't think that calling this function twice is supposed to cause a crash.

**Comment by projectgus** [comment] 2017-08-21 01:06
Thanks for reporting this with so much detail, @Curclamas . Sorry it's taken a while to get back to you.

I've spent some time investigating, and I don't think this is a bug in IDF or mbedTLS. I'm not able to reproduce (I've attached a modified version of the IDF HTTPS example to this comment), and I can't see how this situation could happen during correct usage of the library:

The crash in `seq_cur = seq_cur->next` happens trying to read from memory address 0x0000000d (the EXCVADDR in the dump). The offset of the `next` field in `seq_cur` is 0xc, so this implies the value of the `seq_cur` pointer is 1 (which explains why the null check passes).

The only way this pointer can have (invalid) value 1 is if the `cert_cur->ext_key_usage.next` field value is 1, or if one of the previous certificate's `next` pointer has value 1. Both of these structured are zeroed out by `mbedtls_x509_crt_free`.

The most likely underlying reason for this is memory corruption.

It could happen if an mbedtls_x509_crt structure (or similar) is associated with the ssl context via `mbedtls_ssl_conf_ca_chain()` or `mbedtls_ssl_conf_own_cert()`, but then the structure is either freed or goes out of scope without calling `mbedtls_ssl_conf_ca_chain(ssl, NULL)`. Now the ssl context has a pointer to freed memory. However this shouldn't happen in Arduino ssl_client, as the ssl_client and all of the cert structures are part of the same class' fields.

Another possible explanation is regular memory corruption due to some other function writing into the certificate's memory space between the first call to mbedtls_crt_free() and the second one.

A final possible explanation is if the ssl structure or any CA cert structures is shared between multiple tasks, as mbedTLS is not thread-safe without additional lock protections. This would include using the same Arduino WifiClientSecure object from multiple tasks.

I'm going to close this issue, but please reopen if you're certain there's a bug in IDF. A reproducible test case of any kind (Arduino or IDF app) would be very helpful to track this down.

Angus

**Closed by projectgus** 2017-08-21 01:06 UTC
