### ISSUE TITLE
ESP-IDF VS Code extension setup fails at import _ssl (IDFGH-13833)

### ISSUE THREAD

**Issue by IanLewis42** [espressif/esp-idf#14683] opened 2024-10-07 15:10 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3.1

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I expected the setup to complete successfully.

### What is the actual behavior?

Setup halts with the error message:
non zero exit code 1

Traceback (most recent call last):
  File "c:\Installs\esp-idf-v5.3.1\esp-idf-v5.3.1\tools\idf_tools.py", line 43, in <module>
    import ssl
  File "C:\Users\ilewis\.platformio\python3\Lib\ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: DLL load failed while importing _ssl: The specified procedure could not be found.

### Steps to reproduce.

Follow the instructions here:
https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/install.md
Choose 'Express Setup', and 'Find ESP-IDF in your system' point to previously downloaded esp-idf-v5.3.1 folder.

### Build or installation Logs.

```plain
Using existing C:\Users\ilewis\.espressif\dist\idf-git-2.39.2-win64.zip
Installing C:\Users\ilewis\.espressif\tools\idf-git\2.39.2 ...
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\cmd\git.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\cmd\scalar.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\awk.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\b2sum.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\basename.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\basenc.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\cat.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\chattr.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\cmp.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\comm.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\cp.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\cut.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\cygwin-console-helper.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\dash.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\date.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\diff.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\diff3.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\dirname.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\echo.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\env.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\expr.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\false.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\find.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\gencat.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\getfacl.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\getopt.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\gmondump.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\grep.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\head.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\ls.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\lsattr.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\mkdir.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\mktemp.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-2.0.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-asn1-8.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-cbor-0.9.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-com_err-1.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-crypt-0.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-crypto-1.1.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-fido2-1.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-gcc_s-seh-1.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-gmp-10.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-gssapi-3.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-hcrypto-4.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-heimbase-1.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-heimntlm-0.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-hx509-5.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-iconv-2.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-intl-8.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-krb5-26.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-mpfr-6.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-ncursesw6.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-pcre-1.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-readline8.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-roken-18.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-sqlite3-0.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-wind-0.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\msys-z.dll
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\mv.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\pathchk.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\printf.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\profiler.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\pwd.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\readlink.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\rebase.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\rebaseall
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\rm.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\rmdir.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\sdiff.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\sed.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\sh.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\sort.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\ssh-add.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\ssh-agent.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\ssh.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\tail.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\test.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\touch.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\tr.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\true.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\uname.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\uniq.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\wc.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\bin\xargs.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\etc\profile.d\gawk.csh
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\etc\profile.d\gawk.sh
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\lib\ssh\ssh-keysign.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\lib\ssh\ssh-pkcs11-helper.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\lib\ssh\ssh-sk-helper.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\libexec\getprocaddr32.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\libexec\getprocaddr64.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\assert.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\bits2str.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\cliff_rand.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\ctime.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\ftrans.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\getopt.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\gettime.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\group.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\have_mpfr.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\inplace.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\intdiv0.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\join.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\libintl.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\noassign.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\ns_passwd.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\ord.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\passwd.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\processarray.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\quicksort.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\readable.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\readfile.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\rewind.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\round.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\shellquote.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\strtonum.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\walkarray.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\awk\zerofile.awk
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\licenses\gcc-libs\RUNTIME.LIBRARY.EXCEPTION
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\licenses\libsqlite\LICENSE
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\licenses\openssh\LICENCE
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\licenses\openssl\LICENSE
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\licenses\zlib\LICENSE
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\share\nano\git.nanorc
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\ssl\ct_log_list.cnf
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\ssl\ct_log_list.cnf.dist
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\ssl\openssl.cnf
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\ssl\openssl.cnf.dist
                                        already exists and was not updated.
Extracted C:\Users\ilewis\.espressif\tools\idf-git\2.39.2 ...
Using existing C:\Users\ilewis\.espressif\tools\idf-python\3.11.2

Downloading GDB for Xtensa
Using mirror Github with URL https://github.com/espressif/binutils-gdb/releases/download/esp-gdb-v14.2_20240403/xtensa-esp-elf-gdb-14.2_20240403-x86_64-w64-mingw32.zip
Found xtensa-esp-elf-gdb in C:\Users\ilewis\.espressif\dist
Downloading GDB for RISC-V
Using mirror Github with URL https://github.com/espressif/binutils-gdb/releases/download/esp-gdb-v14.2_20240403/riscv32-esp-elf-gdb-14.2_20240403-x86_64-w64-mingw32.zip
Found riscv32-esp-elf-gdb in C:\Users\ilewis\.espressif\dist
Downloading Toolchain for 32-bit Xtensa based on GCC
Using mirror Github with URL https://github.com/espressif/crosstool-NG/releases/download/esp-13.2.0_20240530/xtensa-esp-elf-13.2.0_20240530-x86_64-w64-mingw32_hotfix.zip
Found xtensa-esp-elf in C:\Users\ilewis\.espressif\dist
Downloading Toolchain for 32-bit RISC-V based on GCC
Using mirror Github with URL https://github.com/espressif/crosstool-NG/releases/download/esp-13.2.0_20240530/riscv32-esp-elf-13.2.0_20240530-x86_64-w64-mingw32.zip
Found riscv32-esp-elf in C:\Users\ilewis\.espressif\dist
Downloading Toolchain for ESP32 ULP coprocessor
Using mirror Github with URL https://github.com/espressif/binutils-gdb/releases/download/esp32ulp-elf-2.38_20240113/esp32ulp-elf-2.38_20240113-win64.zip
Found esp32ulp-elf in C:\Users\ilewis\.espressif\dist
Downloading CMake build system
Using mirror Github with URL https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip
Found cmake in C:\Users\ilewis\.espressif\dist
Downloading OpenOCD for ESP32
Using mirror Github with URL https://github.com/espressif/openocd-esp32/releases/download/v0.12.0-esp32-20240318/openocd-esp32-win32-0.12.0-esp32-20240318.zip
Found openocd-esp32 in C:\Users\ilewis\.espressif\dist
Downloading Ninja build system
Using mirror Github with URL https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip
Found ninja in C:\Users\ilewis\.espressif\dist
Downloading IDF wrapper tool for Windows
Using mirror Github with URL https://github.com/espressif/idf_py_exe_tool/releases/download/v1.0.3/idf-exe-v1.0.3.zip
Found idf-exe in C:\Users\ilewis\.espressif\dist
Downloading Ccache (compiler cache)
Using mirror Github with URL https://github.com/ccache/ccache/releases/download/v4.8/ccache-4.8-windows-x86_64.zip
Found ccache in C:\Users\ilewis\.espressif\dist
Downloading dfu-util (Device Firmware Upgrade Utilities)
Using mirror Github with URL https://dl.espressif.com/dl/dfu-util-0.11-win64.zip
Found dfu-util in C:\Users\ilewis\.espressif\dist
Downloading ESP ROM ELFs
Using mirror Github with URL https://github.com/espressif/esp-rom-elfs/releases/download/20240305/esp-rom-elfs-20240305.tar.gz
Found esp-rom-elfs in C:\Users\ilewis\.espressif\dist

Using existing GDB for Xtensa in C:\Users\ilewis\.espressif\tools\xtensa-esp-elf-gdb\14.2_20240403
Using existing GDB for RISC-V in C:\Users\ilewis\.espressif\tools\riscv32-esp-elf-gdb\14.2_20240403
Using existing Toolchain for 32-bit Xtensa based on GCC in C:\Users\ilewis\.espressif\tools\xtensa-esp-elf\esp-13.2.0_20240530
Using existing Toolchain for 32-bit RISC-V based on GCC in C:\Users\ilewis\.espressif\tools\riscv32-esp-elf\esp-13.2.0_20240530
Using existing Toolchain for ESP32 ULP coprocessor in C:\Users\ilewis\.espressif\tools\esp32ulp-elf\2.38_20240113
Using existing CMake build system in C:\Users\ilewis\.espressif\tools\cmake\3.24.0
Using existing OpenOCD for ESP32 in C:\Users\ilewis\.espressif\tools\openocd-esp32\v0.12.0-esp32-20240318
Using existing Ninja build system in C:\Users\ilewis\.espressif\tools\ninja\1.11.1
Using existing IDF wrapper tool for Windows in C:\Users\ilewis\.espressif\tools\idf-exe\1.0.3
Using existing Ccache (compiler cache) in C:\Users\ilewis\.espressif\tools\ccache\4.8
Using existing dfu-util (Device Firmware Upgrade Utilities) in C:\Users\ilewis\.espressif\tools\dfu-util\0.11
Installing package ESP ROM ELFs
Installing tar.gz package ESP ROM ELFs

Traceback (most recent call last):
  File "c:\Installs\esp-idf-v5.3.1\esp-idf-v5.3.1\tools\idf_tools.py", line 43, in <module>

    import ssl

  File "C:\Users\ilewis\.platformio\python3\Lib\ssl.py", line 100, in <module>

    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: DLL load failed while importing _ssl: The specified procedure could not be found.

non zero exit code 1

Traceback (most recent call last):
  File "c:\Installs\esp-idf-v5.3.1\esp-idf-v5.3.1\tools\idf_tools.py", line 43, in <module>
    import ssl
  File "C:\Users\ilewis\.platformio\python3\Lib\ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: DLL load failed while importing _ssl: The specified procedure could not be found.
```

### More Information.

I ran the doctor command, but the output seems to be too big to include in the issue.

**Comment by jakub-kocka** [comment] 2024-10-08 15:27
Hi @IanLewis42,
I was not able to reproduce your issue.

But it looks like the PATH (`"C:\Users\ilewis\.platformio\python3\Lib\ssl.py"`) is not from the tools directory and should not be here during the installation, can you try to disable the PlatformIO extension during the installation?

**Comment by IanLewis42** [comment] 2024-10-09 08:57
Hi, @jakub-kocka 

I have tried what you suggested, disable platformio extension, but it made no difference, the error was the same, I guess because PYTHONHOME and PYTHONPATH are both pointing to C:\Users\ilewis\.platformio\python3.

I tried changing both PYTHONHOME and PYTHONPATH  to C:\Users\ilewis\.espressif\tools\idf-python\3.11.2

and I got a different error, see below.

Downloading from https://dl.espressif.com/dl/esp-idf/idf_versions.txt
idf_versions.txt has (1) KB
idf_versions.txt progress: 100.00% (0.08 / 0.08) KB
Using existing C:\Users\ilewis\.espressif\dist\idf-git-2.39.2-win64.zip
Installing C:\Users\ilewis\.espressif\tools\idf-git\2.39.2 ...
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\cmd\git.exe
                                        already exists and was not updated.
Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\cmd\scalar.exe
                                        already exists and was not updated.

<snip>
---------
<snip>

Warning File C:\Users\ilewis\.espressif\tools\idf-git\2.39.2\usr\ssl\openssl.cnf.dist
                                        already exists and was not updated.
Extracted C:\Users\ilewis\.espressif\tools\idf-git\2.39.2 ...
Using existing C:\Users\ilewis\.espressif\tools\idf-python\3.11.2
"C:\Users\ilewis\.espressif\tools\idf-python\3.11.2\python.exe -m pip" is not valid. (ERROR_INVALID_PIP)

**Comment by jakub-kocka** [comment] 2024-10-09 09:34
Hi, @IanLewis42,

Okay, this seems to be an issue with the environment.
You can try to run `python -m ensurepip` in the PowerShell console for example ... or VS Code terminal and repeat the installation.

I am not sure how you got the existing `ESP-IDF` environment but in case this does not help, you can try to reinstall the ESP-IDF directory and environment with the IDF installer (https://dl.espressif.com/dl/esp-idf/) - I recommend using the "Universal Online Installer", it will also sets the register values and environmental variables for you. Then proceed with the configuration of the VS Code extension with the installed directory.

**Comment by jakub-kocka** [comment] 2024-10-15 12:38
Hi @IanLewis42,
I am glad that you get it working 👍

However, the `PYTHONPATH` variable determines the global Python interpreter used.

> In resulting CMD prompt, run 'python -m ensurepip'

This should not be needed because when the installation is completed, for the "resulting" terminals its environment with the interpreter is used (e.g. `C:\Espressif\tools\idf-python\3.11.2;C:\Espressif\python_env\idf5.3_py3.11_env`) and there it should be included.

Be aware that this might be a little issue when using Python for other use cases not just with ESP-IDF tools that the interpreter will be the one from the PATH you have specified.

Thanks for providing more information, the resolution should be complete, so we will close this issue.

**Closed** 2024-10-18 08:39 UTC
Labels: Type: Bug, Status: Done, Resolution: Done
