### ISSUE TITLE
ESP peripheral + iOS 13.4: ignored BLE attribute read by type (IDFGH-2843)

### ISSUE THREAD

**Issue by zacwbond** [espressif/esp-idf#4903] opened 2020-03-06 22:31 UTC
## Environment

- Development Kit:      none (custom HW)
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): v4.1-dev-369-g4dac7c7df
- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): gcc8_2_0-esp-2019r1-linux-amd64
- Operating System:     Linux
- Using an IDE?: No
- Power Supply:         external 3.3V

## Problem Description

We have our ESP configured as a GATT server, and have Android and iOS apps that connect to it. 
However, we have just begun having a problem with iPhones running iOS 13.4, and only those iPhones which also support Bluetooth 5.  

It looks like a failure of the BLE stack to process a GATT Read By Type request for the device model string in the device information service shortly after discovery.  30 seconds later, the iOS device disconnects because it never receives a response.

In the ESP debug (BLE GATT and L2CAP debug is turned on), I can see that it receives a message:
```
D (219742) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004
```

But there's nothing else until the disconnect message 30s later, whereas there's lots of L2CAP debug for all other messages.  It's as if the stack is just ignoring it.

I've attached a WireShark log, and the ESP debug log follows.
```
E (200913) Heap: 83000
E (200913) HeapMin: 78000
E (210913) Heap: 82992
E (210913) HeapMin: 78000
D (215435) BT_L2CAP: l2c_ble_link_adjust_allocation  num_hipri: 0  num_lowpri: 1  low_quota: 10  round_robin_quota: 0  qq: 10
D (215435) BT_L2CAP: l2c_ble_link_adjust_allocation LCB 0   Priority: 0  XmitQuota: 10
D (215436) BT_L2CAP:         SentNotAcked: 0  RRUnacked: 0
D (215437) BT_L2CAP: l2cu_allocate_ccb: cid 0x0000
D (215438) BT_L2CAP: l2c_link_adjust_chnl_allocation
D (215438) BT_L2CAP: CID:0x0043 FCR Mode:0 Priority:2 TxDataRate:1 RxDataRate:1 Quota:200
D (215572) BT_L2CAP: l2cu_process_fixed_chnl_resp
D (215572) BT_GATT: GATT   ATT protocol channel with BDA: 52c52dd739e1 is connected
D (215572) BT_GATT: gatt_is_bda_in_the_srv_chg_clt_list :52-c5-2d-d7-39-e1
D (215573) BT_GATT: gatt_set_ch_state: old=0 new=4
D (215573) BT_GATT: gatt_connect_cback: from 52c52dd739e1 connected:1 conn_id=1 reason = 0x0000
D (215575) BT_GATT: gatt_get_ch_state: ch_state=4
I (215575) BT_GATT: GATT_GetConnIdIfConnected status=1

D (215578) BT_GATT: gatt_num_apps_hold_link   num=0
I (215578) BT_L2CAP: L2CA_SetDesireRole() new:x1, disallow_switch:0
I (215580) Esp Ble Server: gatt server event: ESP_GATTS_CONNECT_EVT on interface: 4
I (215581) Esp Ble Server: phone connected!
I (215581) Esp Ble Server: Restart advertising due to connect.
I (215582) Esp Ble Client: gatt server event: ESP_GATTC_CONNECT_EVT on interface: 3
E (215583) Esp Ble Client: Connection to E1:39:D7:2D:C5:52 was started when connection to 00:00:00:00:00:00 was already in progress.
I (215583) GOT ACK!:
D (215585) BT_L2CAP: l2c_link_check_send_pkts
D (215585) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215586) BT_L2CAP: l2c_link_send_to_lower
D (215587) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
I (215590) SEND ACK!:
I (215591) Ble Driver: GAP event: ESP_GAP_BLE_ADV_START_COMPLETE_EVT
I (215591) Ble Driver: Advertising Succeeded!
D (215631) BT_L2CAP: l2c_link_check_send_pkts
D (215631) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215631) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (215632) BT_L2CAP: l2cble_process_data_length_change_event TX data len = 251
D (215662) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (215662) BT_GATT: gatt_get_ch_state: ch_state=4
I (215662) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (215663) BT_L2CAP: l2c_link_check_send_pkts
D (215663) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215665) BT_L2CAP: l2c_link_send_to_lower
D (215665) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (215665) BT_GATT: gatt_request_cback
D (215666) BT_GATT: Get MTU exchange new mtu size: 247
I (215667) BT_GATT: GATT_GetConnectionInfor conn_id=4
D (215670) BT_L2CAP: L2CAP - rcv_cid CID: 0x0005

I (215672) Esp Ble Server: gatt server event: ESP_GATTS_MTU_EVT on interface: 4
I (215673) Esp Ble Server: ESP_GATTS_MTU_EVT, MTU 247, conn_id: 0
I (215673) Ble Driver: GAP event: ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT
E (215676) Ble Driver: update connection params for E1:39:D7:2D:C5:52: status = 15, min_int = 32, max_int = 32,conn_int = 24,latency = 0, timeout = 72
D (215721) BT_L2CAP: l2c_link_check_send_pkts
D (215721) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215721) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (215722) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (215723) BT_GATT: gatt_get_ch_state: ch_state=4
I (215723) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (215724) BT_L2CAP: l2c_link_check_send_pkts
D (215725) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215727) BT_L2CAP: l2c_link_send_to_lower
D (215728) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (215841) BT_L2CAP: l2c_link_check_send_pkts
D (215841) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215841) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (215842) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (215842) BT_GATT: gatt_get_ch_state: ch_state=4
I (215843) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (215844) BT_L2CAP: l2c_link_check_send_pkts
D (215845) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215845) BT_L2CAP: l2c_link_send_to_lower
D (215847) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (215931) BT_L2CAP: l2c_link_check_send_pkts
D (215931) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215931) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (215932) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (215933) BT_GATT: gatt_get_ch_state: ch_state=4
D (215933) BT_GATT: Use 0xFFFF for the last primary attribute
I (215934) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (215935) BT_L2CAP: l2c_link_check_send_pkts
D (215936) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215936) BT_L2CAP: l2c_link_send_to_lower
D (215937) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (215991) BT_L2CAP: l2c_link_check_send_pkts
D (215991) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215991) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (215992) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (215993) BT_GATT: gatt_get_ch_state: ch_state=4
D (215993) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

D (215994) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

I (215995) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (215996) BT_L2CAP: l2c_link_check_send_pkts
D (215997) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (215997) BT_L2CAP: l2c_link_send_to_lower
D (215998) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216051) BT_L2CAP: l2c_link_check_send_pkts
D (216051) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216051) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216052) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216053) BT_GATT: gatt_get_ch_state: ch_state=4
D (216053) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

I (216054) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216055) BT_L2CAP: l2c_link_check_send_pkts
D (216056) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216058) BT_L2CAP: l2c_link_send_to_lower
D (216058) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216111) BT_L2CAP: l2c_link_check_send_pkts
D (216111) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216111) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216112) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216113) BT_GATT: gatt_get_ch_state: ch_state=4
I (216114) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216114) BT_L2CAP: l2c_link_check_send_pkts
D (216115) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216116) BT_L2CAP: l2c_link_send_to_lower
D (216117) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216171) BT_L2CAP: l2c_link_check_send_pkts
D (216171) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216172) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216172) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216173) BT_GATT: gatt_get_ch_state: ch_state=4
I (216174) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216175) BT_L2CAP: l2c_link_check_send_pkts
D (216175) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216176) BT_L2CAP: l2c_link_send_to_lower
D (216177) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216231) BT_L2CAP: l2c_link_check_send_pkts
D (216231) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216231) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216232) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216233) BT_GATT: gatt_get_ch_state: ch_state=4
D (216233) BT_GATT: gatts_write_attr_perm_check op_code=0x12 handle=0x0004 offset=0 len=2 sec_flag=0x0 key_size=0
D (216234) BT_GATT: gatts_write_attr_perm_check p_attr->permission =0x0011 min_key_size==0x0000
D (216236) BT_GATT: gatt_request_cback
D (216236) BT_GATT: GATTS_SetAttributeValue: attr_handle: 4  length: 2

I (216237) BT_GATT: GATTS_SendRsp: conn_id: 1  trans_id: 1  Status: 0x0000

D (216238) BT_GATT: gatt_sr_process_app_rsp gatt_if=1

I (216239) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216239) BT_L2CAP: l2c_link_check_send_pkts
D (216240) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216241) BT_L2CAP: l2c_link_send_to_lower
D (216242) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216242) BT_GATT: gatt_dequeue_sr_cmd
D (216243) BT_GATT: gatt_sr_process_app_rsp ret_code=0

D (216351) BT_L2CAP: l2c_link_check_send_pkts
D (216351) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216351) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216352) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216353) BT_GATT: gatt_get_ch_state: ch_state=4
D (216353) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

D (216354) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216357) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216358) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216359) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

I (216360) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216361) BT_L2CAP: l2c_link_check_send_pkts
D (216361) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216362) BT_L2CAP: l2c_link_send_to_lower
D (216363) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216411) BT_L2CAP: l2c_link_check_send_pkts
D (216411) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216411) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216412) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216413) BT_GATT: gatt_get_ch_state: ch_state=4
D (216413) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

D (216414) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216415) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

I (216416) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216417) BT_L2CAP: l2c_link_check_send_pkts
D (216418) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216419) BT_L2CAP: l2c_link_send_to_lower
D (216419) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216471) BT_L2CAP: l2c_link_check_send_pkts
D (216471) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216471) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216472) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216472) BT_GATT: gatt_get_ch_state: ch_state=4
D (216473) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

D (216474) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216475) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216476) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216477) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

D (216478) BT_GATT: read_attr_value uuid=0x2803 perm=0x1 sec_flag=0x0 offset=0 read_long=0

I (216479) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216480) BT_L2CAP: l2c_link_check_send_pkts
D (216481) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216482) BT_L2CAP: l2c_link_send_to_lower
D (216482) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216531) BT_L2CAP: l2c_link_check_send_pkts
D (216531) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216531) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216532) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216533) BT_GATT: gatt_get_ch_state: ch_state=4
D (216533) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

I (216534) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216535) BT_L2CAP: l2c_link_check_send_pkts
D (216536) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216536) BT_L2CAP: l2c_link_send_to_lower
D (216537) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216591) BT_L2CAP: l2c_link_check_send_pkts
D (216591) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216591) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216592) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216593) BT_GATT: gatt_get_ch_state: ch_state=4
I (216593) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216594) BT_L2CAP: l2c_link_check_send_pkts
D (216595) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216596) BT_L2CAP: l2c_link_send_to_lower
D (216597) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216651) BT_L2CAP: l2c_link_check_send_pkts
D (216651) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216651) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216652) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216653) BT_GATT: gatt_get_ch_state: ch_state=4
I (216653) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216654) BT_L2CAP: l2c_link_check_send_pkts
D (216655) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216656) BT_L2CAP: l2c_link_send_to_lower
D (216656) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216711) BT_L2CAP: l2c_link_check_send_pkts
D (216711) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216711) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (216712) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (216712) BT_GATT: gatt_get_ch_state: ch_state=4
I (216713) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (216714) BT_L2CAP: l2c_link_check_send_pkts
D (216715) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216716) BT_L2CAP: l2c_link_send_to_lower
D (216716) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (216800) BT_L2CAP: l2c_link_check_send_pkts
D (216800) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (216801) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (218691) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (218691) BT_GATT: gatt_get_ch_state: ch_state=4
D (218691) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

D (218691) BT_GATT: read_attr_value uuid=0x2a00 perm=0x1 sec_flag=0x0 offset=0 read_long=0

I (218693) BT_GATT: GATTS_SendRsp: conn_id: 2  trans_id: 2  Status: 0x0000

D (218693) BT_GATT: gatt_sr_process_app_rsp gatt_if=2

I (218694) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (218695) BT_L2CAP: l2c_link_check_send_pkts
D (218696) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (218697) BT_L2CAP: l2c_link_send_to_lower
D (218697) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
D (218698) BT_GATT: gatt_dequeue_sr_cmd
D (218698) BT_GATT: gatt_sr_process_app_rsp ret_code=0

D (218750) BT_L2CAP: l2c_link_check_send_pkts
D (218751) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (218751) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (219681) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (219681) BT_GATT: gatt_get_ch_state: ch_state=4
D (219681) BT_GATT: gatts_process_read_by_type_req, op_code =8, len = 0

D (219682) BT_GATT: read_attr_value uuid=0x2a29 perm=0x1 sec_flag=0x0 offset=0 read_long=0

I (219683) BT_GATT: GATT_GetConnectionInfor conn_id=4
I (219685) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 52c52dd739e1
D (219685) BT_L2CAP: l2c_link_check_send_pkts
D (219685) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (219686) BT_L2CAP: l2c_link_send_to_lower
D (219687) BT_L2CAP: TotalWin=9,Hndl=0x0,Quota=10,Unack=1,RRQuota=0,RRUnack=0
I (219688) Esp Ble Server: gatt server event: ESP_GATTS_READ_EVT on interface: 4
I (219689) Esp Ble Server: read event: conn_id 0, handle 58 [2A29], is_long 0, need_rsp 0, offset 0, trans_id 3
D (219741) BT_L2CAP: l2c_link_check_send_pkts
D (219741) BT_L2CAP: partial_segment_being_sent=0,link_state=4,power_mode=0
D (219741) BT_L2CAP: TotalWin=10,LinkUnack(0x0)=0,RRCheck=0,RRUnack=0

D (219742) BT_L2CAP: L2CAP - rcv_cid CID: 0x0004

D (219742) BT_GATT: gatt_get_ch_state: ch_state=4
E (220913) Heap: 81292
E (220913) HeapMin: 78000
V (225622) esp_adapter: thread sem get: sem=0x3ffe8098
D (227672) event: running post WIFI_EVENT:1 with handler 0x400e2ac4 on loop 0x3ffcbb24
E (227672) ESP Wifi: Event received: WIFI_EVENT_SCAN_DONE
V (227724) esp_adapter: thread sem get: sem=0x3ffe8098
E (230913) Heap: 80812
E (230913) HeapMin: 78000
E (240913) Heap: 81444
E (240913) HeapMin: 78000
D (249710) BT_L2CAP: l2cu_release_ccb: cid 0x0004  in_use: 1
D (249710) BT_GATT: GATT   ATT protocol channel with BDA: 52c52dd739e1 is disconnected
D (249711) BT_GATT: gatt_is_bda_in_the_srv_chg_clt_list :52-c5-2d-d7-39-e1
D (249712) BT_GATT: gatt_cleanup_upon_disc
D (249712) BT_GATT: found p_tcb
D (249713) BT_GATT: gatt_set_ch_state: old=4 new=0
D (249713) BT_GATT: gatt_free_pending_ind
D (249714) BT_GATT: gatt_free_pending_enc_queue
D (249714) BT_GATT: gatt_free_pending_prepare_write_queue
D (249715) BT_GATT: found p_reg tcb_idx=0 gatt_if=1  conn_id=0x1
D (249716) BT_GATT: gatt_connect_cback: from 52c52dd739e1 connected:0 conn_id=1 reason = 0x0013
D (249717) BT_GATT: gatt_get_ch_state: ch_state=0
I (249717) BT_GATT: GATT_GetConnIdIfConnected status=0

D (249718) BT_GATT: found p_reg tcb_idx=0 gatt_if=2  conn_id=0x2
D (249719) BT_GATT: found p_reg tcb_idx=0 gatt_if=3  conn_id=0x3
W (249720) BT_APPL: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0013
D (249721) BT_GATT: found p_reg tcb_idx=0 gatt_if=4  conn_id=0x4
D (249722) BT_GATT: gatt_delete_dev_from_srv_chg_clt_list
D (249722) BT_GATT: gatt_is_bda_in_the_srv_chg_clt_list :52-c5-2d-d7-39-e1
D (249723) BT_GATT: ATT disconnected
I (249724) BT_L2CAP: L2CA_SetDesireRole() new:x1, disallow_switch:0
I (249725) Esp Ble Server: gatt server event: ESP_GATTS_DISCONNECT_EVT on interface: 4
I (249725) Esp Ble Server: phone disconnect!
I (249726) Esp Ble Server: Restart advertising due to disconnect.
I (249727) Esp Ble Client: gatt server event: ESP_GATTC_DISCONNECT_EVT on interface: 3
I (249728) Esp Ble Client: connection failed for unknown device
I (249728) GOT ACK!:
I (249729) Esp Ble Client: 52 c5 2d d7 39 e1
I (249730) Esp Ble Client: Restart scanning due to disconnect
I (249736) Ble Driver: GAP event: ESP_GAP_BLE_ADV_START_COMPLETE_EVT
I (249736) Ble Driver: Advertising Succeeded!
E (250913) Heap: 82952
E (250913) HeapMin: 78000
I (252590) SEND ACK!:
V (257724) esp_adapter: thread sem get: sem=0x3ffe8098
D (259774) event: running post WIFI_EVENT:1 with handler 0x400e2ac4 on loop 0x3ffcbb24
E (259774) ESP Wifi: Event received: WIFI_EVENT_SCAN_DONE
V (259827) esp_adapter: thread sem get: sem=0x3ffe8098
I (259990) SEND ACK!:
E (260913) Heap: 83484
E (260913) HeapMin: 78000
```

[iOS_ConnFail_BLE5.pcapng.log](https://github.com/espressif/esp-idf/files/4300721/iOS_ConnFail_BLE5.pcapng.log)

**Comment by TallDaveWeiss** [comment] 2020-03-31 01:57
Any update on this issue?

**Comment by Alvin1Zhang** [comment] 2020-03-31 02:08
@TallDaveWeiss Thanks for asking the updates, sorry for the slow turnaround, we are looking into the issue, and will provide feedback once available. Thanks.

**Comment by Alvin1Zhang** [comment] 2020-03-31 02:41
@zacwbond @TallDaveWeiss Thanks for reporting and updating, we already have a fix internally now under reviewing, will update once it is available on GitHub. Thanks.

**Comment by stuarthatchbaby** [comment] 2020-03-31 03:55
We're seeing this issue too and it's preventing our customers from registering new devices!

This is critical - please treat this as your highest priority!

**Comment by AndroidBaaaby** [comment] 2020-03-31 04:03
@stuarthatchbaby Sure. We have put the MR in the highest priority.

**Comment by stuarthatchbaby** [comment] 2020-03-31 04:22
We are standing by to help confirm this resolution. Can we get details of the MR ?

**Comment by hm0429** [comment] 2020-04-03 01:41
any updates on this? thanks!

**Comment by Alvin1Zhang** [comment] 2020-04-03 01:55
@hm0429 @stuarthatchbaby @TallDaveWeiss @zacwbond Thanks for following up the updates. The fix has been merged and available on the master branch and release/4.1 branches on GitHub now. The fix will also be back ported to other release branches. Thanks for your patience.

**Comment by canbempbell** [comment] 2020-04-07 12:43
@Alvin1Zhang we're getting a very similar issue with 3.2.2 since iOS 13.4. Could you please specify the commit which fixes this issue and do you plan to backport it to 3.2? When it'll be available on 3.2?

**Comment by Alvin1Zhang** [comment] 2020-04-08 02:30
@canbempbell Thanks for the follow up. On master branch, the fix is https://github.com/espressif/esp-idf/commit/dcc2963d431ef7eccc4c0abd0a95781698bb4e75 ; on release/v4.1, the fix is https://github.com/espressif/esp-idf/commit/5e09d473c70367ce3899706db48ce3313162c0c4 . We do have plan to back port this fix to IDF v3.2, currently we are working on the release planning of IDF v3.2.4, which is the next bug fix release of IDF v3.2, will update you once the fix is available on release/3.2. Thanks.

**Comment by canbempbell** [comment] 2020-04-08 10:57
@Alvin1Zhang Good. Thanks a lot!

**Comment by phatpaul** [comment] 2020-04-28 20:32
I've been searching for this for a while now.  Our product is now broken on iOS 13.4 and Android 10 (at least on Samsung devices)!  https://esp32.com/viewtopic.php?f=13&t=15344

What about porting to IDF 3.3?
Thanks.

**Comment by zacwbond** [comment] 2020-04-28 20:39
FYI, my application has been migrated to Nimble instead of Bluedroid, so I'm not longer able to easily verify fixes for this issue.  I think one of the other folks who have experienced this problem will need to verify & close.  Thanks!

**Comment by phatpaul** [comment] 2020-04-28 21:59
I can confirm my device now works with iOS 13.4.1 on an iPhone 8 thanks to this fix.  

I still need ask my customers who were unable to connect to my device to upgrade the firmware and test with their devices:
iPhone XR, iOS 13.4.1
Samsung Note 10+, Android 10.?
Samsung S20 Ultra, Android 10.?

**Comment by Alvin1Zhang** [comment] 2020-05-25 06:24
@phatpaul Thanks for verifying. Would you please help share if any more updates? Thanks.

**Comment by rahult-github** [comment] 2022-05-23 09:02
Closing this ticket for lack of updates. Please feel to reopen if issue still observed.

**Closed by rahult-github** 2022-05-23 09:02 UTC
