### ISSUE TITLE
mbedtls_ssl_read blocking when esp32 try to download a bunch of files with maximum speed through https with mbedtls API (IDFGH-4089)

### ISSUE THREAD

**Issue by NOA-Vernon** [espressif/esp-idf#5960] opened 2020-10-10 10:53 UTC
Dears, 

I'm trying to download a bunch of files through https from the server, however, sometimes the mbedtls_ssl_read function block the task and keeps blocking always, I refer to the esp/example/protocols/https_mbedtls, also I have modified some parameter of LWIP and mbedtls in menuconfig, 

CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM=16
CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM=64
CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM=64
CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED=y
CONFIG_ESP32_WIFI_TX_BA_WIN=32
CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED=y
CONFIG_ESP32_WIFI_RX_BA_WIN=32

CONFIG_LWIP_TCP_SND_BUF_DEFAULT=65534
CONFIG_LWIP_TCP_WND_DEFAULT=65534

see the attachment, is this a bug for the esp32? 
The startup log is like this, hope it will help

rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7036
load:0x40078000,len:14736
load:0x40080400,len:4112
entry 0x40080678
[0;32mI (29) boot: ESP-IDF v4.3-dev-907-g6c17e3a64-dirty 2nd stage bootloader[0m
[0;32mI (29) boot: compile time 16:56:18[0m
[0;32mI (30) boot: chip revision: 3[0m
[0;32mI (34) boot_comm: chip revision: 3, min. bootloader chip revision: 0[0m
[0;32mI (41) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (46) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (50) boot.esp32: SPI Flash Size : 8MB[0m
[0;32mI (55) boot: Enabling RNG early entropy source...[0m
[0;32mI (60) boot: Partition Table:[0m
[0;32mI (64) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (71) boot:  0 nvs              WiFi data        01 02 00009000 00004000[0m
[0;32mI (79) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (86) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (94) boot:  3 factory          factory app      00 00 00010000 00280000[0m
[0;32mI (101) boot:  4 ota_0            OTA app          00 10 00290000 00280000[0m
[0;32mI (109) boot:  5 ota_1            OTA app          00 11 00510000 00280000[0m
[0;32mI (116) boot: End of partition table[0m
[0;32mI (120) boot: Defaulting to factory image[0m
[0;32mI (125) boot_comm: chip revision: 3, min. application chip revision: 0[0m
[0;32mI (132) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x6cb70 (445296) map[0m
[0;32mI (334) esp_image: segment 1: paddr=0x0007cb98 vaddr=0x3ffbdb60 size=0x03480 ( 13440) load[0m
[0;32mI (341) esp_image: segment 2: paddr=0x00080020 vaddr=0x400d0020 size=0x15e910 (1435920) map[0m
[0;32mI (962) esp_image: segment 3: paddr=0x001de938 vaddr=0x3ffc0fe0 size=0x0166c (  5740) load[0m
[0;32mI (965) esp_image: segment 4: paddr=0x001dffac vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (969) esp_image: segment 5: paddr=0x001e03b8 vaddr=0x40080404 size=0x1b6fc (112380) load[0m
[0;32mI (1048) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (1049) boot: Disabling RNG early entropy source...[0m
[0;32mI (1060) psram: This chip is ESP32-D0WD[0m
[0;32mI (1061) spiram: Found 64MBit SPI RAM device[0m
[0;32mI (1061) spiram: SPI RAM mode: flash 40m sram 40m[0m
[0;32mI (1066) spiram: PSRAM initialized, cache is in normal (1-core) mode.[0m
[0;32mI (1073) cpu_start: cpu freq: 240[0m
[0;32mI (1077) cpu_start: Pro cpu up.[0m
[0;32mI (1081) cpu_start: Single core mode[0m
[0;32mI (1978) spiram: SPI SRAM memory test OK[0m
[0;32mI (2007) cpu_start: Pro cpu start user code[0m
[0;32mI (2007) cpu_start: Application information:[0m
[0;32mI (2007) cpu_start: Project name:     toky_phase_2[0m
[0;32mI (2011) cpu_start: App version:      4c9bfc3-dirty[0m
[0;32mI (2017) cpu_start: Compile time:     Oct 10 2020 15:43:51[0m
[0;32mI (2023) cpu_start: ELF file SHA256:  65d7fd56ae3c7c50...[0m
[0;32mI (2029) cpu_start: ESP-IDF:          v4.3-dev-907-g6c17e3a64-dirty[0m
[0;32mI (2037) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (2043) heap_init: At 3FF80000 len 00002000 (8 KiB): RTCRAM[0m
[0;32mI (2050) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM[0m
[0;32mI (2056) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM[0m
[0;32mI (2062) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM[0m
[0;32mI (2068) heap_init: At 3FFC8828 len 000177D8 (93 KiB): DRAM[0m
[0;32mI (2075) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM[0m
[0;32mI (2081) heap_init: At 40078000 len 00008000 (32 KiB): IRAM[0m
[0;32mI (2087) heap_init: At 4009BB00 len 00004500 (17 KiB): IRAM[0m
[0;32mI (2094) spiram: Adding pool of 3933K of external SPI memory to heap allocator[0m
[0;32mI (2103) spi_flash: detected chip: gd[0m
[0;32mI (2106) spi_flash: flash io: dio[0m
[0;32mI (2111) cpu_start: Starting scheduler on PRO CPU.[0m
[0;32mI (2116) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations[0m

**Comment by Alvin1Zhang** [comment] 2020-10-12 07:22
Thanks for reporting, we will look into.

**Comment by AdityaHPatwardhan** [comment] 2020-11-20 06:03
Hi @NOA-Vernon Thank you for reporting the issue.
I don't see any obvious issue with your modified configurations.( Considering you have enough RAM available ).
Can you please provide the full debug log ( enabling log output with debug level ) !, you have mentioned some attachment, but I am unable to find it.

**Comment by NOA-Vernon** [comment] 2020-11-20 10:05
@AdityaHPatwardhan  I run the task below, it happens sporadically, you can test the  /esp-idf/examples/protocols/https_mbedtls  example for downloading a bunch of files through HTTPS, one by one.



static void download_get_task(void *pvParameters){

	//char buf[1024];
	int ret, flags, len;

	int i = 0;

	uint8_t read_http_header = 0;
	int8_t download_flag = 0;
	char* p = NULL;

	float cur_per = 0.0;
	float pre_per = 0.0;
	int total_read = 0;
	uint8_t led_stat = 0;
	TickType_t update_tick = xTaskGetTickCount();
	TickType_t updateled_tick = xTaskGetTickCount();
	TickType_t readhttp_tick = xTaskGetTickCount();

	mbedtls_entropy_context entropy;
	mbedtls_ctr_drbg_context ctr_drbg;
	mbedtls_ssl_context ssl;
	mbedtls_x509_crt cacert;
	mbedtls_ssl_config conf;
	mbedtls_net_context server_fd;

	mbedtls_ssl_init(&ssl);
	mbedtls_x509_crt_init(&cacert);
	mbedtls_ctr_drbg_init(&ctr_drbg);
	ESP_LOGI(TAG, "Seeding the random number generator");

	mbedtls_ssl_config_init(&conf);

	mbedtls_entropy_init(&entropy);
	if((ret = mbedtls_ctr_drbg_seed(&ctr_drbg, mbedtls_entropy_func, &entropy,
									NULL, 0)) != 0)
	{
		ESP_LOGE(TAG, "mbedtls_ctr_drbg_seed returned %d", ret);
		download_flag = -1;
		//abort();
		goto exit;
	}

	ESP_LOGI(TAG, "Attaching the certificate bundle...");

	ret = esp_crt_bundle_attach(&conf);

	if(ret < 0)
	{
		ESP_LOGE(TAG, "esp_crt_bundle_attach returned -0x%x", -ret);
		download_flag = -1;
		//abort();
		goto exit;
	}

	ESP_LOGI(TAG, "Setting hostname for TLS session...");

	 /* Hostname set here should match CN in server certificate */
	//if((ret = mbedtls_ssl_set_hostname(&ssl, WEB_SERVER)) != 0)
	if((ret = mbedtls_ssl_set_hostname(&ssl, fodetail.file[0].server)) != 0)
	{
		ESP_LOGE(TAG, "mbedtls_ssl_set_hostname returned -0x%x", -ret);
		download_flag = -1;
		//abort();
		goto exit; //
	}

	ESP_LOGI(TAG, "Setting up the SSL/TLS structure...");

	if((ret = mbedtls_ssl_config_defaults(&conf,
										  MBEDTLS_SSL_IS_CLIENT,
										  MBEDTLS_SSL_TRANSPORT_STREAM,
										  MBEDTLS_SSL_PRESET_DEFAULT)) != 0)
	{
		ESP_LOGE(TAG, "mbedtls_ssl_config_defaults returned %d", ret);
		download_flag = -1;
		goto exit;
	}

	/* MBEDTLS_SSL_VERIFY_OPTIONAL is bad for security, in this example it will print
	   a warning if CA verification fails but it will continue to connect.

	   You should consider using MBEDTLS_SSL_VERIFY_REQUIRED in your own code.
	*/
	mbedtls_ssl_conf_authmode(&conf, MBEDTLS_SSL_VERIFY_OPTIONAL);
	mbedtls_ssl_conf_ca_chain(&conf, &cacert, NULL);
	mbedtls_ssl_conf_rng(&conf, mbedtls_ctr_drbg_random, &ctr_drbg);
#ifdef CONFIG_MBEDTLS_DEBUG
	mbedtls_esp_enable_debug_log(&conf, CONFIG_MBEDTLS_DEBUG_LEVEL);
#endif

	if ((ret = mbedtls_ssl_setup(&ssl, &conf)) != 0)
	{
		ESP_LOGE(TAG, "mbedtls_ssl_setup returned -0x%x", -ret);
		download_flag = -1;
		goto exit;
	}

	//download_file_init();
	memset(folder_download_fname, 0x00, sizeof(folder_download_fname));
	sprintf(folder_download_fname, "//story/%s", fodetail.story_uuid);
	if( tfcard_create_directory(folder_download_fname) != 1){
		//create folder failed
		ESP_LOGE(TAG, "create folder %s failed", folder_download_fname);
		download_flag = -1;
		goto exit;
	}

	total_read = 0;

	for(i = 0; i < fodetail.file_num; i++){

		//sdcard/
		memset(folder_download_fname, 0x00, sizeof(folder_download_fname));
		sprintf(folder_download_fname, "/sdcard/story/%s/%s", fodetail.story_uuid, fodetail.file[i].file_name);
		folder_download_fp = fopen(folder_download_fname, "wb");
		if (folder_download_fp == NULL) {
			ESP_LOGE(TAG, "failed to open the file for writing: %s", folder_download_fname);
			download_flag = -1;
			goto exit;
		}
		ESP_LOGI(TAG, "%d, start to write file: %s", i, folder_download_fname);


		mbedtls_net_init(&server_fd);

		//ESP_LOGI(TAG, "Connecting to %s:%s...", WEB_SERVER, WEB_PORT);
		ESP_LOGI(TAG, "Connecting to %s:%s...", fodetail.file[i].server, fodetail.file[i].port);

		if ((ret = mbedtls_net_connect(&server_fd, fodetail.file[i].server,
				fodetail.file[i].port, MBEDTLS_NET_PROTO_TCP)) != 0)
		{
			ESP_LOGE(TAG, "mbedtls_net_connect returned -%x", -ret);
			download_flag = -1;
			goto exit;
		}

		ESP_LOGI(TAG, "Connected.");

		//mbedtls_ssl_set_bio(&ssl, &server_fd, mbedtls_net_send, mbedtls_net_recv, NULL);
		mbedtls_ssl_set_bio(&ssl, &server_fd, mbedtls_net_send, mbedtls_net_recv, mbedtls_net_recv_timeout);

		ESP_LOGI(TAG, "Performing the SSL/TLS handshake...");

		while ((ret = mbedtls_ssl_handshake(&ssl)) != 0)
		{
			if (ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE)
			{
				ESP_LOGE(TAG, "mbedtls_ssl_handshake returned -0x%x", -ret);
				download_flag = -1;
				goto exit;
			}
		}

		ESP_LOGI(TAG, "Verifying peer X.509 certificate...");

		if ((flags = mbedtls_ssl_get_verify_result(&ssl)) != 0)
		{
			/* In real life, we probably want to close connection if ret != 0 */
			ESP_LOGW(TAG, "Failed to verify peer certificate!");
			bzero(buf, sizeof(buf));
			mbedtls_x509_crt_verify_info(buf, sizeof(buf), "  ! ", flags);
			ESP_LOGW(TAG, "verification info: %s", buf);
		}
		else {
			ESP_LOGI(TAG, "Certificate verified.");
		}

		ESP_LOGI(TAG, "Cipher suite is %s", mbedtls_ssl_get_ciphersuite(&ssl));

		ESP_LOGI(TAG, "Writing HTTP request...");

		size_t written_bytes = 0;

#if CONFIG_SPIRAM
		char* req_str = (char*)heap_caps_malloc( 512 , MALLOC_CAP_SPIRAM);
#else
		char* req_str = (char*)malloc( 512 );
#endif
		memset(req_str, 0x00, 512);
		sprintf(req_str, REQUEST_str, fodetail.file[i].url, fodetail.file[i].server);
		ESP_LOGI(TAG, "req_str: %s", req_str);
		do {
			ret = mbedtls_ssl_write(&ssl,
									(const unsigned char *)req_str + written_bytes,
									strlen(req_str) - written_bytes);
			if (ret >= 0) {
				ESP_LOGI(TAG, "%d bytes written", ret);
				written_bytes += ret;
			} else if (ret != MBEDTLS_ERR_SSL_WANT_WRITE && ret != MBEDTLS_ERR_SSL_WANT_READ) {
				ESP_LOGE(TAG, "mbedtls_ssl_write returned -0x%x", -ret);
				download_flag = -1;
				goto exit;
			}
		} while(written_bytes < strlen(req_str));

		ESP_LOGI(TAG, "Reading HTTP response...");
		read_http_header = 0;
		download_flag = 0;

		do
		{
			len = sizeof(buf) - 1;
			bzero(buf, sizeof(buf));
			ESP_LOGE(TAG, "before mbedtls_ssl_read, ret");
			ret = mbedtls_ssl_read(&ssl, (unsigned char *)buf, len);
			ESP_LOGE(TAG, "after mbedtls_ssl_read, ret = %d", ret);
			if(ret == MBEDTLS_ERR_SSL_WANT_READ || ret == MBEDTLS_ERR_SSL_WANT_WRITE)
				continue;

			if(ret == MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY) {
				ret = 0;
				break;
			}

			if(ret < 0)
			{
				ESP_LOGE(TAG, "mbedtls_ssl_read returned -0x%x", -ret);
				break;
			}else if(ret == 0)
			{
				ESP_LOGI(TAG, "connection closed");
				break;
			}else{

				len = ret;
				ESP_LOGD(TAG, "%d bytes read", len);
				/* Print response directly to stdout as it is read */
				for(int i = 0; i < len; i++) {
					putchar(buf[i]);
				}
			}
			//vTaskDelay(5/portTICK_RATE_MS);

		} while(1);

		mbedtls_ssl_close_notify(&ssl);
exit:
		mbedtls_ssl_session_reset(&ssl);
		mbedtls_net_free(&server_fd);

		if(ret != 0)
		{
			mbedtls_strerror(ret, buf, 100);
			ESP_LOGE(TAG, "Last error was: -0x%x - %s", -ret, buf);
			download_flag = -2;
		}

		if (folder_download_fp != NULL) {
			fclose(folder_download_fp);
		}

		if( download_flag < 0){
			break;
		}

		vTaskDelay(100/portTICK_RATE_MS);

	}
	if( download_flag >= 0){		
		ESP_LOGI(TAG,"download succ");

	}else{
		ESP_LOGI(TAG,"download failed");
	}

	vTaskDelete(NULL);
}

**Comment by AdityaHPatwardhan** [comment] 2020-12-15 07:50
Hi @NOA-Vernon Sorry for the late reply, I was unable to reproduce this on my side. I can see you are creating multiple ssl connections for each file to download. Can you please tell me what it the number of files. If I have read above code correctly I think multiple connections are present simultaneously.It is highly probable that the error your are facing is because of a large number simultaneous connections but I would still like to see a complete debug log where the actual error message is printed.
1 ) Can you please provide a complete code with which I could be able to reproduce.
2 ) Provide a complete debug log in which error message can be seen.
Thank you.

**Comment by NOA-Vernon** [comment] 2020-12-16 10:16
@AdityaHPatwardhan can you test to download a bunch of files through HTTPS,  by testing this example esp-idf\examples\protocols\https_mbedtls, the HTTPS server is from Azure from the client, sorry for that I can't provide you the URL, I just add a for loop in this example for downloading a bunch of different files.

**Comment by AdityaHPatwardhan** [comment] 2020-12-21 06:19
Hi @NOA-Vernon I am able to download file from AWS s3 bucket repeatedly with your configurations, I dont see any obvious problem on my side. I couldn't get an Azure URL to test for myself, but I dont think having an azure URL should cause any problem as far as handshake is succeeded.
Do you face such error every time you use that to download the files ?

**Comment by NOA-Vernon** [comment] 2020-12-22 01:53
@AdityaHPatwardhan No, it happened sporadically and stuck at the ret = mbedtls_ssl_read(&ssl, (unsigned char *)buf, len) without returning, so I don't know what's wrong happen during calling this function.

**Comment by AdityaHPatwardhan** [comment] 2020-12-22 02:10
Then I think that it might be some network issue which is unrelated to the ESP. What is the frequency of this error, like you face it frequently ( and randomly) or you have faced this very few times ! ( like once or twice ).

**Comment by NOA-Vernon** [comment] 2020-12-22 02:15
@AdityaHPatwardhan If this is the network issue, how to set the mbedtls_ssl_read expired timeout, is there an example regarding it?

**Comment by AdityaHPatwardhan** [comment] 2020-12-22 02:37
you can set the `timeout_ms`  value in the `esp_tls_cfg_t` at the start of the TLS connection establishment. You can get relevant info about the options in the `esp_tls_cfg_t` at this [link](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/esp_tls.html#_CPPv411esp_tls_cfg). You can also take a look at the [ESP-TLS documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/esp_tls.html#_CPPv411esp_tls_cfg) for more details.

**Comment by AdityaHPatwardhan** [comment] 2020-12-22 05:55
My Bad, I mistakenly suggested to use an `esp_tls` option.( which internally uses mbedtls ). In your case you can set the timeout for `mbedtls_ssl_read` by setting the value of  `read_timeout` in the `mbedtls` configuration (`mbedtls_ssl_config`).

**Comment by AdityaHPatwardhan** [comment] 2021-01-05 08:57
Hi @NOA-Vernon if the problem is resolved, can you please close the issue ? thank you.

**Closed** 2021-01-08 02:03 UTC
