### ISSUE TITLE
New WROVER modules are missing from HW documentation (IDFGH-713)

### ISSUE THREAD

**Issue by gmos** [espressif/esp-idf#3158] opened 2019-03-11 12:32 UTC
## Environment
Documentation https://docs.espressif.com/projects/esp-idf/en/stable/hw-reference/modules-and-boards.html#wroom-and-wrover-modules

## Problem Description
WROVER modules with new external RAM and Flash sizes are missing from table.

### Expected Behavior
8MB RAM and 8/16GB Flash models added.

### Actual Behavior
n/a
### Steps to reproduce
n/a
### Code to reproduce this issue
n/a
## Debug Logs
n/a

**Comment by igrr** [comment] 2019-03-11 12:59
Thanks for raising this issue. I'm going to close it as the issue is not related to ESP-IDF project. Please use the "Contact us" section of the website to report such issues, or post them on the esp32.com forum in Documentation requests/feedback topic: https://esp32.com/viewtopic.php?f=5&t=905.

**Comment by krzychb** [comment] 2019-07-19 10:25
Resolved in 752c7c32d460a92903adb50a60b33db729bfc28a.

Thank for reporting @gmos!

**Closed by krzychb** 2019-07-19 10:25 UTC
Labels: Type: Doc
