### ISSUE TITLE
make: *** No rule to make target '/home/mosma/esp/blink/build/ldgen_libraries', needed by '/home/mosma/esp/blink/build/esp32/esp32.project.ld'.  Stop. (IDFGH-1098)

### ISSUE THREAD

**Issue by Muhammad1997** [espressif/esp-idf#3419] opened 2019-05-03 23:09 UTC
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32]
- IDF version : v4.0-dev-459-gba1ff1692
- Build System:         [Make]
- Compiler version : 5.2.0
- Operating System:     [Windows]
- Power Supply:         [USB]

## Problem Description

i am trying to ``make flash`` but this message appears every time 
i have tried make clean , delete all files and re cloned , searched for 
```/home/mosma/esp/blink/build/esp32/esp32.project.ld ``` or ```/home/mosma/esp/blink/build/ldgen_libraries``` but i didn't find them , tried to make another project but the same problem appeared 
## Debug Logs
```
make: *** No rule to make target '/home/mosma/esp/blink/build/ldgen_libraries', needed by '/home/mosma/esp/blink/build/esp32/esp32.project.ld'.  Stop.
```

![001](https://user-images.githubusercontent.com/24505557/57169787-2c63a680-6e09-11e9-8bc7-3590e78ab032.png)

**Comment by negativekelvin** [comment] 2019-05-04 00:03
https://github.com/espressif/esp-idf/issues/3394

**Comment by vetaldudnik** [comment] 2019-05-04 07:25
There is error in file ldgen.mk line 17

Actual:

$(BUILD_DIR_BASE)/ldgen.**section_infos**: $(LDGEN_LIBRARIES) $(IDF_PATH)/make/ldgen.mk

Expected:

$(BUILD_DIR_BASE)/**ldgen_libraries**: $(LDGEN_LIBRARIES) $(IDF_PATH)/make/ldgen.mk

P.S. I'm new user and now I'm studying how to do pull request :)

**Comment by igrr** [comment] 2019-05-04 08:08
Closing as duplicate of #3394. Please follow the link to that issue and click "Subscribe" to be notified when the fix is merged. In the meantime you can apply the patch from https://github.com/espressif/esp-idf/issues/3394#issuecomment-488528047.

**Closed by igrr** 2019-05-04 08:08 UTC

**Comment by Muhammad1997** [comment] 2019-05-04 16:31
@igrr  thanks a lot ...  gonna use stable version of it tell its merged

**Comment by piercalderan** [comment] 2019-05-22 05:29
On eclipse it's impossible to add a Windows or Unix like full path.

Espressif says: Click “Add…” again, and enter name IDF_PATH. The value should be the full path where ESP-IDF is installed.
Any idea?

**Comment by piercalderan** [comment] 2019-05-22 05:35
C:/msys32/home/pier/esp/esp-idf/make/project.mk:104: *** IDF_PATH cannot contain colons. If overriding IDF_PATH on Windows, use MSYS Unix-style /c/dir instead of C:/dir.  Stop.
Atter doing a unix like path
makefile:8: /c/msys32/home/pier/esp/esp-idf/make/project.mk: No such file or directory

Vadano a cagare sulle ortiche sia eclipse che espressif!
