### ISSUE TITLE
Secure boot re-flashable bootloader esptool.py --flash_size detect (IDFGH-185)

### ISSUE THREAD

**Issue by catalinio** [espressif/esp-idf#1704] opened 2018-03-10 22:50 UTC
Hi,
In the case of enabling Secure Boot and re-flashable bootloader, every time a new bootloader is released, the bootloader digest (containing both digest and the actual bootloader.bin) has to be flashed at address 0x0.
The trouble is with esptool.py, where parameter "--flash_size detect" is used.
For now, esptool.py does not recognize bootloader-reflash-digest.bin as bootloader partition, so it does not modifies the detected flash size.
I've quickly modified esptool.py, to solve this problem, but it's not right. The bootloader-reflash-digest.bin contains a digest (sha256), and when executed by ESP32, the "secure boot fail" appears. Obviously the digest is computed before the esptool.py modification and (in execution) it fails the sha check.
As a note, I have boards with 4MB and other with 8MB, and until now, I've used esptool.py detect the actual flash size.
So, what would be the solution?
thanks!

**Comment by catalinio** [comment] 2018-03-10 23:27
I assume, I have to obtain booloader.bin with flash_size set at compile time, so, basically to obtain a bootloader for each flash size needed.
Does anyone know where is the flash_size set in the bootloader code?

**Comment by negativekelvin** [comment] 2018-03-11 04:34
@projectgus

**Comment by projectgus** [comment] 2019-03-01 04:01
Hi @catalinio ,

Sorry for the extended silence on this issue.

This is the same root cause fixed by this PR: https://github.com/espressif/esptool/pull/386

Will fix in esptool.py soon.

**Closed** 2019-07-18 04:40 UTC

**Comment by projectgus** [comment] 2019-07-18 05:31
(This issue is fixed in esptool v2.7, but we haven't updated the esptool submodule in the ESP-IDF master branch yet. This should happen in the next week or so.)
