### ISSUE TITLE
ESP32 assigning IP 0.0.0.0 to station (IDFGH-177)

### ISSUE THREAD

**Issue by PhilColbert** [espressif/esp-idf#1665] opened 2018-02-28 21:19 UTC
If a wifi client tried to connect when the access point comes up the esp32 assigns it an IP but records this IP as 0.0.0.0 in 

ESP_ERROR_CHECK(esp_wifi_ap_get_sta_list(&stations));
ESP_ERROR_CHECK(tcpip_adapter_get_sta_list(&stations, &infoList));

This IP stays as 0.0.0.0 and doesnt get changed..

If the wifi client connects perhaps one second after the esp32 has started, the IP is assigned correctly.

This happened on the esp8266 aswell if I recall, any ideas on how to fix ?

**Comment by PhilColbert** [comment] 2018-03-01 19:50
Anyone ? :)

Or a way to kick out the unassigned device ? Cant find anyway in the api to forceably remove a connected station ? 

Thanks

**Comment by heyinling** [comment] 2018-03-02 01:43
Does your WIFI STA uses static IP? If yes then ESP32 AP don't know its IP address.

**Comment by PhilColbert** [comment] 2018-03-04 18:33
No, esp32 assigns it - if I wait 1 sec after wifi comes up then it assigns IP correctly, if it assigns when wifi come up immediately, then it assigns 0.0.0.0

any ideas?

**Comment by jstar88** [comment] 2018-03-05 20:35
you could check if IP == 0 in SYSTEM_EVENT_STA_GOT_IP event.
If yes, then stop and restart wifi

**Comment by PhilColbert** [comment] 2018-03-08 07:49
Thanks, tried that , but when you stop and restart wifi, as the wifi comes back up the client jumps back in again and gets IP = 0.0.0.0 again :(

Tried kicking the station off, but it comes back again with ip 0.0.0.0, perhaps it hasnt cleared its tables out yet?

My workaround has been to limit the access point to one user and dhcp to one address, so I know when its assigned 0.0.0.0 , to wait for 5 seconds ... see  it it has time to assign a proper IP, if it doesnt , then  I manually assign the IP in the dhcp range.

The client receives the correct IP but the esp32 doesnt set it up .

Horrible fix, but the only thing I can think to do at the moment.

**Comment by liuzfesp** [comment] 2018-03-10 09:28
Hi @PhilColbert , the DHCP process immediately follows the WiFi is connected. In other words,  the station will start the DHCP discover process after WiFi is connected (In station mode, SYSTEM_EVENT_STA_CONNECTED indicates the WiFi is connected while in soft-AP mode  SYSTEM_EVENT_AP_STACONNECTED indicates the WiFi is connected). So if you call the tcpip_adapter_get_sta_list after event SYSTEM_EVENT_AP_STACONNECTED is raised, the DHCP process may NOT completed, that's why you got all 0 IP. 

Currently we don't have a way for soft-AP to know whether the stations gets the IP or not, we need to write a program to poll the IP value or wait for some time to make sure the DHCP is completed.

Maybe we can add an new event SYSTEM_EVENT_AP_STA_GOT_IP/SYSTEM_EVENT_AP_STA_LOST_IP for soft-AP mode, @zhangyanjiaoesp please help.

**Comment by PhilColbert** [comment] 2018-03-10 09:37
Thanks for the reply, this is the problem.

After the WiFi has been started for some time > 3 seconds you can see it connect and give it the 0.0.0.0 IP and then switch to the correct IP ( 192.168.4.1 ) - this is no problem, we can just wait for the IP to be assigned.

However if the IP is assigned between WiFi up and DHCP up then the IP is never assigned and stays at 0.0.0.0, moreover when the station is kicked off and it reconnects it keeps this 0 IP :(

I think an event , got IP would be great, however there is the major issue that the IP never gets assigned, this is the problem.

Perhaps if the softAP is set to dhcp mode, then dont let clients connect on WiFi until DHCP is up ?

The client has actually got the IP but the tcpip_adapter_get_sta_list hasnt been updated .

Thanks for any help , I have made my own workaround but its pretty horrible and to be honest this does need fixing ! :)

**Comment by liuzfesp** [comment] 2018-03-10 09:44
Thanks @PhilColbert ! 
For the "IP never assigned", it's a bug if it is as what you said, we will fix it. @zhangyanjiaoesp please reproduce this issue and fix it.
For the new event, we will put into the new feature development list.

**Comment by PhilColbert** [comment] 2018-03-10 09:48
Thanks for the reply, you just need to have device that connects immediately when the system comes up, android never has this problem as it takes a bit of time to realise there is an Access point so gives time for the esp32 to boot the dhcp, I have the main problem on a Kobo ereader, this immediately connects when the esp32 opens the access point.

Hope that helps

Regards

**Comment by liuzfesp** [comment] 2018-03-10 09:55
Got it @PhilColbert, we will check it.

**Comment by serkam1953** [comment] 2018-03-21 19:53
Hi
I have the same problem when using ESP32 as AP.
Follows the segment of program that put ESP32 as AP:
<
// initialize the tcp stack
	tcpip_adapter_init();

	// stop DHCP server
	ESP_ERROR_CHECK(tcpip_adapter_dhcps_stop(TCPIP_ADAPTER_IF_AP));
	
	// assign a static IP to the network interface
	tcpip_adapter_ip_info_t info;
    memset(&info, 0, sizeof(info));
	IP4_ADDR(&info.ip, 192, 168, 4, 1);
    IP4_ADDR(&info.gw, 192, 168, 4, 1);
    IP4_ADDR(&info.netmask, 255, 255, 255, 0);
	ESP_ERROR_CHECK(tcpip_adapter_set_ip_info(TCPIP_ADAPTER_IF_AP, &info));
	
	// start the DHCP server   
    ESP_ERROR_CHECK(tcpip_adapter_dhcps_start(TCPIP_ADAPTER_IF_AP));
	
	// initialize the wifi event handler
	ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL));
	
	// initialize the wifi stack in AccessPoint mode with config in RAM
	wifi_init_config_t wifi_init_config = WIFI_INIT_CONFIG_DEFAULT();
	ESP_ERROR_CHECK(esp_wifi_init(&wifi_init_config));
	ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM));
	ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_AP));

	// configure the wifi connection and start the interface
	wifi_config_t ap_config = {
        .ap = {
            .ssid = CONFIG_AP_SSID,
            .password = CONFIG_AP_PASSWORD,
			.ssid_len = 0,
			.channel = CONFIG_AP_CHANNEL,
			.authmode = CONFIG_AP_AUTHMODE,
			.ssid_hidden = CONFIG_AP_SSID_HIDDEN,
			.max_connection = CONFIG_AP_MAX_CONNECTIONS,
			.beacon_interval = CONFIG_AP_BEACON_INTERVAL,			
        },
    };
	ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_AP, &ap_config));
    
	// start the wifi interface
	ESP_ERROR_CHECK(esp_wifi_start());
	printf("Starting access point, SSID=%s\n", CONFIG_AP_SSID);
>

Looks like that IDF lacks a function that exist in esp-open_rtos ( dhcpserver_start(&first_client_ip, 4) ) that assign the first address to DHCP list.

Any fix for this issue?

BR
Sergio

**Comment by PhilColbert** [comment] 2018-03-23 14:01
Glad someone else has this issue aswell!

Hopefully they will release a fix soon, my project is on hold until this is fixed

**Comment by serkam1953** [comment] 2018-03-23 14:37
Hi Phil

 

https://github.com/lucadentella/esp32-tutorial

 

Have a try in 12_acesspoint example from Lucadentella.

 

Strangely it works flawlessly here in my ESP32 board and it is very similar with my own code.

 

Perhaps another code part ( mine code ) is disturbing my AP routine.

 

I am working now on it.

 

Sergio Kamakura

 

 

 

De: PhilColbert <notifications@github.com> 
Enviada em: sexta-feira, 23 de março de 2018 11:01
Para: espressif/esp-idf <esp-idf@noreply.github.com>
Cc: Sergio Kamakura <serkam@terra.com.br>; Comment <comment@noreply.github.com>
Assunto: Re: [espressif/esp-idf] [TW#18947] ESP32 assigning IP 0.0.0.0 to station (#1665)

 

Glad someone else has this issue aswell!

Hopefully they will release a fix soon, my project is on hold until this is fixed

**Comment by PhilColbert** [comment] 2018-03-23 14:41
It works fine if the client connects a second after the access point comes up, the issue is if the client connects as soon as the access point comes up, the dhcp server isnt up yet and therefore doesnt give it an IP.

Therefore most clients connecting dont connect in this small window of time... I have one client that does connect immediately, and that causes the issue.

**Comment by PhilColbert** [comment] 2018-06-08 12:08
Any luck with this ?

Still cant go forward on my project ! 


Thanks

**Comment by vibhorkhurana** [comment] 2019-05-19 06:54
Any updates on this issue. I am facing the same

**Comment by freakyxue** [comment] 2020-03-11 06:46
hi @PhilColbert  @serkam1953 
Does this problem still exist? @serkam1953 I use your code to reproduce this problem. I can get the IP address normally

**Comment by freakyxue** [comment] 2020-03-12 09:46
hi @PhilColbert @serkam1953 

- I did an experiment,After the AP is started, the DHCP server is shut dowm
- then sta connect ap,because of DHCP server is shut dowm,sta can not get address.
- Then open the DHCP service of AP,Sta can get the address.

If sta can not get address,The DHCP client will send a DHCP request packet to request the address
I think you can print  address in `SYSTEM_EVENT_STA_GOT_IP`event,Instead of waiting a few seconds to get the address.

If the problem repeats again, you can provide the code and method of recurrence,Thanks!

**Comment by Alvin1Zhang** [comment] 2021-03-08 02:51
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates, thanks.

**Closed by Alvin1Zhang** 2021-03-08 02:51 UTC
Labels: Type: Bug :bug:, Type: Feature Request

**Comment by alejoorduz** [comment] 2021-09-14 16:57
For anyone, It says 0.0.0.0 but take a look at 192.168.4.1

**Comment by jasonglisson** [comment] 2023-02-15 16:59
> For anyone, It says 0.0.0.0 but take a look at 192.168.4.1

This actually worked for me. I was getting back 0.0.0.0 no matter what I did, but 192.168.4.1 worked for some reason.
