### ISSUE TITLE
运行./install.sh 出错 (IDFGH-4441)

### ISSUE THREAD

**Issue by hqchen118** [espressif/esp-idf#6271] opened 2020-12-15 09:43 UTC
运行./install.sh 出错：

Using cached python_socketio-5.0.3-py2.py3-none-any.whl (51 kB)
Processing /home/hankchen/.cache/pip/wheels/a4/20/bb/5f2ef34c7088b30933fd2b2b19513c2536d4cb21a3902abf7e/greenlet-0.4.17-cp27-cp27mu-linux_i686.whl
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_i686.whl (23 kB)
ERROR: Could not find a version that satisfies the requirement bidict>=0.21.0 (from python-socketio>=1.6.1->Flask-SocketIO<3.0,>=2.9->gdbgui==0.13.2.0->-r /home/hankchen/ESP32/esp-idf/requirements.txt (line 14)) (from versions: 0.1.5, 0.2.1, 0.3.0, 0.3.1, 0.9.0rc0, 0.9.0.post1, 0.10.0, 0.10.0.post1, 0.11.0, 0.12.0.post1, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.15.0.dev0, 0.15.0.dev1, 0.15.0rc1, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4)
ERROR: No matching distribution found for bidict>=0.21.0 (from python-socketio>=1.6.1->Flask-SocketIO<3.0,>=2.9->gdbgui==0.13.2.0->-r /home/hankchen/ESP32/esp-idf/requirements.txt (line 14))
Traceback (most recent call last):
  File "/home/hankchen/ESP32/esp-idf/tools/idf_tools.py", line 1492, in <module>
    main(sys.argv[1:])
  File "/home/hankchen/ESP32/esp-idf/tools/idf_tools.py", line 1488, in main
    action_func(args)
  File "/home/hankchen/ESP32/esp-idf/tools/idf_tools.py", line 1215, in action_install_python_env
    subprocess.check_call(run_args, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/hankchen/.espressif/python_env/idf4.2_py2.7_env/bin/python', '-m', 'pip', 'install', '--no-warn-script-location', '-r', '/home/hankchen/ESP32/esp-idf/requirements.txt']' returned non-zero exit status 1

**Comment by dobairoland** [comment] 2020-12-15 11:55
Hi @hqchen118. I'm sorry for the inconvenience. This issue is duplicate of https://github.com/espressif/esp-idf/issues/6262.

Please see my comment there with possible workarounds:
https://github.com/espressif/esp-idf/issues/6262#issuecomment-745106666

Please subscribe to that issue to get notified when it is fixed. I'm closing this now.

**Closed by dobairoland** 2020-12-15 11:55 UTC
