### ISSUE TITLE
decode QR with the captured Image from ESP32 (IDFGH-3749)

### ISSUE THREAD

**Issue by RAHUL-CAMPUS** [espressif/esp-idf#5669] opened 2020-07-31 05:37 UTC
I have tried to capture QR Image in grayscale as well as RGB565 format from ESP32 and tried to decode using this library https://github.com/donny681/ESP32_CAMERA_QR but could not able to decode it.
I am developing over Arduino Platform.

**Comment by igrr** [comment] 2020-08-01 01:11
Hi @RAHUL-CAMPUS, for this issue related to a third party repository, please use the corresponding issue tracker: https://github.com/donny681/ESP32_CAMERA_QR/issues.

Closing, as the issue is not a bug report or a feature request for the ESP-IDF project.

**Closed by igrr** 2020-08-01 01:11 UTC
