### ISSUE TITLE
assert failed: block_locate_free tlsf.c:566 (block_size(block) >= size) (IDFGH-11025)

### ISSUE THREAD

**Issue by srikanthpalvai** [espressif/esp-idf#12207] opened 2023-09-07 17:40 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.2

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32 S3 USB OTG

### Power Supply used.

USB

### What is the expected behavior?

lwip socket issue

### What is the actual behavior?

it should not throw assert 

### Steps to reproduce.

[sdkconfig.log](https://github.com/espressif/esp-idf/files/12552010/sdkconfig.log)

### Debug Logs.

```plain
Backtrace: 0x40376342:0x3fca9ba0 0x4037db0d:0x3fca9bc0 0x4038808d:0x3fca9be0 0x40383738:0x3fca9d00 0x40383122:0x3fca9d20 0x40376561:0x3fca9d40 0x403765c1:0x3fca9d60 0x403765f6:0x3fca9d80 0x40376fe8:0x3fca9da0 0x40377185:0x3fca9e20 0x4037a151:0x3fca9e40 0x42063947:0x3fca9e60 0x4206c193:0x3fca9e80 0x42069479:0x3fca9ea0 0x42008522:0x3fca9ec0 0x42008575:0x3fca9ef0 0x403815fe:0x3fca9f10
0x40376342: panic_abort at /home/lab/esp/esp-idf/components/esp_system/panic.c:423

0x4037db0d: esp_system_abort at /home/lab/esp/esp-idf/components/esp_system/esp_system.c:153

0x4038808d: __assert_func at /home/lab/esp/esp-idf/components/newlib/assert.c:78

0x40383738: block_locate_free at /home/lab/esp/esp-idf/components/heap/tlsf/tlsf.c:566
 (inlined by) tlsf_malloc at /home/lab/esp/esp-idf/components/heap/tlsf/tlsf.c:1004

0x40383122: multi_heap_malloc_impl at /home/lab/esp/esp-idf/components/heap/multi_heap.c:207

0x40376561: heap_caps_malloc_base at /home/lab/esp/esp-idf/components/heap/heap_caps.c:167

0x403765c1: heap_caps_malloc at /home/lab/esp/esp-idf/components/heap/heap_caps.c:187

0x403765f6: heap_caps_malloc_default at /home/lab/esp/esp-idf/components/heap/heap_caps.c:212

0x40376fe8: trace_malloc at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:97

0x40377185: __wrap_malloc at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:159

0x4037a151: wifi_malloc at /home/lab/esp/esp-idf/components/esp_wifi/esp32s3/esp_adapter.c:68

0x42063947: ieee80211_timer_process at ??:?

0x4206c193: pp_timer_process at ??:?

0x42069479: lmac_stop_hw_txq at ??:?

0x42008522: timer_process_alarm at /home/lab/esp/esp-idf/components/esp_timer/src/esp_timer.c:406

0x42008575: timer_task at /home/lab/esp/esp-idf/components/esp_timer/src/esp_timer.c:432 (discriminator 1)

0x403815fe: vPortTaskWrapper at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154





ELF file SHA256: 60dd697ccb17f30e

Core dump started (further output muted)
Received  36 kB...
Core dump finished!
===============================================================
==================== ESP32 CORE DUMP START ====================

Crashed task handle: 0x3fcaa07c, name: 'esp_timer', GDB name: 'process 1070243964'

================== CURRENT THREAD REGISTERS ===================
exccause       0x1d (StoreProhibitedCause)
excvaddr       0x0
epc1           0x4037c5e7
epc2           0x0
epc3           0x0
epc4           0x0
epc5           0x0
epc6           0x0
eps2           0x0
eps3           0x0
eps4           0x0
eps5           0x0
eps6           0x0
pc             0x40376345          0x40376345 <panic_abort+21>
lbeg           0x40056f08          1074097928
lend           0x40056f12          1074097938
lcount         0x0                 0
sar            0x18                24
ps             0x60323             394019
threadptr      <unavailable>
br             <unavailable>
scompare1      <unavailable>
acclo          <unavailable>
acchi          <unavailable>
m0             <unavailable>
m1             <unavailable>
m2             <unavailable>
m3             <unavailable>
expstate       <unavailable>
f64r_lo        <unavailable>
f64r_hi        <unavailable>
f64s           <unavailable>
fcr            <unavailable>
fsr            <unavailable>
a0             0x8037db10          -2143823088
a1             0x3fca9ba0          1070242720
a2             0x3fca9beb          1070242795
a3             0x3                 3
a4             0xa                 10
a5             0xf28955ec          -225880596
a6             0x60023             393251
a7             0x1                 1
a8             0x0                 0
a9             0x1                 1
a10            0x3fca9cb3          1070242995
a11            0x3fca9cb3          1070242995
a12            0x3fca9cb3          1070242995
a13            0x0                 0
a14            0x1                 1
a15            0x0                 0

==================== CURRENT THREAD STACK =====================
#0  0x40376345 in panic_abort (details=0x3fca9beb \"assert failed: block_locate_free tlsf.c:566 (block_size(block) >= size)\") at /home/lab/esp/esp-idf/components/esp_system/panic.c:423
#1  0x4037db10 in esp_system_abort (details=0x3fca9beb \"assert failed: block_locate_free tlsf.c:566 (block_size(block) >= size)\") at /home/lab/esp/esp-idf/components/esp_system/esp_system.c:153
#2  0x40388090 in __assert_func (file=0x3c0d11f3 \"tlsf.c\", line=<optimized out>, func=<optimized out>, expr=0x3c0d1578 \"block_size(block) >= size\") at /home/lab/esp/esp-idf/components/newlib/assert.c:78
#3  0x4038373b in block_locate_free (size=<optimized out>, control=<optimized out>) at /home/lab/esp/esp-idf/components/heap/tlsf/tlsf.c:566
#4  tlsf_malloc (tlsf=0x3fca617c, size=<optimized out>) at /home/lab/esp/esp-idf/components/heap/tlsf/tlsf.c:1004
#5  0x40383125 in multi_heap_malloc_impl (heap=0x3fca6168, size=8) at /home/lab/esp/esp-idf/components/heap/multi_heap.c:207
#6  0x40376564 in heap_caps_malloc_base (size=8, caps=6144) at /home/lab/esp/esp-idf/components/heap/heap_caps.c:167
#7  0x403765c4 in heap_caps_malloc (size=8, caps=6144) at /home/lab/esp/esp-idf/components/heap/heap_caps.c:187
#8  0x403765f9 in heap_caps_malloc_default (size=8) at /home/lab/esp/esp-idf/components/heap/heap_caps.c:212
#9  0x40376feb in trace_malloc (size=8, caps=0, mode=TRACE_MALLOC_DEFAULT) at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:97
#10 0x40377188 in __wrap_malloc (size=8) at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:159
#11 0x4037a154 in wifi_malloc (size=8) at /home/lab/esp/esp-idf/components/esp_wifi/esp32s3/esp_adapter.c:68
#12 0x4206394a in ieee80211_timer_process ()
#13 0x4206c196 in pp_timer_process ()
#14 0x4206947c in ?? ()
#15 0x42008525 in timer_process_alarm (dispatch_method=ESP_TIMER_TASK) at /home/lab/esp/esp-idf/components/esp_timer/src/esp_timer.c:406
#16 0x42008578 in timer_task (arg=0x0) at /home/lab/esp/esp-idf/components/esp_timer/src/esp_timer.c:432
#17 0x40381601 in vPortTaskWrapper (pxCode=0x42008564 <timer_task>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

======================== THREADS INFO =========================
  Id   Target Id          Frame 
* 1    process 1070243964 0x40376345 in panic_abort (details=0x3fca9beb \"assert failed: block_locate_free tlsf.c:566 (block_size(block) >= size)\") at /home/lab/esp/esp-idf/components/esp_system/panic.c:423
  2    process 1070270204 0x4037c5e2 in esp_cpu_wait_for_intr () at /home/lab/esp/esp-idf/components/esp_hw_support/cpu.c:110
  3    process 1070259844 0x4037c5e2 in esp_cpu_wait_for_intr () at /home/lab/esp/esp-idf/components/esp_hw_support/cpu.c:110
  4    process 1070288916 xQueueReceive (xQueue=0x3fcb52d4, pvBuffer=0x3fcb8680, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1407
  5    process 1070342776 0x4200fbb8 in getResponseFromBsf ()
  6    process 1070233172 0x4037eb9c in xQueueSemaphoreTake (xQueue=0x3fc9d07c <s_ipc_sem_buffer>, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
  7    process 1070272612 0x403813a3 in prvProcessTimerOrBlockTask (xNextExpireTime=<optimized out>, xListWasEmpty=1) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
  8    process 1070280316 0x4037eb9c in xQueueSemaphoreTake (xQueue=0x3fcb19c0, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
  9    process 1070234812 xQueueSemaphoreTake (xQueue=0x3fc9d0d8 <s_ipc_sem_buffer+92>, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1570
  10   process 1070306780 0x4037ea1d in xQueueReceive (xQueue=0x3fcb8818, pvBuffer=0x3fcb9410, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
  11   process 1070284936 0x4037eb9c in xQueueSemaphoreTake (xQueue=0x3fcb4234, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
  12   process 1070317860 0x4037ea1d in xQueueReceive (xQueue=0x3fcba020, pvBuffer=0x3fcbbf80, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40

==================== THREAD 1 (TCB: 0x3fcaa07c, name: 'esp_timer') =====================
#0  0x40376345 in panic_abort (details=0x3fca9beb \"assert failed: block_locate_free tlsf.c:566 (block_size(block) >= size)\") at /home/lab/esp/esp-idf/components/esp_system/panic.c:423
#1  0x4037db10 in esp_system_abort (details=0x3fca9beb \"assert failed: block_locate_free tlsf.c:566 (block_size(block) >= size)\") at /home/lab/esp/esp-idf/components/esp_system/esp_system.c:153
#2  0x40388090 in __assert_func (file=0x3c0d11f3 \"tlsf.c\", line=<optimized out>, func=<optimized out>, expr=0x3c0d1578 \"block_size(block) >= size\") at /home/lab/esp/esp-idf/components/newlib/assert.c:78
#3  0x4038373b in block_locate_free (size=<optimized out>, control=<optimized out>) at /home/lab/esp/esp-idf/components/heap/tlsf/tlsf.c:566
#4  tlsf_malloc (tlsf=0x3fca617c, size=<optimized out>) at /home/lab/esp/esp-idf/components/heap/tlsf/tlsf.c:1004
#5  0x40383125 in multi_heap_malloc_impl (heap=0x3fca6168, size=8) at /home/lab/esp/esp-idf/components/heap/multi_heap.c:207
#6  0x40376564 in heap_caps_malloc_base (size=8, caps=6144) at /home/lab/esp/esp-idf/components/heap/heap_caps.c:167
#7  0x403765c4 in heap_caps_malloc (size=8, caps=6144) at /home/lab/esp/esp-idf/components/heap/heap_caps.c:187
#8  0x403765f9 in heap_caps_malloc_default (size=8) at /home/lab/esp/esp-idf/components/heap/heap_caps.c:212
#9  0x40376feb in trace_malloc (size=8, caps=0, mode=TRACE_MALLOC_DEFAULT) at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:97
#10 0x40377188 in __wrap_malloc (size=8) at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:159
#11 0x4037a154 in wifi_malloc (size=8) at /home/lab/esp/esp-idf/components/esp_wifi/esp32s3/esp_adapter.c:68
#12 0x4206394a in ieee80211_timer_process ()
#13 0x4206c196 in pp_timer_process ()
#14 0x4206947c in ?? ()
#15 0x42008525 in timer_process_alarm (dispatch_method=ESP_TIMER_TASK) at /home/lab/esp/esp-idf/components/esp_timer/src/esp_timer.c:406
#16 0x42008578 in timer_task (arg=0x0) at /home/lab/esp/esp-idf/components/esp_timer/src/esp_timer.c:432
#17 0x40381601 in vPortTaskWrapper (pxCode=0x42008564 <timer_task>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 2 (TCB: 0x3fcb06fc, name: 'IDLE') =====================
#0  0x4037c5e2 in esp_cpu_wait_for_intr () at /home/lab/esp/esp-idf/components/esp_hw_support/cpu.c:110
#1  0x42004409 in esp_vApplicationIdleHook () at /home/lab/esp/esp-idf/components/esp_system/freertos_hooks.c:59
#2  0x4037f2b4 in prvIdleTask (pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:4157
#3  0x40381601 in vPortTaskWrapper (pxCode=0x4037f2a8 <prvIdleTask>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 3 (TCB: 0x3fcade84, name: 'IDLE') =====================
#0  0x4037c5e2 in esp_cpu_wait_for_intr () at /home/lab/esp/esp-idf/components/esp_hw_support/cpu.c:110
#1  0x42004409 in esp_vApplicationIdleHook () at /home/lab/esp/esp-idf/components/esp_system/freertos_hooks.c:59
#2  0x4037f2b4 in prvIdleTask (pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:4157
#3  0x40381601 in vPortTaskWrapper (pxCode=0x4037f2a8 <prvIdleTask>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 4 (TCB: 0x3fcb5014, name: 'tiT') =====================
#0  xQueueReceive (xQueue=0x3fcb52d4, pvBuffer=0x3fcb8680, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1407
#1  0x40387212 in sys_arch_mbox_fetch (mbox=<optimized out>, msg=0x3fcb8680, timeout=<optimized out>) at /home/lab/esp/esp-idf/components/lwip/port/esp32/freertos/sys_arch.c:341
#2  0x420cf710 in tcpip_timeouts_mbox_fetch (mbox=0x3fca15f4 <tcpip_mbox>, msg=0x3fcb8680) at /home/lab/esp/esp-idf/components/lwip/lwip/src/api/tcpip.c:104
#3  0x4038743c in tcpip_thread (arg=0x0) at /home/lab/esp/esp-idf/components/lwip/lwip/src/api/tcpip.c:142
#4  0x40381601 in vPortTaskWrapper (pxCode=0x40387414 <tcpip_thread>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 5 (TCB: 0x3fcc2278, name: 'FetchPendingMes') =====================
#0  0x4200fbb8 in getResponseFromBsf ()

==================== THREAD 6 (TCB: 0x3fca7654, name: 'ipc0') =====================
#0  0x4037eb9c in xQueueSemaphoreTake (xQueue=0x3fc9d07c <s_ipc_sem_buffer>, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
#1  0x40379fc4 in ipc_task (arg=0x0) at /home/lab/esp/esp-idf/components/esp_system/esp_ipc.c:64
#2  0x40381601 in vPortTaskWrapper (pxCode=0x40379f94 <ipc_task>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 7 (TCB: 0x3fcb1064, name: 'Tmr Svc') =====================
#0  0x403813a3 in prvProcessTimerOrBlockTask (xNextExpireTime=<optimized out>, xListWasEmpty=1) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
#1  0x403814f3 in prvTimerTask (pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/timers.c:604
#2  0x40381601 in vPortTaskWrapper (pxCode=0x403814e4 <prvTimerTask>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 8 (TCB: 0x3fcb2e7c, name: 'usb_lib') =====================
#0  0x4037eb9c in xQueueSemaphoreTake (xQueue=0x3fcb19c0, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
#1  0x4201b04c in usb_host_lib_handle_events (timeout_ticks=4294967295, event_flags_ret=0x3fcb2cd8) at /home/lab/esp/esp-idf/components/usb/usb_host.c:498
#2  0x42017513 in usb_lib_task ()
#3  0x40381601 in vPortTaskWrapper (pxCode=0x42017500 <usb_lib_task>, pvParameters=0x3fcab60c) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 9 (TCB: 0x3fca7cbc, name: 'ipc1') =====================
#0  xQueueSemaphoreTake (xQueue=0x3fc9d0d8 <s_ipc_sem_buffer+92>, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1570
#1  0x40379fc4 in ipc_task (arg=0x1) at /home/lab/esp/esp-idf/components/esp_system/esp_ipc.c:64
#2  0x40381601 in vPortTaskWrapper (pxCode=0x40379f94 <ipc_task>, pvParameters=0x1) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 10 (TCB: 0x3fcb95dc, name: 'sys_evt') =====================
#0  0x4037ea1d in xQueueReceive (xQueue=0x3fcb8818, pvBuffer=0x3fcb9410, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
#1  0x420c8bc8 in esp_event_loop_run (event_loop=0x3fcb51d8, ticks_to_run=4294967295) at /home/lab/esp/esp-idf/components/esp_event/esp_event.c:558
#2  0x420c8be0 in esp_event_loop_run_task (args=0x3fcb51d8) at /home/lab/esp/esp-idf/components/esp_event/esp_event.c:107
#3  0x40381601 in vPortTaskWrapper (pxCode=0x420c8bd4 <esp_event_loop_run_task>, pvParameters=0x3fcb51d8) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 11 (TCB: 0x3fcb4088, name: 'USB-CDC') =====================
#0  0x4037eb9c in xQueueSemaphoreTake (xQueue=0x3fcb4234, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
#1  0x4201b35c in usb_host_client_handle_events (client_hdl=0x3fcb41ec, timeout_ticks=4294967295) at /home/lab/esp/esp-idf/components/usb/usb_host.c:730
#2  0x420179e2 in cdc_acm_client_task ()
#3  0x40381601 in vPortTaskWrapper (pxCode=0x42017994 <cdc_acm_client_task>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154

==================== THREAD 12 (TCB: 0x3fcbc124, name: 'wifi') =====================
#0  0x4037ea1d in xQueueReceive (xQueue=0x3fcba020, pvBuffer=0x3fcbbf80, xTicksToWait=<optimized out>) at /home/lab/esp/esp-idf/components/xtensa/include/xt_utils.h:40
#1  0x42038bb4 in queue_recv_wrapper (queue=0x3fcba020, item=0x3fcbbf80, block_time_tick=4294967295) at /home/lab/esp/esp-idf/components/esp_wifi/esp32s3/esp_adapter.c:425
#2  0x420c6c44 in ppTask ()
#3  0x40381601 in vPortTaskWrapper (pxCode=0x420c6c18 <ppTask>, pvParameters=0x0) at /home/lab/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:154


======================= ALL MEMORY REGIONS ========================
Name   Address   Size   Attrs
.rtc.force_fast 0x600fe010 0x0 RW  
.rtc.force_slow 0x50000010 0x0 RW  
.iram0.vectors 0x40374000 0x403 R XA
.iram0.text 0x40374404 0x15c43 R XA
.dram0.data 0x3fc9a100 0x4464 RW A
.noinit 0x3fc9e564 0x0 RW  
.flash.text 0x42000020 0xcfef7 R XA
.flash.appdesc 0x3c0d0020 0x100 R  A
.flash.rodata 0x3c0d0120 0x41044 RW A
.ext_ram.bss 0x3c120000 0x0 RW  
.iram0.data 0x4038a100 0x0 RW  
.iram0.bss 0x4038a100 0x0 RW  
.dram0.heap_start 0x3fca6168 0x0 RW  
.coredump.tasks.data 0x3fcaa07c 0x160 RW 
.coredump.tasks.data 0x3fca9ae0 0x590 RW 
.coredump.tasks.data 0x3fcb06fc 0x160 RW 
.coredump.tasks.data 0x3fcb0470 0x280 RW 
.coredump.tasks.data 0x3fcade84 0x160 RW 
.coredump.tasks.data 0x3fcadbf0 0x280 RW 
.coredump.tasks.data 0x3fcb5014 0x160 RW 
.coredump.tasks.data 0x3fcb8530 0x2e0 RW 
.coredump.tasks.data 0x3fcc2278 0x160 RW 
.coredump.tasks.data 0x3fcc5510 0x1a20 RW 
.coredump.tasks.data 0x3fca7654 0x160 RW 
.coredump.tasks.data 0x3fca73c0 0x280 RW 
.coredump.tasks.data 0x3fcb1064 0x160 RW 
.coredump.tasks.data 0x3fcb0dd0 0x280 RW 
.coredump.tasks.data 0x3fcb2e7c 0x160 RW 
.coredump.tasks.data 0x3fcb2bb0 0x2c0 RW 
.coredump.tasks.data 0x3fca7cbc 0x160 RW 
.coredump.tasks.data 0x3fca7a30 0x280 RW 
.coredump.tasks.data 0x3fcb95dc 0x160 RW 
.coredump.tasks.data 0x3fcb9310 0x2c0 RW 
.coredump.tasks.data 0x3fcb4088 0x160 RW 
.coredump.tasks.data 0x3fcb3db0 0x2d0 RW 
.coredump.tasks.data 0x3fcbc124 0x160 RW 
.coredump.tasks.data 0x3fcbbe60 0x2b0 RW 

===================== ESP32 CORE DUMP END =====================
===============================================================
Done!
Coredump checksum='74a81bf4'
Rebooting...
```

**Comment by ESP-Marius** [comment] 2023-09-11 05:45
@srikanthpalvai this kind of errors are usually caused by heap memory getting corrupted (overwritten by something in your app).

You can take a look at the [heap memory debugging guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html) to see a few ways you can debug this. I suggest trying to run with a higher level of [Heap Poisoning](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html#configuration) first.

**Comment by srikanthpalvai** [comment] 2023-09-13 14:41
Thank you @ESP-Marius 
I will try and let you know the results

**Comment by srikanthpalvai** [comment] 2023-09-15 09:25
void convertByteArrayToHexString (char *target, int len)
{
    ESP_LOGD(TAG,  "convertByteArrayToHexString Start");
    char *val = NULL;
    printf("check 1\n");
    val =  (char *)malloc (len * 2);
    printf("check 2\n");
    if (val != NULL)
    {
        printf("check 3\n");
        int i, j;
        printf("check 4\n");
        for (i = 0, j = 0; i < len; ++i, j += 2)
        {
            printf("check 5\n");
            sprintf (val + j, "%02x", target[i] & 0xff);
            printf("check 6\n");
        }

        printf("check 7\n");
        memset (target, 0, strlen (target));
        printf("check 8\n");
        memcpy (target, val, len * 2);
        printf("check 9\n");
        **free (val);**
        printf("check 10\n");
    }
    else
    {
        ESP_LOGD(TAG,  "No memory available.");
        //log_debug("No memory available.");
    }
    ESP_LOGD(TAG,  "convertByteArrayToHexString End");
}


After deep debugging, this POC creating free issue 

check 5
check 6
check 7
check 8
check 9
CORRUPT HEAP: Bad tail at 0x3fcb0e66. Expected 0xbaad5678 got 0xbaad5600

assert failed: multi_heap_free multi_heap_poisoning.c:276 (head != NULL)


Backtrace: 0x4037630e:0x3fccbb30 0x4037dbc9:0x3fccbb50 0x40387941:0x3fccbb70 0x403832f5:0x3fccbc90 0x4037671a:0x3fccbcb0 0x4037719f:0x3fccbcd0 0x40377221:0x3fccbd20 0x4202028e:0x3fccbd40 0x4201cd96:0x3fccbd80 0x4201e08a:0x3fccbed0 0x4201ec29:0x3fccc720 0x4201be6b:0x3fccce70 0x4201c27b:0x3fcccf80 0x4201b0d5:0x3fcccfd0 0x420184cb:0x3fccd3f0 0x4200d802:0x3fccd4c0 0x403816ba:0x3fccd5e0
0x4037630e: panic_abort at /home/lab/esp/esp-idf/components/esp_system/panic.c:423

0x4037dbc9: esp_system_abort at /home/lab/esp/esp-idf/components/esp_system/esp_system.c:153

0x40387941: __assert_func at /home/lab/esp/esp-idf/components/newlib/assert.c:78

0x403832f5: multi_heap_free at /home/lab/esp/esp-idf/components/heap/multi_heap_poisoning.c:276 (discriminator 1)

0x4037671a: heap_caps_free at /home/lab/esp/esp-idf/components/heap/heap_caps.c:374

0x4037719f: trace_free at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:119

0x40377221: __wrap_free at /home/lab/esp/esp-idf/components/heap/include/heap_trace.inc:164

0x4202028e: convertByteArrayToHexString at ??:?

Could you please suggest how to get rid of it

**Comment by ESP-Marius** [comment] 2023-09-16 03:58
> memcpy (target, val, len * 2);

Isnt the length of `target` `len` here? so you would be way outside the allocated area if you write `len * 2`.

I suggest going to e.g. our forum `www.esp32.com` for generic questions like this, the github issue tracker is mainly meant for reporting ESP-IDF related bugs.

**Comment by SoucheSouche** [comment] 2023-10-12 06:39
Closing issue since it does not report an ESP-IDF bug. The heap corruption encountered is introduced in the application code itself.

**Closed by SoucheSouche** 2023-10-12 06:39 UTC
Labels: Type: Bug, Awaiting Response, Status: Opened
