### ISSUE TITLE
Possible regression - failed to strip unused libstdc++ code after f8319f0 on ESP32-S3 (IDFGH-12843)

### ISSUE THREAD

**Issue by andylinpersonal** [espressif/esp-idf#13809] opened 2024-05-19 17:37 UTC
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

release/v5.2

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Linker should strip unused ```libstdc++``` code, such as ```iostream```, which is so bulky that I noticed this regression immediately :(

### What is the actual behavior?

After f8319f08cca75236c29eecfce01886a671f4fc17 on release/v5.2, the unused `libstdc++` functions remain inside the final binary.

This regression can only be reproduced on ESP32-S3. (and possible for other Xtensa targets due to similar configurations in the LD template.)

### Steps to reproduce.

1. Just update the IDF to any commit newer than f8319f08cca75236c29eecfce01886a671f4fc17
2. Use some standard c++ functions rely on libstdc++.a
3. See the size of final binary by ```idf.py size-components```. 
4. Can also use ```objdump``` to see what still stay in the final binary.

MWE:
```C++
// Other C++ standard library functions implemented in the libstdc++.a can also be used.
#include <mutex>
#include <cmath>
#include <cstdio>

extern "C" void app_main(void)
{
	std::mutex mt;
	std::lock_guard lg(mt);
}

```

Following lines might cause this regression. I just reverted these lines and everything looks ok now.

![image](https://github.com/espressif/esp-idf/assets/26407395/ad7eecfc-04d2-422f-920e-1cecb39eaf22)

#### idf.py size-components before f8319f08cca75236c29eecfce01886a671f4fc17

```plain
Total sizes:
Used static IRAM:   57486 bytes ( 304754 remain, 15.9% used)
      .text size:   56459 bytes
   .vectors size:    1027 bytes
Used stat D/IRAM:   16972 bytes ( 328884 remain, 4.9% used)
      .data size:   11724 bytes
      .bss  size:    5248 bytes
Used Flash size :  157443 bytes
           .text:  103987 bytes
         .rodata:   53200 bytes
Total image size:  226653 bytes (.bin may be padded larger)
Per-archive contributions to ELF file:
            Archive File DRAM .data & 0.bss IRAM0 .text & 0.vectors ram_st_total Flash .text & .rodata & .appdesc flash_total
                  libc.a        264     320           0           0          584       44908      3689          0       48861
            libpthread.a         16      12           0           0           28        1269     36651          0       37936
     libesp_hw_support.a        303      87        6596           0         6986       15459       918          0       23276
           libfreertos.a       4220     757       14377           0        19354         699      1029          0       20325
          libspi_flash.a       1998      32       11425           0        13455        1060       443          0       14926
         libesp_system.a        476     272        3971           0         4719        9357       582          0       14386
                libhal.a       2688       4        7608           0        10300         983         0          0       11279
        libespcoredump.a        112    2712           0           0         2824        8901       610          0        9623
               libheap.a          4       8        5320           0         5332        3209       852          0        9385
             libstdc++.a          8     369           0           0          377        4626      3089          0        7723
                libvfs.a        232      52           0           0          284        3432       371          0        4035
             libxtensa.a       1060       0        2057         424         3541         119        48          0        3708
             libesp_mm.a          4      44         459           0          507        2420       166          0        3049
             libnewlib.a        164     200        1576           0         1940        1209        95          0        3044
             libdriver.a         36       0           0           0           36        1844       281          0        2161
                libsoc.a          0       0           0           0            0           0      2020          0        2020
         libesp_common.a          0       0           0           0            0          51      1742          0        1793
          libesp_timer.a         32      36         512           0          580        1060        57          0        1661
      libesp_partition.a          0       8           0           0            8        1284        75          0        1359
                liblog.a          8     272         238           0          518         636        21          0         903
 libbootloader_support.a          0       0         812           0          812          34        40          0         886
            libesp_rom.a          0       0         446           0          446          78         0          0         524
     libesp_app_format.a          0      10           0           0           10         184         4        256         444
             libxt_hal.a          0       0         405           0          405           0        32          0         437
         libapp_update.a          0       4           0           0            4         152        30          0         182
                libcxx.a          0       0           0           0            0          56         0          0          56
               libmain.a          0       0           0           0            0          45         0          0          45
              libefuse.a          0       0           0           0            0          17         0          0          17
                   (exe)          0       0           0           3            3           3         8          0          14
            libesp_phy.a          0       0           0           0            0           5         0          0           5
   libnvs_sec_provider.a          0       0           0           0            0           5         0          0           5
        libesp_ringbuf.a          0       0           0           0            0           0         0          0           0
                libgcc.a          0       0           0           0            0           0         0          0           0
         libmbedcrypto.a          0       0           0           0            0           0         0          0           0
          libnvs_flash.a          0       0           0           0            0           0         0          0           0
```

#### idf.py size-components after f8319f08cca75236c29eecfce01886a671f4fc17

```plain
Total sizes:
Used static IRAM:   58102 bytes ( 304138 remain, 16.0% used)
      .text size:   57075 bytes
   .vectors size:    1027 bytes
Used stat D/IRAM:   21584 bytes ( 324272 remain, 6.2% used)
      .data size:   12160 bytes
      .bss  size:    9424 bytes
Used Flash size :  494211 bytes
           .text:  408443 bytes
         .rodata:   85512 bytes
Total image size:  564473 bytes (.bin may be padded larger)
Per-archive contributions to ELF file:
            Archive File DRAM .data & 0.bss IRAM0 .text & 0.vectors ram_st_total Flash .text & .rodata & .appdesc flash_total
             libstdc++.a        152    4325           0           0         4477      221558     28028          0      249738
                  libc.a        364     500           0           0          864      108577      7137          0      116078
            libpthread.a         16      12           0           0           28        1377     39700          0       41093
     libesp_hw_support.a        319      91        6596           0         7006       19607      1190          0       27712
           libfreertos.a       4220     757       14447           0        19424         711      1059          0       20437
          libspi_flash.a       1998      32       11425           0        13455        1060       443          0       14926
         libesp_system.a        476     272        3971           0         4719        9362       582          0       14391
                libhal.a       2797       4        7873           0        10674        2992         0          0       13662
        libespcoredump.a        112    2712           0           0         2824        8901       610          0        9623
          libnvs_flash.a          0       4           0           0            4        9125       300          0        9425
               libheap.a          4       8        5320           0         5332        3205       852          0        9381
                libvfs.a        232      52           0           0          284        3432       371          0        4035
             libxtensa.a       1060       0        2057         424         3541         119        48          0        3708
             libnewlib.a        164     200        1593           0         1957        1209        95          0        3061
             libesp_mm.a          4      44         459           0          507        2420       166          0        3049
         libmbedcrypto.a         56      12           0           0           68        2651        56          0        2763
                libsoc.a          0       0         245           0          245           0      2020          0        2265
             libdriver.a         36       0           0           0           36        1844       281          0        2161
      libesp_partition.a          0       8           0           0            8        1669       168          0        1837
         libesp_common.a          0       0           0           0            0          51      1742          0        1793
          libesp_timer.a         32      36         512           0          580        1060        57          0        1661
                libcxx.a          8      16           0           0           24         946         0          0         954
                liblog.a          8     272         238           0          518         636        21          0         903
 libbootloader_support.a          0       0         812           0          812          34        40          0         886
            libesp_rom.a          0       0         446           0          446          78         0          0         524
     libesp_app_format.a          0      10           0           0           10         184         4        256         444
             libxt_hal.a          0       0         405           0          405           0        32          0         437
         libapp_update.a          0       4           0           0            4         152        30          0         182
               libmain.a          0       0           0           0            0          45         0          0          45
              libefuse.a          0       0           0           0            0          17         0          0          17
                   (exe)          0       0           0           3            3           3         8          0          14
            libesp_phy.a          0       0           0           0            0           5         0          0           5
   libnvs_sec_provider.a          0       0           0           0            0           5         0          0           5
        libesp_ringbuf.a          0       0           0           0            0           0         0          0           0
                libgcc.a          0       0           0           0            0           0         0          0           0
```

**Comment by sudeep-mohanty** [comment] 2024-05-20 08:21
Hello @andylinpersonal, I can confirm that I observe the same behavior. We will take a look and update you once we have more information. Thanks!

**Comment by AxelLin** [comment] 2024-06-06 02:11
@Lapshin Is there any update for the fix? 
v5.2 is a release branch, I think this should be fixed ASAP.
(If it really takes time to fix it, maybe you can consider revert the bad commit first.)

**Comment by Lapshin** [comment] 2024-06-13 05:06
@AxelLin , thank you for your attention on this. The commit https://github.com/espressif/esp-idf/commit/5320ec20f9302f260265b27d55ade1bc92b92ea9 was ready a few weeks ago but waited to be synced with GitHub repo.

Closing this issue because fixed for all affected branches

**Closed by Lapshin** 2024-06-13 05:06 UTC
Labels: Type: Bug, Status: Opened

**Comment by andylinpersonal** [comment] 2024-06-13 08:51
Fixed in master so close this ticket
